### ISSUE TITLE
inspect detect should additionally output virtualization platform

### ISSUE THREAD

**Issue by nvtkaszpir** [inspec/inspec#1005]
### Description

As user when using inspec detec command on remote host I'd like to be able to see virtualization platform.
### InSpec and Platform Version

inspec 0.30.0
### Replication Case

In LXC:

``` bash
17:08:50 $ inspec detect -t ssh://root@10.0.3.251 --password root

== Operating System Details

Name:      debian
Family:    debian
Release:   7.9
Arch:      x86_64
```

Expected output:

``` bash
17:08:50 $ inspec detect -t ssh://root@10.0.3.251 --password root

== Operating System Details

Name:      debian
Family:    debian
Release:   7.9
Arch:      x86_64
Virtual:   lxc
```
### Possible Solutions

It could leverage using virt-what http://git.annexia.org/?p=virt-what.git;a=summary

Maybe extend inspec os module with more detailed info https://docs.chef.io/inspec_os.html ? 
But I think it should be as separate module.
### Stacktrace

No stacktrace.

**Comment by chris-rock** [comment]
@nvtkaszpir That is a great idea. Once we add this, we should thank about the detection of multiple virtual platforms. I would propose we implement this in two steps:
- add the InSpec resource to detect the virtual platform (this would allow us to use that information in InSpec tests as well)
- include this resource in InSpec detect
  A PR is welcome to add this feature to InSpec.

**Comment by lamont-granquist** [comment]
There's going to be a lot of duplication with ohai here.  Highly encourage you to look at that code, since detecting virtualization and cloud platforms is something that we've been fighting with there for years now.

**Comment by chris-rock** [comment]
Awesome @lamont-granquist Lets see how we can reuse that.

**Comment by aaronlippold** [comment]
Hi, I second this as it would apply to the generalization and implementation of profiles for all profiles - such as the STIG and CIS - that will have different control implications given they are inside a container or not. 

With respect to @lamont-granquist comment - the code in ohai is here : https://github.com/chef/ohai/blob/master/lib/ohai/plugins/linux/virtualization.rb#L163

**Comment by kekaichinose** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
