### ISSUE TITLE
Ability to export reports in SCAP format

### ISSUE THREAD

**Issue by glasschef** [inspec/inspec#1056]
The ability to export reports in an SCAP format would be very beneficial: https://scap.nist.gov/

**Comment by kekaichinose** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
