### ISSUE TITLE
resource fail (exception) aborts all tests

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#1205]
### Description

The ssl resource fails if it cannot connect to an external host https://github.com/chef/inspec/blob/master/lib/resources/ssl.rb#L55. This results in a strange behavior, if this is only one tests in a profile, since the full profile execution is aborted:

```
 b inspec exec https://github.com/chris-rock/acme-inspec-profile -t docker://67bcf1bf4019
Cannot determine host for SSL test. Please specify it or use a different target.
```
### InSpec and Platform Version

InSpec 1.0
### Possible Solutions

We should not use fail in the resource or handle resource failures as a control failure.

**Comment by alexpop** [comment]
Chris, agree that a failure for this resource should not stop the entire run.

As an alternative to this:
  https://github.com/chef/inspec/blob/v1.1.0/lib/resources/ssl.rb#L55

I looked into using the `skip_resource` option we have:

``` ruby
  return skip_resource 'Cannot determine host for SSL test. Please specify it or use a different target.'
```

With that ^, targeting a docker container with this spec:

``` ruby
describe ssl(port: 443) do
  it { should be_enabled }
end

describe 5 do
  it { should be_positive }
end
```

results in:

``` ruby
Target:  docker://92222ab36457157f7be6ebefbd775860918ec131e61a1c0bd2c34e829039e647

  SSL/TLS on
     ○  Cannot determine host for SSL test. Please specify it or use a different target.
  5 should
     ✔  be positive

Test Summary: 1 successful, 0 failures, 1 skipped
```

This is because resources calling `skip_resource` in initialize will be skipped here:
  https://github.com/chef/inspec/blob/v1.1.0/lib/inspec/runner.rb#L221-L223

Problem is when we are calling a method of the ssl resource, like here:

``` ruby
describe ssl(port: 443).mymethod do
  it { should_not be_enabled }
end
```

`arg[0]` [here](https://github.com/chef/inspec/blob/v1.1.0/lib/inspec/runner.rb#L222) is the instance returned by `mymethod`

This prevents the `resource_skipped` attribute, set for the ssl instance, to be available to the instance retuned by `mymethod`.

A workaround for this in the ssl resource would be to define the method like:

``` ruby
def mymethod
  return self if resource_skipped
  'value'
end
```

This way `arg[0]` will be the ssl instance and have the `resource_skipped` attribute set.

Is it possible not to evaluate `ssl(port: 443).mymethod` if the `ssl(port: 443)` instance contains an attribute like `resource_skipped`?

**Comment by alexpop** [comment]
What if we want a particular resource error to flag the resource as failed instead of skipped?
