### ISSUE TITLE
add AD support for `user` resource to be able to check users from AD

### ISSUE THREAD

**Issue by ricardolupo** [inspec/inspec#1218]
### Description

This issue is a request to enhance the `user` resource to allow an InSpec profile to query an AD user against a running system. As enterprises often use AD for both Windows and Linux/UNIX, we would want this to work across platforms, with Windows being the priority.

**Comment by Happycoil** [comment]
re: https://github.com/chef/inspec/issues/1688 @chris-rock 

The WinNT ADSI provider doesn't return domain users<sup>1</sup>, we would have to use the LDAP provider for that. In writing that I now realise that even when querying Win32_UserAccount we would need domain credentials to be able to read the directory... That presents a problem unless we can pass credentials to the PowerShell script.

Regarding Win32_UserAccount performance, it's not slow if you cheat! Fetching the names of users you want to query and then querying for only those is pretty fast:
```powershell
$computerName = $env:COMPUTERNAME
$adsi = [ADSI]"WinNT://$computerName"
($adsi.Children | where {$_.SchemaClassName -eq  'group'} | % { $_.psbase.Invoke('members') } | % { $_.GetType().InvokeMember('Name', 'GetProperty', $null, $_, $null) } | sort | unique) -join "' OR NAME = '" | % { Get-CimInstance -Query "SELECT * FROM Win32_UserAccount WHERE Name='$_'" }
```

<sup>1</sup> As far as I'm aware. We can get the names of domain users and groups by invoking the members property of the group COM objects, though.

**Comment by chris-rock** [comment]
Good feedback. Is there any reason why we are not using the LDAP provider? See https://social.technet.microsoft.com/wiki/contents/articles/4231.working-with-active-directory-using-powershell-adsi-adapter.aspx
Lets experiment with PURE Powershell first. Its easier to ensure we have the right script first before using it in inspec. We can use attributes to pass domain users, but lets try to avoid that if possible

**Comment by Happycoil** [comment]
In the example I posted? I only had user names available, and LDAP provider queries use distinguishedNames. Win32_LocalAccount returns [info](https://msdn.microsoft.com/en-us/library/aa394507(v=vs.85).aspx) about both local and domain users, but we could easily be using the WinNT provider for local users and the LDAP provider, DirectorySearcher, or something else for AD users. This _will_ require domain credentials though.

I can dig around for more locally accessible info, but thus far all I've been able to find are the names of group members. As I mentioned in https://github.com/chef/inspec/issues/1688, we can probably use that to create a windows equivalent of `etc_group`.

**Comment by usepowershell** [comment]
@chris-rock  @Happycoil  @ricardolupo  What's the scenario here?  Are we testing a user's level of access?Then I'm not sure the user resource is the place to address this.  If we want information about the user account specifically, the existing `user` resource works against domain users if the test is run against a domain controller.  Rather than reaching out to a member server to reach out to the DC to query a user, I think the better pattern would be to query against the DC directly.

**Comment by Happycoil** [comment]
What we would typically like to test would be domain user memberships in member server groups (Administrators, Power Users, IIS groups and the like).

At the moment I can't think of any other aspects of a domain user I would like to test on a member server, so I see your point, @smurawski 

Should testing for that be a separate resource like etc_group? It's easy to assume you can test for the users and groups you see in computer management on the member server with the user and/or group resources, though...

**Comment by usepowershell** [comment]
@Happycoil I was just puzzling over the `group` and `etc_group` resources and `etc_group`'s current behavior seems closer, but just doesn't feel right to me as a Windows admin.  I would want to use `group` with similar behavior to `etc_group`.

I will readily admit my ignorance when it comes to inspec.  I haven't spent very much time using it myself (though I plan to spend much more time in the near future).

**Comment by Happycoil** [comment]
Yes, that would make sense to be as well. It would also be fairly easy to add a `members` property to the `groups` resource, and that would allow us to test for domain users in local groups without domain credentials. Does that make sense for inspec, though? @chris-rock

**Comment by chris-rock** [comment]
Due to the complexity of that matter, I think we should do the following:
- ensure that we can verify AD uses on a local machine, but leave complex logic for groups out of that resource
- improve the `group` resource to ask for its members

Therefore you would ask the following question for a test: Please give me all members of group x i. Does that make any sense?

**Comment by Happycoil** [comment]
Yeah, the second point at least should be relatively simple to add. Still looking for a good way to address the first.

Would you accept a PR which adds a `members` property to `group`? What should the collection contain on Linux based systems?

**Comment by chris-rock** [comment]
@Happycoil I think it makes sense to add members to it. Lets discuss first how that could look like, since groups can be nested.

**Comment by usepowershell** [comment]
Tackling group membership seems like the right course of action. ;)

**Comment by Happycoil** [comment]
@chris-rock As far as I'm aware neither (local) Windows groups nor Linux groups can be nested? As for AD groups, I don't think we should recurse into them at all, since the local `Users` group will by default contain `DOMAIN\Domain Users`, and we would have to reach out to a DC with valid credentials for that anyway. I imagine `members` to be a string array of direct members' user names.

Regarding the users, only some very basic info seems to be locally accessible. Examples include username, objectSID and domain, but I don't see a way of getting stuff like `UserFlags` or even `FullName` and the like without domain credentials.

**Comment by Happycoil** [comment]
@chris-rock thoughts on extending `groups` with `members` (string array with the names of member users and groups)?

**Comment by chris-rock** [comment]
@Happycoil makes sense. I like `members`

**Comment by zenspider** [comment]
I'm guessing this has been done in the last couple weeks... @miah? Is there anything else to this that wasn't covered by the recent members/AD snafu?
