### ISSUE TITLE
Link web docs to github docs

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#1229]
It would be good to have a direct 'Edit' link from http://inspec.io/docs/reference/profiles/ to https://github.com/chef/inspec/blob/master/docs/profiles.md This allows users to make easier contributions.

**Comment by kekaichinose** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
