### ISSUE TITLE
Custom resource naming issue

### ISSUE THREAD

**Issue by cjohannsen81** [inspec/inspec#1230]
### Description

I´m creating different custom resources. As soon as I name them nearly similar (host_product, host_settings) all tests fail. When I rename one to a non host_ name all works fine.
### InSpec and Platform Version

InSpec 1.2.1
### Replication Case

Just name 2 custom resource nearly similar.
### Possible Solutions

Seems that this is caused internally when extending the Inspec.resource(1) class.
### Stacktrace

➜ cjo@ChristiansMBP3  ~  inspec exec inspec-vsphere 

Profile: VMware vSphere/ESXi Resource Pack (vsphere)
Version: 0.1.0
Target:  local://

  ✖  test-1.1: Checks that the Annotations are not emty. (stack level too deep)
     ✖  hostsetting Annotations_WelcomeMessage 
     stack level too deep
  ✖  test-1.2: Checks that the actual patches are applied. (
     expected: "4192238"
          got: "3620759"

```
 (compared using ==)
 )
 ✖  hostbuildnumber build should eq "4192238"

 expected: "4192238"
      got: "3620759"

 (compared using ==)
```

**Comment by stevendanna** [comment]
Hi,

Would you mind sharing your reproduction case with us?  I've tried out a simple case similar to what you described but haven't been able to reproduce the issue yet.

Cheers,

Steven

**Comment by cjohannsen81** [comment]
Hey, 

just validated the issue and that the same/identical resource class name is a problem. Here is an example:

class ExampleResource < Inspec.resource(1) do
 name 'host_test1'

class ExampleResource < Inspec.resource(1) do
 name 'host_test2'

Cheers
Christian

**Comment by stevendanna** [comment]
Thanks. @cjohannsen81 and I had a quick chat.  The problem here is the class name being the same.  The `stack level too deep` error in the original report is a bit of a red herring as that was likely caused in the reporter or somewhere elsebecause of the large number of errors produced.  Inspec will load these resources and run the controls, but `host_test1` will essentially get overwritten with the content of `host_test2` the classes are named the same.
