### ISSUE TITLE
How is the bash resource different from the command resource.

### ISSUE THREAD

**Issue by AnotherWorkingNerd** [inspec/inspec#1287]
I feel this is documentation that will lead to much confusion. If I compare http://inspec.io/docs/reference/resources/bash/ with http://inspec.io/docs/reference/resources/command/ They appear to be very similar with the following exceptions:
- The bash resource has an example in the Syntax section that the Command does not.
- The Command resource page has many examples at the bottom of the page in the Example section not on the Bash page.

There is no documentation with regard to differences if any.  

### InSpec and Platform Version
Web site documentation see url's above

### Possible Solutions
These appear to be the same but just syntactic sugar. I feel that in order to clarify the Inspec documentation that the bash page should **only** have a simplified syntax section and then a block that explains that this is just a lasy developers version of the command resource and refer to the command resource for complete info, Of course links would be provided. Any content not on the command should be added.

Unless I'm completely wrong, I'd be willing to write page change and submit them as a PR

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
