### ISSUE TITLE
Passing options to SSH target to enable tty for sudo

### ISSUE THREAD

**Issue by vikatgithub** [inspec/inspec#1293]
InSpec version: 1.4.1

I am trying to audit the .ssh/authorized_keys file for a user different from the target user. And the --sudo-options or --sudo-comands flags do not work, because the sudo command requires tty.

This can be verified by using simple ssh commands like this:

```
> ssh user1@hostname 'sudo -u root cat /home/user2/.ssh/authorized_keys'
stdin: is not a tty 
sudo: sorry, you must have a tty to run sudo

> ssh -t user1@hostname 'sudo -u root cat /home/user2/.ssh/authorized_keys'
normal output with keys

```

Note the '-t' option to ssh that made the difference.

I created a InSpec control with command resource

`describe command('cat /home/user2/.ssh/authorized_keys')`

and ran the test as:

`inspec exec control-path -i key/path --sudo-command='sudo -u root' -t ssh://user1@hostname`

and the test failed. If I use 

`inspec exec control-path -i key/path --sudo --sudo-options='-u root' -t ssh://user1@hostname`

It gives error:

`Sudo failed: Sudo requires a TTY. Please see README ....`

So, is there a way to pass the '-t' options to ssh target?

Note: This might resolve #362, for some cases.

**Comment by vikatgithub** [comment]
Also tried the --shell option:
`inspec exec control-path -i key/path --sudo --shell -t ssh://user1@hostname`

Still getting same error

**Comment by vikatgithub** [comment]
This issue shows up only if 'requiretty' option is enabled in the sudoers file on target host.

```
# Disable "ssh hostname sudo <cmd>", beacuse it will show the password in clear
#       You have to run "ssh -t hostname sudo <cmd>".
Defaults requiretty
```

In my environment,  I cannot change that option on the target hosts.

**Comment by doertedev** [comment]
:+1: need the same. One option would be to enable --ssh-options or something similar via CLI. Then, you could send a shell-"-t" which would force a pseudo-TTY. This doesn't always help, its just an idea.

**Comment by mattlqx** [comment]
I have a need for this as well. I'm trying to use `login -f` to test whether a user can login, but that needs a PTTY to work. It works over SSH when using `-t`.

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
