### ISSUE TITLE
`inspec check` does not error on older `its(:matcher)` method calls

### ISSUE THREAD

**Issue by ricardolupo** [inspec/inspec#1299]
### Description

`inspec check` does not flag matches that use the old matcher methods

### InSpec and Platform Version

InSpec version 1.4.1
== Operating System Details

Name:      Windows Server 2012 Standard
Family:    windows
Release:   6.2.9200
Arch:      x86_64

== Operating System Details

Name:      mac_os_x
Family:    darwin
Release:   10.12.1
Arch:      x86_64

== Replication Case
Create an inspec profile using unsupported matchers do not fail an `inspec check` test and are allowed to be uploaded to a Chef Compliance server. Upon scanning using this profile, its matcher errors pop up and all controls utilizing the faulty matchers are skipped

**Comment by chris-rock** [comment]
@ricardolupo Could you share which matcher and resource you are using?

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
