### ISSUE TITLE
Introduce colors to the inspec compliance cli

### ISSUE THREAD

**Issue by vjeffrey** [inspec/inspec#1311]
### Description

Introduce colors to inspec compliance cli, as discussed here: https://github.com/chef/inspec/pull/1297

cc @hannah-radish

**Comment by vjeffrey** [comment]
![image](https://cloud.githubusercontent.com/assets/10341541/20550609/7c7bf5e6-b105-11e6-9a27-3754e04ae1f2.png)

**Comment by vjeffrey** [comment]
@hannah-radish can you post the ansi color codes for each of those colors, please?

**Comment by vjeffrey** [comment]
wip: https://github.com/chef/inspec/commit/6f04cdda391154c8c9a43d922b047c9d4146e14b formatting is off. looking into it.

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
