### ISSUE TITLE
Apache_conf should be able to understand configuration sections

### ISSUE THREAD

**Issue by jeremymv2** [inspec/inspec#1374]
### Description

As a secops engineer I should be able to write inspec controls that verify content of Apache's configuration sections so that I can ensure my entire configuration is secure.

Apache's configuration sections: https://httpd.apache.org/docs/current/sections.html

For example: 
```
~/Devel/ChefProject/tmp$ cat /Users/jmiller/Devel/ChefProject/tmp/httpd.conf
<IfDefine ClosedForNow>
    Redirect "/" "http://otherserver.example.com/"
</IfDefine>

<IfModule mod_mime_magic.c>
    MimeMagicFile "conf/magic"
</IfModule>

<Directory "/var/web/dir1">
    Options +Indexes
</Directory>

<Files "private.html">
    Require all denied
</Files>

<LocationMatch "^/private">
    Require all denied
</LocationMatch>
~/Devel/ChefProject/tmp$
```

Currently, everything is flat key/value:
```
inspec> apache_conf('/Users/jmiller/Devel/ChefProject/tmp/httpd.conf').params
=> {"<IfDefine"=>["ClosedForNow>"],
 "Redirect"=>["\"/\" \"http://otherserver.example.com/\""],
 "</IfDefine>"=>[],
 "<IfModule"=>["mod_mime_magic.c>"],
 "MimeMagicFile"=>["\"conf/magic\""],
 "</IfModule>"=>[],
 "<Directory"=>["\"/var/web/dir1\">"],
 "Options"=>["+Indexes"],
 "</Directory>"=>[],
 "<Files"=>["\"private.html\">"],
 "Require"=>["all denied", "all denied"],
 "</Files>"=>[],
 "<LocationMatch"=>["\"^/private\">"],
 "</LocationMatch>"=>[]}
inspec>
```

**Comment by chris-rock** [comment]
Indeed, that would be great!

**Comment by ronykr** [comment]
👍

**Comment by CosminG** [comment]
👍

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
