### ISSUE TITLE
inspec compliance upload profile.zip [feature request]

### ISSUE THREAD

**Issue by username-is-already-taken2** [inspec/inspec#1379]
### Description

Could we have the option to upload profiles in zip format please.

### InSpec and Platform Version

windows 10 inspec 1.8.0

### Replication Case

```
chef exec ruby inspec compliance upload C:\git-repo\inspec\bin\microsoft-windows-server-0.2.0.zip --overwrite
WARN: Unresolved specs during Gem::Specification.reset:
      httpclient (>= 2.2.0.2, ~> 2.2)
      docker-api (~> 1.26)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
I, [2016-12-22T12:05:08.197917 #20448]  INFO -- : Checking profile in C:\git-repo\inspec\bin\microsoft-windows-server-0.2.0.zip
I, [2016-12-22T12:05:08.198869 #20448]  INFO -- : Metadata OK.
I, [2016-12-22T12:05:08.200873 #20448]  INFO -- : Found 3 controls.
I, [2016-12-22T12:05:08.201875 #20448]  INFO -- : Control definitions OK.
Profile is valid
Start upload to gbright/microsoft-windows-server
Uploading to Chef Compliance
Error during profile upload:
"Failed to POST /owners/gbright/compliance/microsoft-windows-server/tar."
```

**Comment by chris-rock** [comment]
This issue may be related to https://github.com/chef/inspec/issues/1378. We should support that option, since all pieces are available in InSpec already.

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
