### ISSUE TITLE
RFC: Allow loading of arbitrary files in InSpec resources.

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#1396]
### Description

InSpec Resources do not allow users to load files via `IO.read(File.dirname(__FILE__))`. Sometimes InSpec resources store meta information in json or xml files to separate data from code. InSpec resources should support loading data from files.

I propose we add an optional `files` directory to our profiles.
```
tree examples/profile
examples/profile
├── README.md
├── controls
│   ├── gordon.rb
│   └── meta.rb
├── inspec.yml
├── files
│   ├── file1.xml
│   └── 2016.09.json
└── libraries
    └── gordon_config.rb
```

Once the directory is available, InSpec resources are allowed to load files via

```
inspec.profile.file('2016.09.json')
# in subdirectories
inspec.profile.file('platforms/amazon/2016.09.json')
```

Alternative options, not preferred by me are:
```
# everything within the profile root can be loaded
inspec.profile.file('files/platforms/amazon/2016.09.json')
```

A simple resource would look like:

```
class GordonConfig < Inspec.resource(1)
  name 'gordon_config'

  def initialize
    content = inspec.profile.file('2016.09.json')
    @params = JSON.parse(content, :symbolize_names => true)
  end

  def [](name)
    @params[name]
  end
end
```

**Comment by arlimus** [comment]
Love the idea, also love that files are gated, i.e. that we don't just expose everything in the profile and provide a nice guideline on the location of these files.

* Would love to expose this in regular `control` files as well; for that to happen, we'd need to expose the `inspec` keyword in the core DSL. This might be a good place to do this and stop the constant workarounds a la `os.inspec` 😁 
* I really like your first option of accessing files, i.e. `inspec.profile.file('platforms/amazon/...')` (instead of `files/...`)

What do you think @adamleff ?

**Comment by adamleff** [comment]
Seems like this would be a handy feature for sure. Agreed with limiting it to the `files` directory only.
