### ISSUE TITLE
user resource is not fetching groups for windows

### ISSUE THREAD

**Issue by pariminaresh** [inspec/inspec#1400]
### Description

Inspec user resource is not fetching groups for windows platform.

### InSpec and windows2012R2

Tell us which version of InSpec : 1.7.2

### Replication Case

1. create a user and add to a group
2.check for inspec test 
describe user('user1') do
  it { should exist }
  its('groups') { should include %r{admins} }
end
3. Inpec test fails with "expected nil to include /admins/, but it does not respond to `include?`"

### Possible Solutions

If you have already ideas how to solve the issue, add them here.

I see ' groups = $null' is getting assigned in the users.rb resource.Need to update this with powershelgl way of getting user groups.

### Stacktrace

∅  groupname should include /admins/
     expected nil to include /admins/, but it does not respond to `include?`

**Comment by chris-rock** [comment]
Indeed, groups are not fetched. See https://github.com/chef/inspec/blob/master/lib/resources/users.rb#L630

Dou you know an easy way to fetch the groups for a user via Powershell?

**Comment by pariminaresh** [comment]
Don't see the actual powershell script is fetching user groups there.But can try out other commands to fetch user groups and parse it as part of 'collect_user_details'.Interested to try out and see.

**Comment by pariminaresh** [comment]
Well, tried with 'net user <name>'.The challenge here is parsing the output and ConvertTo-Json returns a raw string of user info.

 $grs = net user $_.Name[0] | ConvertTo-Json
 groups = $grs

We get unformatted string. but we can check a group existence in user info with something like  user('username').groups.include?('group'). that returns true/false. 

Appreciate any comments :)

**Comment by MichaelStankiewicz** [comment]
@chris-rock There is [Get-LocalGroupMember](https://msdn.microsoft.com/en-us/powershell/reference/5.1/microsoft.powershell.localaccounts/get-localgroupmember).  However, I've encountered [this same error](https://github.com/PowerShell/PowerShell/issues/2996) when trying to use this method myself.

The [CIM workaround](http://jdhitsolutions.com/blog/scripting/2342/query-local-administrators-with-cim/) for this is probably the most ideal, since CIM is faster than the WMI method.

And although there is also good 'ol WMI, as articulated [here](https://gallery.technet.microsoft.com/scriptcenter/List-local-group-members-c25dbcc4), CIM is the better option since it is more efficient and more strategic.

Example:
```
$group = 'Administrators'
$query="Associators of {Win32_Group.Domain='$hostname',Name='$group'} where Role=GroupComponent"
Get-CimInstance -Query $query | Select-Object -Property Name | ConvertTo-Json
```
