### ISSUE TITLE
apache_conf resource does not preserve/merge configuration values across multiple files

### ISSUE THREAD

**Issue by carldjohnston** [inspec/inspec#1408]
### Description

The apache_conf resource does not preserve/merge configuration values correctly when the directives are duplicated across multiple files. The parser only retains the values from the last file parsed.

An example is having multiple LoadModule directives across multiple files (which is a pretty common httpd configuration), one .conf file for each module to load; the parser will only show the 'LoadModule' parameters from the last file parsed (sorted by name).

### InSpec and Platform Version

InSpec 1.7.1 on Oracle and RedHat Linux 7.3 

### Replication Case

This can be easily replicated on a vanilla EL7 install; just install httpd and look for something that exists in the `/etc/httpd/conf.modules.d/00-base.conf` file (first by name):
```
describe apache_conf do
  its('LoadModule') { should include 'alias_module modules/mod_alias.so' }
end
```

### Possible Solutions

I think the issue is with the way that `apache_conf.rb` merges the configuration directives from multiple files; using the `Array.merge!` method which does not preserve existing values for a given key.
https://github.com/chef/inspec/blob/master/lib/resources/apache_conf.rb#L88

I see issues with blindly changing this behavior to retain all values parsed however:
 - We will have parameters with values from all files and sections (for example including a directive within the core config, and also within a VirtualHost section would probably result in multiple values for one parameter)
 - Without representing the configuration like issue #1374 suggests, it would be impossible to determine (and accurately test) where a value was included.
 - Some directives don't allow multiple values and should only be listed once in the configuration [section] (eg DocumentRoot), where others are designed to be listed multiple times (eg AddIcon).

Replacing apache_conf.rb line 88 `@params.merge!(params)` with `@params.merge!(params){ |key,oldval,newval| oldval | newval }` does keep all values, but as I said this might not be desirable.

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
