### ISSUE TITLE
How can we extend inspec exec backends

### ISSUE THREAD

**Issue by pkleanthous-zz** [inspec/inspec#1415]
### Description

How can we add support for more backend methods?
We would like to add support for network devices. Most of them already have a python driver.

Examples:
https://github.com/Juniper/py-junos-eznc
https://github.com/fooelisa/pyiosxr

### InSpec and Platform Version

`inspec version: 1.7.2`

### Replication Case

N/A

### Possible Solutions

Somehow call python libraries from ruby ?

### Stacktrace

N/A

**Comment by chris-rock** [comment]
@pkleanthous Which underlying protocols do both systems use? Are those custom?

**Comment by pkleanthous-zz** [comment]
@chris-rock 
Juniper's library is using their Junos XML API.
IOSXR again is using their XML API.

Also, I tried inspec with some Mikrotik routers, it seems to work with ssh as backend.

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
