### ISSUE TITLE
apt resource should include support for local files

### ISSUE THREAD

**Issue by ghost** [inspec/inspec#1417]
### Description

The apt resource appears to only support files coming form http and https: https://github.com/chef/inspec/blob/master/lib/resources/apt.rb#L74

However a perfectly valid use case is when somebody hosts an apt-repository locally on the Chef node for caching purposes and the location of the apt-repository is file://....

### InSpec and Platform Version

1.7.2

### Possible Solutions

I think it would just be a matter of adjusting the regular expression located here: https://github.com/chef/inspec/blob/master/lib/resources/apt.rb#L74

**Comment by chris-rock** [comment]
@pantocrator27 Great idea. Are you going to adapt the regular expression and to add unit tests?

Unit tests are implemented here: https://github.com/chef/inspec/blob/master/test/unit/resources/apt_test.rb#L10-L14

Mock is reading the simulated file here:
https://github.com/chef/inspec/blob/master/test/helper.rb#L235

Which loads the content from:
https://github.com/chef/inspec/blob/master/test/unit/mock/cmd/etc-apt

You can run the individual unit test for apt via:
`bundle exec ruby -W -Ilib:test test/unit/resources/apt_test.rb`

**Comment by ghost** [comment]
@chris-rock I normally would but at the moment am bandwidth constrained.  Once my time get freed up, I can, unless someone else gets to it earlier ...

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
