### ISSUE TITLE
expose password age in `passwd` resource

### ISSUE THREAD

**Issue by arlimus** [inspec/inspec#1427]
### Description

Tell me how old my passwords are on Linux.

### Possible Solutions

Either add a field or give me docs on how to do it.

**Comment by trumant** [comment]
Should this be on the `passwd` resource or the `users` resource? The user resource already exposes mindays, maxdays and warndays around password expiry by parsing the output of `chage -l user`

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
