### ISSUE TITLE
windows_task fails if multiple triggers

### ISSUE THREAD

**Issue by guilhem** [inspec/inspec#1430]
### Description

`windows_task` fails if there are multiple triggers in a task.

### Replication Case

Just create a task with 2 dummy triggers.
Any test will fail on it because of code wait for a `{ Type: ""... }` and get `[ { Type: "" ....}, { Type: "" ...} ]`

### Possible Solutions

* Use `win32ole` lib instead of a `schtasks.exe` command.
* Test if response is an array and get first (the objects in array are strictly the same)

**Comment by chris-rock** [comment]
@guilhem Can you push a chef example for our integration tests, so that we can use that for testing?

**Comment by kekaichinose** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.

**Comment by clintoncwolfe** [comment]
Re-opening as this is the subject of a current PR

**Comment by clintoncwolfe** [comment]
Nevermind, #3395 is the re-open already. Confused!
