### ISSUE TITLE
cmp matcher should also compare string to single-element array

### ISSUE THREAD

**Issue by artem-sidorenko** [inspec/inspec#1434]
### Description

From the [docs](http://inspec.io/docs/reference/matchers/):

```
Compare arrays with only one entry to a value

describe passwd.uids(0) do
  its('users') { should cmp 'root' }
  its('users') { should cmp ['root'] }
end
```

I have a use case from the other side: `its('HostKey')` of `sshd_resource` might return a string for a single value, or an array for multiple values. My idea was to use `cmp` for comparing array-to-array or string-to-single-element-array, but I get following:

```
 ✖  sshd-14: Server: Specify SSH HostKeys (
     expected: ["/etc/ssh/ssh_host_rsa_key"]
          got: /etc/ssh/ssh_host_rsa_key

     (compared using `cmp` matcher)
```

### InSpec and Platform Version

`1.5.0` on ubuntu 16.04 via rvm

**Comment by chris-rock** [comment]
@artem-sidorenko Agreed, we can implement this in here: https://github.com/chef/inspec/blob/master/lib/matchers/matchers.rb#L296-L302

**Comment by artem-sidorenko** [comment]
I try to have a look if this is still the case. IMHO this is a valid enhancement

**Comment by zenspider** [comment]
I stongly disagree with this ticket. `cmp` is a convenience matcher to help when the user is testing against cmdline output, iow, textual output. That's why it will auto-convert between strings and numbers, for example. It should not go much past that functionality. Converting between higher level types means it is impossible to distinguish between those higher level types.

I'm happy to discuss this further, but I'm closing this for now.
