### ISSUE TITLE
`http` resource cannot access localhost of the target

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#1436]
### Description

The current http resource is executed on the inspec `workstation` where ruby is executed. A simple test like

```
describe http('http://localhost') do
        its('status') { should cmp 200 }
end
```

demonstrates the complexity. It does not matter if I run:

```
$ hostname
inspechost
# run the tests locally
$ inspec exec http_test.rb
# run the tests agains remote target
$ inspec exec http_test.rb -t ssh://root@remotetarget.com
```

The current implementation will always run against `inspechost` and never against `remotetarget.com`. This may lead to confusion, since all other inspec resources are targeting the OS on `remotetarget.com`

### InSpec and Platform Version

1.10.0

### Possible Solutions

```
# rubocop:disable LineLength
if os['family'] == 'windows'
  curl_command = '&{ Invoke-WebRequest http://localhost:8080 } 2>&1 | Out-String'
else
  curl_command = 'curl http://localhost:8080/'
end
# rubocop:enable LineLength

describe command(curl_command) do
  its('stdout') { should match( ... ) }
end
```

This raises a conceptual question. I think, both use cases are valid run http test on that machine and test a machine from outside. We just need to make it more obvious for InSpec users.

**Comment by schisamo** [comment]
This makes me 😢 , hopefully we can implement executing HTTP requests locally on the target node soon.

**Comment by mwrock** [comment]
Agreed that there is a need to test http endpoints on the target machine. I'd love to be able to respond to https://github.com/test-kitchen/test-kitchen/issues/1200 with "yes. Inspec can test a test-kitchen target's HTTP API."

**Comment by aladmit** [comment]
> This raises a conceptual question. I think, both use cases are valid run http test on that machine and test a machine from outside. We just need to make it more obvious for InSpec users.

I think we should add parameter `run: remote/local` and use `remote` by default, because all other resources run on remote host.

Example for remote host:
```
describe http('http://localhost') do
        its('status') { should cmp 200 }
end
```

For local host:
```
describe http('http://localhost', run: :local) do
        its('status') { should cmp 200 }
end
```

**Comment by kcorupe** [comment]
I can agree with expecting different behavior because all other tests run locally. I am using kitchen and attempting to use the http resource and couldn't figure out why it was not working until I found this issue.

I was also hoping to use the same tests in kitchen and remotely. But I'll need to use the curl command as a work around.

**Comment by chris-rock** [comment]
@postgred @kcorupe Thank you for your feedback. I agree that we may should use the curl command / powershell as a default right now (local) until we have a proper concept for the requested remote capabilities. Seems like most of the tests target the local machine. Is that correct?

**Comment by aladmit** [comment]
@chris-rock Yes, that is correct.

**Comment by trickyearlobe** [comment]
Another use case:-  you may want to check a target node can reach some external endpoint, perhaps through a proxy (eg. A machine in an enterprise datacentre that consumes the Twitter REST API through a proxy for sentiment analysis)

**Comment by jerryaldrichiii** [comment]
Quick note about the possible solution @chris-rock mentioned:

I believe `curl` is not available by default on Ubuntu 16.04. Also, the default Bash ins't complied with `/dev/tcp` support, so we can't do `cat /dev/tcp/127.0.0.1/80`.

So we will need to find another way to test a TCP connect on Ubuntu 16.04.

**Comment by jkerry** [comment]
that's going to be tough.  It would be pretty sweet if we should open a temporary SOCKS proxy into the ubuntu box over ssh and send traffic from the local faraday gem but that doesn't seem possible with the train gem.

I'd hate doing it but it might make sense, at the start, to detect if curl is available and to send a skip resource if not windows and no curl. I'm sure community demand would drive how to best respond for ubuntu after that work is done

**Comment by jkerry** [comment]
@jerryaldrichiii netcat is an option but..  not a pretty one

**Comment by guilhem** [comment]
I may be wrong... but best option to me is to create a simple `go` application who can be used as proxy for resources.
Binary is copy on target host, executed with parameter or with an API.

Why _go_? because it works on many systems (Linux/Darwin/NT/Freebsd...) and is statically link avoiding libraries problem.

It's a quite huge change... but I think it's the cleanest solution

**Comment by jerryaldrichiii** [comment]
@jkerry does `netcat` come on both Ubuntu and CentOS by default? I think one has `nc` but the other doesn't.

Not 100% sure though.

@guilhem, I had considered something like that, or a C program that uses kernel socket. That is a huge conceptual change though.

**Comment by adamleff** [comment]
@guilhem that indeed would be the most predictable method, however as @jerryaldrichiii said, that would be a major shift in how we talk about InSpec... we really pride ourselves on not needed to install ANY software on the remote machine in order to successfully scan, and this would be a violation of that design. That's not to say that we wouldn't consider that approach in the future, but we'd need to explore many other options first.

**Comment by jkerry** [comment]
Pretty sure Ubuntu has netcat, not sure on centos. The main problem there is you won't be able to follow http forwards / redirects without a lot of wheel reinvention. I personally prefer the skip if you don't have PowerShell 4+ or have curl in your image approach since the former is already an active assumption for the use of json conversion and the later can be patched in with a layer PR based on a discussion dedicated to doing this right for Ubuntu / curl'less distros

**Comment by adamleff** [comment]
@jkerry I'm with you... I have very little interest in reimplementing an HTTP client by way of netcat commands. :)

My vote is to try for curl or wget, and if it doesn't work, we `skip_resource` that resource with a very clear message as to why, and how to rectify.

**Comment by spkane** [comment]
Another note regarding netcat/nc. CoreOS only ships with `ncat`, which already causes some grief for certain Inspec functionality.

**Comment by jkodroff** [comment]
Is there a preferred workaround for this?  Seems like testing that your target is correctly serving some content or forcing an HTTPS redirect is important to verify.

If there is a preferred workaround, would be good to put this in the docs as well.

**Comment by wesm-outreach** [comment]
I'd love inside-inside testing, but outside-in (current functionality) seems fine. The only problem is that when running in kitchen, I don't have a domain to use, nor do I know the IP address of the remote box. How can those be collected?

**Comment by ghostsquad** [comment]
I'd love inside-inside testing, but outside-in (current functionality) seems fine. The only problem is that when running in kitchen, I don't have a domain to use, nor do I know the IP address of the remote box. How can those be collected?

**Comment by adamleff** [comment]
Hey folks - PR #2209 is open to add the ability for the http resource to properly execute on the scanned target (provided the scanned target has `curl` installed).
