### ISSUE TITLE
Demo unstructured output when using ssh

### ISSUE THREAD

**Issue by 8la** [inspec/inspec#1443]
### Description
When using ssh output is hard to read due to wrong tabbed output

### InSpec and Platform Version

Online Demo 

### Replication Case
Use the demo either on firefox 50.2 or chrome 50.0.2661.86 (64-bit) on Linux (Ubuntu 16.04)

### Possible Solutions

Fix css
![seleccion_005](https://cloud.githubusercontent.com/assets/315194/22421794/edd50f3c-e6e0-11e6-8a03-292e9fc9eddc.png)

**Comment by chris-rock** [comment]
@8la Thank you, yes this is broken.

**Comment by kekaichinose** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
