### ISSUE TITLE
Re-add stability index and minimum inspec version for each resource

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#1447]
### Description

Originally we had the stability index attached to each resource e.g. stable, experimental etc. This is missing in latest docs. Additionally it would be helpful to see the InSpec version when the resource was added.

### InSpec and Platform Version

1.10

**Comment by chris-rock** [comment]
It would be nice to have something like:

```
module Inspec::Resources
  class Bash < Cmd
    name 'bash'
    desc 'Run a command or script in BASH.'
    stability: STABILITY.experimental
    inspec: '1.11.0'

...

    def to_s
      "Bash command #{@raw_command}"
    end
  end
end
```

The definition of states is defined here: https://github.com/chef/inspec/blob/47c6427082d5622b77bb0769229cd8fab9dec62c/docs/README.md#stability-index

The inspec value should be the same as in https://github.com/chef/inspec/blob/master/lib/inspec/metadata.rb#L78-L81

Once this is in code, we should use it to incorporate those values into our documentation

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
