### ISSUE TITLE
Add test case to ensure inspec runs without ruby-dev

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#1453]
### Description

InSpec should not require a dependency on a gem that requires `ruby-dev`. We need to have an integration test for that.

### InSpec and Platform Version

1.11.0

**Comment by yvovandoorn** [comment]
I completely agree with this @chris-rock. Avoiding compilation on a Linux instance is definitely :+1:, but close to a :100: requirement on Solaris. 

Would the integration test be platform family specific (one for debian, rhel, solaris, etc) or can it cover all platforms in one test?

**Comment by arlimus** [comment]
I love the aspiration here :+1: 
Currently, I don't think we can do anything about it, nor in the near future as inspec supports winrm, winrm depends on gssapi, and gssapi on ffi, and ffi requires compilation (since it works with native libraries). Closing this for now as it's not something we intend to pursue (unless anyone has any idea?)
