### ISSUE TITLE
Requesting php_config support

### ISSUE THREAD

**Issue by erenfro** [inspec/inspec#1460]
### Description

ServerSpec supports php_config to validate configuration being set up in a way that may be specific to compliance, even simple things such as timezone being set properly. Use of this serverspec resource could be used during integration testing and continued compliance testing to maintain security and setup of running systems, reporting any potential issues.

**Comment by erenfro** [comment]
Some of my use cases here would be to go over basically every configuration value of the php.ini, insuring certain settings exist and are set a specific way.

For example, date.timezone = America/New_York, a very often important value that needs to be known, verified, and set accordingly, because for some reason PHP can't seem to know this value from the system with accuracy. heh

Per other things, knowing what basically any setting is and can be verified would be ideal. Also, from my understanding, most of the [sections] are pretty much meaningless, so it's just varname.subname = value, that matters.  I could be wrong on this, but I use php cookbook and it's only method for managing configuration values is to add them to the bottom of the file. Which I was not really sure would be accurate.

**Comment by mostafahussein** [comment]
Hello @erenfro ,
Have you tried this [ini](https://www.inspec.io/docs/reference/resources/ini/) resource ?

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
