### ISSUE TITLE
Processes resource fails in certain cases

### ISSUE THREAD

**Issue by LordGaav** [inspec/inspec#1497]
### Description

Trying to use this spec:

```
control "agent-processes" do
    impact 1.0
    title "Testing status of Zabbix Agent processes"
    describe processes('zabbix_agentd') do
        its('users') { should include "zabbix" }
    end
end
```

Fails on certain distributions of Linux.

### InSpec and Platform Version

inspec version 1.11.0. Host OS is Ubuntu 14.04, running Kitchen using dokken. Tested on Guest OS in Dockers: Ubuntu 14.04 and 16.04, CentOS 6 and 7 .

### Replication Case

1. Run a Docker using CentOS 6: `docker run -it --rm centos:6 bash`
2. Run the processes regex from processes.rb: `ps axo label,pid,pcpu,pmem,vsz,rss,tty,stat,start,time,user:32,command`
3. Note that all results are spread across two lines, breaking the matching. There are also spaces in the label.

Example output
```
[root@38ea131e50f3 /]# ps axo label,pid,pcpu,pmem,vsz,rss,tty,stat,start,time,user:32,command
LABEL                             PID %CPU %MEM    VSZ   RSS TT       STAT  STARTED     TIME USER                             COMMAND
docker-default (enforce)
           1  0.0  0.0  11504  2624 ?        Ss   13:32:10 00:00:00 root                             bash
docker-default (enforce)
          13  0.0  0.0  13376  1876 ?        R+   13:32:22 00:00:00 root                             ps axo label,pid,pcpu,pmem,vsz,rss,tty,stat,start,time,user:32,command
```

### Possible Solutions

A new regex was added to add labels on Linux in this commit: https://github.com/chef/inspec/commit/1811eb6666321659ada2a3fde66f4b70e9d102bb#diff-2d97e98326803a2c8b96f252c362f318R50 .

The regex is: 
`^([^ ]+)\s+([^ ]+)\s+([^ ]+)\s+([^ ]+)\s+([^ ]+)\s+([^ ]+)\s+([^ ]+)\s+([^ ]+)\s+(\w{3} \d{2}|\d{2}:\d{2}:\d{2})\s+([^ ]+)\s+([^ ]+)\s+(.*)$`  .

This regex assumes that there are no spaces in the process label, which is not correct in this case.

I see a few options:

1. Remove label support (probably unwanted).
2. Fix the regex to support situations when results are spread across two/multiple lines and there are spaces in the label.
3. Add an option to disable labels.

**Comment by chris-rock** [comment]
@LordGaav Could you pipe the output into a file to see if the newlines are just in terminal due to window width or if they are inside the ps output?

**Comment by LordGaav** [comment]
Both, depending on the OS. I believe on CentOS they are split over two lines, on Ubuntu they are not.

**Comment by aalmenar** [comment]
I can add that this happens also with a simple test also, but only fails on ubuntu 16.04 images on debian images it works ok. (All images are bento images)

sample_spec.rb:
describe processes 'haveged' do
  it { should exist }
end

ps axo label,pid,pcpu,pmem,vsz,rss,tty,stat,start,time,user:32,command output:

LABEL                             PID %CPU %MEM    VSZ   RSS TT       STAT  STARTED     TIME USER                             COMMAND
/usr/sbin/haveged (enforce)     14815  0.0  0.9  14252  4692 ?        Ss   01:16:31 00:00:00 root                             /usr/sbin/haveged --Foreground --verbose=1 -w 1024

but the output of inspec says:

  Processes haveged
     ∅  should exist
     expected Processes haveged to exist

even though the process is running.

From what i see this is due to apparmor, here is included both outputs, reduced to help. One that works (Debian 9), and one that doesnt (Ubuntu 16.04).

[processes.txt](https://github.com/chef/inspec/files/1169309/processes.txt)

**Comment by RayBeaumont** [comment]
InSpec 1.31.1
Ubuntu 16.04
Ruby 2.1.10

On linux `Inspec::Resources::Processes#ps_axo`  uses the command `ps axo label,pid,pcpu,pmem,vsz,rss,tty,stat,start,time,user:32,command` which produces the following line of output for mysql on my server:

```
/usr/sbin/mysqld (enforce)       6357  1.1 15.5 15289236 5129320 ?    Ssl    Jul 21 03:30:13 mysql                            /usr/sbin/mysqld
```

`Inspec::Resources::Processes#ps_axo` defines the following Regex, which is used in `Inspec::Resources::Processes#build_process_list` to filter the process lsting:

```ruby
regex = /^([^ ]+)\s+([^ ]+)\s+([^ ]+)\s+([^ ]+)\s+([^ ]+)\s+([^ ]+)\s+([^ ]+)\s+([^ ]+)\s+(\w{3} \d{2}|\d{2}:\d{2}:\d{2})\s+([^ ]+)\s+([^ ]+)\s+(.*)$/
```
This regex fails to match the process listing because of the **space in the label**.

```ruby
2.1.10 > r = /^([^ ]+)\s+([^ ]+)\s+([^ ]+)\s+([^ ]+)\s+([^ ]+)\s+([^ ]+)\s+([^ ]+)\s+([^ ]+)\s+(\w{3} \d{2}|\d{2}:\d{2}:\d{2})\s+([^ ]+)\s+([^ ]+)\s+(.*)$/
2.1.10 > ps = "/usr/sbin/mysqld (enforce)       6357  1.1 15.5 15289236 5129320 ?    Ssl    Jul 21 03:30:13 mysql                            /usr/sbin/mysqld"
2.1.10 > ps =~ r
 => nil 
```

Remove the space and it matches successfully 

```ruby
2.1.10 > r = /^([^ ]+)\s+([^ ]+)\s+([^ ]+)\s+([^ ]+)\s+([^ ]+)\s+([^ ]+)\s+([^ ]+)\s+([^ ]+)\s+(\w{3} \d{2}|\d{2}:\d{2}:\d{2})\s+([^ ]+)\s+([^ ]+)\s+(.*)$/
2.1.10 > ps = "/usr/sbin/mysqld(enforce)       6357  1.1 15.5 15289236 5129320 ?    Ssl    Jul 21 03:30:13 mysql                            /usr/sbin/mysqld"
2.1.10 > ps =~ r
 => 0 
```

I'm afraid my Regex is not strong enough to contribute a fix.
