### ISSUE TITLE
Inspec login fails

### ISSUE THREAD

**Issue by samsonkolge** [inspec/inspec#1503]
### Description

inspec compliance login fails

### InSpec and Platform Version

inspec -v
1.14.1

### Replication Case
$ inspec compliance login https://chef-compliance --insecure --user='admin' --token='5/_GleTs...-w=='
WARN: Unresolved specs during Gem::Specification.reset:
      multi_json (~> 1.10)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.

API access token stored

Please advise...

**Comment by adamleff** [comment]
@samsonkolge Thanks for your issue, and I'm sorry you're experiencing a problem.

I do not see any evidence of your output that indicates that the login failed. You are receiving a warning because of an unsatisfied gem dependency, but `inspec` indicates that the login was successful.

Since the issue involves one of our commercial offerings (Chef Compliance) and we don't have enough data here to reproduce the issue, I'd like to ask that you contact Chef Support at https://www.chef.io/support/ for further assistance if you are unable to upload compliance profiles to Chef Compliance after this login attempt.

Thank you!
~Adam
