### ISSUE TITLE
warn users not to use native ruby OS calls

### ISSUE THREAD

**Issue by arlimus** [inspec/inspec#1514]
### Description

Users who know Ruby or read some of our previous docs on InSpec (or Chef) may try calls like this one:

```
describe sth do
  only_if { File.exist?('this.file') }
...
```

These will result in different results from local vs remote calls.

### InSpec and Platform Version

all

### Possible Solutions

It'd be great to warn users during

```
inspec check
```

or other inspec calls in case they ever use `File`, `Dir`, or ruby OS detections. We shouldn't strictly prevent this, but at least inform of the pattern and offer the alternative solution

(just for reference, in the example above that'd be:
```
describe sth do
  only_if { file('this.file').exist? }
...
```
)

**Comment by trickyearlobe** [comment]
Actually, this would be a great feature as I get a lot of questions about why people can't upload profiles to Compliance server (they don't get a meaningful error).

It often turns out the profiles are rejected because they made native Ruby calls which work locally when they test, but which Compliance couldn't use in a remote scan.

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
