### ISSUE TITLE
Exporting convenience methods or parameterized examples from profiles

### ISSUE THREAD

**Issue by jayhendren** [inspec/inspec#1522]
I'm investigating moving my team's infrastructure tests from Severspec to Inspec.  One of the features of Serverspec we use quite a lot is [shared examples (which come from RSpec)](https://www.relishapp.com/rspec/rspec-core/docs/example-groups/shared-examples).  Essentially, these are convenience methods with a little bit of RSpec syntactic sugar. For example, we have libraries that define helper shared examples like this:

```
shared_examples 'nrpe_check' do |name, args: nil, matcher: /^OK:/|
  describe command("/usr/lib64/nagios/plugins/check_nrpe -H localhost -4 -t 60 -c check_#{name}#{" -a #{args}" if args}") do
    its(:stdout) { is_expected.to match(matcher) }
  end
end

shared_examples 'firewall_rule' do |source, protocol, port = nil|
  # method snipped for brevity
  describe command('firewall-cmd --direct --get-all-rules') do
    its(:stdout) { is_expected.to match(rule) }
  end
end

monitoring_hosts = [
  '1.2.3.4',
  '5.6.7.8'
]

shared_examples 'monitoring_firewall_rule' do |protocol, port = nil|
  monitoring_hosts.each do |h|
    include_examples 'firewall_rule', h, protocol, port
  end
end
```

Then we can include these tests repeatedly from contingent test suites, like so:

```
it_behaves_like 'monitoring_firewall_rule', 'icmp'
it_behaves_like 'monitoring_firewall_rule', 'tcp', 22

%w(memory ioblock ssh_keys).each do |c|
  it_behaves_like 'nrpe_check', c 
end

it_behaves_like 'nrpe_check', 'icmp_wildcard', args: "'-H 8.8.8.8'", matcher: /^OK -/
```

I've tried to do something similar in Inspec, but I've found this to be rather difficult, or at least not obvious:

* Profiles can be parameterized with attributes, but attributes are global, so controls/profiles can't be included multiple times with different parameters the way shared examples can be above.
* Code in `controls/` and `libraries/` are executed in independent anonymous class contexts, meaning arbitrary method definitions in control or library files are not available outside those contexts. So, for instance, I can't define a method in `libraries/my_helper_methods.rb` and have the method available to contingent profiles (or even to the current profile - the only thing that appears to be exported from libraries files are custom resources).
* This use case doesn't seem to match the intended use case for custom resources. I've found it awkward and difficult to translate shared examples into custom Inspec resources. I'm not testing a new type of thing, just wrapping up a bunch of existing tests into a reusable entity.
* I could export convenience methods as gems, but this adds a whole lot of overhead. Our test suites are private, and we don't have any infrastructure for privately publishing and distributing gems, for instance.

How can I address this use case in Inspec? Is there any way for a profile to export convenience/helper methods? Can a profile be re-run multiple times with different parameters (attributes) each time? Or should this be a feature request for something that Inspec does not yet support?

**Comment by chris-rock** [comment]
@Poohblah If I understood you correctly, the main purpose is to reuse the same tests in different contexts with different parameters. Is that correct?
Are you using the serverspec tests with test-kitchen? If so, can you share your kitchen configuration?

**Comment by jayhendren** [comment]
@chris-rock that's correct. We want to reuse the same tests not only in different contexts with different parameters, but also within the same context multiple times with different parameters each time.

We are indeed currently running our serverspec tests with testkitchen.  I'm not sure which part of our kitchen configuration you're interested in, but all of our cookbooks have a .kitchen.yml similar to this one:

```
---
driver:
  name: vagrant
  require_chef_omnibus: 12.17.44
  customize:
    cpus: 2
    memory: 1024
provisioner:
  name: chef_zero
  cookbook_files_glob: "**/*"
platforms:
- name: cub_rh7
suites:
- name: default
```

**Comment by jayhendren** [comment]
Ok, I figured out a way to do this from native Inspec using a little bit of monkey patching. Not sure if this is "supported" or even desirable, but it seems to work just fine.

In one profile, I created a `libraries/foo.rb` that looks like this:

```
module Foo
  def bar(flavor: 'openjdk', version: '1.8.0')
    describe package("java-#{version}-#{flavor}") do
      it { is_expected.to be_installed } 
    end
  end
end

::Inspec::DSL.include(Foo)
```

Then, in a contingent profile, I wrote a control file that looks like this:

```
bar
bar(flavor: 'oracle')
bar(version: '1.7.0')
```

And when the tests are run on the contingent profile, I get the following output - as you can see, `describe package(...)` is run multiple times with different arguments each time:

```
-----> Starting Kitchen (v1.15.0)
-----> Verifying <default-cub-rh7>...
       Detected alternative framework tests for `inspec`
       Loaded cub_baz::default 

Profile: cub_baz::default (cub_baz::default)
Version: 0.1.0
Target:  ssh://vagrant@127.0.0.1:2222


  System Package
     ✔  java-1.8.0-openjdk should be installed
  System Package
     ✔  java-1.8.0-oracle should be installed
  System Package
     ✔  java-1.7.0-openjdk should be installed


Profile: cub_foo::default (cub_foo::default)
Version: 0.1.0
Target:  ssh://vagrant@127.0.0.1:2222

     No tests executed.

Test Summary: 3 successful, 0 failures, 0 skipped
       Finished verifying <default-cub-rh7> (0m3.55s).
-----> Kitchen is finished. (0m4.04s)
```

**Comment by chris-rock** [comment]
@Poohblah That looks a little bit complicated and I do not encourage you to use monkey patching, since we may change our internal api at any time.

Wouldn't a simple loop work in your case?

```
packages = ['java-1.8.0-openjdk', 'java-1.8.0-oracle', 'java-1.7.0-openjdk']
packages.each { |pkg|
  describe package(pkg) do
     it { is_expected.to be_installed } 
  end
}
```

If you want to abstract the java pkg name generation, you could do the following:


```
# libraries/java
class Docker < Inspec.resource(1)
  name 'java'

  def pkg_name(flavor: 'openjdk', version: '1.8.0')
     "java-#{version}-#{flavor}"
  end
...
end
```

This allows you to write
```
[
  java.pkg_name,
  java.pkg_name(flavor: 'oracle'),
  java.pkg_name(version: '1.7.0')
].each { |pkg|
  describe package(pkg) do
     it { is_expected.to be_installed } 
  end
}
```

We use a mixed approach of describe and resources in https://github.com/dev-sec/ssh-baseline, too. InSpec resources are used to determine the os-specific values. https://github.com/dev-sec/ssh-baseline/blob/master/libraries/ssh_crypto.rb#L124-L175

```
describe ssh_config do
   its('MACs') { should eq(ssh_crypto.valid_macs) }
end
```

Is that solving your problem? Also with test-kitchen, you can run multiple inspec test. We are not limited to the specific suite anymore:
```
   verifier:
      inspec_tests:
        - path: test/integration/tests1
        - path: test/integration/tests2
```
See https://github.com/chef/kitchen-inspec#use-attributes-with-your-inspec-profiles or https://github.com/sous-chefs/apache2/blob/master/.kitchen.yml#L56-L84

**Comment by jayhendren** [comment]
@chris-rock I really appreciate you taking your time to help me with this issue, however I believe you are missing the forest for the trees.

The solutions you gave address the specific Java example I gave, but not the problem in general:

> Wouldn't a simple loop work in your case?

> If you want to abstract the java pkg name generation, you could do the following:

In reality, the Java test that we have actually looks like this:

```
describe package("java-#{version}-#{flavor}") do
  it { is_expected.to be_installed }
end

describe command('echo $JAVA_HOME') do
  its(:stdout) { is_expected.to match %r{\/usr\/lib\/jvm\/java} }
end

describe command('readlink $(which java)') do
  its(:stdout) { is_expected.to match %r{^\/etc\/alternatives\/java$} }
end

if default_system_java
  describe command('readlink -f $(which java)') do
    re = %r{#{Regexp.escape("/usr/lib/jvm/java-#{version}-#{flavor}")}[^\/]*\/bin\/java}
    its(:stdout) { is_expected.to match re }
  end
end

describe command('alternatives --display java') do
  its(:stdout) { is_expected.to match %r{^java - status is auto\.$} }
  its(:stdout) do
    is_expected.to match(
      %r{^ link currently points to \/usr\/lib\/jvm\/java\/bin\/java$},
    )
  end
end
```

Since we have many cookbooks that depend on Java, I would like to run Java tests in my test suites for those cookbooks, and I don't want to have to re-write this series of tests in every single one of those suites.  _I want these tests abstracted away_.  Moreover, I have some cookbooks that install multiple Javas simultaneously, so I need a way to run these tests multiple times in one test suite with different parameters each time, which _rules out Inspec profiles as an option_.  Finally, a series of tests like this is _difficult to write as an Inspec custom resource_, since custom resources don't support composing tests out of existing resources.

In addition to the Java example, take a look at the `shared_examples` definitions I gave in my original post.  Can those be rewritten as some kind of existing Inspec construct?  I don't believe they can be, at least not in a natural and straightforward way.

**Comment by jayhendren** [comment]
@chris-rock after looking through some of the other issues posted to this project, I believe this is quite similar to https://github.com/chef/kitchen-inspec/issues/25 and https://github.com/chef/inspec/issues/338.  I'll leave it up to you to decide whether or not to close this as a duplicate of those, but it is fine with me if you would like to close this issue as a duplicate. :)

**Comment by chris-rock** [comment]
@Poohblah Thank you for your extensive feedback. 

I see your point. If you want to run the same tests (without different parameters) in multiple test suites, I recommend to go with profile inheritance. This is explained in more detail here: http://lollyrock.com/articles/chef-compliance-meta-profiles/ and http://inspec.io/docs/reference/profiles/ Based on that concept, you write reusable tests in a InSpec profile (eg. Java InSpec profile) and reference this profile from a new profile (see https://github.com/chris-rock/acme-inspec-profile and https://github.com/chris-rock/acme-inspec-profile/blob/master/inspec.yml#L9-L19). If you want to abstract from parsing `command` output, I recommend to write custom InSpec resources (see http://inspec.io/docs/reference/dsl_resource/). Right now, we have been able to map everything to the two concepts of `profile inheritance` and `custom resources`. Do you see more use cases that cannot mapped on those two concepts?

Nevertheless, I think a `java` resource could be very handy for InSpec.

**Comment by Poohblah** [comment]
I've already explained why Inspec profiles don't work for this use case:

> Profiles can be parameterized with attributes, but attributes are global, so controls/profiles can't be included multiple times with different parameters the way shared examples can be above.

> Moreover, I have some cookbooks that install multiple Javas simultaneously, so I need a way to run these tests multiple times in one test suite with different parameters each time, which rules out Inspec profiles as an option.

**Comment by chris-rock** [comment]
@Poohblah Just saw you deleted a comment. Would love to help you more, but without seeing the code and working on a specific example it is very difficult to solve your problem. Let me know if you could share that somehow.

**Comment by jayhendren** [comment]
The deleted comment was because I wrote a reply to your most recent post and then realized I had misread your post.

I am not sure what more you want from me in terms of examples.  I have already provided several examples in this issue: https://github.com/chef/inspec/issues/1522#issue-210883532 https://github.com/chef/inspec/issues/1522#issuecomment-283161316

**Comment by adamleff** [comment]
@chris-rock since you've led the conversation on this one, I'm assigning this issue to you to decide how best to proceed. Thanks!

**Comment by majormoses** [comment]
I'd also very much like to see `shared_examples` implemented, its a standard `rspec` construct which both `serverspec` and `inspec` are based on. The more standard `rspec`things we support the easier it is to get someone else to write a test for it. Not everyone spends all their day in chef and app developers who know rspec should be able to pick this up quickly. I think a very clear example would say you are wanting to write integration tests for elasitcsearch. Say you want to have a suite for `master`, `data`, and `client` each as they have very different testing but have a common set of things that you would want to test. Rather than creating something more complex like a profile a `shared_example` does exactly what we want.

For example we want to make sure that regardless of the suite that it is alive:
```ruby
# in helpers/shared_spec.rb
shared_examples 'elasticsearch::alive' do
  describe 'elasticsearch service' do
    # the service should run
    it 'should enable and start the elasticsearch service' do
      expect(service('elasticsearch')).to be_enabled
      expect(service('elasticsearch')).to be_running
    end
  end

  describe user('elasticsearch') do
    it { should exist }
    it { should belong_to_group 'elasticsearch' }
  end

  describe command('which java') do
    its(:exit_status) { should eq 0 }
  end

  describe command('java -version') do
    its(:stderr) { should include '1.8' }
  end

  describe file('/etc/elasticsearch/log4j2.properties') do
    its(:content) { should match(/logger.action.level = warn/) }
    its(:content) { should match(/logger.deprecation.level = warn/) }
    its(:content) { should match(/logger.amazonaws.level = error/) }
    its(:content) { should match(/logger.gateway.level = warn/) }
    its(:content) { should match(/logger.indexgateway.level = warn/) }
    its(:content) { should match(/logger.indicesrecovery.level = warn/) }
    its(:content) { should match(/logger.discovery.level = warn/) }
    its(:content) { should match(/logger.index_search_slowlog_rolling.level = info/) }
    its(:content) { should match(/logger.index_indexing_slowlog_rolling.level = info/) }
  end

  describe 'Log file /var/log/elasticsearch/es5-app.log' do
    it 'Content should have INFO logging' do
      expect(file('/var/log/elasticsearch/es5-app.log').content).to match(/INFO/)
    end
  end

  # Deal with ES lagging startup time
  version_regex = /number\"\ \:\ \"5\./

  require 'net/http'
  ip = getipaddress
  attempt_num = 1
  retry_num = 6
  url = "http://#{ip}:9200"
  uri = URI.parse(url)

  begin
    Net::HTTP.get_response(uri)
    puts "Elasticsearch at '#{url}' is successfully initialized"
  rescue StandardError => e
    puts "Attempt #{attempt_num}/#{retry_num} to connect to #{url} failed: #{e.message}"
    if attempt_num == retry_num
      raise e, "Failed to connect to #{url}: #{e.message}"
    end
    attempt_num += 1
    sleep 15
    retry
  end

  describe command("curl #{ip}:9200") do
    its(:stdout) { should match version_regex }
  end

  describe 'it should have plugins installed' do
    describe command('/usr/share/elasticsearch/bin/elasticsearch-plugin list') do
      its(:stdout) { should match(/discovery-ec2/) }
      its(:stdout) { should match(/repository-s3/) }
    end
  end
end


# in one of the three suites
require 'shared_spec.rb'
describe 'elasticsearch data node' do
  it_should_behave_like 'elasticsearch::alive'
end
# more data specific tests
```

**Comment by parameshdsn** [comment]
I need DIsks to be present with drive letters and formatting in windows servers

**Comment by parameshdsn** [comment]
Hi @chris-rock, We are automating our infrastructure using ansible. We want to validate all the automation using inspec. For the same i am getting trouble to find the inspec test cases for them.  I am stuck with the Database inspec test cases
==> verify the user of the SQL services is C2WTS service account.
==> Unable to validate the databases in sql server.
==> Testing specific database users and roles.
Please let me know if any refereneces.
Thank you in advance.

**Comment by jayhendren** [comment]
@parameshdsn I think you need to open a new, separate issue.  This issue is a feature request for something similar to Rspec's `shared_examples` feature.

**Comment by chris-rock** [comment]
@majormoses Thank you for your feedback. I understand your intention and the idea to use shared tests no matter if you are testing a elastic search master or client. 

We are not supporting the RSpec approach, because we think this is too complex and difficult to read. The syntax makes it very difficult for non-Ruby developers to understand the behavior. We aim to keep the controls and test description as simple as possible, so that everybody understands by reading the test what the expected outcome is.

That said, InSpec provides a lot of capabilities to implement your needs and at this point I do not fully understand why your needs cannot be implement with current InSpec capabilities. This is how I would tackle your requirement:
- create an InSpec profile https://www.inspec.io/docs/reference/profiles/
- create different test files for `master.rb`, `client.rb` and `generic.rb` in the controls `directory`
- place all tests that apply to both master and client into generic.rb
- place all specific tests into `master.rb` or `client.rb`
- use our `only_if` capability to run tests only if required https://www.inspec.io/docs/reference/dsl_inspec/#exclude-specific-test
- if you need shared code, use an InSpec resource and abstract the the testing there https://www.inspec.io/docs/reference/dsl_resource/
- put all variable settings are becoming InSpec attributes

**Comment by chris-rock** [comment]
@parameshdsn I agree with @Poohblah that this should be a separate issue. Please state the error that you face in that issue too.

**Comment by majormoses** [comment]
> We are not supporting the RSpec approach, because we think this is too complex and difficult to read. The syntax makes it very difficult for non-Ruby developers to understand the behavior.

Playing devils advocate here: profiles are more difficult for non chef folks than a shared example. This creates a further wall between app developers and infra developers. From my experiences in order to really leverage chef you need some basic ruby skills, pretending you don't is a fallacy. I am all for making it easier for people who don't want to learn a lot of ruby but not at the cost of those that want to properly leverage it. I realize that `inspec` can be used outside of the context of chef and I'd like to move all the sensu plugin testing from `serverspec` to `inspec` but without shared examples that is a non starter because I am not gonna push people using inspec profiles for ~200 projects unrelated to chef. I probably _can_ do it with profiles but I also do not want to have to teach ~100 app developers how to use profiles when they already know how to use a `shared_examples`. Honestly its more effort than defining a shared example, you had to outline a bulleted list when using a `shared_examples` you write the example and leverage it, that seems more easy to use than a profile. According to the docs `inspec` is meant to be a drop in replacement for `serverspec`. I think you either need to live by your messaging or change it.

**Comment by majormoses** [comment]
I think I am gonna go more the more custom resource route for my chef projects over profiles if `shared_examples` will not be implemented as I think its a more natural replacement for `shared_examples` than profiles but again I question this making it easier.

**Comment by jayhendren** [comment]
@majormoses I thought about doing the custom resource approach as well - the issue I ran into was that existing matchers/resources are not available from within custom resources, and I was hoping to do something along the lines of creating reusable test libraries out of existing matchers, which is exactly what `shared_examples` is good for.

**Comment by majormoses** [comment]
@Poohblah Gotcha thanks for the heads up as I am sure I would have run into that. It just feels wrong to have to define it as a lib function but thats clearly the best path forward unless the maintainers change their mind.

@chris-rock I think this is a perfect example of why you can't stop people from doing smart things and attempting to preventing them has only decreased the readability further. Instead of just supporting a standard construct and someone does not know what `shared_examples` does a search in their favorite search engine it has the answers the need. Instead now they are gonna have to track it down ins some custom library. From a search on Google the entire first page is relevant, I did not specify ruby, rspec, or anything else to help me refine the answers.

**Comment by majormoses** [comment]
Can I propose adding it as `inspec/shared-examples` or something that is not included by default and then those that want to use it can just `require 'inspec/shared-examples'` in their tests.

**Comment by huynt1979** [comment]
I'm not an expert in Inspec but imho the lacking of a straightforward mechanism to write reusable & parameterized tests seems to defeat the purpose of making Inspec 'simple'. While I do believe custom resources in general can solve this, it can not be compared with serverspec's `shared_example` in terms of simplicity and ease of use.

Our use case for leveraging serverspec's  `shared_example` is very similar to that of @Poohblah and works great. Would really love to see if Inspec can offer something similar or even better.

**Comment by metmajer** [comment]
@huynt1979 really brings it to the point. This is one in a series of design decisions that make me a little uneasy about InSpec. Here's another example: with `awspec`, we were able to access a resource's underlying AWS SDK resource instance to have access to raw properties via, e.g., `its('resource.vpc.id')`. With InSpec, the accessor to the resource instance is `private` (see #3438), which forces us to make heavy use of the AWS SDK together with InSpec.

Alan Kay said: "Simple things should be simple, complex things should be possible." In my opinion, writing tests with InSpec is not as simple as it could be. This makes it hard to get people write these tests and get buy-in from management. It would be great if your team could borrow some of the simple design we're used to from `serverspec` a `awspec`.

**Comment by clintoncwolfe** [comment]
Refs #3476

**Comment by miah** [comment]
I think much of this is handled by our updated Inputs system. 

ref: https://github.com/inspec/inspec/pull/3875
