### ISSUE TITLE
should access hash keys using strings when testing options in INI files

### ISSUE THREAD

**Issue by shoekstra** [inspec/inspec#1543]
When testing an INI style config file you cannot specify the hash key as a string, for example if you have a file:

```
[mysqld]
log_bin = /var/log/mysql/mariadb-bin
sync_binlog = 0
```

You currently write a test like this:

```
describe mysql_conf('/tmp/my.cnf').mysqld do
  its(['sync_binlog']) { should eq '0' }
end
```

We should be able to access config options/parameters using strings, e.g.:

```
describe mysql_conf('/tmp/my.cnf').mysqld do
  its('sync_binlog') { should eq '0' }
end
```

**Comment by adamleff** [comment]
@shoekstra because of our use of `rspec-its` our ability to accept strings when hierarchy or dots are involved is rather limited.

To remain consistent across all resources that have this type of experience, the recommended way to do what you've described it:

```
describe mysql_conf('/tmp/my.cnf') do
  its(['mysqld', 'sync_binlog']) { should eq '0' }
end
```

Should we move away from RSpec as the engine in the future, our options may open up. But for now, that is the supported way to access those values.

Thanks for submitting this issue - and my apologies for the delay in our response!
