### ISSUE TITLE
Inspec profile attributes are not inheritable/composable

### ISSUE THREAD

**Issue by jayhendren** [inspec/inspec#1545]
I believe Inspec attributes should be inheritable in the same way that Chef attributes are inheritable and for the same reasons. An Inspec profile contains controls, resources, and attributes in much the same way that Chef cookbooks contain recipes, resources (LWRPs and HWRPs), and attributes.  It seems strange to me that Chef cookbooks inherit all three types of entities from their dependencies while Inspec profiles inherit everything from their dependencies except attributes. This makes it cumbersome to compose tests out of controls defined in dependencies when those controls rely on Inspec attributes to determine their behavior.

**Comment by adamleff** [comment]
@Poohblah Thanks for your feature request. I'm not sure how doable this will be since attributes are an item passed in at runtime and not really defined or set in the profile itself - they're just evaluated. Therefore, you can pass in a single attributes file with the `--attrs` CLI flag and any profile run during that InSpec run would have access to it.

Could you describe a more specific use case?

**Comment by jayhendren** [comment]
Sure.

We have a bunch of Chef cookbooks we've written that set up individual services per our org's needs - Apache, MySQL, PHP, etc.  Those cookbooks have integration tests bundled with them. 

We also have cookbooks that tie together multiple services - for instance, a LAMP cookbook, which includes the Apache, MySQL, and PHP cookbooks.  These also have integration tests bundled with them, and the integration tests are composed from the integration tests exported by the Apache, PHP, and MySQL cookbooks.  However, the LAMP cookbook alters the default behavior of all of those cookbooks in order to ensure that those services work properly together - therefore, the LAMP cookbook needs to alter the default behavior of the tests it exports, too.

Finally, we have policy cookbooks, which define a complete set of services applied to a node by composing service cookbooks described above.  Following the pattern, we also compose tests for our policy cookbooks out of the tests for our services cookbooks.  When those service cookbooks include things like the LAMP cookbook mentioned above, we want to inherit exactly the tests defined by the LAMP cookbook, which would include attributes, parameters, or anything along those lines.

Currently, we are using Serverspec tests and have looked into replacing them with Inspec.  Since Serverspec supports native RSpec, we have been using RSpec's `shared_examples` feature to support composable tests.  For example:

```
shared_examples 'apache' do |modules: []|
  describe(package('httpd')) { it { is_expected.to be_installed } }
  describe(service('httpd')) { it { is_expected.to be_running } }
  modules.each { |m| describe(package(m)) { it { is_expected.to be_installed } } }
  # etc.
end
```
```
shared_examples 'php' do
  describe(package('php')) { it { is_expected.to be_installed } }
  # etc.
end
```
```
shared_examples 'mysql' do
  describe(package('mysql')) { it { is_expected.to be_installed } }
  describe(service('mysql')) { it { is_expected.to be_running } }
  # etc.
end
```
```
shared_examples 'lamp' do
  # in addition to the default behavior for the httpd cookbook, the lamp cookbook also
  # instructs the httpd cookbook to install and configure the mod_php and mod_ssl modules
  include_examples 'httpd', modules: %w(mod_php mod_ssl)
  include_examples 'php'
  include_examples 'mysql'
  # possibly some other tests depending on the details of the lamp cookbook
end
```
```
describe 'my_awesome_policy' do
  # my_awesome_policy installs a lamp stack and does some other stuff too
  include_examples 'lamp'
  # ^^^ I want this to also run the tests for the mod_php and mod_ssl additions made by the
  # lamp cookbook tests! RSpec's include_examples does what I want in this case, but I can't
  # figure out how to get Inspec to do something similar.
  include_examples 'some_other_cookbook'
  # etc.
end

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
