### ISSUE TITLE
LVM resource

### ISSUE THREAD

**Issue by nvtkaszpir** [inspec/inspec#1554]
### Description

I'd like to be able to parse LVM related data.
This is a placeholder for future improvements.

### InSpec and Platform Version

N/A

### Replication Case

N/A

### Possible Solutions

Use custom parameter parser with lvs/pvs/vgs commands with custom formatting: https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/Logical_Volume_Manager_Administration/custom_report.html

There's option to load it output with json format, which looks like a 'good enough' for now.

### Stacktrace

N/A

**Comment by aaronlippold** [comment]
👍 I would also agree with this, we would also be able to support OS X as well I think.

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
