### ISSUE TITLE
Add Regular Expression Support to Service Resource

### ISSUE THREAD

**Issue by tylerkron** [inspec/inspec#1556]
### Description

It would be beneficial if the service resource could take in as input a regular expression.  An example use case is looking for an Oracle TNS Listener service.  The oracle database name can change but the TNS Listener service is guaranteed to have "TNSListener" at the end of its name (i.e. OracleOraDB12home1TNSListener).

A good example is the package resource which currently accepts regex:
```
describe packages(/xserver-xorg.*/) do
   its('entries') { should be_empty }
end
```

### Possible Solutions

The tricky part here might be supporting the multiple operating systems.  I currently am on Windows.  The service resource leverages powershell and the command "Get-Service".

**Comment by adamleff** [comment]
If we alter the `service` resource to use FilterTable, we'd get the `where` accessor for free which would allow filtering like this. Seems like a good feature to have. Flagging as a feature request.

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
