### ISSUE TITLE
gem resource needs support for different ruby environments

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#1568]
### Description

As reported by @howdoicomputer in https://github.com/chef/kitchen-inspec/issues/107

```
  gem package
     ✖  kitchen-ec2 should be installed
     expected that `gem package kitchen-ec2` is installed
```

```
vagrant@default-ubuntu-1604:/etc/systemd/system$ gem list -i kitchen-ec2
true
```

```
vagrant@default-ubuntu-1604:/etc/systemd/system$ which gem
/opt/chefdk/embedded/bin/gem
```

### InSpec and Platform Version

latest

### Possible Solutions

Mitigation:
```
describe bash('/opt/chefdk/embedded/bin/gem list -i kitchen-ec2') do
  its('exit_status') { should eq 0 }
end
```

We need to be able to overwrite the path of the ruby environment that we want to check. Since ChefDK overwrites the path in your shell, that may only be valid in user shell, but not all ruby environments

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
