### ISSUE TITLE
command('diff') fails on Windows

### ISSUE THREAD

**Issue by grv87** [inspec/inspec#1577]
Problem with command('diff') resource on Windows.

InSpec version: 1.16.1
Platform: Windows 7 SP1, Windows 8 SP1

Replication case: https://gist.github.com/grv87/afcbd158686c81893a3ea0731248cab2

Output on Ubuntu - everything's OK:
```
Profile: Inspec Diff (inspec_diff)
Version: 1.0.0
Target:  ssh://ubuntu@localhost:2222

  [PASS]  commands: Command diff should exist; Command diff --version stdout sho...
     [PASS]  Command diff should exist
     [PASS]  Command diff --version stdout should match /^diff \(GNU diffutils\)/

Profile Summary: 1 successful, 0 failures, 0 skipped
Test Summary: 2 successful, 0 failures, 0 skipped
```

On Windows, firstly, I get the folowing question:
```
Supply values for the following parameters:
DifferenceObject[0]:
```
After pressing Enter test fails:
```
Profile: Inspec Diff (inspec_diff)
Version: 1.0.0
Target:  local://

  [CRIT]  commands: Command diff should exist; Command diff --version stdout sho... (1 failed)
     [PASS]  Command diff should exist
     [FAIL]  Command diff --version stdout should match /^diff \(GNU diffutils\)/
     expected "\r\nInputObject                                                                                     ...
     \r\n\r\n\r\n" to match /^diff \(GNU diffutils\)/
     Diff:
     @@ -1,2 +1,7 @@
     -/^diff \(GNU diffutils\)/
     +
     +InputObject                                                                                         SideIndicator

     +-----------                                                                                         -------------

     +--version                                                                                           <=

     +
     +
```

As far as I can say the problem is with `diff` command only. All other my cross-platform tests are passed.

**Comment by adamleff** [comment]
@grv87 Thank you for submitting this issue.

From my initial look at this, it's actually functioning as I would expect. On Windows, the `should exist` check succeeds, but the output from the `diff` command doesn't match what you specified in your control. That's because it's finding the Windows `diff` powershell command on your Windows machine and not the GNU version.

So my suggestion would be to either remove the stdout contents check, or break that out into a separate control that you can use an `only_if` for to ensure it doesn't run on Windows.

Does this answer your question/concern?

**Comment by grv87** [comment]
No, it doesn't.

I expect that command resource would check the command in the system, not in the specific implementation of test framework. The goal for me is to check that environment has all required tools, versions etc. So that it could be used to run builds. These builds would be run without PowerShell or inspec.

If there is a need to test the command of PowerShell, it could be tested with command(`powershell diff`) or something like that.

Is there a way to test pure system without side effects from test framework?

**Comment by adamleff** [comment]
@grv87 InSpec operates by interacting with the shell on the target system. In the case of Windows systems, that shell is obviously going to be PowerShell. The reason InSpec approaches testing in this manner is to eliminate any need to install software on remote targets in order to effectively test and report the compliance of that target.

That does mean that when you execute raw commands and test their output, such as with `command('diff')`, you are going to be testing in the scope of the shell that InSpec has used to gain access and insight into that system. This is actually no different than testing on a linux or *nix based machine... InSpec logs into the host as a given user, and the shell of that user is used to perform the tests.

If your builds on Windows are not going to use powershell, but you wish to see that the GNU diff utility is installed, you will need to execute a different command to determine whether the command is installed. This could be a similar situation on a Linux machine if you were testing via inSpec as "user1" which used bash, but "user2" was doing the builds and their default shell was ksh with a completely different `$PATH` set.

If the existing `command` resource doesn't provide you the ability to do so, you may need to author your own custom resource which you can include in your profile that performs the necessary steps to give you the output you're looking for.

There are no plans to use something other than PowerShell to perform the scans on Windows nodes.

**Comment by grv87** [comment]
I propose this behavior (for Windows):
If the specified command doesn't have an extension then try extensions from PATHEXT environment variable. If something is found in the current directory or in the PATH then use it.
If nothing is found then go with the current behavior.

**Comment by grv87** [comment]
Another solution is to always specify file extension in command resource on Windows.
This could be noted in the documentation.

But that would make cross-platform tests awkward.

**Comment by adamleff** [comment]
I'm not particularly a fan of either of these solutions. The first behavior change suggestion, which it makes the behavior of InSpec very explicit, would be a different behavior than what is done today and would not necessarily be backward compatible. In addition, it adds additional logic when running commands that are not matched on other operating systems. If we were to adopt this, it would have to wait until a InSpec v2.x release. I'm still not sure it's necessariy.

The second suggestion makes cross-platform tests even further awkward as you described.

Given the scope of this issue is isolated to those targets where a shell built-in command could share the same name as a user-provided / package-provided command, I do not believe modifying core InSpec to account for this behavior is warranted. I'd recommend adapting the profile with `only_if` statements or providing your own resource that implements one of the suggestions you already provided. If there is more feedback from the community that this is a pain point, we can certainly revisit this issue.

@chris-rock / @arlimus, feedback requested on this issue, please.

**Comment by grv87** [comment]
OK, I got you.
I agree that this would be a breaking change and couldn't be implemented before 2.x.

I don't want to write platform-specific tests in any way (with the choice of extension or with `only_if`), so I'll write my own resource implementing search with extension.

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
