### ISSUE TITLE
inspec fails to install on centos 7

### ISSUE THREAD

**Issue by anandchida** [inspec/inspec#1597]
### Description

Briefly describe the issue and the expected behavior
```
# gem install inspec   
```
above command fails on centos 7 with
```
ERROR:  Error installing inspec:
	nokogiri requires Ruby version >= 2.1.0.
```

### InSpec and Platform Version
```
Linux localhost.localdomain 3.10.0-514.10.2.el7.x86_64 #1 SMP Fri Mar 3 00:04:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
Ruby version on centos 7 is 
```
ruby 2.0.0p648 (2015-12-16) [x86_64-linux]
```
centos 7 instance is up-to-date

**Comment by adamleff** [comment]
@anandchida thanks for submitting this issue. You will need to update your Ruby version to at least 2.1 because of the nokogiri dependency. Ruby 2.0 is end-of-support (as of Feb 2016). Ruby 2.1 is still in maintenance but only for security updates.

I will put forth a change to require Ruby 2.1 for InSpec for the rest of the maintainers to review. Sorry for the inconvenience.
