### ISSUE TITLE
Support method arguments in 'its' assertions

### ISSUE THREAD

**Issue by chris-redekop** [inspec/inspec#1606]
### Description

Please add the ability to pass arguments to the method call in an `its` assertion.  Something like
```ruby
describe my_resource('id') do
    its('method(argument)') { should be > 0 }
end
```
 
### InSpec and Platform Version

InSpec 1.10.0 on Ubuntu Linux.

### Possible Solutions

The **README** at https://github.com/rspec/rspec-its describes support for "metadata parameters".  I understand (from my **Gemfile.lock**) that InSpec depends on rspec-its, so I'm don't understand why this method-parameter behaviour does not come through.

Issues like https://github.com/rspec/rspec-core/issues/553 and https://github.com/rspec/rspec-core/issues/786 describe the desired behaviour.

**Comment by chris-rock** [comment]
@chris-redekop I agree that we need to find a better way. RSpec its is a complex thing and we need to be very careful with that. For now, I recommend to do the following:

```
describe my_resource('id').method(argument) do
    it { should be > 0 }
end
```

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
