### ISSUE TITLE
NGINIX Resource

### ISSUE THREAD

**Issue by aaronlippold** [inspec/inspec#1615]
### Description

I would like to request that we look at creating an NGINIX resource that mirrors the apache and httpd_conf resources. I will be doing work with NGINIX soon. 

### InSpec and Platform Version

All

**Comment by aaronlippold** [comment]
@chris-rock @arlimus Any updates on this enhancement? I will be starting my work with the NGINIX team soon - i.e. within the next week or so. Thanks. Aaron

**Comment by atomic111** [comment]
i need the nginx resource too. because i implemented a nginx baseline with regex stuff. but such a resource makes life easier

**Comment by aaronlippold** [comment]
@atomic111 Cool as a start can we just steal from the libs here? https://github.com/dev-sec/nginx-baseline to create the resource?

**Comment by atomic111** [comment]
@aaronlippold i agree with you. i need to push some additions to the dev-sec repo

**Comment by aaronlippold** [comment]
Great. Go ahead and either push a branch with the resource or add me to
your repo and I'm happy to help.

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
