### ISSUE TITLE
Resource "command" does not find command `cd`

### ISSUE THREAD

**Issue by starx** [inspec/inspec#1625]
### Description

When you describe a command to change directory and run a command, for example:

```
describe command "cd /tmp && echo 'foo'" do
	its('exit_status') { should eq 0 }
	its('stdout') { should match (/foo/) }
	its('stderr') { should match (/foo/) }
end
```
Outputs the following during `kitchen verify`

```
  Command cd
     ∅  /tmp && echo 'foo' exit_status should eq 0

     expected: 0
          got: 1

     (compared using ==)

     ∅  /tmp && echo 'foo' stdout should match /foo/
     expected "" to match /foo/
     Diff:
     @@ -1,2 +1,2 @@
     -/foo/
     +""

     ∅  /tmp && echo 'foo' stderr should match /foo/
     expected "sudo: cd: command not found\n" to match /foo/
     Diff:
     @@ -1,2 +1,2 @@
     -/foo/
     +sudo: cd: command not found

```

Running the same from inspec shell also gives the same result:

```
inspec> command("cd /tmp && echo 'foo'").stdout
=> ""
inspec> command("cd /tmp && echo 'foo'").stderr
=> "sudo: cd: command not found\n"
it outputs
inspec> command("cd /tmp && echo 'foo'").stdout
=> ""
inspec> command("cd /tmp && echo 'foo'").stderr
=> "sudo: cd: command not found\n"
```

### InSpec and Platform Version

Inspec version: 1.11.0
Guest os: Ubuntu 16.04
Workstation: Windows 10 MingW64
Guest driver: vagrant

**Comment by chris-rock** [comment]
Thank you @starx for reporting this issue. A workaround is the use of the `bash` resource.

**Comment by kekaichinose** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
