### ISSUE TITLE
User experience with inheritance / long control names

### ISSUE THREAD

**Issue by aaronlippold** [inspec/inspec#1633]
@chris-rock @arlimus @asturtevant
### Description

I am hoping we can find a way to make inheritance and 'Organizational Overlays' of meta-profiles easier. One of the challenges is that, epically on the windows side, the published content (xccdf/oval) uses very long and descriptive titles which makes our control names unreasonably long. Another factor is the difference in construction of controls between InSpec and OVAL/XCCDF.

What we are really trying to accomplish is just to over-ride some of the metadata in many of the standard CIS controls but we very rarely change the test or want to change it. 

The structure we will have is:
```
ORG_Infosec_Profile
  - CIS_CHECKS
    - ADDED ORG METADATA
  - ORG CREATED Controls
  - Other inherited controls/profiles ( *optional )
```

### Example
```include_controls 'cis-windows2012r2-level1-memberserver' do
  control "xccdf_org.cisecurity.benchmarks_rule_18.3.3_L1_Ensure_MSS_DisableIPSourceRouting_IP_source_routing_protection_level_protects_against_packet_spoofing_is_set_to_Enabled_Highest_protection_source_routing_is_completely_disabled" do
    tag   "ORG_CIS"
    tag   "18.1.3.3"
    impact 0.5
  end
end 
```
There are a number of things we can change to make this control a bit more DSL friendly.
```
include_controls 'cis-windows2012r2-level1-memberserver' do
  control "18.3.3_L1" do
    impact 0.5
    title "MSS_DisableIPSourceRouting"
    desc "Ensure 'MSS DisableIPSourceRouting' IP source routing protection level protects against packet spoofing is set to Enabled Highest protection source routing is completely disabled
    tag "ORG"
    tag "CIS"
    tag "18.1.3.3"
    tag "L1"
  end
end 
```
The fundamental change here is:
* ```xccdf_org.cisecurity.benchmarks_rule_1``` is repeated information
* ```_Ensure_MSS_DisableIPSourceRouting_IP_source_routing_protection_level_protects_against_packet_spoofing_is_set_to_Enabled_Highest_protection_source_routing_is_completely_disabled``` is really the description but this comes from the CIS naming convention so I get it but still makes it painful.

**Comment by adamleff** [comment]
@aaronlippold After re-reading this a few times, I'm still a bit confused as to what the ask is here. Since the control ID (the parameter to the `control` keyword) is the unique identifier, I don't believe what you're asking for is possible. Perhaps this should be a feature request to Chef Software (vs. the InSpec project itself) to have the commercial conversion tools use better control names and add tags?

I don't think this is something we'd actually address in InSpec core since you won't be able to inherit a profile and then change the control ID.

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
