### ISSUE TITLE
Resources for windows OS

### ISSUE THREAD

**Issue by aira86** [inspec/inspec#1637]
Hi,

I`m just starting to learn Inspec. I`m wondering to know is there any resources for check installed driver(e.x virtio-win) or kernel in windows?

Thanks

**Comment by chris-rock** [comment]
@aira86 has the question been answered?

**Comment by aira86** [comment]
@chris-rock No, I thought maybe here is just for coding issue! but I still looking for some hints for this issue

**Comment by chris-rock** [comment]
@aira86 Right now we do not have a resource to list windows kernel drivers. Are you looking for a resource to check the installed drivers? Similar to http://www.thewindowsclub.com/get-installed-driver-list-windows-powershell ?

**Comment by aira86** [comment]
@chris-rock I`m looking for installed driver as you mentioned but I want to do it in Inspec. Currently, I just used a path of the installed folder in system32 to check .sys, or .cat files exist or not. But I don't think this is a right approach or not!
Do you have any suggestion?

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
