### ISSUE TITLE
Integration tests with Chef Automate & Chef Compliance

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#1652]
### Description

As we have seen with #1646 and #1647, updates may break the integration between InSpec and our Servers. To ensure this is not happening again, we need to add integration tests that run

- fetch profiles
- upload profile to server
- re-upload profile to server with overwrite
- run profile from server
- delete profile from server
- upload profile and a second one with profile inheritance
- run profile with inheritance

### InSpec and Platform Version

1.19.2

### Possible Solutions

Test against AWS Opsworks

**Comment by aaronlippold** [comment]
@chris-rock: Is this still an open issue or does 1.20.x resolve issues with running profiles with inheritance on Automate?

**Comment by chris-rock** [comment]
We have integration tests, but we need to update them and run them for every PR.

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
