### ISSUE TITLE
Optimize interface between InSpec and Train

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#1653]
### Description

When we instantiate train as our InSpec backend, we should validate that we only pass options that need to be passed. Right now, we could send to many options or use the same option name in inspec as in train. See https://github.com/chef/inspec/blob/master/lib/inspec/profile.rb#L92

This happened before in https://github.com/chef/inspec/pull/1646/files

### InSpec and Platform Version

1.19.2

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
