### ISSUE TITLE
net-tools/netstat deprecated

### ISSUE THREAD

**Issue by MariusCC** [inspec/inspec#1655]
### Description

net-tools package (which used to provide netstat) is deprecated.
See here: https://bugzilla.redhat.com/show_bug.cgi?id=1119297

This affects all newer Linux distro that provides minimal installation (RHEL 7.x, CentOS 7.x, Ubuntu 16.04) - ie all deployments in cloud that are using inspec as a validation tool.

### InSpec and Platform Version

RHEl 7.x
CentOS 7.x
Ubuntu 16.04

Inspec versions:
1.15.0 up to 1.19.1

### Replication Case

Use kitchen to run integration testing on an webserver cobook.
Platform is RHEL 7.x.
inpsec test contains the following piece of code:
` 
 describe port.where { protocol =~ /tcp/ && port == ihs_port } do
    it { should be_listening }
    its('processes') { should include 'httpd' }
    its('processes.length') { should eq 1 }
  end
`
The result is:
`
  ✖  webserver-restart: Server: HTTP Server deployment - Service restart behaviour (IHS) (2 failed)
     ✖  Port  with protocol =~ /tcp/ port == 80 should be listening
     expected `Port  with protocol =~ /tcp/ port == 80.listening?` to return true, got false
     ✖  Port  with protocol =~ /tcp/ port == 80 processes should include "httpd"
     expected [] to include "httpd"
`

### Possible Solutions

[Use ss instead of netstat](https://linux.die.net/man/8/netstat).
>This program is obsolete. Replacement for netstat is ss. Replacement for netstat -r is ip route. >Replacement for netstat -i is ip -s link. Replacement for netstat -g is ip maddr.

**Comment by adamleff** [comment]
@MariusCC Thanks for submitting this issue! We'll put this on our backlog and address in the future.

**Comment by rmoriz** [comment]
Upcoming Debian 9 will also drop `net-tools` by default (including `iptables` and `netstat`)

**Comment by conn** [comment]
Debian 9 has been released. I can confirm that inspec isn't able to get port information on new installations. As all major and modern distributions of Linux come packaged with `ss`, would it be acceptable to just switch over to `ss` completely? Or would it be better to use `ss` by default and then use `netstat` as a fallback?

**Comment by adamleff** [comment]
@decomposite it's always important for us to maintain compatibility with as many older versions of Operating Systems as possible without increasing our maintenance burden unnecessarily. Since it's easy for us to detect whether a command is available to us, I'd rather see us try to use `ss` first, and if it's not available, use `netstat`. That way older OSs that don't have `ss` by default do not lose InSpec functionality.

**Comment by conn** [comment]
@adamleff sounds like a good idea. We'll have to branch at two places [here](https://github.com/chef/inspec/blob/master/lib/resources/port.rb#L269) and [here](https://github.com/chef/inspec/blob/master/lib/resources/port.rb#L338). Looking at other resources, I can see that most choices made about executables are solely based on which OS or distribution of Linux is being ran. Since things would be done a bit differently here, would you just want to probe for the existence of `ss` in `PATH`? Also, design-wise, is there a happy way to only probe for this once instead of sticking the same conditional in the resource twice?

**Comment by adamleff** [comment]
@decomposite I'm taking a day off tomorrow but I'll reply when I'm back. I'm sure we can come up with a way that's clean and advises duplication. If you want to start on a WIP PR and check the box that lets me commit to it, I'll be happy to tag-team this with you.

Talk to you on Thursday.

**Comment by conn** [comment]
@adamleff sounds good to me. I'll try mocking something up if I have time

**Comment by conn** [comment]
Just following up: some life stuff came up and I probably won't be able to tackle this for a couple of weeks. If this issue exists passed mid-July, I'd be happy to lend a hand.

**Comment by adamleff** [comment]
@MariusCC and @decomposite - I have opened PR #2110 that updates the `port` InSpec resource to use `ss` if it's available, otherwise fall back to `netstat`, on Linux targets.

**Comment by conn** [comment]
@adamleff brilliant! thanks
