### ISSUE TITLE
RFC: Consistent hashing for InSpec profiles

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#1658]
### Description

An InSpec profile json and an InSpec report json are not linked together very efficiently. Right now, only the profile name is used as an identifier. This mechanism is not working for profiles with differnt versions.

In order to make the linking between a profile and a report more consistent, we should use the profile hash and add the profile name as well as the hash in every report.

The challenge with that approach is that we generate different hashs for profiles, based on its packaging (tar, zip, folder). This makes it very difficult to identify the same profile.

### Possible Solutions

Instead of using the directory or the archive directly, we should use its content to generate the hash. Lets assume the following profile:

```
examples/profile
├── README.md
├── controls
│   ├── example.rb
│   ├── gordon.rb
│   └── meta.rb
├── inspec.lock
├── inspec.yml
├── libraries
│   └── gordon_config.rb
└── vendor

3 directories, 7 files
```

In order to achieve the same results, we blacklist some files. Blacklisted files are:

 - any directory with `.` at the beginning of the name
- `inspec.lock`

## Calculation

1. We determine the list of files:
```
README.md
controls/example.rb
controls/gordon.rb
controls/meta.rb
inspec.yml
libraries/gordon_config.rb
```

2. We sort the files array
3. We generate a hash for each `sha256(filename)`
4. sha(filename + sha256(filename) + filename2 + sha256(filename2) ... )

## Open Questions

How can we incorporate profile dependencies into our hashing algorithm? I assume we need to align our vendoring mechanism before. I am going to write an adaption for that.

**Comment by adamleff** [comment]
I like this approach.

Should we include the `inspec.lock` file instead of blacklisting it? If we combine this effort with the vendoring change we were discussing as well, we'd actually want the checksum of Profile A to change if its dependency versions changed too.

**Comment by adamleff** [comment]
In line with #1659, maybe we should include the `vendor` directory when calculating the checksum, and before we do, raise an exception if the checksums in the `inspec.lock` don't match the checksums of the vendored/extracted dependencies' content and instruct the user to re-vendor.

**Comment by alexpop** [comment]
Files added by users in the profile that are not blacklisted will impact the checksum. For example: `Jenkinsfile`, `Gemfile`, `tests/*`, `OTHER.md` etc.

Instead we could hash only the files we care about(`controls/*.rb`, `libraries/*.rb`, `vendor/*` `inspec.yml`, `inspec.lock`). It will be more cpu/disk friendly by not including any other files or directories.

**Comment by chris-rock** [comment]
@alexpop That is a great discussion and I am not sure about this. The first step that I wanted to achieve is consistency. I think no matter how many files we are including or excluding, the hash will be consistent.

Question: Isn't a change in `Gemfile` a change in our profile?

**Comment by chris-rock** [comment]
@adamleff I think it makes sense to include the lockfile, since it should not change once vendored

**Comment by arlimus** [comment]
Please note of the outcome of https://github.com/chef/inspec/issues/1396 for hashing.

**Comment by arlimus** [comment]
To add a few more thoughts:

* Do not vendor "Readme.md". It is not required by a profile, it is not checked (`inspec check`), it is not included in any of our outputs. If we want to make the readme a part of the profile, we should tackle that in a separate discussion imho.
* 👍 on inspec.yml and inspec.lock
* ~👍 on including `vendor`~ (see edit1)
* The field for this checksum in the JSON of each profile should be named `sha256`, since we only use this hashing mechanism. If it changes in the future the field can change too
* For the calculation (step 4) how about:
    ```
    sha256( file.path + sha256(file.path) + sha256(file.content) + ... )
    ```
    The alternative is:
    ```
    sha256( file.path + "\0" + file.content + ... )
    ```
    Also all files are sorted by their file.path first (regular sort)

Edit1:

On the vendor directory, I believe it should be handled recursively via InSpec dependency chain, instead of read manually. 
(This way we don't include any files that aren't relevant for the profile. In terms of walking its files, the behavior would be the same as for profile anyway; we could try to grab all folders in vendor and see if they are profiles and then generate the checksum; however, we already have the latter part covered and I'm wondering about the value of the former, if the profile isn't used. There is also a point for including files in the hash that aren't InSpec-related in vendor, but I cannot determine a use-case where this is relevant.)

**Comment by chris-rock** [comment]
The first would work better in-memory for large files (which we do not have within an inspec profile). I also like the second since it avoids nested hashing. I fine with both approaches.
