### ISSUE TITLE
Retrying Inspec Tests

### ISSUE THREAD

**Issue by ghost** [inspec/inspec#1665]
### Question

I have a test:

```
describe file('/var/log/cron') do
  its(:content) { should include('/some/cron/thing') }
end
```

This test is highly dependent on the timing of cron so my test may or may not pass.  I came across this blog post https://discourse.chef.io/t/inspec-retries-wait-option-until-service-comes-up/9242 and tried for a few hours to make it work to no avail.  

I was eventually reminded of https://discourse.chef.io/t/test-kitchen-1-10-0-released/8721 which got me thinking that we could possibly do something on the test-kitchen verifier side and submitted https://github.com/test-kitchen/test-kitchen/issues/1217.

That issue indicates that inspec does not use rspec which would render something like what is described https://discourse.chef.io/t/inspec-retries-wait-option-until-service-comes-up/9242 a moot point.  

So the question is what is the proper way to try to incorporate some retry logic with inspec.  Is what is provided https://github.com/test-kitchen/test-kitchen/issues/1217 correct and if so how would I make that work with the above example?

I apologize in advance for the noob question!

### InSpec and Platform Version

1.19.1

**Comment by jason-riddle** [comment]
Related: https://github.com/chef/inspec/issues/1404

**Comment by adamleff** [comment]
Hi @pantocrator27! Thanks for submitting this issue, and welcome to the InSpec community!

Currently, InSpec does not support any retry functionality natively and there are no plans to add that functionality. We're focusing on ensuring the InSpec core itself is finely-tuned to perform the testing at the moment it's asked to, vs. having to make a determination as to whether a failure might be transient and a retry is acceptable. I know some people may find this decision unfortunate, but we want to ensure InSpec operates as cleanly as possible with a low maintenance cost.

Since you're using Test Kitchen, you have a couple of options... one that exists today, and one that would need an enhancement to `kitchen-inspec`:

Option 1: use a recipe to block the Chef run until the node is ready-for-test. You could add another recipe called `_inspec_prepare` or something similar that you put at the end of your run_list in the .kitchen.yml. This would ONLY ever appear in a Test Kitchen run-list. In that recipe, you could use a `ruby_block` or an `execute` block to sleep/retry until you decide that the node is ready to be tested. That way, the "verify" stage of TK won't fire until your converge stage finishes, and you're in control of the converge stage finishing.

Option 2: enhance kitchen-inspec with retry logic, or perhaps a "this command must exit 0 for TK to verify" functionality. I don't know what would be acceptable there, but it seems reasonable to start at discussion over on the kitchen-inspec repo and go from there.

Hopefully this help. Don't apologize for "noob questions" ever! We want you to be comfortable using InSpec and we're here to help. We won't always be able to modify InSpec in the way you want, but we're here to help you make the most of your time with it.

Thanks!
~Adam

**Comment by omry** [comment]
it makes no sense to retry on the kitchen level for a single failed test.
the test file can have many tests, and only one of them may have timing issues.
please reconsider supporting retries, the alternative is for people to add sleep into their commands, making the test ALWAYS be slow, not just sometimes.

**Comment by stiller-leser** [comment]
Hi,

sorry for adding a "me-too" comment, but hopefully I can add some extra value. In my case I am using InSpec not to test chef cookbooks, but things happening in docker containers. I am for example testing the connection to a cloud provider. Due to random failures in my setup (that unfortunately have to be acceptable) I want to add a retry (since the failures are not test related and sporadic).

I know that this is kind of misusing InSpec, but it was providing so much value for my use case that i chose it.

Thanks ahead!
