### ISSUE TITLE
Add a find_one_where accessor for FilterTable

### ISSUE THREAD

**Issue by adamleff** [inspec/inspec#1678]
As seen in #1566, it's very handy to be able to use FilterTable on a higher-level resource and extract a second resource that filters on one item. For example, a top-level `docker` resource can allow us to list a myriad of data about what's running in docker and provide a `containers` method that uses FilterTable to provide data about all the containers, but exposing a `docker_container` resource that allows the querying of a single container is a delightful user experience.

Currently, this can be done with a FilterTable `#where` method call but even if there is only one match, all the returns are arrays, leading to code like this:

```
def labels
  container_info.labels[0] if container_info.entries.length == 1
end
```

I'd like to propose a `#find_one_where` method that operates just like the `#where` method in terms of searching using an expression or a block, with the following modifications:

 * If there are no matches, an empty Hashie::Mash is returned so that method calls on the returned object do not throw exceptions
   * TODO: this should actually be an exception that can be properly caught, such as `Inspec::Exceptions::FilterTableNoMatchFound`
 * If there are more than matches, an empty Hashie::Mash is returned so that method calls on the returned object do not throw execptions
   * TODO: this should actually be an exception that can be properly caught, such as `Inspec::Exceptions::FilterTableMultipleMatchesFound`
 * If exactly one match is found, a Hashie::Mash is returned with each of the `#add` accessors as keys and the single value removed from the array and returned as the actual value so that a user can fetch a single parameter without treating like a single-element array

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
