### ISSUE TITLE
User GEM_{HOME,PATH} alters official inspec ruby env

### ISSUE THREAD

**Issue by skull-squadron** [inspec/inspec#1679]
### Details

**OS:** macOS 10.12.4
**Inspec:** 1.20.0-1
**Installation artifact URL:** https://packages.chef.io/files/stable/inspec/1.20.0/mac_os_x/10.12/inspec-1.20.0-1.dmg (on page https://downloads.chef.io/inspec)

### Replication Case
```
# Install via url above
0 ~ git:master ❯❯❯ ls -l `which -a inspec`
lrwxr-xr-x  1 root  admin  31 Apr 18 20:47 /usr/local/bin/inspec -> /opt/inspec/embedded/bin/inspec
0 ~ git:master ❯❯❯ env GEM_HOME= GEM_PATH= inspec -v
/opt/inspec/embedded/lib/ruby/site_ruby/2.3.0/rubygems.rb:270:in `find_spec_for_exe': can't find gem inspec (>= 0.a) (Gem::GemNotFoundException)
	from /opt/inspec/embedded/lib/ruby/site_ruby/2.3.0/rubygems.rb:298:in `activate_bin_path'
	from /usr/local/bin/inspec:22:in `<main>'
1 ~ git:master ❯❯❯
```

### Success Cases

```
0 ~ git:master ❯❯❯ (unset GEM_PATH GEM_HOME; inspec -v)
1.20.0
0 ~ git:master ❯❯❯ env RUBYOPT=--disable-gems inspec -v
1.20.0
0 ~ git:master ❯❯❯ 
```

### Possible Solution

Similar to the resulting official chef dk scripts, somewhere in `omnibus/` packaging plumbing:
**Append `--disable-gems` to ruby scripts shebangs**

**Comment by chris-rock** [comment]
Thank you for highlighting this issue @steakknife . Do you want to submit a PR for that?

**Comment by skull-squadron** [comment]
Sorry, If I knew where the fix lived specifically, I would've just
submitted a PR.

**Comment by skull-squadron** [comment]
Still broken as of inspec 2.1.59

Workaround: modify `/opt/inspec/bin/inspec`

```diff
-ENV["GEM_HOME"] = ENV["GEM_PATH"] = nil unless ENV["APPBUNDLER_ALLOW_RVM"] == "true"
+ENV["GEM_HOME"] = ENV["GEM_PATH"] = "/opt/inspec/embedded/lib/ruby/gems/2.4.0" unless ENV["APPBUNDLER_ALLOW_RVM"] == "true"
```

**Comment by skull-squadron** [comment]
@chris-rock The cause of this issue has a detailed explanation and possible solution here https://github.com/chef/appbundler/pull/34

**Comment by kekaichinose** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please reopen the issue and continue the discussion.

Thank you!
__Chef InSpec Team__
