### ISSUE TITLE
Windows resources check: processes, firewall rules

### ISSUE THREAD

**Issue by juju4** [inspec/inspec#1697]
### Description

I'm testing https://github.com/juju4/windows-baseline from dev-sec but there are a couple checks that don't seem to work or possible, mostly
- process check with option to check executable path and other attributes
- firewall rules

### InSpec and Platform Version

Inspec 1.18 on Windows.
will check 1.20 but nothing related in Changelog

### Replication Case

Run https://github.com/juju4/windows-baseline on a windows system
Following will fail

```
control 'sysmon-1' do
  impact 0.7 
  title 'Sysinternals Sysmon is running'
  desc 'Sysmon process monitoring is active'
  ## FIXME! process listing NOK
  describe processes('sysmon.exe') do
    #describe processes('c:\windows\sysmon.exe') do
    its('list.length') { should eq 1 } 
    #its('users') { should cmp 'SYSTEM' }
  end 
end
```

### Possible Solutions

At this point, I'm not sure processes module support windows. That's a part were documentation is not really clear between linux&variants(ubuntu/redhat/alpine/...), osx, windows
But processes or firewall rules are definitely part of a good hardening.

Thanks

**Comment by chris-rock** [comment]
Indeed, `processes` is not working on Windows. See https://github.com/chef/inspec/blob/master/lib/resources/processes.rb. It is definitely a bug that this is not raised in that specific resource. Windows support would be an enhancement.

**Comment by tas50** [comment]
Firewall rule would be a very useful rule. I'm currently working to get windows_firewall_rule added as a rule in Chef and it would be helpful to be able to validate those firewall rules with InSpec.

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
