### ISSUE TITLE
list of required os packages / check for them

### ISSUE THREAD

**Issue by rmoriz** [inspec/inspec#1701]
Inspec should provide a list of required os/distro packages (e.g. in the README) and also, as the first step, check the availability of all dependencies.

e.g. `net-tools` in Ubuntu/Debian.

<s>I've also ran into case where this simple test

```ruby
describe command('rabbitmqadmin --version') do
  its(:exit_status) { should eq 0 }
end
```
produces:

```>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #verify action: [undefined method `[]=' for nil:NilClass] on lwrps-ubuntu-1604
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```
</s>

(^- happend when using an old inspec version (1.9.0) went away with (1.19.0))

**Comment by adamleff** [comment]
I think such a list of packages could be very fluid, and wouldn't necessarily apply to every user - i.e. if resource "foo" relies on `wget` to be installed, we shouldn't tell all InSpec users that they need `wget` installed.

We have an open issue about better exception handling, and my hope is that rather than failing hard or in opaque ways because a command we rely on isn't installed, we instead skip or error-out that particular test with a useful message indicating WHY it failed and a possible resolution.

**Comment by rmoriz** [comment]
I'm fine with that. As long as I don't have to grep the Inspec source to find the tool that is missing (and the package it provides) ;-)

**Comment by adamleff** [comment]
Once #1205 (better exception handling) is handled, this can be addressed in a more sane way (skipping/failing tests and providing better user feedback).

**Comment by chris-rock** [comment]
I like that approach. Then we can throw a proper exception and say, this executable is missing.

**Comment by aaronlippold** [comment]
The recent conversation I had in the channel - with once related to the `port` resource and `netstat` also supports this issue.

**Comment by ferrarimarco** [comment]
Hi, any updates on this? I have been bitten by `netstat`, `hostname` and `ps` commands missing...

**Comment by adamleff** [comment]
@ferrarimarco This is an ongoing improvement as we work on each resource. If you have a specific resource that you ran into an issue on, please open a separate issue for that and we'll be happy to make the user experience better. We're also going to work on #2418 over the next month which should also provide better error messaging.

I'm going to close this issue since it will be addressed through the course of normal resource maintenance and the implementation of #2418.
