### ISSUE TITLE
Inherited rules from tertiary profile not being executed

### ISSUE THREAD

**Issue by anweiss** [inspec/inspec#1702]
### Description

When requiring controls from a profile that subsequently also includes controls from a tertiary profile, the controls from the tertiary profile are not executed. Example below:

```ruby
# profile A - profileA.rb
include_controls 'tertiaryProfile'
control 'control1-profileA' do
  ...
end

# profile B - profileB.rb
require_controls 'profileA' do
  control 'control1-profileA'
end

...
```

`inspec exec profileB ...`

In the example above, when executing profile B, profile B requires `control1-profileA` and you would expect it to also include the controls from `tertiaryProfile` but it does not register nor execute the controls from the `tertiaryProfile`.

### InSpec and Platform Version

InSpec v1.20.0

**Comment by anweiss** [comment]
Ok so an update on this. My interpretation of `include_controls` is incorrect. I was wrapping `control1-profileA` in the `include_controls` block but `control1-profileA` is part of profileA. Example above updated. However, it still doesn't run the tertiary profile when doing an exec against profile B

**Comment by chris-rock** [comment]
Thank you for raising that issue @anweiss Lets assume you have 3 profiles: `tertiaryProfile`, `profileA` and `profileB`. 

Essentially you want to execute `profileB` and you expect that all controls from `profileA` and `tertiaryProfile` are executed. Internally the dependency is as following:

`profileB` -> `profileA` -> `tertiaryProfile`

Now, `profileA` looks as following and includes all controls from `tertiaryProfile`

```
# profile A - profileA.rb
include_controls 'tertiaryProfile'
control 'control1-profileA' do
  ...
end
```

Since the idea of profile B is to load all controls from `profileA`, you just need to use 

```
# profile B - profileB.rb
include_controls 'profileA'
```

Once you run `inspec exec profileB`, all controls are executed. `require_controls` allows you to pick specific controls from dependencies only.

**Comment by anweiss** [comment]
Worked great! Thanks! I confused myself on `require_controls` vs `include_controls`.
