### ISSUE TITLE
link inspec.io/docs pages to the source code in GitHub

### ISSUE THREAD

**Issue by arlimus** [inspec/inspec#1712]
Make it easier for users to contribute improvements to docs and tutorials.

**Comment by adamleff** [comment]
@arlimus what were you thinking in terms of implementation for this one? Adding an `[edit on GitHub]` link on each resource/docs page? Or just including a blurb on the main docs index page pointing users to where we keep the docs?

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
