### ISSUE TITLE
Postgresql 'hba_conf' resource

### ISSUE THREAD

**Issue by aaronlippold** [inspec/inspec#1725]
### Description

The postgresql hba_conf needs to be parsed for many security setting settings in the postgres stig. 

Creating a resource similar to that of 'grub_conf' and 'users' and 'passwd' resource would make the development of the controls much easier and more stable overall. Given that we will have to develop a set of attributes to define 'project defined' or 'program defined' roles and access and then loop over the target db to either match or execute those. 

See: https://www.postgresql.org/docs/current/static/auth-pg-hba-conf.html
see: https://github.com/CrunchyData/postgresql-baseline/issues/9
see: https://github.com/CrunchyData/postgresql-baseline/issues/10

example controls in the STIG are : V-72849 and V-72959. see: https://github.com/chef/inspec/files/895092/Postgres-9-stig.pdf for examples

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
