### ISSUE TITLE
InSpec does not run *_spec.rb recursively like rspec does

### ISSUE THREAD

**Issue by walterdolce** [inspec/inspec#1787]
### Description

I am trying to have InSpec run `*_spec.rb` files nested in various directories. Please see image attached below.

![screen shot 2017-05-09 at 14 28 23](https://cloud.githubusercontent.com/assets/6195629/25854220/31b2a992-34c7-11e7-8aa8-47a690737167.png)

Expected behaviour: all the `*_spec.rb` files are run by InSpec
Actual behaviour: only the files coloured in blue as shown in the image above are run by InSpec.

### InSpec and Platform Version

InSpec version: `1.23.0`
OS: Debian Jessie64

### Replication Case

Setup a basic `.kitchen.yml` file containing the necessary setup to run InSpec as a verifier and then nest various `*_spec.rb` files as shown in the image above.

### Possible Solutions

InSpec should run all the spec files recursively just like Rspec does.

### Stacktrace

Not available.

**Comment by chris-rock** [comment]
InSpec has no requirement on `*.spec` instead it runs all `*.rb` files in a directory. We really need to be careful about the nested searching behavior. Any opinions @adamleff @arlimus

**Comment by adamleff** [comment]
Sorry it's taken me so longer to reply to this. While it seems fairly innocuous to implement this behavior, I'm 👎  on the change. I'd rather see these tests formatted as profiles and then each profile listed in the `.kitchen.yml` under the `inspec_tests` section in the verifier. It makes the behavior more predictable.

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
