### ISSUE TITLE
apache_conf resource wraps parsed directives in a list

### ISSUE THREAD

**Issue by walterdolce** [inspec/inspec#1818]
### Description

The `apache_conf` runs verifications against a list, not a string. Also the docs don't currently mention this.

### InSpec and Platform Version
`0.18.0`, `debian/jessie64`

### Replication Case

```
# site.conf
<VirtualHost *:80>
    DirectoryIndex index.php
</VirtualHost>

# site_spec.rb
    describe apache_conf('site.conf') do
        its('DirectoryIndex') { should eq 'index.php' }
    end
```

### Possible Solutions
Either InSpec's behaviour or the docs need correcting.

### Stacktrace
```
/etc/apache2/sites-available/site.conf DirectoryIndex should eq "index.php"

     expected: "index.php"
          got: ["index.php"]

     (compared using ==)
```

**Comment by adamleff** [comment]
@walterdolce I'm going to dig into this a bit more after lunch. Many times we do this because some configs can support having the same key multiple times with the values being concatenated. But to avoid the issue in your tests, you can use the `cmp` matcher instead of the `eq` matcher. The `cmp` matcher will strip the array off of a single item before comparing it if necessary.

```ruby
describe apache_conf('site.conf') do
  its('DirectoryIndex') { should cmp 'index.php' }
end
```

**Comment by adamleff** [comment]
@walterdolce we essentially need to refactor the `apache_conf` resource because it doesn't properly handle a config with multiple VirtualHost sections with the same key (for example).

For now, using the `cmp` matcher is the right thing to do, and I'm going to open up a separate issue for us to revamp this resource.

Thanks in advance for your understanding :)
