### ISSUE TITLE
Upstart is_enabled check on Trusty doesn't take into account the Chef's workaround

### ISSUE THREAD

**Issue by maoe** [inspec/inspec#1834]
### Description

Chef's `Upstart` service provider disables a service by [commenting out the line](https://github.com/chef/chef/blob/a2890be2422453dee593ffb1f5eb6a49271c83be/lib/chef/provider/service/upstart.rb#L234-L239) of `start on` in the upstart file.

InSpec, on the other hand, uses `initctl show-config` to check if a service is enabled if the version of `initctl` is greater than 1.3.

The problem is that `initctl` on Trusty doesn't take into account the Chef's hack:

```console
$ cat /etc/init/my-service.conf | grep start
#start on runlevel [2345]
$ initctl show-config my-service
my-service
  start on runlevel [2345]
  stop on runlevel [!2345]
``` 

This means if I check the service in InSpec like this, it will fail:

```ruby
descrive upstart_service('my-service') do
  it { should_not be_enabled }
end
```

### InSpec and Platform Version

I'm using the InSpec from Chef DK:

* Chef Development Kit Version: 1.3.43
* InSpec 1.19.1
* Ubuntu 14.04.1 LTS
* initctl (upstart 1.12.1)

### Replication Case

I don't have a concrete minimal test case but it should be replicated like this:

Use Chef to disable an upstart service:
```ruby
service 'my-service' do
  provider Chef::Provider::Service::Upstart
  action :disable
end
```
then check it with InSpec:
```ruby
descrive upstart_service('my-service') do
  it { should_not be_enabled }
end
```
This fails.

### Possible Solutions

I see a few possible solutions:

* Add an additional check in [info_enabled](https://github.com/chef/inspec/blob/6c53188e8566c2785fd3da7a2e6940580860c1b6/lib/resources/service.rb#L357) to see if `start on` is commented out.
* Do not use `initctl`

### Stacktrace

I don't have a stacktrace.

**Comment by adamleff** [comment]
@maoe thanks for submitting this issue. I did some digging into this and definitely see some less-than-desirable behavior from `initctl`:

 * see that `initctl show-config ufw` matches `/etc/init/ufw.conf`:
```shell
root@vagrant:~# initctl show-config ufw
ufw
  start on ((starting network-interface or starting network-manager) or starting networking)
  stop on runlevel [!023456]
```

 * see that `ufw` is running
```shell
root@vagrant:~# service ufw status
ufw start/running
```

* modify the ufw upstart config, commenting out the `start on` lines

* run `initctl show-config ufw` and see that the `start on` section is still there:
```shell
root@vagrant:~# initctl show-config ufw
ufw
  start on ((starting network-interface or starting network-manager) or starting networking)
  stop on runlevel [!023456]
```

* stop the `ufw` service
```shell
root@vagrant:~# service ufw stop
ufw stop/waiting
```

* run `initctl show-config ufw` and see the updated output now the the `ufw` service is no longer running:
```
root@vagrant:~# initctl show-config ufw
ufw
  stop on runlevel [!023456]
```

So it appears to me that using `initctl show-config` to determine whether a service is enabled/disabled isn't a good idea since it may not reflect the actual configuration (i.e. that the service is truly disabled on boot) if the service itself is running.

@arlimus @chris-rock my gut says to stop relying on initctl and just use the config file like we do for Ubuntu 10. What do you think?
