### ISSUE TITLE
Command resource with path doesn't exist under Windows

### ISSUE THREAD

**Issue by grv87** [inspec/inspec#1839]
Under Windows `command` resource doesn't exist if command has path:
```ruby
  describe command('C:\Windows\System32\cscript.exe') do
    it { should exist }
    its('exit_status') { should eq 0 }
  end
```
```
  [CRIT]  windows: Command C:\Windows\System32\cscript.exe should exist (expected Command C:\Windows\System32\cscript.exe to exist)
     [FAIL]  Command C:\Windows\System32\cscript.exe should exist
     expected Command C:\Windows\System32\cscript.exe to exist
```

Under Linux the behavior is different:
```ruby
  describe command('/usr/bin/gcc') do
    it { should exist }
    its('exit_status') { should eq 1 }
  end
```
```
  ✔  linux: Command /usr/bin/gcc should exist; Command /usr/bin/gcc exit...
     ✔  Command /usr/bin/gcc should exist
     ✔  Command /usr/bin/gcc exit_status should eq 1
```
Inspec 1.25.0

**Comment by grv87** [comment]
Workaround: use `file` resource

**Comment by adamleff** [comment]
Started looking at this. The `command` resource calls `where.exe` which doesn't take a full path - it searches in the current directory and in PATH.

One option would be to split `C:\Windows\System32\cscript.exe` into `C:\Windows\System32` and `cscript.exe` and then call `where.exe /R C:\Windows\System32 cscript.exe`

Unfortunately, we cannot use `Pathname` since we could be running InSpec on a Linux machine scanning a Windows machine.

**Comment by adamleff** [comment]
Excited to state that community member @username-is-already-taken2 is working on a PR for this right now as part of the ChefConf 2017 hack day!
