### ISSUE TITLE
Should, Must, Could, Would, Shall, Shalt, ... and friends

### ISSUE THREAD

**Issue by arlimus** [inspec/inspec#1868]
Introduce alternative keywords for tests: We have been using this due the foundation on Ruby/RSpec, but actually if you read: https://tools.ietf.org/html/rfc2119

Then you `should` use `must` for tests instead of `should`, soft requirement for us.
You `must` use `must` for tests instead of `should` if we see it closely to the RFC

Also:

```
describe testcase do
  thou { shalt_not exist }
end
```

**Comment by aaronlippold** [comment]
{ shall_not exist }

**Comment by adamleff** [comment]
This is a potentially interesting (and possibly divisive!) conversation topic.

Even if we choose not to use RSpec under the covers in the future, keeping with the same syntax will continue to help existing Rubyists adopt the tool. So diverging from what `should` or `expects` could be confusing.

Also, if we take this RFC-of-RFCs to exact interpretation, does `should` get eliminated outright? We really don't have a concept of a test that *could* pass optionally or otherwise... and how we would track and communicate that? What's the use case?

Personally, I've never liked the `should` syntax and much more prefer the `expects` syntax which feels much closer to `must` than `should`. If we overall the CLI reporter properly, we can use both syntaxes and get cleaner output. Right now, with `expect`, depending on what you put in the `describe` parameter, can produce pretty unusable CLI output.

**Comment by clintoncwolfe** [comment]
Refs #3109
