### ISSUE TITLE
Ship powershell modules with InSpec profiles

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#1880]
### Description

With #1396 we introduced the capability to store additional files with an inspec profile. There should be an easy way do ship powershell modules and load them with each call from the powershell resource

### Possible Solutions

The powershell learns additional arguments to load modules. Right now I am in favor of an explicit loading mechanism, so that it is visible for all `powershell` calls

```
describe powershell("script", { modules: ["myModule.psm1"]}) do
  its('stdout') { should eq 'output' }
end
```

Under the hood powershell will transfer all modules to the Windows machine and load the module before execution:
```
Import-Module –Name C:\myModule -Verbose
```

```
tree examples/profile
examples/profile
├── README.md
├── controls
│   ├── gordon.rb
│   └── meta.rb
├── inspec.yml
├── files
│   └── powershell-modules
│       └── mymodule.psm1
└── libraries
    └── gordon_config.rb
```

**Comment by adamleff** [comment]
This is a really interesting proposal... and I'm both 👍  and 👎  on it.

Being able to have InSpec ship a file out to a host does open us up to additional abilities. For example, we could test if Ruby is installed on a host and then ship a small file that uses `Net::HTTP` that outputs JSON, and fix the `http` resource properly.

```
{
  "code": 200,
  "headers": {},
  "body": "some HTML content here"
}
```

And as you've suggested, it would make profiles that do lots of shell work a lot cleaner, less escaping, etc.

However, I think this violates one of the core principles we've been touting for a while: we don't make changes to a host in order to properly scan it. I'm concerned that once exposed, users may use this to make changes to a host during a scan. Sure, they could do that now with the `command` resource or a custom resource, but it's not something we natively support nor advocate.

We'd also need to be taking extra special care to ensure that paths to which we write files is unpredictable so that other actors can't alter the results of a scan simply by modifying files InSpec deploys during its scan, and to ensure that multiple InSpec runs can be happening simultaneously without introducing race conditions (run A removes a file that run B was expecting). And we'd need to be able to clean up those files after a scan, even if InSpec execution fails, leading to even deeper exception handling. 

Ultimately, I think I'm 👎  on this. If we do decide it's necessary, I'd consider it a breaking change that we could implement before 2.0 but require the users to pass in a `--allow-file-transfers` flag on the CLI to opt-in to the behavior. But I'm hoping we can come up with a different solution that doesn't require altering files on a host as I believe many people find its ability to do what it does without making changes a trust factor.

**Comment by Happycoil** [comment]
Is this just for the `powershell` resource, or is the goal to bundle modules for other resources which use PowerShell as well?

There's a lot of non DRY-y embedded PowerShell in other resources which would look much nicer in a module, as well as community and official modules which would help greatly simplify PowerShell code in some resources. If the module isn't in `$PSModulePath` the extent to which it changes the system is "just" storing a file.

Come to think of it, the module doesn't _have_ to be stored on the target though, does it? It could just be embedded at the start of the PowerShell command which gets executed anyway.

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
