### ISSUE TITLE
crontab command matcher is mismatching

### ISSUE THREAD

**Issue by kplimack** [inspec/inspec#1885]
### Description

I expect the 'include' matcher to partial match a command that might be grouped into a long string of commands, but it doesnt work consistently.  This works in test-kitchen, but fails on real nodes.  

```
     ✔  System Package chef should be installed
     ✔  Service chef-client should not be running
     ✔  Service chef-client should not be enabled
     ×  crontab for user root commands should include "/usr/bin/chef-client > /var/log/chef/client.log 2>&1"
     expected ["/bin/sleep 290;  /usr/bin/chef-client > /var/log/chef/client.log 2>&1", "/bin/bash -lc 'ruby /usr/libexec/<other thing>'"] to include "/usr/bin/chef-client > /var/log/chef/client.log 2>&1"
```
### InSpec and Platform Version

```
Chef Development Kit Version: 1.4.3
chef-client version: 12.19.36
delivery version: master (41b94ffb5efd33723cf72a89bf4d273c8151c9dc)
berks version: 5.6.4
kitchen version: 1.16.0
inspec version: 1.25.1

but this fails on:
CentOS Linux release 7.2.1511 (Core)
inspec (1.26.0)
```

### Replication Case

run this spec on cent7
```
control 'myorg_chef_client' do
  title 'default'
  describe package('chef') do
    it { should be_installed }
  end

  describe service('chef-client') do
    it { should_not be_running }
    it { should_not be_enabled }
  end

  describe crontab('root') do
    its('commands') { should include '/usr/bin/chef-client > /var/log/chef/client.log 2>&1' }
  end
end
```

**Comment by adamleff** [comment]
Hi @kplimack and thanks for submitting this issue.

Since the `crontab` resource can return multiple entries, all the methods that return values (such as `commands`) return arrays of data. When the return is an array, the `include` matcher doesn't partially match individual items but rather looks for a single item within the array and it has to be an exact match.

For your particular use case, I can propose this solution. Since `crontab` uses our `FilterTable` class underneath, you can use the `where` accessor to filter the data and then check the count of results.  The following test will get you the same outcome as you're looking for:

```
describe crontab.where { command.include?('/usr/bin/chef-client > /var/log/chef/client.log') } do
  its('entries.length') { should cmp 1 }
end
```

This will first filter the `crontab` entries to only entries that have the string `/usr/bin/chef-client > /var/log/chef/client.log` in the command, and then you can test to ensure that only 1 exists.

I hope this helps! Please feel free to reopen the issue if you can't get it working.

~Adam

**Comment by kplimack** [comment]
@adamleff i was able to get it to work like this.  is one method preferable over the other?
```
  describe crontab('root') do
    its('commands') { should include %r{/usr/bin/chef-client > /var/log/chef/client.log 2>&1} }
  end
```

**Comment by adamleff** [comment]
@kplimack either are fine! Your method uses straight ruby `include` tricks to do a regex match, and mine just filters out all the entries we don't care about.  Both are fine. :)
