### ISSUE TITLE
refactor apache_conf resource with a smarter config parser

### ISSUE THREAD

**Issue by adamleff** [inspec/inspec#1886]
As part of the discussion in #1818, it was determined that the `apache_conf` resource needs some love. 🙂 

Given the following valid config:

```
<VirtualHost 172.20.30.50>
    DocumentRoot "/www/example1"
    ServerName www.example.com

    # Other directives here ...
</VirtualHost>

<VirtualHost 172.20.30.50>
    DocumentRoot "/www/example2"
    ServerName www.example.org

    # Other directives here ...
</VirtualHost>
```

... the parsed params have some issues:

```
=> {"<VirtualHost"=>["172.20.30.50>", "172.20.30.50>"],
 "DocumentRoot"=>["\"/www/example1\"", "\"/www/example2\""],
 "ServerName"=>["www.example.com", "www.example.org"],
 "</VirtualHost>"=>[]}
```

 * the section headers (such as `VirtualHost`) aren't being treated as such and include the config markup (i.e. `<`)
 * the second headers parameters include the markup (i.e. `>`)
 * multiple config parameters of the same name (i.e. `DocumentRoot`) are getting read in correctly but not getting attributed to the section in which they were defined, making it impossible to make good assertions of those values (i.e. ensure the VirtualHost 172.20.30.50 with DocumentRoot '/www/example1' has a ServerName of 'www.example.com' -- not a test we can write today)... I think for config sections that can be repeated, we may find ourself wanting to do a FilterTable for these so we can do good filtering

I think we'll likely need to do a special parser for this one. @arlimus and @chris-rock, would love your feedback on this one.

**Comment by adamleff** [comment]
Seeing what @arlimus has been doing with parselet and the nginx work, that seems like could be a reusable pattern for this work, too.

**Comment by peco8** [comment]
+1

**Comment by ramereth** [comment]
Any further updates on this?

**Comment by kekaichinose** [comment]
Thank you for tracking down this issue. As with many large open source projects, we have a backlog of bugs and issues of varying user impact. Some issues are perpetually subject to lower priority than others in our backlog. We have reviewed the issue, and we have determined this a very low priority when considered in the context of the entire backlog. We have elected to close it as "Declined" due to competing priorities. We very much appreciate you bringing this to our attention.

Thank you!
__Chef InSpec Team__
