### ISSUE TITLE
Q. regarding running inspec shell locally on windows.

### ISSUE THREAD

**Issue by username-is-already-taken2** [inspec/inspec#1890]
Hi there

I noticed something today and wanted to check if this was by design or if its a `feature` :)

If I launch `inspec shell` (from an elevated command prompt) on my local workstation (windows 10) and execute either a `command` or `powershell` resource I noticed that my request **doesn't** have elevated privileges.

If I launch `inspec shell target` against a remote windows computer and execute the same command my request **does** have elevated privileges.

I used the follow code to determine if I have an elevated access or not.  It returns `True` if that's the case
```command('([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)').stdout```

**Example Locally**
```
C:\git-repo\chef\inspec [gb/update_processes +0 ~1 -0 !]> chef exec ruby .\bin\inspec shell
Welcome to the interactive InSpec Shell
To find out how to use it, type: ☺☻help☺☻

You are currently running on:

    OS platform:  ☺☻Windows 10 Pro☺☻
    OS family:  ☺☻windows☺☻
inspec> command('([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)').stdoutIdentity]::GetCurrent()).IsInRole([Security.PrincipailtInRole]::Administrator)').stdout

=> "False\r\n"
```

**Example Remote** 
```
C:\git-repo\chef\inspec [gb/update_processes +0 ~1 -0 !]> chef exec ruby .\bin\inspec shell --target=winrm://vagrant:************@192.168.**.**
Welcome to the interactive InSpec Shell
To find out how to use it, type: ☺☻help☺☻

You are currently running on:

    OS platform:  ☺☻Windows Server 2012 R2 Standard☺☻
    OS family:  ☺☻windows☺☻
inspec> command('([Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)').stdoutIdentity]::GetCurrent()).IsInRole([Security.PrincipailtInRole]::Administrator)').stdout

=> "True\r\n"
```

I'm currently working against `1.26.0`

**Comment by adamleff** [comment]
Hi @username-is-already-taken2!

InSpec doesn't elevate privileges itself under normal operation. The only time we ever attempt to elevate is during a remote scan of a Linux/Unix-based operating system when the user passes the `--sudo` flag (and they're not already connecting as the `root` user).

The `vagrant` user is a member of the `Administrators` group, so I presume that's why your remote session returns `True`. I don't know enough about Windows/Powershell to explain your local workstation experience other than I know that I never had luck with starting PowerShell as an administrator and then running another application from within that shell and having it retain it's Administrator privileges. I always had to do some `/runas` magic...

How can I further assist with this issue?

**Comment by clintoncwolfe** [comment]
As this has been idle for a while, I'm closing this. If you have any further questions on this topic, please re-open the ticket.
