### ISSUE TITLE
way to make data available to all profiles

### ISSUE THREAD

**Issue by kplimack** [inspec/inspec#1891]
### Description

I've created an inspec_handler cookbook that is able to deploy and run tests that live with my cookbooks (much the same way we are accustomed to with the audit cookbook, or minitest).  (I'm in the process of getting approvals to release this cookbook to the community with an accompanying blog post).  My handlers deploy and run the correct things based upon the run_context; however, I would like to be able to pass variables (node object) to my tests to make sure they have actually integrated properly.

@adamleff told me that there is no way to pass data directly to the inspec runner, so I've instead dumped the node as json to disk.  its quite simple reading and parsing it, but I would like a way to do this once and then have the data available in all the profiles.  Is this possible to implement?  Since I'm creating an Inspec::InspecCLI object, can be be injected this way?  Is there somewhere I can drop libraries on disk that inspec will pick up?  what about a flag for inspec ?

**Comment by adamleff** [comment]
@kplimack this sounds really great. 🙂 

One possible solution is to use Profile Attributes -- see the "Profile Attributes" section here: https://www.inspec.io/docs/reference/profiles/

If you could serialize the node object as YAML instead of JSON, one could then declare the following attribute in the profile to pull in the node data (assuming the node object is in YAML with a top-level key of `node`):

```ruby
node = attribute('node', default: {}, description: 'the node object')
```

Maybe perhaps we need to extend the attributes system with a JSON plugin? Here's where the YAML stuff happens: https://github.com/chef/inspec/blob/master/lib/inspec/secrets/yaml.rb

**Comment by kplimack** [comment]
@adamleff does that mean that each of my profiles will require an inspec.yml that declares a dependency on my node-providing profiles ?

**Comment by adamleff** [comment]
No, attributes are not part of the dependency system. They're part of the "runner" for lack of a better term. When you run InSpec and you pass in attributes, any profile can use them. But they have to call `attribute` in the profile in order to gain access to it, like the example I provided above.

**Comment by kplimack** [comment]
@adamleff I've stripped a ton of stuff out of the node.yaml, but I'm getting this error and I'm unsure what it's expecting. the example yaml file just has a couple key/vals, nothing as complex as a node hash.
```
Could not fetch inspec profile in "--attrs /tmp/node.yaml".
```

**Comment by kplimack** [comment]
@adamleff got it working!  thank you for your help!  I'll shoot you a link when it gets released, hopefully later this week.

**Comment by adamleff** [comment]
@kplimack sounds awesome! can't wait to see it.
