### ISSUE TITLE
User not prompted for password when running `inspec exec` with a remote target

### ISSUE THREAD

**Issue by jerryaldrichiii** [inspec/inspec#1902]
### Description

When a user runs `inspec exec foo -t winrm://someone@some.host.com --password` they are not prompted for a password. Currently, it is required that a password be passed in from the CLI.

This allows anyone who can view the history or is watching the user execute the command see sensitive information.

### Possible Solutions

When the user uses the `--password` argument without a password, prompt the user for a password.

**Comment by adamleff** [comment]
Given the findings of how Thor handles default values for config flags where a value is not passed in (see #1901 and the resulting PR #1904), there is not going to be an easy way to implement this without pissing off people who truly have a password of `password`. I'm afraid I have to close this one for now, but if we end up being able to implement or a better idea comes up, I'll be happy to reopen.

**Comment by trickyearlobe** [comment]
How about `--prompt-for-password true` ?

**Comment by adamleff** [comment]
We actually have a reasonable solution for this now, and we fixed it with `--password` already. I'll reopen this and flag it as a feature request.

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
