### ISSUE TITLE
RSpec unit tests on resource methods for matchers

### ISSUE THREAD

**Issue by mschuchard** [inspec/inspec#1903]
I am attempting to write RSpec unit tests for matcher methods for a custom Inspec resource that uses the `Inspec::Resource` module class mixin as per normal (`ResourceClasss < Inspec.resource(version)`, but I keep slamming into

> undefined local variable or method `inspec'

when executing rspec. I have tried to bootstrap this method in the RSpec unit test block with

```ruby
Inspec::Resource.create_dsl(Inspec::ProfileContext.new('test-profile', mock, {}))
```

but it does not seem to circumvent the error. I have checked around and nobody else has even attempted to do this kind of thing, so i am wondering if it is even possible.

Would you guys recommend using the `MockLoader` (https://github.com/chef/inspec/blob/12951eecd39440baca2fa32437a59dfb55de4ea3/test/helper.rb) like you have been using, or would that be overkill (it seems to do a lot more than I need)?

**Comment by adamleff** [comment]
Hi, @mschuchard!

You have successfully tiptoed into a bit of a world of pain. 🙂  Because InSpec is built on RSpec, and RSpec uses a lot of global state to do its thing, using RSpec to test anything with InSpec is likely to not turn out well. That is why our unit tests and functional tests are written with minitest instead.

My recommendation would be to use minitest instead if at all possible.

**Comment by mschuchard** [comment]
Can I use parts of the `MockLoader` without minitest? I noticed the use of minitest, but it seemed like its use was separate from most of the `MockLoader`.

**Comment by adamleff** [comment]
@mschuchard I don't honestly know. The `MockLoader` exists specifically to mock out calls that InSpec resources might make during unit testing so we can return the mocked data in order to test the functionality of a resource. Since we do all that work in minitest, I don't believe anyone has taken the MockLoader work and tried it elsewhere.

**Comment by mschuchard** [comment]
Ok, I think I will refactor to separate out the backend provider so I can write tests like I do for Serverspec with the helper https://github.com/mizzy/serverspec/blob/master/spec/spec_helper.rb.

Thanks for the info.

**Comment by mschuchard** [comment]
Yep, that worked. I was able to mock the message from the provider method to the matcher method and was able to do the unit tests.

**Comment by adamleff** [comment]
that's great - would you mind sharing a gist of what you did in case others stumble upon this same need?

**Comment by mschuchard** [comment]
I was certainly planning on it, but will need to sanitize first. It is pretty simple yet effective, so I do not know how many use cases it will fit, but it definitely fit mine.

**Comment by adamleff** [comment]
That's all that matters :) Thanks for being willing to consider sharing your work!
