### ISSUE TITLE
InSpec and Audit Cookbook interdependency issues

### ISSUE THREAD

**Issue by adamleff** [inspec/inspec#1909]
The audit cookbook depends directly on InSpec for scanning and reporting functionality. In addition, the audit cookbook calls methods within InSpec (specifically methods in `Compliance::API`) that haven't been designed or tested the way externally-available APIs should be.

This has caused an issue where `Compliance::API.version` method was modified recently to not be backward compatible, and the audit cookbook was not updated accordingly even though it uses that method directly. Additionally, even if the cookbook were updated, it would force users to upgrade both the cookbook and InSpec simultaneously to avoid the issue.

Proposed plan moving forward:

## Phase 1

1. The `Compliance::API.version` change should be reverted or enhanced so that it is backward compatible. A patch release of InSpec should be made accordingly.
1. The audit cookbook should be modified to enforce a minimum required InSpec version. It should raise an exception if the version is not met.
1. Maintainers agree that any increase in the minimum required InSpec version is a major version bump to the audit cookbook.
1. The audit cookbook is bumped to 5.0 and released.

## Phase 2

An integration test is added to InSpec that tests any InSpec changes against the latest audit cookbook in an effort to catch any issues that may arise from InSpec changes. While this would normally make more sense to implement as a test in the audit cookbook rather than InSpec, I'm proposing doing it in InSpec because:

 * InSpec is modified more frequently than the audit cookbook
 * While audit cookbook consumes InSpec, it is more of a plugin/extension to InSpec, allowing InSpec to be run under Chef. Much like we test a handful of community cookbook's in Chef's Travis runs, we should do the same with the audit cookbook in InSpec's travis runs.

## Phase 3

`Compliance::API` should likely be broken out into its own gem. This would allow both InSpec and the audit cookbook to depend on it and properly version constrain.

**Comment by arlimus** [comment]
Thank you for writing all of this up!! Intermitten phases 1+2 are good stepping stones to get to happy phase 3.

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
