### ISSUE TITLE
`inspec json` report does not include inspec version

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#1949]
### Description

For debugging, it would be helpful if the command `inspec json examples/profile | jq .` would include the inspec version, similar to `inspec exec examples/profile --format json | jq .`.

There we use:       
```
{
  "version": "1.28.0",
...
}
```

### InSpec and Platform Version

1.28.0

### Replication Case

Run commands above.

### Possible Solutions

Since we cannot use `version` in `inspec json`, we could use a `generator` attribute:
```
{
   "generator": {
      "name": "inspec"
      "version": "1.28.0"
   },
...
}
```

This would ease debugging and audit trails

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
