### ISSUE TITLE
skip_resource

### ISSUE THREAD

**Issue by rx294** [inspec/inspec#1965]
### Description
The skip_resource method does not skip the resource, when the methods of the resource are directly called for the test.  

eg: 
describe pg_hba_conf.where { type == 'local' } do
  its('auth_method') { should eq ['peer'] }
end

The OS test and skip condition was defined in the initialize method. 
The following eg does skip the resource :

describe pg_hba_conf do
  describe pg_hba_conf.where { type == 'local' } do
    its('Setting') { should eq true }
  end
end
 
### InSpec and Platform Version

1.28.1 / CentOS 7.2

### Replication Case

describe pg_hba_conf.where { type == 'local' } do
  its('auth_method') { should eq ['peer'] }
end

output :

Profile: inspec-shell
Version: (not specified)

  PG HBA
     ∅  Config with type == "local" auth_method should eq ["peer"]

     expected: ["peer"]
          got: []

     (compared using ==)

describe pg_hba_conf do
  describe pg_hba_conf.where { type == 'local' } do
    its('Setting') { should eq true }
  end
end

output :

Profile: inspec-shell
Version: (not specified)

  PG HBA
     ↺  The `pg_hba_conf` resource is not supported on your OS.

Test Summary: 0 successful, 0 failures, 1 skipped

### Possible Solutions

The skip_resource should skip the resource if the skip condition in the initialize method is true, when member functions are directly called.

**Comment by chris-rock** [comment]
You cannot skip resources outside of the initialization method as you do in https://github.com/chef/inspec/pull/1964/files#diff-2b6b0ee3585089bb08a90b49541ea7e1R72 right now. We want to cover your use case and that is tracked in #613

**Comment by adamleff** [comment]
Additionally, expecting InSpec to be able to not execute instance methods because skip_resource is called somewhere would require some massive monkeypatching of Ruby to accomplish. I suspect this request is coming from the issues a recent PR of yours and @aaronlippold's had on Appveyor where you did not expect the unit tests to fire on Windows.

The solution to the unit-test-on-a-different-platform issue you're encountering is solved with stubs and mocks instead to ensure that other methods don't leak to OS-specific code paths.

I'm going to close this issue now as I believe issue #613 and the suggestions I provided in the PR address this issue. Thanks for opening this!
