### ISSUE TITLE
Control with no tests defaults to 'pass' - false positive reporting

### ISSUE THREAD

**Issue by aaronlippold** [inspec/inspec#1975]
### Description

In working on some reporting for a customer I noticed that when a control has no tests it defaults to a 'passed' status. Logically yes the control did 'pass' all its tests but given that we cannot know from the reporting data if it passed because it complied with all its statements or didn't have any I think it leaves us in a state where we could be reporting a 'false positive' result. 

From the compliance point of view no testing was done so the outcome would be considered a 'not reviewed' state. 

I suggest we move the default to 'skipped' because that is true in this case - we did skip it by not having any tests run. The best solution would be to add a status of 'no tests' to make it clear that this control did not evaluate anything.

**Comment by aaronlippold** [comment]
@chris-rock In thinking about it more, I think we should add a *`no tests`* status, we actually already have it in a way, `inspec check` already correctly reports that data - i.e. `control x has no tests`. I think putting in the execution path makes just as much sense. The system should report consistently in all its modes right?

**Comment by aaronlippold** [comment]
@chris-rock totally agree.

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
