### ISSUE TITLE
Allow upload to specific organization

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#1984]
### Description

Right now, `inspec compliance upload` only supports the upload to the user namespace. Many organizations want to upload profiles to a shared namespace. The CLI should support that.

### InSpec and Platform Version

1.30.0

**Comment by chris-rock** [comment]
this already works via:

```
inspec compliance login https://compliance.test --insecure --user='brewinc' --token=$COMPLIANCE_TOKEN
```

Since we do not support user/password login anymore, we should consider to deprecate `user` and use `owner` or `namespace` instead

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
