### ISSUE TITLE
DRY common profile overrides in meta profile

### ISSUE THREAD

**Issue by jeremymv2** [inspec/inspec#2000]
### Description

As of inspec version 1.31.1, if you have the following meta profiles:
```
# meta profile: acme-server-level-1
include_controls 'cis-level-1' do

  control "cis-fs-2.7" do
    impact 1.0
  ...
  bunch of other overrides..

end
```
```
# meta profile: acme-server-level-2
include_controls 'cis-level-2' do

  control "cis-fs-2.7" do
    impact 1.0
  ...
  exact same overrides as above

end
```

There is not yet a built-in pattern for handling the above scenario where Acme org creates meta/wrapper profiles for the standard CIS ones but wants to use the same overrides in each wrapper profile, without having to maintain that duplicate override code across meta profiles.

A real-world example of this, for example, is the cis-rhel7-level1-server and cis-rhel7-level2-server profiles that have a bunch of control duplication that someone wants to override, yet maintain separate meta profiles for each. Duplicating the profile overrides in meta profiles for each upstream profile is not DRY.

### InSpec and Platform Version

1.31.1

### Possible Solutions

A work around pattern proposed [here](https://github.com/jeremymv2/one-profile-to-rule-them-all)

### Stacktrace

Please include the stacktrace output or link to a gist of it, if there is one.

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
