### ISSUE TITLE
host ipaddress no longer honors /etc/hosts entries as of Inspec 1.31

### ISSUE THREAD

**Issue by aogail** [inspec/inspec#2001]
### Description

The host resource no longer honors /etc/hosts entries when verifying the ipaddress of a host, as of version 1.31.0. This worked in Inspec 1.30.0.

### InSpec and Platform Version

I am using kitchen-inspec to verify an Oracle Linux 7.2 VM from my Mac running Mac OS 10.11.6.

Working Inspec version:

```
$ inspec --version
1.30.0
```

No longer working Inspec version:

```
$ inspec --version
1.31.1
```

### Replication Case

Add an entry to /etc/hosts for a host name that is also resolvable in DNS, and use Inspec to assert that the host has an IP address listed in /etc/hosts.

```
$ grep google.com /etc/hosts
127.0.0.2 google.com
```

Inspec resource:

```ruby
describe host('google.com') do
  it {should be_resolvable}
  its('ipaddress') {should include '127.0.0.2'}
end
```

Failure with Inspec 1.31:

```
  Host google.com
     ✔  should be resolvable
     ∅  ipaddress should include "127.0.0.2"
     expected ["216.58.208.142"] to include "127.0.0.2"
```

Success with Inspec 1.30:

```
  Host google.com
     ✔  should be resolvable
     ✔  ipaddress should include "127.0.0.2"
```

### Possible Solutions

This behavior changed in version 1.31.0, so I'm guessing the difference has something to do with the switch from `host` to `dig` for the ipaddress matcher, but that's just a guess.

### Stacktrace

n/a

**Comment by adamleff** [comment]
Hi @aogail and thanks for submitting this issue!

This is likely because we changed from using `getent hosts` to `dig` on Linux targets because `getent hosts` does not return full results (i.e. if a v6 address exists, it only returns v6 and not the v4 addresses) and to make the implementation on Linux and Darwin similar. However, it does have the side effect that `dig`/`host` only use the host resolver library (and do remote queries) vs using the Name Service Switch library.

I think the best thing to do is to go back to using `getent` on Linux OS families, but use `getent ahosts` which will return both v4 and v6 addresses and deal with the fact that the Darwin implementation will be different.

I'll work up a PR for this.
