### ISSUE TITLE
contain_match returns false positives in auditd_rules resource

### ISSUE THREAD

**Issue by jburns12** [inspec/inspec#2025]
### Description

When the auditd_rules resource is used along with contain_match, any provided input to match upon is returning a successful result.

### InSpec and Platform Version

Running on macOS Sierra 10.12.6 on Rhel7 VM on Virtualbox. Inspec version 1.31.1.

### Replication Case

Execute the following with an empty /etc/audit/audit.rules and auditd_rules.lines containing only ["No rules"]:

describe auditd_rules do
  its('lines') { should contain_match(%r{anytext})}
end

This result is produced:
     ✔  Audit Daemon Rules lines should contain match /anytext/

Profile Summary: 1 successful, 0 failures, 0 skipped

### Possible Solutions

Since it's known that contain_match is deprecated, switching to match and updating docs could provide a fix.

**Comment by adamleff** [comment]
@jburns12 with the recent work on the auditd stuff, is this still an issue?

**Comment by jburns12** [comment]
I need to test and see if the issue is with the matcher or resource. I'll post an update here in the next couple days. Thanks!

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
