### ISSUE TITLE
hide profile and version when inspec exec

### ISSUE THREAD

**Issue by Azaroths** [inspec/inspec#2030]
Hello,

I have a question about inspec.

When you execute the inspec exec file.rb command, is it possible to hide profile : and version : in the test result ?

Best regards,
Azaroths

**Comment by chris-rock** [comment]
@Azaroths Can you share your use case a little bit more in detail?

**Comment by Azaroths** [comment]
I execute inspec test inside docker container with :
inspec exec file.rb -t docker://my_container

I have this result : 

Profile: tests from 12746.rb
Version: (not specified)
Target:  docker://8b181a17bf232805e5e383270453c465d7f180df72173227977dd8c78c7c8e67


  Command ps
     ✔  -U root exit_status should eq 1

Test Summary: 1 successful, 0 failures, 0 skipped


I would know if it's possible to hide Profile, Version and Target in the result

**Comment by adamleff** [comment]
@Azaroths thank you for your reply. We understand your request, but we're not understanding the *why* of what you're asking. 🙂 If you could help us understand *why* you're looking to filter that out, that would help us determine whether this is something we should account for.

In the meantime, you could pipe the output through `egrep` and fliter out those lines:

```
inspec exec profiles/test1 | egrep -v "^(Profile|Version|Target)"
```

To provide you an alternative, you can use `--format=json` to get JSON output instead of the pretty-print CLI output, and you could then parse that and pluck out exactly what you need without filtering out other data you don't need.
