### ISSUE TITLE
YAML resource with symbol keys

### ISSUE THREAD

**Issue by meringu** [inspec/inspec#2036]
### Description

The yaml resource assumes the yaml file has strings as keys

### InSpec and Platform Version

```
$ chef -v
Chef Development Kit Version: 2.0.28
chef-client version: 13.2.20
delivery version: master (17c1b0fed9be4c70f69091a6d21a4cbf0df60a23)
berks version: 6.2.0
kitchen version: 1.16.0
inspec version: 1.31.1
```

### Replication Case

For a given file on disk `file.yml`

```yaml
---
:key: value
```

And a test:

```yaml
describe yaml('file.yml') do
  its(:key) { should eq 'value' }
end
```

Outputs:

```
  ×  YAML file.yml max_revisions should eq "value"
     
     expected: "value"
          got: nil
     
     (compared using ==)
```

### Possible Solutions

The YAML resource inherits this logic from the JSON resource. As there is no such thing as Symbol in JSON, this isn't an issue for the JSON resource.

Looks like the problem lies with [`ObjectTraverser`](https://github.com/chef/inspec/blob/56986d1bdbb1b0dd2f0c7c60804e2ab617678940/lib/utils/object_traversal.rb#L16) that the JSON resource uses. [`ObjectTraverser`](https://github.com/chef/inspec/blob/56986d1bdbb1b0dd2f0c7c60804e2ab617678940/lib/utils/object_traversal.rb#L16) calls `#to_s` on the key, and the value comes back nil.

Solution could be to not call `#to_s`, but this may might cause issues elsewhere with other things that use [`ObjectTraverser`](https://github.com/chef/inspec/blob/56986d1bdbb1b0dd2f0c7c60804e2ab617678940/lib/utils/object_traversal.rb#L16).

**Comment by adamleff** [comment]
@meringu thanks for submitting this issue. I did reproduce this one successfully.

There are a couple of options here, probably more. Removing the `#to_s` call will likely uncover other issues, but we could be smarter about checking for the unconverted key first, return that if it exists, otherwise try for the string.

Another option could be to convert symbol keys to strings on the way in. Again, not sure of the side-effects there.

As a workaround, you could do something ugly like this for now:

```
inspec> describe yaml('/tmp/test.yaml').params[:key] do
inspec>   it { should eq 'value' }
inspec> end

Profile: inspec-shell
Version: (not specified)

  value should
     ✔  eq "value"

Test Summary: 1 successful, 0 failures, 0 skipped
```

The output isn't pretty (value == value) but you could clean that up a bit with a `subject` call:

```
inspec> describe 'yaml key1' do
inspec>   subject { yaml('/tmp/test.yaml').params[:key] }
inspec>   it { should eq 'value' }
inspec> end

Profile: inspec-shell
Version: (not specified)

  yaml key1
     ✔  should eq "value"

Test Summary: 1 successful, 0 failures, 0 skipped
```

Flagging this as a bug, and we'll have to see about the best way of getting it fixed.  Hopefully the workaround can hold you over for now!
