### ISSUE TITLE
Libraries with custom resources not accessible when running controls outside of full profile

### ISSUE THREAD

**Issue by jburns12** [inspec/inspec#2045]
When a custom library is added to the libraries folder of a profile, the only way to run a single control is to pull in the full profile. 

For instance, the profile must be executed using "inspec exec profiles/<profile name>" which iterates through all controls vs. "inspec exec profiles/<profile name>/controls/<control name>" or even "inspec exec profiles/<profile name>/controls/."

Otherwise the following error occurs:

`method_missing': undefined method `<resource_name>' for #<#<Class:0x007fd84e6048b0>:0x007fd84e5f6530> (NoMethodError)

**Comment by chris-rock** [comment]
You can select single controls. See `inspec help exec`:

```
[--controls=one two three]                   # A list of controls to run. Ignore all other tests.
```

Therefore you can run the profile and select the control you need. Is that solving your problem?

**Comment by jburns12** [comment]
This works, but since it requires processing of the entire profile it makes the testing of a single control time consuming, especially with large profiles such as the Rhel7 profile that we are working on. For example, in our case it takes over 1 minute to process the profile before executing the single control that is specified.

We have been renaming our controls folder and adding single/multiple controls to a new folder we named controls as a workaround, but it's not ideal.

**Comment by chris-rock** [comment]
Which OS are you on? It seems like we want to improve the load time for inspec. resources for inspec are tight to a profile, you cannot use additional resources without a profile.

**Comment by adamleff** [comment]
Closing this issue as this is currently working as-designed. Please open a new issue for any performance-related problems you are encountering so we can troubleshoot them accordingly. Thank you!

**Comment by rockandska** [comment]
Hi,

Just hit the same behavior and would be really really really nice if we could specify the root directory of the profile to let inspec load the common libraries and be able to filter the tests by directories.
I tried something like bellow without success : 
```
$ inspec exec --profiles-path=$(pwd) $(pwd)/controls/webserver -t docker://a03cf9daf283
``` 
But my test fail due to the "undefined method"

Could you please consider this as a feature request ?

Regards,

**Comment by chris-rock** [comment]
@rockandska I am not sure I understand your use case. Can you help me to understand what you are trying to achieve?

**Comment by rockandska** [comment]
Thanks for your fast answer @chris-rock 

I have a profile with some "groups" (subdirectory inside controls).
The profile tree looks like bellow for exemple 
```
.
├── controls
│   ├── services-x
│   │   ├── 01-test.rb
│   │   └── 02-test.rb
│   ├── services-y
│   │   ├── 01-test.rb
│   │   └── 02-test.rb
│   ├── services-z
│   │   ├── 01-test.rb
│   │   └── 02-test.rb    ---> multiples controls inside
│   └── webserver
│       ├── 01-connections_backend.rb    ---> multiples controls inside
│       ├── 02-webserver-config.rb   ---> multiples controls inside
│       └── inspec.lock
├── inspec.lock
├── inspec.yml
├── libraries
│   └── user_resource.rb
└── README.md
```
We have two cases : 
- all the services and the webserver are on the same host
- each services are on different hosts, and the webserver on another host.

What i'm trying to achieve is having one profile who cover my 2 cases.

Without libraries there is no problem at all, i could run my test only on the corresponding group depending on the host and filtering controls too : 
```
$ inspec exec controls/webserver -t docker://a03cf9daf283
$ inspec exec controls/webserver -t docker://a03cf9daf283 --controls 'control-test3'
$ inspec exec controls/services-z -t docker://fb1555c52939
$ inspec exec controls/services-z -t docker://fb1555c52939 --controls 'control-test1'
```

But if a control need to use a library (or another profile too i suppose) , my test fail because inspec is not aware of the library and hit the "undefined method" error.
I will be really nice to be able to filtering test by directories and by 'controls'

Just my 2cts, but it could be achieve this way :
- Be able to tell to inspec where to find the libraries (rootdir of the profile), and everything will run as expected
- Be able to create group of 'controls'

Best regards,

**Comment by chris-rock** [comment]
You can achieve this with InSpec, but you need to structure this well and use profile inheritance:
```
├── profiles
│   ├── resource_pack
│   │   ├── inspec.lock
│   │   ├── inspec.yml
│   │   └── libraries
│   │       └── user_resource.rb
│   ├── services-x
│   │   ├── inspec.lock
│   │   ├── inspec.yml
│   │   └── controls
│   │       ├── 01-test.rb
│   │       └── 02-test.rb
│   ├── services-y
│   │   ├── inspec.lock
│   │   ├── inspec.yml
│   │   └── controls
│   │       ├── 01-test.rb
│   │       └── 02-test.rb
│   ├── services-z
│   │   ├── inspec.lock
│   │   ├── inspec.yml
│   │   └── controls
│   │       ├── 01-test.rb
│   │       └── 02-test.rb
│   └── webserver
│       ├── inspec.lock
│       ├── inspec.yml
│       └── controls
│           ├── 01-connections_backend.rb
│           ├── 02-webserver-config.rb
│           └── inspec.lock
└── README.md
```
More information is here https://www.inspec.io/docs/reference/profiles/#using-controls-from-an-included-profile. All the service profiles depend on the resource pack. (resource pack is a essentially a profile with libraries but no control). Resources are available in all dependencies. You can even build a meta profile that aggregates multiple profiles into one. Have a look at https://github.com/chris-rock/acme-inspec-profile as an example. Please let me know if this helps

**Comment by rockandska** [comment]
Thanks for your answer.

I just dig in this structure to test it and it seems to work, but it require to : 

- add new profile to the root inspec.yml when we add a profile
- don't pay attention to the 'No tests executed' triggered by empty controls only here to "orchestrate" the profiles
- be careful with the order of the profile inside the root inspec.yml because it seems that is this order who prime over the order of 'include_profiles'
```
$ cat inspec.yml 
name: test
depends:
  - name: backend
    path: profiles/backend/
  - name: webserver
    path: profiles/webserver/
$ cat controls/all.rb 
include_controls 'backend'
include_controls 'webserver'
$ inspec exec .  -t docker://a03cf9daf283 | grep 'Profile:'
Profile: test
Profile: backend
Profile: resource_pack
Profile: webserver
```
With reverser order only inside root inspec.yml
```
$ cat inspec.yml 
name: test
depends:
  - name: webserver
    path: profiles/webserver/
  - name: backend
    path: profiles/backend/
$ cat controls/all.rb 
include_controls 'backend'
include_controls 'webserver'
$ inspec exec .  -t docker://a03cf9daf283 | grep 'Profile:'
Profile: test
Profile: webserver
Profile: backend
Profile: resource_pack
```
Not sure if it is a bug, but it we'll be more relevant to base the order of what is inside "controls/all.rb" :)

Thanks for the tips,

Best regards

**Comment by FilBot3** [comment]
There isn't an include libraries option for InSpec?
