### ISSUE TITLE
[QUESTION] do resources such as inetd_conf, xinetd_conf support drop in configuration?

### ISSUE THREAD

**Issue by ghost** [inspec/inspec#2098]
do resources such as inetd_conf, xinetd_conf support drop in configuration?  like `/etc/xinetd.d/*` or `/etc/inetd.d/*`?

**Comment by clintoncwolfe** [comment]
It looks like "no".

The inetd.conf resource simply reads the main config file, and does not loop over any file located in a drop-in directory.  See [the inetd.conf reading code](https://github.com/chef/inspec/blob/master/lib/resources/inetd_conf.rb#L37)

The xinetd code is similar.

As a counterexample, the postgres_conf resource _does_ look for "drop-in" config files, and loops over them, reading their contents - [see here](https://github.com/chef/inspec/blob/a6582bea9b66a9808a04c47afc88369847867035/lib/resources/postgres_conf.rb#L96).

If the location of the drop-in files is consistent, it wouldn't be difficult to add that functionality to inetd_conf and xinetd.

In the meantime, a workaround would be - since both inetd_conf and xinetd resource accept the conf path as the argument - you could explicitly target your drop-in files.  That means you have to know what's there (you could glob and loop, at the cost of readability).

```
describe inetd_conf do
  # Tests for the main file
end
describe inetd_conf('/etc/inetd.conf.d/telnet.conf') do
  # tests for the telnet drop-in, which you expect, presumably
end
```

**Comment by ghost** [comment]
Is this something worth supporting?

**Comment by adamleff** [comment]
Hi friends, @pantocrator27 and @clintoncwolfe!

Unfortunately, the `inetd_conf` resource does not support drop-in configuration.

However, the `xinetd_conf` service does actually parse drop-in files. It specifically looks at the config file (`/etc/xinetd.conf` by default, but a non-standard path can be provided), reads that in, and looks for any `includedir` directives and parses all files in those directories.

Here's an example Ubuntu 16.04 machine I just spun up, did an `apt-get install xinetd` on it, and then ran a test in the InSpec shell:

```
root@vagrant:~# ls -l /etc/xinetd.d
total 20
-rw-r--r-- 1 root root 640 Oct 26  2013 chargen
-rw-r--r-- 1 root root 502 Oct 26  2013 daytime
-rw-r--r-- 1 root root 391 Oct 26  2013 discard
-rw-r--r-- 1 root root 422 Oct 26  2013 echo
-rw-r--r-- 1 root root 569 Oct 26  2013 time
```

```
inspec> xinetd_conf.where { protocol == 'tcp' }.services
=> ["discard", "echo", "daytime", "chargen", "time"]
```

If there are configurations InSpec supports today that support drop-in configs like this but InSpec doesn't know how to handle it, we happily accept contributions to enhance that functionality. If you're uncomfortable contributing code, please don't hesitate to log an issue asking for a feature enhancement and hopefully someone will help contribute toward that enhancement.

I hope this helps! I'm going to close this issue for now, but if you have any additional questions, please don't hesitate to ask, or feel free to drop into the [community slack](http://community-slack.chef.io) in the `#inspec` channel!
