### ISSUE TITLE
Feature Request: gem dependency checks for profile

### ISSUE THREAD

**Issue by adamleff** [inspec/inspec#2113]
When writing a custom resource, a user may wish to utilize a gem that's not part of InSpec's dependency tree. While I don't think vendoring gems or providing a method for installing them should be part of InSpec core (at least for right now), it would be great to define a gem as a dependency and have InSpec fail if the gem is not available.

I'd love to see the required gems listed in the `inspec.yml` and then `inspec check` and `inspec exec` would provide helpful user messaging if the gem is not available.

**Comment by clintoncwolfe** [comment]
For the gem listing in inspec.yml, do you envision that including versioning constraints?

**Comment by adamleff** [comment]
Not necessarily for the first iteration, but it's the natural progression of a feature like this to go from "make sure this gem is here" to "make sure a gem matching this constraint is here" to "install this gem if needed"

I want to stop at the constraint evolution first to see how people use this kind of feature, especially given how many various ways InSpec can be used and how we likely won't be able to control the Ruby runtime in each of those various situations.

**Comment by nicutor** [comment]
+1

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
