### ISSUE TITLE
Display execution time of each test step

### ISSUE THREAD

**Issue by dialex** [inspec/inspec#2118]
### Description

It would be helpful if each line outputted by InSpec on `format=cli` had the execution time of that specific step. For `control` lines, it could display the sum of its test steps.

This is useful to find which tests are taking the longest, so we can optimise our suite execution time.

### Example

```
2017-09-04T13:36:01 ✔  Test framework (1.0): InSpec is running correctly (223ms)
2017-09-04T13:36:01   ✔  File unit/controls/test_framework.rb should be file (100ms)
2017-09-04T13:36:01   ✔  Command echo Hello World stdout should match "^Hello World$" (123ms)
```

**Comment by adamleff** [comment]
Thanks for your feature request, @dialex! I agree this would be good information to have.

I would hesitate to include it in the CLI formatter by default just because it might clutter up the output for users who don't currently care about output, but I would definitely support a new formatter that subclasses the existing CLI formatter (maybe call it `cli-with-times` or something like that that would add this info.

I'd also add it to the `json` formatter, too. It would be super-easy to add the timing as another key/value pair to each control and still have it be backward-compatible with other systems that consume it.

**Comment by dialex** [comment]
That makes perfect sense! I don't mind using a specific formatter like `cli-timestamped`.
Please ping me when such feature is implemented.

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
