### ISSUE TITLE
auditd_rules does not handle disabling of file watches properly

### ISSUE THREAD

**Issue by trevor-vaughan** [inspec/inspec#2123]
### Description

If you enter `auditctl -A exit,never -F path=/tmp/foo -F perm=x` this effectively removes the file watch from the list.

However, the `auditd_rules.rule` hash has the following: `{:file=>"/tmp/foo", :key=>nil, :permissions=>"x"}`.

### InSpec and Platform Version

1.35.2

### Possible Solutions

The `auditd_rules` processor needs to handle `exit,never` cases.

**Comment by jburns12** [comment]
@trevor-vaughan 

I think this is moreso related to the behavior of auditctl. When I run this auditcl -A command, it adds the following file watch rule to the beginning of the rules list as perceived when running auditctl -l:

`-w /tmp/foo -p x`

It seems that since it's in file format vs. syscall format then exit, never isn't parsed. Since the auditd_rules resource uses auditctl -l to grab the rules list, I don't think it's a bug in the resource.

**Comment by adamleff** [comment]
@trevor-vaughan I'm inclined to close this issue based on @jburns12's response. Do you feel there is any further action to be taken on this issue?

**Comment by trevor-vaughan** [comment]
@adamleff I need to run through it manually again and see if I can repeat what I was doing.

**Comment by adamleff** [comment]
OK @trevor-vaughan that's fair. I'll keep this issue open for a week or so, close it if we don't hear from you, and then we can always reopen it if necessary!
