### ISSUE TITLE
command resource does not handle '*' wildcard

### ISSUE THREAD

**Issue by rx294** [inspec/inspec#2135]
### Description
@arlimus @adamleff @aaronlippold 
The command resource does not handle commands with  '*' wildcard
This issue shows up when the backend is 'ssh' and sudo is active.
it is NOT an issue when the backend is docker (no surprise since you are root) or local (WinRM should be different since this is caused by sudo).

This is a pretty serious issue. 

### InSpec and Platform Version

Inspec version : 1.36.1

### Replication Case
The screenshot below shows inspec shell onto an centos 7 image using ssh

![image](https://user-images.githubusercontent.com/17052944/30275872-e4618d72-96d0-11e7-9cc6-c508a117afee.png)
As you can see when the command('ls /etc/nginx/sites-enabled/vserver1.conf') lists the file
while command('ls /etc/nginx/sites-enabled/*.conf') does not

below is the screenshot shows comand execution without inspec using ssh 
![image](https://user-images.githubusercontent.com/17052944/30277564-2ed8af84-96d6-11e7-9d77-223ea05c335d.png)

### Possible Solutions

Sudo to wrap the entire command.

**Comment by arlimus** [comment]
This is caused by an unprivileged glob extraction before sudo permissions are actually given. It can easily be replicated by running the command manually (`sudo ls /something/with/no/perms*.glob`)

**Comment by arlimus** [comment]
Possible workaround for now: `bash` or wrap in another shell (`sudo bash -c ...`)

**Comment by adamleff** [comment]
After thinking about this for quite a while and after some lengthy discussions, I believe this is "working as designed." If you log into a host and run the example command `sudo ls /something/with/no/perms*.glob`, it will also fail because the glob expansion happens before the arguments are passed to `sudo`. Any change to the `command` resource to add some magic to make this work will either eliminate the predictability of the resource, or will introduce unintended side effects - the only real fix we can implement is to execute in a subshell and we either will need to do shell detection or just "pick a shell" which will definitely irritate some users (i.e. environment variables in rc files may not be present, etc.) and would definitely be a breaking change.

I see the existing workarounds as the actual correct user-side fixes as they would need to be implemented whether InSpec was in use or not... either use the `bash` resource (which acts as a sub-shell) or call the sub-shell of your choice yourself i.e. `describe command('su -c ls /etc/foo.*')`

We will address the `find_files` issue separately by executing that in a sub-shell since that implementation is isolated in its use and expected return. But changing the `command` resource to address glob expansion will have many negative impacts.

Thanks for submitting this issue, @rx294.
