### ISSUE TITLE
SysV service should be running bug

### ISSUE THREAD

**Issue by danhiris** [inspec/inspec#2137]
### Description

The service test is failing.

This is my spec test:
`describe service('nslcd') do
  it { should be_enabled }
  it { should be_running }
end`

This is the output:
`  Service nslcd
     ✔  should be enabled
     ∅  should be running`

The problem stems from this code:
/opt/chefdk/embedded/lib/ruby/gems/2.4.0/gems/inspec-1.35.1/lib/resources/service.rb 

on SystemV systems, 

service <service> status returns 1, even though when run manually it returns 0

This is the version of inspec that the latest chefdk uses.

I added the following to debug:

```
...
class SysV < ServiceManager
...
      cmd = inspec.command("#{service_ctl} #{service_name} status")
      **p "DEBUG"
      p cmd
      p cmd.result
      p cmd.exit_status**
      running = cmd.exit_status == 0


```

output is:
```
"DEBUG"
Command service nslcd status
#<struct Train::Extras::CommandResult stdout="", stderr="sudo: service: command not found\n", exit_status=1>
1
```

On the kitchen system:

```
[dev] root@<edited server name> ~ # service nslcd status
nslcd (pid  3146) is running...
[dev] root@<edited server name> ~ # echo $?
0
```

### InSpec and Platform Version

inspec-1.35.1 (latest chef dk version)

### Replication Case

try to verify if a service is running on any system that is using SysV

### Possible Solutions
look for service in /sbin

### Stacktrace
NA

**Comment by jerryaldrichiii** [comment]
@danhiris, which OS are you testing on? I am unable to replicate this behavior on using InSpec 1.35.1 and CentOS 5.10.

Most code paths pass in `/usr/sbin/service` or `/sbin/service`, however the following paths would lead to just `service` being ran:

  - Using Wind River Linux:
    https://github.com/chef/inspec/blob/v1.35.1/lib/resources/service.rb#L145
    https://github.com/chef/inspec/blob/v1.35.1/lib/resources/service.rb#L400

  - Using Upstart and `initctl` exits non-0 or returns no info:
    https://github.com/chef/inspec/blob/v1.35.1/lib/resources/service.rb#L341

In either case, the issue comes down to the $PATH variable. See my note here: https://github.com/chef/inspec/issues/450

If you can get me the OS details then I can begin working to resolve the issue. In the meantime you can do the following:

```
describe service('sshd', '/sbin/service') do
  it { should be_running }
  it { should be_enabled }
end
```

Looking forward to hearing from you!

**Comment by jerryaldrichiii** [comment]
Given the age and inability to reproduce, I'm going to close this.

Feel free to reopen if this is still an issue.
