### ISSUE TITLE
RFC: XCCDF Specification Support

### ISSUE THREAD

**Issue by adamleff** [inspec/inspec#2142]
# Support XCCDF for control metadata and specification

## Motivation

    As an user focused on compliance in my organization,

    I want to use InSpec to execute my compliance tests
    and consume already-created control specifications,

    so that I avoid duplication of effort when creating
    compliance profiles and reduce the time necessary to
    begin using InSpec to audit my fleet.

The [Extensive Configuration Checklist Description Format](https://scap.nist.gov/specifications/xccdf/) (XCCDF) is a common mechanism for describing, in a machine-readble format, a set of items that must be checked in order for a machine or application to be compliant. Each of these items generally has a collection of metadata that is useful to those implementing the tests or consuming the test results, such as title, description, target platforms, and more.

XCCDF (and the OVAL format in which it is usually embedded) is primarily XML and difficult for humans to read and consume. Many users choose to use InSpec because of its easy-to-read language. However, it is time-consuming to copy/paste from the OVAL/XCCDF data into an InSpec profile and to keep the data in-sync between the original OVAL files and the InSpec profile over time.

This effort is focused on the control metadata only. The actual tests to be executed are not covered by this work and there are no plans to support test language import from other sources; the InSpec language remains the sole manner in which to describe the tests to be executed.

## Specification

Within a profile, InSpec will support including XML files that contain XCCDF information in a new directory named `specifications/xccdf`. By placing in an `xccdf` subdirectory, we can more fluidly support additional specification formats in the future. Each file in `specifications/xccdf` should contain a single `<xccdf:Benchmark>` node.

The initial implementation will support reading the title and description from the XCCDF specifications file. Additional tags and other metadata may be supported in future iterations.

### Controls

The control DSL will be enhanced to support specifying the specification and rule ID to use for the title and description using a new `specification` keyword:

```ruby
control 'prevent-customer-experience' do
  specification type: :xccdf,
    source: 'scap_gov.nist_USGCB-ie7.xml',
    id: 'xccdf_gov.nist_rule_PreventParticipationInCustomerExperienceImprovementPrograms_LocalComputer'
  impact 1.0

  describe some_resource do
    it { should exist }
  end
end
```

If a `title` or `desc` is specified in the control in addition to the `specifications`, the `title` and/or `desc` will override the `specifications` content.

### Error Checking

The `inspec check` command should check the following:
 - Each file in `specifications/xccdf` is a valid XML document
 - All rule IDs across all XML files in `specifications/xccdf` are unique
 - Any control that uses the `specification` keyword passes"
   - a valid `type` (with `:xccdf` being the only initial valid type)
   - a source file name that exists within the profile
   - an ID that exists within the source file

### Report Formatters

The `json` formatter should be modified to include the specifications information as a hash object for each control for which specifications were provided:

```json
{
    "specification": {
        "type": "xccdf",
        "source": "scap_gov.nist_USGCB-ie7.xml",
        "id": "nist_rule_PreventParticipationInCustomerExperienceImprovementPrograms_LocalComputer"
    }
}
```

There are no plans to modify any other report formatter to include the specification details; the existing report formatters will display the title and description as provided by the specifications source.

## Inspiration

This work was inspired by Pull Request #2008 by @NF07.

## Copyright

This work is in the public domain. In jurisdictions that do not allow for this,
this work is available under CC0. To the extent possible under law, the person
who associated CC0 with this work has waived all copyright and related or
neighboring rights to this work.

**Comment by adamleff** [comment]
@trevor-vaughan we're kicking around an approach to properly support XCCDF as a way of specifying control metadata/specifications. I'd be interested in your feedback for this RFC. Thank you!

**Comment by trevor-vaughan** [comment]
@adamleff Thanks for the heads up, I definitely want to be part of this.

* Suggestion: Link back to the original XCCDF PR since this format seems to be directly derived from that
* Thought: I think that this format is ideal for my purposes including ease of understanding and use
* Thought: Should we provide a way to capture other information?
  * Probably not for the first cut
* Thought: We *may* want to allow for multiple specifications, with one being marked default.
  * Many, if not most, checks can meet multiple specifications and sometimes controls within those specifications. Being able to note *all* of them at the same time, could be very advantageous. Basically, if you stop focusing on the specs, and focus on the tests, you can mine the output for what you need on the other side and/or drive the entire process from profiles. Doing this would pretty much eliminate code duplication and make it a data manipulation problems instead of a drudgery problem.

**Comment by adamleff** [comment]
@trevor-vaughan 

 * link to the prior PR has been added
 * I opted to just focus on title/description for the first cut because a) it's a pretty easy win based on prior feedback, and b) we want to approach this iteratively so we better understand how people are using this and what other pain points exist
 * I'm not sold on multiple specifications because controls can (and should) only have one title/description and allowing multiple but displaying one eludes transparency. I understand the need though. Is this something that could be addressed on a per-use-case by having a tag called "satisfied_rules" that could be an array of Rule IDs that you could then mine for purposes of reporting?

**Comment by trevor-vaughan** [comment]
@adamleff I'm fine with all of this. My main issue is that I'm rapidly finding that there needs to be a solution for reusable checks since there is a LOT of cross-pollination. For round 1 all of this is just fine and we can figure out the rest as we go along.

**Comment by adamleff** [comment]
Thanks for taking the time to provide your feedback, @trevor-vaughan!

**Comment by trevor-vaughan** [comment]
Has this moved forward at all?

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
