### ISSUE TITLE
semver comparison of version numbers

### ISSUE THREAD

**Issue by yzl** [inspec/inspec#2147]
### Description
It would be convenient to have `semver` as a method on `package` that returns the semver version, so that one could do something like:

```
inspec> describe package('automate') do
inspec>   its('version') { should be >= '1.6.2-1.el7' }
inspec> end 
``` 

Additionally, a generic `semver` resource that could be used with any version string would be lovely.

Note that, as @adamleff and @mivok explained to me, inspec already pulls in the `semverse` gem, allowing one to do semver comparisons like this:

```
inspec> describe Semverse::Version.new('1.2.4') do
inspec>   it { should be >= Semverse::Version.new('1.2.3') }
inspec> end
```

The additional syntactic sugar would be nice to have, though.

### InSpec and Platform Version

inspec 1.33.1 on OS X 10.11.6

**Comment by adamleff** [comment]
Thanks for the feature request, @yzl! I agree this would be great to have.

**Comment by clintoncwolfe** [comment]
What should we do when we can't parse a platform's version numbers? 

Semver seems to do OK on most platforms - though it may be a bit lossy.  The only one I've hit a problem with is windows packages of the form w.x.y.x (like Chef: 12.12.15.1) - Semverse throws an exception on that (see https://github.com/berkshelf/semverse/blob/master/lib/semverse/version.rb#L18 )

**Comment by adamleff** [comment]
Ideally we'd raise an exception that would indicate we couldn't parse the version. If not, we should just return `nil` for now.

**Comment by clintoncwolfe** [comment]
Implementing as proposed is a bit problematic, as we'd have to constantly be trying to coerce things from strings into Semverse package versions (without any hint that we're looking at a version).

However, it turns out that InSpec implements a [custom matcher](https://github.com/chef/inspec/blob/master/lib/matchers/matchers.rb#L269), `cmp`, which is intended for exactly the case when you want to be sloppy about casting.   It runs a series of heuristics (some of which are not presently documented), and in fact one of the heuristics is whether it looks like a version number (currently according to Gem::Version).

So, one approach would be to replace the Gem::Version check with a Semverse::Version check (which I think is a superset of Gem::Version - I'll need to check on that) and possibly reorder the heuristics if needed.  Then your experience would be:

```
inspec> describe package('automate') do
inspec>   its('version') { should cmp >= '1.6.2-1.el7' }
inspec> end 
```

It's not full syntactic sugar, but it beats having to spell out `Semverse::Version.new()` each time.  Thoughts?

**Comment by adamleff** [comment]
@clintoncwolfe that approach seems totally fine to me, with an exception raised with a helpful message if we couldn't coerce the version into a valid SemVer string with which to compare.

Re: syntactic sugar, it'd probably be good to just make a standalone resource that can be used:

```ruby
describe semver('1.2.3') do
  it { should >= 1.0.0 }
end
```

... then users can use that in their own custom resources or anything else that might emit a version string that can be compared.

**Comment by clintoncwolfe** [comment]
It appears that Gem::Version may be better; it can already parse things like "1.2.3.4".  `cmp` intercepts the exception and falls back to string comparison if it can't parse.

So, it looks like the desired functionality is already in place using cmp - this just works:
```
inspec> package('curl').version
=> "7.35.0-1ubuntu2.10"
inspec> describe package('curl') do; its('version') { should cmp > '7.4.0-1ubuntu2.10' };  end

Profile: inspec-shell
Version: (not specified)

  System Package
     ✔  curl version should cmp > "7.4.0-1ubuntu2.10"

Test Summary: 1 successful, 0 failures, 0 skipped
inspec> describe package('curl') do; its('version') { should cmp < '7.35.0-1ubuntu3.10' };  end

Profile: inspec-shell
Version: (not specified)

  System Package
     ✔  curl version should cmp < "7.35.0-1ubuntu3.10"

Test Summary: 1 successful, 0 failures, 0 skipped
```

I'm less clear on the uses of a dedicated semver resource, but I don't see any obstacles there.

**Comment by clintoncwolfe** [comment]
Knowing that the `cmp` matcher can be used with any resource, and will attempt version string comparison prior to string or numeric comparison,  is there still a need for a semver resource?

**Comment by yzl** [comment]
I don't have a strong opinion either way, since you've documented that `cmp` will do version string comparisons in a reasonable way.

**Comment by adamleff** [comment]
I'm fine closing it until we have more demand for a standalone resource.
