### ISSUE TITLE
etc_fstab resource: method nfs_file_systems not working as expected in relation to given example

### ISSUE THREAD

**Issue by jburns12** [inspec/inspec#2195]
### Description

The method nfs_file_systems in the etc_fstab resource was returns a single hash vs. an array of hashes as expected in the given examples.

### InSpec and Platform Version

1.39.1

### Possible Solutions

Solution is represented in PR #2190

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
