### ISSUE TITLE
[Feature] Ability to specify number of matches

### ISSUE THREAD

**Issue by qvallance-ctc** [inspec/inspec#2212]
### Description

When using matchers it would be useful to able to specify whether there should only be one match (or possibly, the number of matches).  Currently, we can only determine if there is one or more matches in a file.  This can be problematic if duplicate entries are accidentally added to a file, as it will pass the match and be deemed compliant by Inspec but be an invalid config.

**Comment by aaronlippold** [comment]
Could you provide some example use cases so we can better understand the scope of what you are trying to describe in your tests.

**Comment by qvallance-ctc** [comment]
Sure.   We use a config management tool (Ansible) to configure systems as part of our image building pipeline.  We also use Inspec to test the final state of the image configuration before promoting it.   Sometimes, rather than managing a file's configuration using a template, we will perform a search and replace to add an entry to a file.   We've encountered issues we're someone has made a mistake and their Ansible task accidentally adds a duplicate entry to a file, rather then just updating/replacing the existing entry.   With Inspec, we are checking to make sure the entry exists with a matcher, which it does, but we cannot catch accidental duplication of entries (e.g., match > 1).  This could easily be the same issue when a user manually adds entry to the end of a long configuration file, not realizing the entry already exists near the beginning of the file.

**Comment by ryancurrah** [comment]
I think an example of what he is trying to explain is...

/etc/somesettings.conf

```
some_setting1 = 0
some_setting1 = 100
```

It would be nice if there was a matcher that ensures there is only one match of `some_setting1 =` in this file and it’s value should equal 100. Otherwise fail the match.

**Comment by adamleff** [comment]
It's not easy to modify matchers to permit this behavior because, by the time the matchers are invoked, the content has already been read and parsed by the resource.

However, you can take advantage of some core InSpec functionality to do this. For example, we provide a `parse_config_file` resource that uses our `SimpleConfig` parser underneath. By default, SimpleConfig only permits one value per key, taking the last value as the "actual" value, but you can override that behavior.

For example, given this file contents:

```
foo = bar
test1 = value1
foo = another_bar
```

... you can use `parse_config_file` in the InSpec shell to read in the contents:

```
inspec> parse_config_file('/tmp/test.ini', multiple_values: true).params
=> {"foo"=>["bar", "another_bar"], "test1"=>["value1"]}
```

Note that every key has an Array of values will contain all the values that match the key. So you can write a test like this:

```ruby
describe parse_config_file('/tmp/test.ini', multiple_values: true) do
  its('foo.length') { should eq 1 }
end
```

That test would fail on the above example config because `foo` has multiple values.

I hope this helps!
~Adam
