### ISSUE TITLE
BUG: etc_fstab resource returns a list of list instead of just a list

### ISSUE THREAD

**Issue by linusguan** [inspec/inspec#2236]
### Description

When using etc_fstab resource, `its('mount_options')` returns a list of list (i.e. `[['value']]`) instead of just a list (i.e. `['value']`).
This behaviour is not consistent with other resources like `passwd` and made `include` matcher useless.

### InSpec and Platform Version

1.41.0 running on macOS against Amazon Linux

### Replication Case
```
control 'test' do
  describe etc_fstab.where { mount_point == '/' } do
    its('mount_options') { should include 'noatime' }
  end
end
```
### Stacktrace
```
∅  test: etc_fstab with mount_point == "/" mount_options should include "noatime" (expected [["defaults", "noatime"]] to include "noatime")
     ×  etc_fstab with mount_point == "/" mount_options should include "noatime"
     expected [["defaults", "noatime"]] to include "noatime"
```

**Comment by jburns12** [comment]
Hi @linusguan .... @adamleff may have additional feedback, but this I believe this is actually the expected behavior for the resource at this point. A two-dimensional array is returned when using the where clause because there may be multiple entries in etc_fstab based on the given option. Even though you wouldn't likely see two entries with this same mount_point, this is a by-product of using the FilterTable data structure within the etc_fstab resource.

If you're only expecting a single entry in etc_fstab with the mount_point of '/', I believe you can use flatten as such to remove the outside layer of the array..

    control 'test' do
      describe etc_fstab.where { mount_point == '/' } do
        its('mount_options.flatten') { should include 'noatime' }
      end
    end

**Comment by linusguan** [comment]
Thanks a lot @jburns12, your solution is much elegant than my workaround. 
I was using 
```
fs = etc_fstab.where { mount_point == '/' }.entries
  fs.each do |file_system|
    describe file_system do
      its ('mount_options') { should include 'noatime' }
```
I will close the ticket and learn more Ruby =)
Maybe we should include some common patterns of manipulating data using Ruby in the documentation.

**Comment by adamleff** [comment]
@linusguan as you discovered, this is a side-effect of a component in InSpec called `FilterTable` (which is where the `where` method comes from). As @jburns12 described, items in the FilterTable can contain multiple values so they are returned as an Array. And a `where` method can return multiple items, so it will return an Array... so that's the origin of the Array-within-an-Array response you got.

I agree that it's less-than-desirable, so we have an issue in our backlog (#1678) to add another `where`-type searcher that will only return one item and strip the outer Array if needed.

Thanks to @jburns12 for pitching in to explain!

~Adam

**Comment by linusguan** [comment]
@adamleff Thanks for your explanation. I have subscribed to the backlog item. Cheers!
