### ISSUE TITLE
describe.one should exit as soon as there is a match

### ISSUE THREAD

**Issue by mattray** [inspec/inspec#2251]
### Description

When using a describe.one loop, all conditions are checked even if there has already been a successful match. 

### Replication Case

In the [WannaCry profile](https://github.com/adamleff/inspec-profile-wannacry-exploit/blob/master/controls/hotfixes.rb) 86 Hotfixes are checked even if there has already been a successful check, and this very slow on older versions of Windows.

```ruby
  describe.one do
    hotfixes.each do |hotfix|
      describe windows_hotfix(hotfix) do
        it { should be_installed }
        # break if ...
      end
    end
  end
```

### Possible Solutions

Check the output of the resource and break if it was successful.

**Comment by adamleff** [comment]
This is probably worthy of some additional discussion since this would be breaking behavior. The current behavior is to show the result of all passed tests. While it should be technically possible to break out of the test cycle for a `describe.one` block once a passed test is hit, we would be eliminating the success results of any other tests that succeeded.

I think it might be better to see if we can refactor the `windows_hotfix` resource to be faster (as discussed in community slack last night... maybe refactor it to grab ALL the hotfixes, use FilterTable, and then we can do the searching in one test rather than looping over multiple) instead of introducing a behavior change on `describe.one`.

If it's decided this functionality is required, then we need some graceful way for a user to opt-in... probably with some sort of DSL keyword we can expose inside the `describe.one` block...

```ruby
describe.one do
  stop_on_first_success true
  describe foo ...
```

@arlimus @chris-rock your thoughts?

**Comment by chris-rock** [comment]
I think that is a very dangerous move and we should not mix system logic with ruby logic. @mattray is there any reason why the following is not working?

```
 describe.one do
    fix = false
    hotfixes.each do |hotfix|
      next if fix
      hf = windows_hotfix(hotfix)
      fix = true if hf.installed?
      describe hf do
        it { should be_installed }
      end
    end
  end
```
Maybe we can simplify the code still, but essentially that problem should be already solvable in ruby and we are not adding any additional compliance logic. Are we?

**Comment by adamleff** [comment]
I'm not sure I see the difference between "system logic" and "ruby logic" in this case. I also don't know that I'd call it "dangerous"... it's just a different use case where the acceptance criteria isn't as strict.

For example, for an integration test user, if they're testing that 1 of 7 things must pass, they likely only care that at least 1 passed and don't really care the success status of ALL the tests that passed. A compliance user likely has a very different point-of-view about that and wishes to see ALL the passing tests. One could even make the argument that we should be also returning the failed tests but in a different color so the user with a compliance mindset sees what failed vs. what we do now which is hide those results.

While the Ruby code provided above would work fine, we can't assume all of our users have enough Ruby knowledge to do that.

Again, I'm not advocating that we must introduce this feature request... but I can totally see the use case and we should be welcoming to that. Ultimately, I think this feature request stems from the fact that a particular test chain is super-slow, and I'd rather fix that than introduce this feature.

**Comment by chris-rock** [comment]
I agree with you @adamleff making it fast is the first priority. Maybe we need to return a result from the describe block, to avoid the call to the resource twice?

**Comment by mattray** [comment]
I tried rolling in @chris-rock's version, it works. 

I opened the issue to point out that ```describe.one``` should be optimistic and exit as soon as ```one``` match was made. I've made the code more efficient by splitting the testing by Windows versions, but exiting on a match would be even faster. Feel free to close it if we don't want to optimize this.

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
