### ISSUE TITLE
http resource execute locally should not be deprecated

### ISSUE THREAD

**Issue by chrisLeeTW** [inspec/inspec#2281]
### Description
In current latest version, If you use http resource with ```enable_remote_worker: false```
you will got deprecated warning message.

But in some testing scenarios. you will need http resource execute locally, such as testing location allow directive with different ip ranges with docker.

If make http resource always execute remotely, you will not be able to testing such scenario.

### InSpec and Platform Version
inspec version : 1.43.5 via docker (https://hub.docker.com/r/chef/inspec/)
target OS platform: ubuntu
target OS family: debian
target OS release: 16.04

**Comment by adamleff** [comment]
@chrisLeeTW the decision to deprecate this behavior is important to maintain consistency with all other InSpec resources. All other resources operate on the local system when executed remotely, and on the remote system when scanning a remote target. Blurring this behavior for a single resource will yield a more confusing experience for our users.

Is there any reason you couldn't break out your HTTP tests into a separate profile that you execute locally instead of while scanning a remote target? If you're testing the ability for machine A (ex: your workstation) to reach machine B (ex: the node you're testing), the test should be initiated from machine A. That would be more in-line with the expected behavior of any other resource, including the `host` resource for example.

**Comment by chrisLeeTW** [comment]
@adamleff Thanks for your reply and I'm fully understand the reason.

Currently I want to http resource execute locally is because I want to testing allow directive with my server location in nginx.conf.

So If http resource always execute remotely, then I was not able to access nginx with another ip different to 127.0.0.1.

And I will never know nginx allow directive is fully functional.

**Comment by chrisLeeTW** [comment]
@adamleff Thanks for your reply and I'm fully understand the reason.

Currently I want to http resource execute locally is because I want to testing allow directive with my server location in nginx.conf.

So If http resource always execute remotely, then I was not able to access nginx with another ip different to 127.0.0.1.

And I will never know nginx allow directive is fully functional.

**Comment by adamleff** [comment]
@chrisLeeTW your use case makes perfect sense to me, and I'm glad to see you use InSpec for that purpose.

The solution will be to move those HTTP checks to a separate profile and run them in local execution mode, rather than with `--target`, so that the HTTP calls will be initiated from your local machine instead of from within the remote machine. You can use InSpec Attributes to make the HTTP host a variable so you don't have to hardcode information and therefore build only one profile for your needs.

I hope this helps.
