### ISSUE TITLE
Add a 'sudo_required' feature to tests

### ISSUE THREAD

**Issue by trevor-vaughan** [inspec/inspec#2300]
### Description

Based on the conversation over at https://github.com/simp/inspec-profile-disa_stig-el7/issues/2, it would be nice to have the ability to indicate that a test requires `sudo` privileges to run.

This would allow tests to fail and/or be skipped if the user does not have permissions to run commands under `sudo`.

### Possible Solutions

I would suggest a `sudo_required` keyword to effect this restriction.

**Comment by adamleff** [comment]
While I totally understand the use case, I'm :-1: on adding something specific to sudo being required. The end-state for the user is the same: they need some feedback as to why their test was skipped or failed. That COULD be done initially by the control/test author, but in fact could affect more than just root privileges.

We recently implemented a change that allows resource authors and the InSpec core team to raise better exceptions in resources, the messages of which will be surfaced to the user. So, we now possess the ability to return a message like "Could not read file /foo/bar, insufficient permissions" instead of just returning `nil`s for all the parameters.

Whether the control/test author predicted root privileges were needed or whether InSpec/Train is smart enough to give feedback, the UX is the same... the user needs to get feedback as to why the test failed/skipped.

I'd rather see us add better error messaging into the existing resources to provide that feedback.

**Comment by trevor-vaughan** [comment]
@adamleff That makes sense. The reason I was thinking this for `sudo` is that it's probably, by far, going to be the thing that causes issues across the board. No issue with the closure.

**Comment by adamleff** [comment]
In some ways, `sudo` is the hammer with which you solve the symptom, but in fact it could mask the real issue. For example, it's perfectly acceptable for a non-root user to do a `file` test against a file for which the user cannot read the file. Perhaps that's on purpose, but without surfacing that feedback, the user won't know. And "run with sudo" may not be the right option.

**Comment by trevor-vaughan** [comment]
That was actually the idea.

This may explain it better:

```ruby
control "V-72089" do
  title "The operating system must immediately notify the System Administrator (SA)
and Information System Security Officer ISSO (at a minimum) when allocated audit
record storage volume reaches 75% of the repository maximum audit record storage
capacity."
  desc  "If security personnel are not notified immediately when storage volume
reaches 75 percent utilization, they are unable to plan for audit record storage
capacity expansion."
  impact 0.5
  describe auditd_conf do
    # EXAMPLE
    # This evaluation, like many others, simply can't be done without 'root' privileges.
    #
    # This could be 'apache' in some cases, or other application names in others.
    #
    # The point is that this is a *very* common point of failure and irritation for users
    # and it can either be abstracted by inspec core or the burden placed on
    # the individual profiles/plugins

    sudo_required('root')

    # END EXAMPLE

    before(:all) do
      @audit_log_dir = File.dirname(auditd_conf.log_file)

      if File.directory?(@audit_log_dir)
        partition_info = command("df -h #{@audit_log_dir}").stdout.split("\n")

        partition_sz_arr = partition_info.last.gsub(/\s+/m, ' ').strip.split(" ")

        # Get partition size in GB
        partition_sz = partition_sz_arr[1].gsub(/G/, '')

        # Convert to MB and get 25%
        @exp_space_left = partition_sz.to_i * 1024 / 4 
      end
    end

    it 'should have an audit log directory' do
      expect(File.directory?(@audit_log_dir)).to be true
    end

    its('space_left.to_i') { should cmp(@exp_space_left) } 
  end
end
```

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
