### ISSUE TITLE
Support for HOCON file format

### ISSUE THREAD

**Issue by oblutak** [inspec/inspec#2337]
### Description

Add resource/support for parsing files formatted as [HOCON](https://github.com/lightbend/config/blob/master/HOCON.md)

### InSpec and Platform Version

inspec --version
1.45.13

### Replication Case

N/A - Feature Request

### Possible Solutions

There is a ruby gem, [hocon](https://rubygems.org/gems/hocon/versions/1.2.5) to parse the file format.

**Comment by adamleff** [comment]
Thanks for the feature request, @oblutak!

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
