### ISSUE TITLE
Profile attributes are not discovered correctly while using a profile dependent of another one

### ISSUE THREAD

**Issue by dmytro-malovany** [inspec/inspec#2345]
Initial idea was to discover _ALL_ Oracle instances running on a system and iterate over them.
So I decided to search for the instances and create an array where I store all the attributes related to each instance in separate hash.

But I've got a problem with passing of attributes to multiple profiles (when one profile is dependent of another one).
I will describe it further.
 
So, we have two profiles - custom-oracle depends of cis-oracle:
[root@centos-oracle-chef vagrant]# tree .
.
├── cis-oracledatabase12c-level1-rdbms
│   ├── controls
│   │   ├── controls.rb
│   ├── inspec.lock
│   ├── inspec.yml
│   └── vendor
├── custom-oracledatabase12c-level1-rdbms
│   ├── controls
│   │   └── custom-controls.rb
│   ├── inspec.lock
│   ├── inspec.yml
│   ├── libraries
│   └── vendor
│       └── hash_here.tar.gz
 
My cookbook contains a profile_detection.rb recipe with this code:
 
instances_env = []
 
`/bin/ps -eo user,args|grep -v grep|grep ora_pmon_`.lines.each do |line|
  instance_env = {}
  instance_env['User'] = line.split[0]
  instance_env['Instance'] = line.split[1].split('_')[2]
  instance_env['Home'] = `/bin/cat /etc/oratab|grep ^#{instance_env['Instance']}`.split(':')[1]
  instance_env['Sqlplus'] = Dir["#{instance_env['Home']}/**/sqlplus"][0]
  instance_env['Port'] = `/bin/sudo -u oracle -i trcroute #{instance_env['Instance']}|grep PORT`.split('=')[-1].strip
  instances_env << instance_env
end
 
node.default['audit']['attributes'] = {
  user: chef_vault_item('credentials', 'oracle')['username'],
  password: chef_vault_item('credentials', 'oracle')['password'],
  ora_attributes: instances_env
}
 
So in this case output will look like this (array with hashes):
puts instances_env
[{"User"=>"oracle1", "Instance"=>"FOO", "Home"=>"/opt/oracle/12R1/FOO", "Sqlplus"=>"/opt/oracle/12R1/FOO/bin/sqlplus", "Port"=>"1521"},
{"User"=>"oracle2", "Instance"=>"BAR", "Home"=>"/opt/oracle/12R1/BAR", "Sqlplus"=>"/opt/oracle/12R1/BAR/bin/sqlplus", "Port"=>"1522"}]
 
Later I define new attribute in profile(s):
 
ORA_ATTRIBUTES = attribute(
  'ora_attributes',
  description: 'Oracle instances attributes',
  default: [{'User'=>'oracle1', 'Instance'=>'AAA', 'Home'=>'/opt/oracle/12R1/AAA', 'Sqlplus'=>'/opt/oracle/12R1/AAA/bin/sqlplus', 'Port'=>'1528'}, {'User'=>'oracle2', 'Instance'=>'BBB', 'Home'=>'/opt/oracle/12R1/BBB', 'Sqlplus'=>'/opt/oracle/12R1/BBB/bin/sqlplus', 'Port'=>'1529'}]
)
 
And later I iterate over this array in the profiles:
ORA_ATTRIBUTES.each do |h|
  sql = oracledb_session(user: SQL_USER, password: SQL_PASSWORD, host: SQL_HOST, port: h['Port'], service: h['Instance'], sqlplus_bin: "sudo -u #{h['User']} -i #{h['Sqlplus']}")
 
  <controls here>
  ...
end
 
When I define cis-oracle profile in node.default['audit']['profiles'], it catches all attributes and works fine:
node.default['audit']['profiles'].push 'name' => 'cis-oracledatabase12c-level1-rdbms', 'compliance' => 'automate_user/cis-oracledatabase12c-level1-rdbms'
 
Sql query looks like that (it’s correct):
SELECT AUDIT_OPTION, SUCCESS, FAILURE
                                FROM DBA_STMT_AUDIT_OPTS
                                WHERE AUDIT_OPTION='ALTER SYSTEM'
                                AND USER_NAME IS NULL
                                AND PROXY_NAME IS NULL
                                AND SUCCESS = 'BY ACCESS'
                                AND FAILURE = 'BY ACCESS';
EXIT" | sudo -u oracle2 -i /opt/oracle/12R1/BAR/bin/sqlplus "ORAUSER"/"Password@123"@localhost:1522/BAR
 
 
But when I set custom-oracle profile in node.default['audit']['profiles'] which is dependent of cis-oracle profile, the ORA_ATTRIBUTES is ignored:
node.default['audit']['profiles'].push 'name' => 'custom-oracledatabase12c-level1-rdbms', 'compliance' => 'automate_user/custom-oracledatabase12c-level1-rdbms'
 
In result sql queries from CIS profile look like that:
echo "SET MARKUP HTML ON
SET FEEDBACK OFF
SELECT AUDIT_OPTION, SUCCESS, FAILURE
                                FROM DBA_STMT_AUDIT_OPTS
                                WHERE AUDIT_OPTION='ROLE'
                                AND USER_NAME IS NULL
                                AND PROXY_NAME IS NULL
                                AND SUCCESS = 'BY ACCESS'
                                AND FAILURE = 'BY ACCESS';
EXIT" | sqlplus "ORAUSER"/"Password@123"@localhost:1527/ORCL.localdomain
 
It catches correctly login and password only.
 
And then appear queries from CUSTOM profile where this ORA_ATTRIBUTES is recognised correctly:
echo "SET MARKUP HTML ON
SET FEEDBACK OFF
SELECT USERNAME
                                FROM DBA_USERS_WITH_DEFPWD
                                WHERE USERNAME NOT LIKE '%XS\$NULL%';
EXIT" | sudo -u oracle2 -i /opt/oracle/12R1/BAR/bin/sqlplus "ORAUSER"/"Password@123"@localhost:1522/BAR

Seems like there is a problem with passing of custom profile attributes over dependent profiles.
Thank you for looking into this!

**Comment by adamleff** [comment]
@bratdim thanks for submitting this issue, sorry you're running into some problems.

I have to admit I'm having trouble deciphering where the problem is in your problem report. While it's very detailed, I don't have quite as easy of a reproducible test care for me to start digging into where the problem is.

My main concern here right now is potentially a misunderstanding of our InSpec Attributes work. Attributes aren't "passed" between profiles; instead, InSpec makes them available to ANY profile that wishes to make use of them, regardless of whether they are a dependent profile or a top-level profile. It's up to the profile to request the correct attribute.

If I look at the cis-oracledatabase12c profile that I have available to me, it has attributes such as `SQL_HOST`, `SQL_SERVICE`, etc. defined. It's up to you to provide those attributes. The cis-oracledatabase12c is not going to be able to make use of your `ora_attributes` attribute array nor can you create an `oracledb_session` instance pass it to the profile.

If you're trying to run the `cis-oracledatabase12c` profile against each instance of Oracle running on a host, I'm afraid that will not work. We do not currently have a facility in which you can run a dependent profile multiple times with different attribute values in a single InSpec run.

If I'm understanding your need correctly, you would actually need to run InSpec multiple times, one for each DB instance, providing different attributes each time.

Please let me know if I'm misunderstanding your issue/concern/problem.
