### ISSUE TITLE
[idea] report to remote syslog

### ISSUE THREAD

**Issue by juju4** [inspec/inspec#2355]
### Description

I'm looking to check compliance of many systems and use my syslog server to aggregate results.
On linux, I can pipe to logger command to achieve that with for example a json output.
On windows, I would need a more integrated way.

For now `inspec exec` has no output option (https://www.inspec.io/docs/reference/cli/)
It would be nice to be able to natively send to stdout (current), a file or a remote host like syslog or netcat server.

Thanks

### InSpec and Platform Version

1.46 (not relevant)

**Comment by adamleff** [comment]
Thanks for your feature request, @juju4

**Comment by clintoncwolfe** [comment]
refs #3667

**Comment by kekaichinose** [comment]
@clintoncwolfe can this be tracked in #3667 or does it need to stay its own issue?

**Comment by kekaichinose** [comment]
Thank you for filing this issue. As with many large open source projects, we have a backlog of bugs and issues of varying user impact. Some issues are perpetually subject to lower priority than others in our backlog. We have reviewed the issue, and we have determined this a very low priority when considered in the context of the entire backlog. We have elected to close it as "Declined" due to competing priorities.

We very much appreciate you bringing this to our attention.

Thank you!
__Chef InSpec Team__
