### ISSUE TITLE
RFC: enhance git fetcher "version constraint" behavior - "Profile x from git has a version 2.2.0 which doesn't match 2.1.1"

### ISSUE THREAD

**Issue by alexpop** [inspec/inspec#2367]
With `linux-baseline` profile at version `2.2.0` in github:
```
$ tail -4 inspec.yml
depends:
  - name: linux-baseline
    git: https://github.com/dev-sec/linux-baseline
    version: 2.1.1

$ inspec vendor --overwrite
The profile linux-baseline from {:git=>"https://github.com/dev-sec/linux-baseline", :ref=>"4a62b90cbeb9126ec914ab390dcb179065736a94"} has a version 2.2.0 which doesn't match = 2.1.1
[02:09:37 ~/git/delivery/compliance-loader/pass/inspec {ap/fix-inspec-profile-pin}]$ echo $?
1

$ inspec -v
1.46.2
```

Workaround for now:
```
$ tail -3 inspec.yml
depends:
  - name: linux-baseline
    url: https://github.com/dev-sec/linux-baseline/archive/2.1.1.tar.gz

$ inspec vendor
Dependencies for profile /Users/apop/git/delivery/compliance-loader/pass/inspec successfully vendored to /Users/apop/git/delivery/compliance-loader/pass/inspec/vendor

$ echo $?
0
```

**Comment by stevendanna** [comment]
The issue here is that by default the `git` source will pull the latest master branch unless `branch`, `tag` or `ref` is specified in the dependency description (or if an inspec.lock is in use).

Once pulled, we then additionally check that any `version` constraint is satisfied.

The documentation says we do "git tags via semantic versioning" which we could certainly do.

**Comment by adamleff** [comment]
While I'm not a huge fan of adding magic, I think we can make the git fetcher and dependency finder smarter in this case with the intention of harmonizing the experience between the `compliance` fetcher and `git` fetcher. With the `compliance` fetcher, if you supply a constraint list in the `version` field, we'll find the profile that best matches. I think we can do the same here.

Pre-requisite: users must tag, and the tag must either be `X.Y.Z` or `vX.Y.Z`

Example: `version: 1.2.3` or `version: = 1.2.3`
Result: Look for a `1.2.3` tag or `v1.2.3` and use it. Raise error if not found.

Example: `version: >= 1.2.3` or `version: >= 1.2.3, < 2.0`
Result: Pull all tags from repo, strip `v` characters as needed, build array, use something like semverse to find the best version that satisfies the constraints. Raise error if not found.

Example: `version: 1.2.3 / ref: mybranch`
Result: Use the `mybranch` branch, and check the version to see if it matches the constraint. Raise error if the constraint is not met.

I think this UX will get us closer to the experience of the `compliance` fetcher. @arlimus @alexpop what do you think?

**Comment by stevendanna** [comment]
@adamleff Your write-up looks reasonable to me!  A couple of Qs below:

> Example: version: >= 1.2.3 or version: >= 1.2.3, < 2.0
> Result: Pull all tags from repo, strip v characters as needed, build array, use something like semverse to find the best version that satisfies the constraints. Raise error if not found.

If we don't find a tag, this will be a behaviour change for existing users.  I wonder if we want to "pull master and see if that satisfies the constraint" as a final step before failing.

> Example: version: 1.2.3 / ref: mybranch
I'm assuming the same behavior for `tag:` and `branch:` as well.

**Comment by adamleff** [comment]
@stevendanna:

> If we don't find a tag, this will be a behaviour change for existing users. I wonder if we want to "pull master and see if that satisfies the constraint" as a final step before failing.

Yes, agreed. We also need to debug-log the hell out of our decision-making process so people have a way to figure out our madness.

> I'm assuming the same behavior for tag: and branch: as well.

Yes absolutely. I implied but wasn't explicit. I view all three of those keywords as similar but should've been clearer. Thank you for asking!

I appreciate the feedback.

**Comment by adamleff** [comment]
Situation:
 * user supplies: `version: 1.2.3`
 * InSpec successfully finds tag `v1.2.3`
 * inspec.yml has `version: 1.2.2`

Result: raised exception with clear error message

I don't think we want to trust that just because it's tagged with a version string that the version string is correct. In the compliance profile store, the inspec.yml is authoritative.

Another option is to ignore tags and walk every tag looking for an inspec.yml that matches the user-supplied constraint, but that feels overkill to me and I'd rather be opinionated about tag formats than walk their repo. Thoughts on this one welcome as well.

**Comment by kekaichinose** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
