### ISSUE TITLE
Inspec docs: serverspec migration guide doesnt mention tests need to be in `controls/` dir

### ISSUE THREAD

**Issue by atheiman** [inspec/inspec#2369]
### Description

no idea if this is the right location for a docs issue, but this just tripped us up. It looks like when migrating from serverspec to inspec you need to move your test files into `test/integration/<suite>/controls`. This isnt mentioned on the migration guide https://www.inspec.io/docs/reference/migration/

**Comment by adamleff** [comment]
Thanks for the docs suggestion, @atheiman! This is a fine place to log it.

You are correct that tests belong in the `controls` directory, but only if you're using an "InSpec profile" structure (i.e. if you have an `inspec.yml` file, etc.). We obviously recommend that because structuring your tests in a profile provide additional benefits, such as inheriting other profiles, adding custom resources, etc.

If you were to not use a profile, you wouldn't need to put them in a `controls` directory.

I'll log this as a docs issue and we'll try to make that clearer. Thanks for your suggestion!

**Comment by atheiman** [comment]
Ahh, thank you for clearing that up for me

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
