### ISSUE TITLE
RFC: Lazy column fetching for FilterTable-based resources

### ISSUE THREAD

**Issue by clintoncwolfe** [inspec/inspec#2370]
Over at [inspec-aws issue #100](https://github.com/chef/inspec-aws/issues/100), we've been discussing the need for and advantages of being able to "lazy load" columns in the underlying dataset in a FIlterTable-based resource.

As a non-AWS example, the pattern we keep seeing is one in which we have a generic data fetching operation (say, listing running processes) with a property which must be populated by a potentially expensive secondary call (say, listing open files for a process).  In some cases we might be able to get the column value for all rows; in other cases, we are obliged to make one call per-row.

In inspec-aws land (or any other resource pack that involves remote API calls), being obliged to populate all possible cells in the table can be a large performance hit (see aws_iam_access_keys for an example).  Ideally, we'd prefer to only populate a column if it is being requested.

Several approaches involve adding a Proc (a ruby object that represents code to be executed in the future) to the FilterTable.  Where to add it, and what args the Proc should expect, are matters for discussion.  

Any solution would have to be optional: all existing FilterTable-based resources should not have to be modified.

I'd like to thank @aduric and @chris-redekop for bringing up this issue, all their careful thought into the matter, and their experimental implementations.

**Comment by aduric** [comment]
PR can be found here: https://github.com/chef/inspec/pull/2371

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
