### ISSUE TITLE
XML resource docs need updating: key with periods fails.

### ISSUE THREAD

**Issue by jekriske-lilly** [inspec/inspec#2380]
### Description

According to the current documentation, something like
``` 
describe xml('/data/backup/current/security.xml') do
    its('security/users/user/groups/org.artifactory.model.xstream.security.UserGroupImpl') { should include 'somestring' }
end
```
should function, but instead this results in an error trying to call 'artifactory' as a method in this case.
```
undefined method `artifactory' for []:Array
```

### InSpec and Platform Version

inspec 1.42.3
RHEL 7.4

### Replication Case

Try the xml resource with a leaf key that has periods.

### Possible Solutions

An alternate syntax, in this case:
```
its(['security/users/user/groups/org.artifactory.model.xstream.security.UserGroupImpl']) { should include 'somestring' }
```
works fine, but this is not documented on the website, therefore the behavior should be corrected (as a string should act like a string) or the docs should be updated with such an example using square brackets.

**Comment by adamleff** [comment]
@jekriske-lilly we cannot make a "string act like a string" in this case because the underlying library in use `rspec-its` takes the string, splits on period, and creates the method chain.

We can, however, and will update the documentation to include the alternate syntax like we have for the JSON and INI resources as well. Thanks for submitting this issue.
