### ISSUE TITLE
InSpec exec switches PS standard out to red to show an error but forgets to unset the color

### ISSUE THREAD

**Issue by SteveDelFante** [inspec/inspec#2384]
### Description

From Windows, InSpec exec switches PS stdout to red to show an error but forgets to unset the color. I am told this also happen in MacOS.

### InSpec and Platform Version

InSpec v1.48.0  and Windows 10 Pro

### Replication Case

Tell us what steps to take to replicate your problem.  

We discovered this while testing this tutorial: https://learn.chef.io/modules/try-inspec/

Then when you run this, you get the issue:

inspec exec https://github.com/dev-sec/linux-baseline -t ssh://root:password@target | grep -A 7 package-08

### Possible Solutions

If you have already ideas how to solve the issue, add them here.

### Stacktrace

Please include the stacktrace output or link to a gist of it, if there is one.
N/A but here is a screenshot of the colors sticking to thte prompt:

![image](https://user-images.githubusercontent.com/12142968/33784121-73487180-dc14-11e7-81f1-f1fc3a01079d.png)

**Comment by SteveDelFante** [comment]
I qam checking on the InSpec version used in the container.

**Comment by megamorf** [comment]
By the way, it'd be good to add very specific windows version information since each Windows 10 release can be considered a major release with changes to the Windows console host and other internals.

```
PS C:\> Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\' | 
Select ProductName,ReleaseID,Build*,Current*

ProductName               : Windows 10 Pro
ReleaseId                 : 1709
BuildBranch               : rs3_release
BuildGUID                 : ffffffff-ffff-ffff-ffff-ffffffffffff
BuildLab                  : 16299.rs3_release.170928-1534
BuildLabEx                : 16299.15.amd64fre.rs3_release.170928-1534
CurrentBuild              : 16299
CurrentBuildNumber        : 16299
CurrentMajorVersionNumber : 10
CurrentMinorVersionNumber : 0
CurrentType               : Multiprocessor Free
CurrentVersion            : 6.3
```

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
