### ISSUE TITLE
ntp_conf resource and testing clock drift

### ISSUE THREAD

**Issue by y0nigt** [inspec/inspec#2411]
Hi,
According to the [ntp_conf resource reference](https://www.inspec.io/docs/reference/resources/ntp_conf/)

The following example -
```
describe ntp_conf do
  its('driftfile') { should eq '/var/lib/ntp/ntp.drift' }
  its('server') { should eq [
    0.ubuntu.pool.ntp.org,
    1.ubuntu.pool.ntp.org,
    2.ubuntu.pool.ntp.org
  ] }
end
```
has the title 'Test for clock drift against named servers'
but it seems like it only validates the servers are defined in the ntp configuration file, nothing more. Is it possible to use this resource to test for clock drift?

**Comment by adamleff** [comment]
@y0nigt Your assumption is correct - the `ntp_conf` resource only reads the configuration. It doesn't actually interrogate the NTP daemon which would be required to determine if there is drift.

I'll flag this as a feature request and perhaps someone can implement a new `ntpd` resource... it would be cool to see something like this:

```ruby
describe ntpd do
  its('max_drift_for_any_peer') { should cmp < 0.01 }
end
```

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
