### ISSUE TITLE
Using '.where' on the 'passwd' resource fails when passing a hash of parameters

### ISSUE THREAD

**Issue by jerryaldrichiii** [inspec/inspec#2420]
### Description

The `passwd` resource should accept both a block and an expression passed to `.where`.

See the following for examples:

#### Fails

```ruby
describe passwd.where(user: 'root') do
  its('count') { should eq 1 }
end
```

#### Passes

```ruby
describe passwd.where { user == 'root' } do
  its('count') { should eq 1 }
end
```
### InSpec and Platform Version

InSpec Version: 1.48.5
OS: Arch Linux

### Stacktrace

```
inspec> passwd.where(user: 'root').entries
=> []
```

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
