### ISSUE TITLE
Unable to use docker relative resource with chef/inspec docker image.

### ISSUE THREAD

**Issue by chrisLeeTW** [inspec/inspec#2427]
### Description

Unable to use docker relative resource with docker instance (chef/inspec), always return empty results.

### InSpec and Platform Version
Inspec Version : 1.48.0
Docker version Docker Community Edition Version 17.09.1-ce (macOS)

### Replication Case
1. install docker for MacOS
2. run inspec with docker image - chef/inspec
```
docker run -v /var/run/docker.sock:/var/run/docker.sock:ro --rm -it chef/inspec shell
```
3. enter this command in inspec shell
```
docker.containers
```
4. will get this result
```
=> #<Inspec::Resources::DockerContainerFilter:0x0000557e94fe4058 @containers=[]>
```

### Possible Solutions

After some researches. I found out that you need install docker package in alpine. like,
```
apk update; apk add docker
```

And Then everything works fine.

### Stacktrace
none.

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
