### ISSUE TITLE
resource request: dns

### ISSUE THREAD

**Issue by adamleff** [inspec/inspec#2439]
While we have some support for this on the `host` resource, a fully-fledged DNS resource to check DNS records and configuration would be mighty cool to have.

This feature request inspired by the [rspec-dns](https://github.com/spotify/rspec-dns) project which looks pretty awesome.

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
