### ISSUE TITLE
docker_container resource needs to be able to check status

### ISSUE THREAD

**Issue by tas50** [inspec/inspec#2460]
### Description

Currently we have a is_running matcher for the docker_container resource, but there's more to docker containers that is/isn't running. Did it exit? Is it paused? We need to support all status types so we can really check the status of the container.

### InSpec and Platform Version

1.48.0 on Ubuntu 14.04

### Replication Case

Pause a docker container
Use the docker_container resource and try to check if it's paused

### Possible Solutions

is_stopped
is_paused

### Stacktrace

N/A

**Comment by tas50** [comment]
It should also be noted that we currently consider paused to be running, which is wrong

**Comment by kmf** [comment]
watching this.

**Comment by adamleff** [comment]
@tas50 so, right now, InSpec considers any container that hasn't exited to be "running" (i.e. if it shows up in `docker ps` output) whether or not the execution has been paused. In its current incarnation, seeing as there are no other statuses available to check, I do not believe this is a bug but rather simply the first iteration of how we viewed containers when the resource was created. 

I'd encourage you to open a separate issue logging that as a bug if you think it needs appropriate treatment, and I'm going to flag this issue as a feature request to support additional statuses.

**Comment by tas50** [comment]
It's like 1/2 way between the two.

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
