### ISSUE TITLE
x509_certificate resource: fetch cert from remote

### ISSUE THREAD

**Issue by mgrobelin** [inspec/inspec#2501]
### Description

Dear Chef's, 

this is a feature proposal/request for the `x509_certificate` resource.

Currently it expects the cert to be available on a filesystem of SUT.

This might not be possible due to access restrictions or technical barriers (e.g. lb/firewall/gateway appliances).

So what do you think of adding the possiblity to pass a socket instead, e.g. like  `x509_certificate('google.com:443')` and fetch that cert-file from remote?

### InSpec and Platform Version

1.49.9

### Possible Solutions

I can create a PR if you find this feature useful: https://github.com/mgrobelin/inspec/tree/x509_fetch_remote

Beware: 
* Ruby 2.0+ is required due to the Socket.connect_nonblock timeout parameter
* It may not work for any protocol extension, e.g.  HTTPS with SNI (multiple vhosts on single IP address)

### Stacktrace

None, but here is a output from a test profile (https://github.com/mgrobelin/inspec-x509-remote):

```
  x509_certificate google.li:443
     ✔  should be valid
     ✔  validity_in_days should not be < 100
  x509_certificate imap.mail.yahoo.com:993
     ↺  Unable to fetch remote certificate from imap.mail.yahoo.com:993 due to Connection timed out - user specified timeout
  x509_certificate does.not.exist.example.com:993
     ↺  Unable to fetch remote certificate from does.not.exist.example.com:993 due to getaddrinfo: Name or service not known
  x509_certificate 256.0.0.0:993
     ↺  Unable to fetch remote certificate from 256.0.0.0:993 due to getaddrinfo: Name or service not known
  x509_certificate imap.mail.yahoo.com
     ↺  Unable to find certificate file imap.mail.yahoo.com
  x509_certificate 172.217.22.99:443
     ✔  should be valid
     ∅  issuer_dn should eq "/C=US/O=Google Inc/CN=Google Internet Authority G2"
     
     expected: "/C=US/O=Google Inc/CN=Google Internet Authority G2"
          got: "XXX"
     
     (compared using ==)
     
     ✔  subject_dn should eq "/C=US/ST=California/L=Mountain View/O=Google Inc/CN=google.com"

Test Summary: 4 successful, 1 failure, 4 skipped

```
(The `got: XXX`-failure is actually valid, as I ran it behind a firewall that mitm's me in a not-that-smart fashion)

**Comment by adamleff** [comment]
Hi, @mgrobelin! Thanks for submitting this.

I think this is a terrific idea. However, your proposed method of handling this introduces a problem we initially had with the `http` resource: if InSpec is scanning a remote machine (i.e. with `inspec exec /path/to/profile --target ssh://myhost`, the socket will still be created on the machine actually executing InSpec rather than the system under test. This creates confusion for our users and therefore this approach is not something we could permit.

As an interim step, I think it would be helpful to modify the `x509_certificate` resource to accept certificate content as a parameter (in addition to the resource accepting a filename that is a path to the certificate on the SUT), and then the rest of the resource would function as normal. A profile author could then decide how they would fetch the certificate (whether it be by socket or otherwise). This feels like a reasonable first step in achieving this solution as you could take the code you've written to fetch a certificate and then put it directly into a profile and still use the resource we provide.

What are your thoughts?

**Comment by mgrobelin** [comment]
@adamleff Thanks for your feedback! Indeed I didn't reflected at all on "who" actually initializes the socket connection.

I have some problems to understand the benefits of the scratched interim step. Most likely a regular profile author is not able / don't want to maintain connection/transport related code, right? Pardon if I underestimate capabilities here.

So in contrast, it would be appropriate to mimic the `http` resource behavior with its `curl` (Worker::Remote) / `ruby-faraday` (Worker::Local) usage? 

I just flew quickly over the code, but a nice analogy could be `openssl` (Worker::Remote) / `ruby-socket` (Worker::Local) for this purpose. Or is the Remote/Local worker code+concept subject to change soon anyway?

**Comment by adamleff** [comment]
I mean, I don't think everyone should need to know how to set up sockets, but if they have a need, then modifying the core resource to accept an in-line certificate is one step in that direction. I offered that as an interim step for you to meet your needs since this is the first time we're hearing of it and don't want to solve for a need that's not yet pressing.

The Local/Remote worker model is something I like very much, and it will remain in `http` for the foreseeable future. The biggest challenge is that `openssl` might not be available on all targets, such as Windows machines, but we can fail gracefully in that case. If you want to try your hand at it, I support that. :)

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
