### ISSUE TITLE
404 page shows GitHub pages 404 and not InSpec branded 404.

### ISSUE THREAD

**Issue by burtlo** [inspec/inspec#2723]
### Description

![image](https://user-images.githubusercontent.com/244426/36491562-a4998e42-16f0-11e8-82c5-84571047756f.png)

### Replication Case

Visit any url that is not defined.

**Comment by jerryaldrichiii** [comment]
Great catch! No reason we should have a branded 404. I'm going to mark this as a `feature request` and `docs` since I think it is tangentially related.

To whomever takes this on, I think this may help:
https://help.github.com/articles/creating-a-custom-404-page-for-your-github-pages-site/

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
