### ISSUE TITLE
new reporters missing 'start_time' from report

### ISSUE THREAD

**Issue by aaronlippold** [inspec/inspec#2729]
The 'start_time' data which used to be in the 'controls' array in the JSON and other reports didn't make its way down the new 'stats' array to record the start time of the profile execution.

This needs to be put back into the reports as the `profile_sha` and or `profile_name` + `start_time` is a way to ensure that when we ship results to other systems or for post processing that unique results sets are distinguishable from one run to the next of the same profile on the same host, etc.

i.e. if I want to run the profile every 30 min, the json, json-min or junit report has a way to seperate the reports.

**Comment by jquick** [comment]
The same data should be available under the results section in profile controls.

**Comment by aaronlippold** [comment]
Yes the run time for each control - but we are looking for an overall start time for the profile as a whole. Can we assume the first entry for the for the first control result is the start time of the profile?

**Comment by jquick** [comment]
It `should`. We do not guarantee it as it based on the underline test runner. Its the same guarantee used before with the controls array in the json though as that was based of this.

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
