### ISSUE TITLE
How do I use Chef Attributes in Chef Inspec

### ISSUE THREAD

**Issue by mohamednazar** [inspec/inspec#2744]
### Description

How do I use Chef Attributes in Chef Inspec

### InSpec and Platform Version

PS C:\Users\Administrator> inspec --version
1.30.0
OS: Windows 2012 R2

for example I am passing attribute for SQL Service account (default['cookbook']['sqlservice'] ="example.com\sqlservice"). This attribute will assign MSSQLSERVER service account via chef recipe. I have to validate via Chef Inspec whether service account successfully updated on the service, so how can I use chef attribute to Chef Inspec?

Regards,
Mohamed Nazar

**Comment by jerryaldrichiii** [comment]
@mohamednazar there are a few ways to accomplish this. See: https://github.com/chef/inspec/issues/541

However, I personally would advise against using Chef attributes in your InSpec tests. 

A common use case for InSpec is doing exactly what you describe, having Chef make a configuration change and using InSpec to verify the change actually took place.

The issue here is that if you use the same input for Chef and InSpec what are you actually testing?Essentially in those cases you are NOT testing the configuration change, but rather you are testing that Chef is capable of making that change.

For example, let's say you have a Chef attribute that is used to create a file named `foo` and an InSpec test that uses the same attribute to test for a file named `foo`. Then, someday in the future, someone makes a typo in the Chef attribute and modifies it to `foob`. This would cause Chef to create a file called `foob` and then InSpec would verify that `foob` was created. Such a mistake would likely not be caught since the InSpec test "passes".

In these cases you should hardcode the value you expect in your InSpec tests, thereby catching these sorts of mistakes.

I'm going to close this issue for now, but please reopen if you need further assistance. We can also chat more in-depth if you'd like in the #inspec channel on the [Chef Community Slack](http://community-slack.chef.io/). I am `@jerry` over there.

**Comment by mohamednazar** [comment]
@jerry thanks for the detailed response, but however please see my scenario below.

We have to create users based on application name, each server hosted with one application. Once we provisioned the server we want to make sure those application users are created using chef recipe.

The application name will be mentioned in Chef attribute, using that the recipe will add some values in suffix and will create the users like below. This users has to be validated using chef inspec.

For ex: 

Server1
appname1_ro
appname1_rw

Server2
appname2_ro
appname2_rw

Server3
appname3_ro
appname3_rw

How do I use one inspec file for all three servers, so it will be very nice if I use chef attribute in Chef inspec to achieve the same.

Regards,
Mohamed Nazar

**Comment by jquick** [comment]
I agree with @jerryaldrichiii that this assurance should come from chef as that is implementing it. With that said you could use attributes file for each server via https://www.inspec.io/docs/reference/profiles/. But it sounds like you want to be able to do it dynamically. For that you would have to get server/app name at the beginning of your inspec control file. Something like:
```
server = command('hostname').stdout
appname = command('xyz').stdout
```

If you had the attributes listed somewhere on the server you could pull it from there also.

**Comment by jerryaldrichiii** [comment]
To pile on what @jquick is saying, the way I would solve it is with separate profiles for each application.

For example, create a generic application profile (one that fits most cases) then specific application profiles that include the generic profiles and modifies controls where needed via an attributes file (or a file in `files/` like [this](https://www.inspec.io/docs/reference/profiles/#profile-files)).

**Comment by ikari7789** [comment]
@jerryaldrichiii While what you say makes a lot of sense in the case of cookbook attributes, it doesn't apply well when talking about actual server information gathered via ohai, such as the FQDN, in which recipes could definitely make use of and would be a valid use case for having variable information in a test as this will change based on the test host itself. If you're absolutely concerned about making sure that a default attribute is exactly the value you want it to be, you can check it specifically in it's own test I say.
