### ISSUE TITLE
inspec.io all non-index pages generate errors

### ISSUE THREAD

**Issue by burtlo** [inspec/inspec#2772]
### 🎛 Description

🐛 bug report

![image](https://user-images.githubusercontent.com/244426/36909465-a2859820-1e03-11e8-963e-fddbf8dcb605.png)

### 🌍 InSpec and Platform Version

Visit the website on 3/2/218. Commit? 01357e1e29346f261811a5f9ba714715727dec92

Do you version the releases? I want to use the commit version of master but I don't know if that is what is delivered.

### 🤔 Replication Case

1. Visit https://www.inspec.io
2. Inspect the page
3. Visit https://www.inspec.io/docs
3. Inspect the page

### 💁 Possible Solutions

The URLS defined are likely defined as relative and when it is loaded on the other pages it is appending it to the current URL.

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
