### ISSUE TITLE
Windows Feature resource incorrectly sees features as installed

### ISSUE THREAD

**Issue by tas50** [inspec/inspec#2774]
### 🎛 Description

This a 🐛 bug report

The windows feature matcher currently sees InstallPending state as being installed. InstallPending isn't installed until a reboot so auditing that the features are installed will lead you to believe they are in fact fully installed when they're not.

### 🌍 InSpec and Platform Version

Inspec 1.51.21
Windows 2016

### 🤔 Replication Case

Install a feature like SNMP that requires a reboot

### 💁 Possible Solutions

???

**Comment by jquick** [comment]
@tas50 - Thanks for reporting this!

**Comment by kekaichinose** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
