### ISSUE TITLE
Resources inconsistently define exist? / exists? methods

### ISSUE THREAD

**Issue by burtlo** [inspec/inspec#2779]
### 🎛 `exist?` and `exists?`use is inconsistent across resources

🙋 feature request

The `user` resource defines `exist?` but not `exists?`.
The `file` resource defines `exists?` but not `exist?`.

Having a consistent method or supporting both will make it an easier experience when working with InSpec resources.

### 🌍 InSpec and Platform Version

InSpec 2.0.17, Mac 10.13.13

### 🤔 Replication Case

Given that you have a user that exists with the name `mr_robot` and a file that exists at the path `fsociety.dat`.

```
$ inspec shell
inspec> user('mr_robot').exists?
=> true
inspec> file('fsociety.dat').exists?
NoMethodError: undefined method `exists?' for File fsociety.dat:#<Class:0x00007fa7830dfca0>
from (pry):36:in `load_with_context'
inspec> file('fsociety.dat').exist?
=> true
```

### 💁 Possible Solutions

* Choose either `exist?` or `exists?`.

I do not get a feeling that a standard has been defined for all resources. It feels like there is usage of both as I have found in this instance. It sounds like the community would need to agree on what is preferred, the methods not in alignment would need to be deprecated, the documentation would need to be upgraded, and then the deprecated choice would need to be removed in the next release.

* Support both `exist?` and `exists?`

As a standard has not been defined perhaps the best approach is to support both. Review existing resources and add aliases to ensure they support both methods. It may still be a good idea to review the documentation to ensure the usage is consistent.

* Take no action

When defining controls with the expectations around existence the differing methods do not appear to impact the individual test case written.

**Comment by jquick** [comment]
This is a good point! I know ruby moved to `exist?` and deprecated `exists?` for its File methods. Not saying we should because of that but noting it. I would say lets pick one and deprecate the other.

My vote is to move them to `exist?`

**Comment by jquick** [comment]
Note, if we plan on updating the file to support `exist?` That would be a Train change.

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
