### ISSUE TITLE
bug - aws_iam_access_key - cannot find by access_key_id

### ISSUE THREAD

**Issue by JohnVonNeumann** [inspec/inspec#2782]
### 🎛 Description
Bug Report

Whilst using the aws_iam_access_key resource, I have attempted to use access_key_id when calling the resource, the module fails out. 

I ended up just finding by `username` instead and then doing a `cmp` on `access_key_id` inside the block of the test, and that worked just fine. Maybe I'm doing something wrong? At first I thought it could be a permissions issue with say my aws creds but that is not likely to be a problem as I have fairly unrestricted perms.

### 🌍 InSpec and Platform Version

```
(venv-36-ans) lw@RobertOppenheimer:inspec$ inspec --version
2.0.17
```
```
(venv-36-ans) lw@RobertOppenheimer:inspec$ inspec detect

== Platform Details

Name:      ubuntu
Families:  debian, linux, unix
Release:   16.04
Arch:      x86_64
```
### 🤔 Replication Case

```
describe aws_iam_access_key(access_key_id: 'ACCESS_KEY_ID') do
    it { should exist }
end
```

### 💁 Possible Solutions

Ruby isn't my domain, I have been reading through code but nothing I say will be of help.

### 💻 Stacktrace

No stacktrace.

**Comment by jquick** [comment]
@JohnVonNeumann - Thanks for reporting this!

**Comment by kekaichinose** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue under the __inspec/inspec-aws__ project to continue the discussion. Please make sure to provide a stack trace or repro data that is relevant to the current version.

Thank you!
__Chef InSpec Team__
