### ISSUE TITLE
Allow arrays to be accessed using ordinal values

### ISSUE THREAD

**Issue by russellseymour** [inspec/inspec#2788]
### 🎛 Description

🙋 feature request

When interrogating system things often come back as arrays. To test for things other than `first` and `last` the element number has to be specified, e.g. `its ('return[3]') { should be 'russell' }` which is not terribly readble (and is the 4th element).

### 💁 Possible Solutions

By using this library - https://github.com/kdisneur/ordinal_array - it would be possible to reference things using an ordinal value, e.g. `its ('return.third') { should be 'russell' }` which is much more readable and is the third element.

This gem supports up to the 999th element.

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
