### ISSUE TITLE
Execute inspec tests on containers hosted on remote docker host

### ISSUE THREAD

**Issue by sauravnz** [inspec/inspec#2789]
### 🎛 Description

🙋 For now we are able to connect to the docker service running locally on my machine. Request to provide a feature to connect to remote docker API and execute inspec tests for those containers.

Briefly describe the issue and the expected behavior

### 🌍 InSpec and Platform Version

Inspec Version: **2.0.32** on MAC (**10.13.3**)

### 💁 Possible Solutions

As we can provide a remote target for SSH, if we can enable the remote API for the docker host, inspec should be a able to access the remote docker host and execute the inspec tests.

**Comment by jquick** [comment]
Thanks @tonan  - This would be a https://github.com/chef/train request but we can track it here. This would be a great feature though!

**Comment by rockandska** [comment]
It is already possible with the use of docker environnement variables.
```
# docker ps
bash: docker: command not found

# inspec exec https://github.com/dev-sec/linux-baseline -t docker://workstation 2>&1 | head -n1
/opt/inspec/embedded/lib/ruby/2.4.0/socket.rb:1198:in `__connect_nonblock': No such file or directory - connect(2) for /var/run/docker.sock (Errno::ENOENT) (Excon::Error::Socket)

# export DOCKER_HOST=tcp://127.0.0.1:4243

# inspec exec https://github.com/dev-sec/linux-baseline -t docker://workstation 2>&1 | tail -n2
Profile Summary: 22 successful controls, 31 control failures, 1 control skipped
Test Summary: 64 successful, 57 failures, 1 skipped
```

**Comment by scalp42** [comment]
@rockandska unfortunately it doesn't cover something like test-kitchen for example.

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
