### ISSUE TITLE
Testing of chocolatey packages in Windows

### ISSUE THREAD

**Issue by eugeneromero** [inspec/inspec#2796]
### 🎛 Description

**Choose one:** 🙋 feature request

Packages installed through `chocolatey` (including `chocolatey` itself) don't show up as installed programs in the Programs and Features window. I might be missing something, but it seems inspec does not see these packages. Would be nice to be able to test for at least the existence of these packages.

### 🌍 InSpec and Platform Version
inspec version: 1.48.0, which is the version bundled with the latest chefdk-current (2.4.22)

### 🤔 Replication Case
A test such as:

```
describe package('chocolatey') do
  it { should be_installed }
end
```

fails, even though chocolatey is installed. Same for other packages installed with chocolatey.

### 💁 Possible Solutions
(keep in mind I know nothing about how inspec works :D)
Chocolatey provides a way of listing installed choco packages, `choco list -li`. Maybe testing for the choco command and parsing the output of this list could be a starting point?

Thank you for taking a look at this request! If this functionality already exists and my google-foo has failed me, please point me in the right direction. Thanks!

**Comment by frezbo** [comment]
Ref: https://github.com/chef/inspec/pull/2793

**Comment by eugeneromero** [comment]
Wow, great timing! Will wait for that PR to be merged. Thanks!

**Comment by TheLonelyGhost** [comment]
@papa-gene FYI, #2793 uses the `choco` command like you described and, if `choco` doesn't exist on the target machine, it will raise an exception. This means your example of `it { should be_installed }` on the above resource would be pointless since it would always return true or raise an exception before it got there.

**Comment by eugeneromero** [comment]
@TheLonelyGhost makes sense, I guess checking for `chocolatey` would be a bad example here. Thanks for the note!

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
