### ISSUE TITLE
Add Azure Virtual Network Resource

### ISSUE THREAD

**Issue by sharepointoscar** [inspec/inspec#2799]
**Feature Request**
Though we have the `azure_generic_resource`, it would be nice to have some foundational network resources starting with a vNET (`azure_virtual_network`)

InSpec 2.0.32 on OS X 10.12.6

**Comment by jquick** [comment]
Thanks for this request!

**Comment by sharepointoscar** [comment]
Thank you @jquick, I actually cloned the repo and have created the `azure_virtual_network` resource, I am now writing the unit test as per the contributing guidelines.  Just running into a small issue, but hopefully get it to a point where I do the pull request soon.

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
