### ISSUE TITLE
Add Azure Network Security Group Resource

### ISSUE THREAD

**Issue by sharepointoscar** [inspec/inspec#2800]
**Feature Request**
Though we have the `azure_generic_resource`, it would be nice to have some foundational network resources including  `azure_network_security_group`

InSpec 2.0.32 on OS X 10.12.6

**Comment by jquick** [comment]
Thanks for this request!

**Comment by sharepointoscar** [comment]
I'll take on this one as well.

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
