### ISSUE TITLE
Display the actual value found in the registry, not just "got false" 

### ISSUE THREAD

**Issue by pinterl** [inspec/inspec#2806]
**Feature Request**

When I test a value in the registry it would be great to see the actual value, not just an error message. SeverSpec displayed the actual value too, InSpec only displays "got false"

    ∅  HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full should have property value "Release", :dword, 460805
     expected #has_property_value?("Release", :dword, 460805) to return true, got false

**Comment by aaronlippold** [comment]
Hi, you would actually want to add a property to the resource called value
which could then return the actual value under the inspection. Methods with
a '?' should always return a Boolean value.

**Comment by pinterl** [comment]
@aaronlippold 
I use this test. How can I see the actual value on the console?
```
  describe registry_key('HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\NET Framework Setup\NDP\v4\Full') do
    it { should have_property 'Release' }
    it { should have_property_value('Release', :dword, 461310) } # For dword use the decimal value, no quotes
  end

```

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
