### ISSUE TITLE
port.rb should die with suitable msg when no 'ss' or 'netstat' method exists

### ISSUE THREAD

**Issue by frank-carnovale** [inspec/inspec#2817]
### 🎛 Description

Bug report.

Even when a port is listening, a 'should be_listening' test will report failure; if running on a Linux installation with neither netstat nor ss tools installed.  This can be the case for e.g. thin Docker containers that are being used to run Chef tests.

### 🌍 InSpec and Platform Version

```
[root@d1bf16d26073 resources]# inspec -v
2.0.45
[root@d1bf16d26073 resources]# uname -a
Linux d1bf16d26073 4.9.60-linuxkit-aufs #1 SMP Mon Nov 6 16:00:12 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
[root@d1bf16d26073 resources]# cat /etc/redhat-release
CentOS Linux release 7.4.1708 (Core)
[root@d1bf16d26073 resources]# chef-client -v
Chef: 13.8.5
```

### 🤔 Replication Case

To replicate: remove/disable 'netstat' and 'ss' on any linux-style build.  Then test for a should-be-listening scenario.

### 💁 Possible Solutions

This type of code construction..
```
    def info
      ports_via_ss || ports_via_netstat
    end
```
.. does not distinguish failure (because both tools missing) from failure (because ports not open).  This code needs re-factoring to be less sexy and more robust.. this is a correctness testing suite after all.

.. Thanks

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
