### ISSUE TITLE
False failure using when and etc_fstab resource

### ISSUE THREAD

**Issue by ryancurrah** [inspec/inspec#2818]
### 🎛 Description

A potential bug using `when` with the `etc_fstab` resource. If the `when` filter keyword does not match a entry in a file it fails the resource when it should skip the resource. As that filter doesn't match anything and does apply to the resource check. 

### 🌍 InSpec and Platform Version

InSpec version

```
[root@localhost inspec-stig-rhel7]# inspec version
2.0.45
```

Platform version

```
[root@localhost inspec-stig-rhel7]# cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.3 (Maipo)
```

### 🤔 Replication Case

Example InSpec test using the resource `etc_fstab` that checks if the mount option `nosuid` is set for the mount point `/home`...

```ruby
title 'RHEL-07-021010 - Files systems that contain user home directories must be mounted to prevent files with the setuid and setgid bit set from being executed.'
control 'RHEL-07-021010' do
  impact 0.5

  describe etc_fstab.where { mount_point == '/home' } do
    its('mount_options') { should include 'nosuid' }
  end

end
```

Example` /etc/fstab` configuration... without a `/home` mount point...

```
/dev/mapper/rhel-root / xfs defaults 0 0
UUID=2618daed-2430-466c-94e8-481162e9dd33 /boot xfs defaults 0 0
/dev/mapper/rhel-swap swap swap defaults 0 0
```

The test fails, even though there is no mount point `/home`... This is a false failure because the mount point does not exist, the resource should be skipped instead...

```
[root@localhost inspec-stig-rhel7]# inspec exec . --controls=RHEL-07-021010

Profile: STIG for Redhat Enterprise Linux 7 (STIG_RHEL7)
Version: 0.1.0
Target:  local://

  ×  RHEL-07-021010: Files systems that contain user home directories must be mounted to prevent files with the setuid and setgid bit set from being executed.
     ×  etc_fstab with mount_point == "/home" mount_options should include "nosuid"
     expected [] to include "nosuid"


Profile Summary: 0 successful controls, 1 control failure, 0 controls skipped
Test Summary: 0 successful, 1 failure, 0 skipped
```

### 💁 Possible Solutions

If `where` does not match any entry in the `/etc/fstab` file then the resource should be skipped instead of failed.

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
