### ISSUE TITLE
OS resource does not define a consistent interface.

### ISSUE THREAD

**Issue by burtlo** [inspec/inspec#2819]
### 🎛 Description

This is a 🐛 bug report.

The `os` resource does not define a `platforms` method and does not consistently define all the methods for a specific platform.

### 🌍 InSpec and Platform Version

InSpec 2.0.32 / Mac OSX 10.13.3

### 🤔 Replication Case

Connecting to a CentOS 7.4 instance:

```shell
$ inspec shell -t ssh://chef@34.201.49.48
inspec> os.platform
NoMethodError: undefined method `platform' for Operating System Detection:#<Class:0x00007fee4b8c96c8>
from (pry):1:in `load_with_context'
inspec> os[:platform]
=> {:arch=>"x86_64", :release=>"7.4.1708"}
inspec> os.arch
=> "x86_64"
inspec> os.release
=> "7.4.1708"
```

Connecting to a Windows 2012R2 instance:

```shell
inspec shell -t winrm://Administrator@34.200.252.19
inspec> os[:platform]
=> {:family=>"windows",
 :release=>"6.3.9600",
 :name=>"windows_server_2012_r2_standard",
 :build=>"9600",
 :arch=>"x86_64"}
inspec> os.family
=> "windows"
inspec> os.release
=> "6.3.9600"
inspec> os.name
=> "windows_server_2012_r2_standard"
inspec> os.build
NoMethodError: undefined method `build' for Operating System Detection:#<Class:0x00007fc04724ced0>
from (pry):5:in `load_with_context'
inspec> os.arch
=> "x86_64"
```

### 💁 Possible Solutions

I believe `os.platform` should be implemented. 

The `Inspec::Resources::PlatformResource` superclass does not include the `build` method making windows platforms work extra hard to get to their build `os[:platform][:build]` vs `os.build`.

**Comment by jquick** [comment]
This is as expected. `os.platform` should really not be used and only contains extra info from the detect scan. You should just use `platform.arch` or other `platform.x` calls. `build` is available via `platform.build` but only specific platforms support it at this time.

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
