### ISSUE TITLE
Idea: InSpec Linter

### ISSUE THREAD

**Issue by clintoncwolfe** [inspec/inspec#2867]
### 🎛 Description

🙋 feature request

Idea: a linter for InSpec.

This came up from a discussion within Chef, from a customers needs.

### 🌍 InSpec and Platform Version

Presumably we'd target 2.0+

### 💁 Possible Solutions

`inspec check` already exists, but that does actually evaluate some code.

Rubocop might be a good starting point; and Foodcritic might be a good comparison.

**Comment by burtlo** [comment]
https://github.com/chef/cookstyle

**Comment by chris-rock** [comment]
@great idea @clintoncwolfe We need to decide if we want to integrate this into the existing `inspec check` or create our own. At this point, inspec check is doing some linting and some checking. We may need to revisit how we parse and manage that. I agree that this should be part of the inspec cli.

InSpec will not folllow cookstyle since it does not follow our security patterns (single quotes over double quotes)

**Comment by clintoncwolfe** [comment]
Refs #3549

**Comment by clintoncwolfe** [comment]
Closing as a duplicate of #3600
