### ISSUE TITLE
Skipped tests shouldn't result in a non-zero exit value since it breaks logic tests

### ISSUE THREAD

**Issue by woneill** [inspec/inspec#2896]
### 🎛 Description

🐛 bug report

When a control is skipped due to an only_if condition it returns a 101 exit code. While this is planned behavior due to #1825, it makes it difficult to do simple boolean logic such as `inspec exec || echo "Failed"`.

In my use case, I'm using InSpec as part of a Packer build and it's causing all builds to fail since certain controls only are valid per platform (i.e. Docker vs AWS AMI)

### 🌍 InSpec and Platform Version

```
$ inspec --version
2.1.10
```

Running on OSX against an Amazon Linux target

### 🤔 Replication Case

Run the https://github.com/dev-sec/linux-baseline InSpec profile against a docker target and check the return code. It will be 101 (i.e. non-zero, breaking boolean comparisons) 

### 💁 Possible Solutions

Revert the 101 exit code in https://github.com/chef/inspec/blob/master/lib/inspec/runner_rspec.rb#L91-L92

**Comment by clintoncwolfe** [comment]
Could this need be accommodated by means of a new CLI option?  Something like `--treat-skips-as-pass` (we'd have to come up with a decent name, and a good single-letter form).

So then:
```bash
$ inspec exec profile-with-skips; echo $?
101
$ inspec exec profile-with-skips --treat-skips-as-pass; echo $?
0
```

**Comment by msiebeneicher** [comment]
Defiantly +1  for this change request: We test built images on gcp by inspec in our CI system and need to build a workaround for now to handle the uncommon exit code for skipped specs.

**Comment by chris-rock** [comment]
We had specific asks before to introduce multiple exit code to understand the result without parsing the report. In addition, reverting the exit codes would be a breaking change. I like the idea from @clintoncwolfe but we need to think about edge cases. Are there other things users may wanna pass?

**Comment by mechastorm** [comment]
In our use case, we are running InSpec tests in a Packer Build. We want to fail the build if Inspec detects a non-zero exit code.

The current behaviour we are encountering is like what @woneill encountered, resulting in Inspec tests that pass but Packer failing to complete the build because it detect Inspec existing with a non-zero exit code.

We initially encountered this error when running an open source profile and thought it was the profile's issue (https://github.com/dev-sec/linux-baseline/issues/92) but the team redirected us to this ticket.

**Comment by chris-rock** [comment]
@mechastorm Can you share the packer snippet? I assume the mitigation is to write a small bash script around.

**Comment by woneill** [comment]
Here's our workaround:
```inspec exec inspec/{{user `packer_role`}}; rc=$?; if [ $rc -eq 0 ] || [ $rc -eq 101 ]; then exit 0; else exit 1; fi```

The point is that the non-zero exit value *is* the breaking change, not reverting it. It goes against the philosophy of "A successful command returns a 0, while an unsuccessful one returns a non-zero value that usually can be interpreted as an error code" (per http://tldp.org/LDP/abs/html/exit-status.html)

How about a change that implements something like `curl`'s `--fail` flag? So that it will flag things as failures that normally aren't technically errors?

**Comment by trevor-vaughan** [comment]
I think I'm hitting something like this with `inspec --check` as well https://travis-ci.org/simp/inspec-profile-disa_stig-el7/jobs/370798078#L1003 My check should not fail on a skipped test.

**Comment by clintoncwolfe** [comment]
@trevor-vaughan : Your Travis log shows an exception being thrown, and the check run aborting because of it.  The exit code there is 1, because the ruby interpreter exited with an unhandled exception. That's likely an example of https://github.com/chef/inspec/issues/2981 .

If `inspec check` were exhibiting behavior like `inspec exec`, on a profile with skipped tests, it would run to completion and then exit with code 101. I don't know if it is doing that; if it is, I think that's wrong - we want `check` to validate the profile, and a profile with skipped tests is valid.

**Comment by clintoncwolfe** [comment]
Fundamentally, this comes down to two things:
 1. Is a test run with skipped tests considered a passing run?  Current inspec team doctrine says "no, and we communicate that with the special exit code 101."
 2. Regardless of whether you agree with 1 or not, you should have a way of choosing behavior.  My personal preference is for `inspec exec` to exit with 101 if any tests are skipped; and allow you to have it exit 0 by passing a CLI flag, such as `--treat-skips-as-pass`.

I think exiting non-zero by default is good behavior for this executable - it is an auditing tool, and a skip could be seen as a deviation , depending on the profile code.  The circumstances under which we exit 0 - "Everything is fine, everything passed" should be pretty tight, semantically.  If a profile being run under automation suddenly started having skips, this behavior will alert a human.

**Comment by trevor-vaughan** [comment]
In my case, I don't exactly want to run as `root` when I'm just hacking on code. Therefore, I think the *default* for `inspec check` should be to tell me that things were skipped but pass and then add a flag for `--fail-on-skipped`.

I would hope that running as `root` for routine development would be a finding on any system being scanned by `inspec` :-D

**Comment by woneill** [comment]
I agree with @clintoncwolfe's point that 

> The circumstances under which we exit 0 - "Everything is fine, everything passed" should be pretty tight

But disagree that skips could be seen as a deviation and should be flagged as possible failures. The most common reasons for skips that I've seen have to do with platform specifics (i.e. OS differences, versions of a tool generating different output, etc.) and as a result, those will _always_ need skips.

Thusly, `--treat-skips-as-pass` will almost always need to be passed in! It feels like the `--fail-on-skipped` is the best option intent-wise if skips are indeed supposed to be deviations.

**Comment by clintoncwolfe** [comment]
@woneill 's argument that '--treat-skips-as-pass will almost always need to be passed in' rings true for me.  I think as soon as you have even one skip, you'll add that, and then there is no value.

I'll bring this up at standup; my personal position has shifted to "when skips are present, exit 0, unless there is a --fail-on-skipped flag, in which case exit 101."

One planned feature for InSpec 3 is support for finer gradations of "skipping": 
 * skipped due to implementation reasons (e.g., this check does not apply to this platform)
 * skipped because this particular regulatory control doesn't apply to our business
 * skipped because we know we're not in compliance on this control, and we're working on it yet
 * other meanings as you suggest 😄

**Comment by clintoncwolfe** [comment]
So, here's the inspec team's consensus.  If you have strong opinions / great pain, let us know.

 * Because changing the exit code behavior was a breaking change, it was introduced on a major version change. Likewise, if we revert it, that would also be a breaking change.  So, we think we should wait to change the exit-code-on-skip behavior on a major version change, InSpec 3.  At that point, exiting 101 with skips will become opt-in; there may be other complex behavior around skipping.
 * We can and should provide a CLI option to opt out (like `--treat-skips-as-pass`) soon, on InSpec 2.  That relieves the sorest pain point, of having to wrap inspec in a bash script for CI.
 * We'll look to prior art to try to pick names for the CLI opts.  Suggestions welcome.

**Comment by woneill** [comment]
@clintoncwolfe Thanks for the summary and roadmap! I hadn't realized the exit code change mapped to the new major version change but I can see that historical context now.

**Comment by clintoncwolfe** [comment]
Thoughts on v3+ behavior: Here's how terraform's CLI handles this:

```
  -detailed-exitcode  Return detailed exit codes when the command exits. This
                      will change the meaning of exit codes to:
                      0 - Succeeded, diff is empty (no changes)
                      1 - Errored
                      2 - Succeeded, there is a diff
```

**Comment by chris-rock** [comment]
Just for reference, we defined the exit codes here https://github.com/inspec/inspec/issues/1825#issuecomment-382650911

**Comment by aaronlippold** [comment]
@clintoncwolfe et all:

I know I am a bit late to this discussion, however we must remember that when we truly skip we do not know the 'result' and so we do not know the state unless we report it or 'cast' it-  aka update the impact or update a describe block to report the 'deviation' as valid. 

From the assessment point of view we must always group into a known state and `skip` helps us do this. Statements we need to be able to resolve to are like:

- This control skipped due to a `something` not being there
- This control skipped because a package was not installed
- This control skipped because it is Not Applicable on this platform, os, os-version etc
- This control skipped because it does not apply when this service is enabled 

Notice here that we are not actually SKIPPING ( aka not doing a test ) we are actually changing the procedure of the test due to a known condition. We tested that a "fail fast" condition was met for this control and rather than testing with the standard describe blocks I used others. 

Truly skipped tests with no data one way or another are useless in validation as we can't validate if we don't understand context and state so we must always execute a test even if all that 'test' does is 'report on why we didn't run any tests'.
