### ISSUE TITLE
File resource shows wrong octal mode number at checking permissions

### ISSUE THREAD

**Issue by patriciomac** [inspec/inspec#2897]
### 🎛 Description

 🐛 bug report

I have written the following control

control "E.1.8.6.4" do
  title "/var/tmp file system permissions"
  desc  "Settings for files for other in this directory must be rwxrwxrwt(1777). Note: This particular requirement is not recursive."
  impact 1.0
  describe  directory('/var/tmp') do
    its('mode') { should cmp '1777' }
  end
end

the output of its execution on a linux system is:

inspec exec compliance-profile -t ssh://root:xxxxxxx@myserver --controls E.1.8.6.4

Version: 0.1.0
Target:  ssh://root@xxxxxxxxx

  ×  E.1.8.6.4: /var/tmp file system permissions (
     expected: "1777"
          got: 1023
     
     (compared using `cmp` matcher)
     )
     ×  Directory /var/tmp mode should cmp == "1777"
     
     expected: "1777"
          got: 1023
     
     (compared using `cmp` matcher)
     

Profile Summary: 0 successful controls, 1 control failure, 0 controls skipped
Test Summary: 0 successful, 1 failure, 0 skipped

The file system actually has 1777 permissions, so the test should not fail.

ls -ld /var/tmp
drwxrwxrwt. 5 root root 4096 Mar 29 12:07 /var/tmp

### 🌍 InSpec and Platform Version
inspect version = 1.45.13
ruby version = 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
Target Linux OS = Linux 3.10.0-693.21.1.el7.x86_64 #1 SMP Fri Feb 23 18:54:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
Target Linux Flavor = Red Hat Enterprise Linux Server release 7.4 (Maipo)

### 🤔 Replication Case
Please recreate the control and try it

**Comment by jcowhigjr** [comment]
I see a similar issue.

describe file('foo') do
  its('mode') { should eq 0750 }
end

passes correctly but in the output:
     ✔  mode should eq 488

inspec version -> 2.1.0
Your version of InSpec is out of date! The latest version is 2.1.83.

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
