### ISSUE TITLE
Check for JSON hash inside array

### ISSUE THREAD

**Issue by scalp42** [inspec/inspec#2903]
Hi folks,

Assuming a file `sensu.json`:

```json
  "rabbitmq": [
    {
      "host": "localhost",
      "port": 5671,
      "vhost": "/sensu",
      "user": "sensu",
    }
  ]
```

Is there a way to access the first hash inside the array? Something like this:

```ruby
describe json('sensu.json') do
  its(['rabbimtq', 0, 'port']) { should eq 5671 }
end
```

I'm assuming it's not possible but never knows 🍾

**Comment by scalp42** [comment]
Workaround for now:

```json
[{"name":"kitchen-server-ubuntu-1604","address":"172.28.128.11","subscriptions":["common","client:kitchen-server-ubuntu-1604"],"chef_environment":"kitchen","fqdn":"server-ubuntu-1604.vagrantup.com","chef_roles":"none","version":"0.29.0","timestamp":1522788541}]
```

```ruby
client_request = http('http://127.0.0.1:4567/clients', enable_remote_worker: true).body

sensu_json = json(content: client_request).first

describe json(content: JSON.dump(sensu_json)) do
  its('name') { should eq 'kitchen-server-ubuntu-1604' if os.name == 'ubuntu' }
  its('name') { should eq 'kitchen-server-centos-1604' if os.name == 'centos' }
end
```

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
