### ISSUE TITLE
[processes] : /proc instead of "procps" tools

### ISSUE THREAD

**Issue by rockandska** [inspec/inspec#2914]
### 🎛 Description

🙋 feature request

It seems than the "processes" resource relay on "procps" (linux) to be able to work.

### 🌍 InSpec and Platform Version

```
$ inspec --version
2.1.0
```
Inspec host: 
```
$ head -n2 /etc/os-release
NAME="Ubuntu"
VERSION="16.04.4 LTS (Xenial Xerus)"
```
Remote host (docker):
```
# cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
# ps -ef           
bash: ps: command not found
```

### 💁 Possible Solutions

Retrieve information from /proc when possible ?

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
