### ISSUE TITLE
Docs: Consider having an All-in-One Resources Page

### ISSUE THREAD

**Issue by clintoncwolfe** [inspec/inspec#2951]
### 🎛 Description

🙋 feature request

I was speaking with a customer this morning; when asked what they would love to see changed about InSpec, they answered that the docs could be improved.  He described the delightful experience people have when learning Chef, especially when browsing the [all-in-one Chef resources page](https://docs.chef.io/resource_reference.html). 

An all-in-one page allows:
* Easy in-page searching.  Our site search facility (in the scrollable header) scrolls off-screen quickly, and like most site searches, is not well-tuned to return relevant results.
* Discovery through browsing.
* Convenience.  If you're developing, you can leave an all-in-one page open for reference; split pages require 3-4 clicks or Back actions to traverse the tree, digging into the OS/AWS/Azure division.

### 🌍 InSpec and Platform Version

2.1.30

### 💁 Possible Solutions

I think we should retain the resource-per-page approach but *add* a compiled all-in-one page.

We could choose to split it out by platform root, as it's not likely users would be simultaneously doing OS and AWS development.

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
