### ISSUE TITLE
Inspec should warn if the user mixes --host --password or --user with -t

### ISSUE THREAD

**Issue by james-stocks** [inspec/inspec#2957]
### 🎛 Description

The following command might seem reasonable, but is unsupported:

`bundle exec inspec exec -t winrm://my-server.example.com --user Administrator --password hunter2  my_profile-1.0.0-1.tar.gz`

The user has given an incomplete target and mistakenly tried to provide the auth details separately.

If the user chooses to specify a target with `-t` but also provides a `--user` `--host` or `--password` then Inspec should warn them to either put the entire connection URI into `-t` or to omit `-t` and use `--user` `--host` and `--password`instead

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
