### ISSUE TITLE
Docs: Broken example links in Azure Resource docs

### ISSUE THREAD

**Issue by clintoncwolfe** [inspec/inspec#2959]
### 🎛 Description

🐛 bug report

Most Azure docs refer to the integration tests at the bottom of the page.  While the appropriateness of that is questionable, one thing that is certain is that the links are broken, ever since we moved to cloud integration tests from `test/azure/` to `test/integration/azure`.

Example: https://www.inspec.io/docs/reference/resources/azure_generic_resource/

### 🌍 InSpec and Platform Version

2.1.43

### 💁 Possible Solutions

Update the links!

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
