### ISSUE TITLE
Add UUID to all reporters and to inspec detect

### ISSUE THREAD

**Issue by aaronlippold** [inspec/inspec#2966]
🙋 feature request

* https://github.com/chef/train/blob/master/lib/train/platforms/detect/uuid.rb
* https://github.com/chef/inspec/blob/master/lib/inspec/reporters/automate.rb#L23

The UUID identifier was added to train and the automate reporter but should also be added to `inspec detect`, to the `json-full` and `json-min` and `cli` reporters.

This would very much needed to ensure traceability on which profile ( profile-sha ) and on which node ( uuid )  the ability for end users to run a profile multiple times or know which node has an issue and which one doesn't.

Look like the hard part is done - we just need to surface this very useful info into the reporters.

This would be a very good feature for conf as we can talk very directly about uniquely identify the `who` and the `where` of 100k nodes being scanned paired with the existing `what` of the profile sha :)

**Comment by aaronlippold** [comment]
I also would like to suggest that we add:
  - target ip address
  - target mac address 
  - target FQDN
  - target uuid

**Comment by aaronlippold** [comment]
This connects to our RSA Archer integration work

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
