### ISSUE TITLE
Ability to initialise InSpec profile in the current directory

### ISSUE THREAD

**Issue by walterdolce** [inspec/inspec#2975]
### 🎛 Description
This 🙋 feature request

When running `inspec init profile my_profile`, InSpec creates the necessary files so that one can start working on a profile. If I am already in the InSpec profile directory I want to create/develop but I haven't initialised it yet, I have no way of telling InSpec to initialise the profile in the current directory and therefore skipping the creation of the `my_profile` directory.

In order to clarify this a little bit more, think about cloning a git repository:
- When running `git clone git@provider:some-repo.git`, git will create the `some-repo` folder with the cloned repository in it.
- When running `git clone git@provider:some-repo.git .` instead, git will _not_ create the `some-repo` folder and it will clone the repository in the folder specified (in this case `.`, current directory).

I am happy to contribute to this if you think it adds value to the tool (it certainly would for me!).

### 🌍 InSpec and Platform Version
InSpec version is `2.1.21` running on a macOS High Sierra 10.13.4

### 💁 Possible Solutions

I was thinking about the ability to add an optional CLI parameter to the current `inspec init profile` command options available:
```
inspec init help profile
Usage:
  inspec init profile NAME

Options:
  [--overwrite], [--no-overwrite]  # Overwrites existing directory

Create a new profile
```
Perhaps a `--destination-path` optional parameter taking a directory path would make sense?
Or perhaps a `--path` would be better?

I would assume that:
- The `~` character, if passed, would have to be resolved to the user's home folder
- The `.` and `..` characters would have to resolve accordingly, regardless of how many times they appear in a path (i.e. `../../../some-path`)

### 💻 Stacktrace
N/A

**Comment by clintoncwolfe** [comment]
@walterdolce sounds like a great addition, and if you'd like to contribute, that would be wonderful!

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
