### ISSUE TITLE
AWS connections using STS fail with "Must specify userName..." error

### ISSUE THREAD

**Issue by chriswood123** [inspec/inspec#2982]
### 🎛 Description

🐛 bug report

When running inspec cli on an AWS EC2 instance which has a role attached via an instance profile an error **"Must specify userName when calling with non-User credentials"** is given and no tests are run.

### 🌍 InSpec and Platform Version

```
# inspec version
2.1.54
```

Installed from `https://packages.chef.io/files/stable/inspec/2.1.54/el/6/inspec-2.1.54-1.el6.x86_64.rpm`

```
# cat /etc/os-release
NAME="Amazon Linux AMI"
VERSION="2017.09"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2017.09"
PRETTY_NAME="Amazon Linux AMI 2017.09"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2017.09:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"
```

### 🤔 Replication Case

Note that no AWS API credentials are set in `~/.aws/credentials` or in environment variables.

Run AWS CLI to ensure that the permissions are correct
```
[root@ip-10---]# aws --region=eu-west-1 ec2 describe-instances --filter "Name=tag-value,Values=jenkins-server" --query "Reservations[0].Instances[0].State"
{
    "Code": 16,
    "Name": "running"
}
```
Check the inspec control
```
[root@ip-10---]# cat inspec/test-profile/controls/example.rb
describe aws_ec2_instance(name: 'jenkins-server') do
  it { should be_running }
end
```
Run inspec
```
[root@ip-10---]# inspec exec inspec/test-profile -t aws://eu-west-1
Must specify userName when calling with non-User credentials
```
#### Extra Info
The policy attached to the instance is:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": "*",
            "Resource": "*",
            "Effect": "Allow"
        }
    ]
}
```

**Comment by clintoncwolfe** [comment]
As far as I know, this (using instance profile metadata) has never been implemented - see https://github.com/chef/inspec/pull/2359. We also "mostly" rely on the SDK for creds handling, but interfere with it just enough to break this sort of thing - see #2717 for example.

We've had a number of AWS auth issues come in this week, but have had inconsistent reproducibility.  We should be able to take a harder look next week.

**Comment by clintoncwolfe** [comment]
Ahh, this just occurred to me, a possibility, which we can look into ... the recent changes in Train introduced a UUID support.  For AWS, the UUID is simply the account number, but train [gets it by fetching the current user ARN](https://github.com/chef/train/blob/master/lib/train/transports/aws.rb#L66) (without args, thus defaulting to the current user), and parsing it out.  We can get that ID in a better way - IAM get account_summary for instance.

On other words, this isn't an authentication failure - your STS creds are fine.  Train immediately tries to do a user lookup on the "current user", and since you're using an STS token...  "Must specify userName when calling with non-User credentials".

A PR is under review for this - https://github.com/chef/train/pull/286

**Comment by clintoncwolfe** [comment]
I've updated the title here because the error is due to using temporary credentials (which is intended to be supported).  It is coincidental that you are running this from an EC2 instance - you'd get the same error from a local connection attempt using STS.  Mind you, EC2 does fall back automatically to STS when running as you describe.

**Comment by chriswood123** [comment]
Makes sense @clintoncwolfe thanks for the updates.

**Comment by clintoncwolfe** [comment]
https://github.com/chef/train/pull/286 is merged . We'll cut a new Train release tomorrow, and bump the version dependency for inspec at that point.  That should fix this.

**Comment by clintoncwolfe** [comment]
@chriswood123 InSpec v2.1.59 relies on Train v1.4.2, which has a fix for this.  Can you verify, and close this issue if your needs are met?

**Comment by chriswood123** [comment]
Yes, I can verify this now works with version 2.1.59

Many thanks for your efforts @clintoncwolfe
