### ISSUE TITLE
etc_group implements its own version of FilterTable

### ISSUE THREAD

**Issue by clintoncwolfe** [inspec/inspec#2983]
### 🎛 Description

🐛 bug report

`etc_group` has its own partial implementation of FilterTable built into it.  We thus see odd defects and missing features from it.

Determine if we can shift it using the normal FilterTable.

### 🌍 InSpec and Platform Version

2.1.54

### 🤔 Replication Case

(needed)

### 💁 Possible Solutions

Try to have it use FilterTable.

### 💻 Stacktrace

(needed)

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
