### ISSUE TITLE
Add an integration test to verify pin of postgresql library

### ISSUE THREAD

**Issue by clintoncwolfe** [inspec/inspec#3002]
### 🎛 Description

🙋 feature request

For (reasons), we need to make sure that we match the version pin made in Habitat builder for the Automate channel.

Since we just use the postgresql dependency to provide client library support for the postgresql resource, we're pretty flexible.

### 🌍 InSpec and Platform Version

2.1.59

### 🤔 Replication Case

We'd like a test (integration?) that runs under CI that verifies the version pin we have matches that of the automate team.  If they change the pin, our build should fail.

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
