### ISSUE TITLE
RFC: Finer-grained test outcomes - Waiver and TODO support - nuanced skipping / failure

### ISSUE THREAD

**Issue by clintoncwolfe** [inspec/inspec#3017]
### 🎛 Description

🙋 feature request

There has been some desire for more nuance around "skipping" or failing a control or test.  Currently, controls may be skipped or failed for any number of reasons, but they are aggregated, potentially losing meaning.

This has also been described as new ways of interpreting failure types.

Some reasons to skip a control or test (please propose others):

* Implementation reasons (for example, the resource is not supported on the target platform)
* "Waiver" reasons - you may be using a profile that includes controls that do not apply to your business.  "Accepted Failure" has also been mentioned as a possible terminology.
* "TODO" reasons - it is a known point of noncompliance, and you want to mark it as such, while your team gradually brings things into compliance.  Differentiating it from plain failures would allow you to have a run that has "known failures", and you would be very interested if a new failure occurred.  The term "Exception" has been suggested as another term for this case.

Any of these skip/fail outcomes might also have a conditional applied.  For example, an organization may have a failed audit, with 60 days to correct the failures.  That could be expressed with "TODO" failures that, after 60 days, become regular failures.

Refs #2896 #1825 

Attn: @galenemery @ericcalabretta 

### 🌍 InSpec and Platform Version

This would be targeted for 3.x, most likely.

### 🤔 Replication Case

This is currently sometimes implemented using either `supports`, `skip` or `only_if`.

### 💁 Possible Solutions

The RFC is to determine what people want.  Use cases and suggested syntax and UX experiences are welcome.

**Comment by clintoncwolfe** [comment]
If a regulatory benchmark includes 150 rules and the corresponding profile only tests a subset (because some maybe can't be programmatically tested), that would be a good thing to distinguish: control skipped because it is not automatable.

Attn: @larryebaum

**Comment by galenemery** [comment]
A couple of the use cases I've run into are the following, typically when inheriting a base profile (for instance CIS or STIG):

The base profile is overly restrictive and I have controls (n) that will not be applied in my infrastructure.  So I will skip these controls always.  This feels fairly well covered with `skip_controls`.

Another use case is: my security team has these controls I must follow, but my system isn't finished yet.  I want to see the checks I would fail, but I don't want them to impact my compliance score, as they don't apply currently from a compliance/security perspective.

There's two ways I've seen people want to do that.  Some do not want to run the check itself, because the check can be time/cpu intensive and it doesn't make sense to run it since we don't care what its result is currently.

Others do want to run the control to see its current state, this is particularly true when starting the process of hardening systems, it gives a TDD feel to the work and progress can be watched more easily.

Currently the way we're doing time-based waivers is an `only_if { ::Date.Parse(Expiration_Date) < Date.today }`.

That works pretty well, but only if we want to see the control itself, but not have it run.  It doesn't support either skipping the control entirely (you could wrap the control in an if block in your wrapper profile, but thats not core Inspec). and it doesn't support running the control with no impact associated.

**Comment by galenemery** [comment]
Another comment: a control that is waived, either by being skipped, or having an impact set to 0, should not result in a system being registered as 'uncompliant' from a compliance viewpoint.

**Comment by clintoncwolfe** [comment]
We (the community) can think of new syntax - we don't have to be constrained by existing approaches using severity or skip_control.  We could invent `waiver`, or `waiver_if { some_condition }`, `tolerate_failure`, etc.  Names and syntax are open.

**Comment by clintoncwolfe** [comment]
Regarding "being reported as noncompliant", I imagine that we'd have several new outcomes in the report:
```
 10 controls passed
  5 controls waivered
  3 controls skipped for implementation reasons
  2 controls expected to fail
  0 unexpected failures
```

Depending on what is interpreting that report, the above result could be considered compliant or noncompliant.  Automate and the inspec CLI are two things that have such opinions. #2896 is an open issue that would alter how the CLI interprets such results (but allow you to control its interpretation, too).

**Comment by bruce-one** [comment]
A thought could be to have a "roadmap" (or "pending" or maybe "underway"?) annotation that means "I know this doesn't pass yet, but it will start passing at some point, and if goes back to non-compliant from there, _then_ start telling me about it".

I sort of see it in combination with the waivered until date concept: we want to be compliant with _x_ by date y, but maybe we'll get it done early - so if we do, please start reporting on it.

**Comment by frezbo** [comment]
@bruce-one are you talking about POAM's?

**Comment by james-stocks** [comment]
`controls expected to fail` would be really useful for testing of profiles; because we'd want some negative testing (i.e. we need to see the control correctly fail for a non-compliant target host).
Also our test VMs are never 100% compliant and it would be great to run non-compliant controls and assert they result in a specific expected failure rather then skip them.

**Comment by miah** [comment]
A lot of good ideas here =)

I'd like to see optional `message` support in `waiver_if` and similar.

We should also consider waivers at the `inspec.yml` level, this could be performed by excluding tags.

It might look like this

```
waivers:
 - tag: ssh
   until: 15-12-2018
   message: Accepted Failure
```

**Comment by aaronlippold** [comment]
Hi all, this is one of the most sensitive areas of our compliance work. We
need to be very careful about how we approach this as we must not forget
that risk decisions versus compliance data are two different processes. We
need a way to articulate accepted risk decisions but while doing that we
need to ensure that we don't obfuscates or mute the compliance data
necessary that informs those risk decisions. Literally this is a shoot
yourself in the foot type of an area. At the very minimum one of the key
concerns and requirements that I would leverage in any of these is that
even if we set the result output of the test that we don't mute the
results. If a result is set to waived accepted or soft pass we still report
the results of the test itself and or if we skip or do not run a test that
we report clearly that the test was skipped Etc.

Just a few thoughts to keep in mind.

**Comment by jquick** [comment]
Need to finalize UX for filter properties in the inspec.yml

**Comment by clintoncwolfe** [comment]
Summarizing a discussion with a customer success engineer JS at Chef Rally:

* His uses involve things like POAMs. He'd like to have the ability to inject customer-centric terminology into any messaging.
* I'd been thinking that the need to make waivers, etc conditional was very general - that a block similar to an `only_if` (perhaps `waiver_if { ... }`) was what was needed. That may be desirable, but enforcing a waiver until a certain date is very important - it should be a first-class clear option (consider waiver_until, perhaps).
* If we know a waiver has an expiration date, then we can do things like issue warnings when it has only 5 days left (for example). If the conditional is always general, we can't do that.
* We see a need for "things that are expected to fail but should still run" as well as "things we expect to fail but should not be run".  We do not have consensus on terminology for those things.  It's also clear that within certain sectors or industries, they have terminology already, and it varies between industry (finance and military use different terms here, for example)

**Comment by aaronlippold** [comment]
Hello, I think this would be a good topic for us to bring up at our next
sync meaning I will make sure that our security accreditors and security
control assessors are on the call. I will forward this message to them and
they can provide additional feedback but we have talked internally on the
pros and cons on this topic numerous times and we need to make sure that we
balance the ability of users to inject useful metadata but not compromise
the validity of the test or the results by being able to too freely
manipulate testing scenarios. We as a community just have to balance the
social contract I guess is how I would put it.

**Comment by aaronlippold** [comment]
```
pass({block},{message}) <= tests run
na({block},{message},{impact (default 0}) <= tests run
fail({block},{message}) <= tests run
skip({block},{message}) <= tests skip
```

**Comment by aaronlippold** [comment]
This is basically getting us to the end point of our `exit codes` in the 'groups'.

**Comment by ejaronne** [comment]
I understand, but I think we have plenty of flexibility with overlays and description sub-sections for "caveats" such as waivers, deviations, exceptions, risk-based decisions, risk-based acceptances, its currently being worked in a POAM, "I'm still working on its", whatever.

If we _*must*_ go down this path, where we're trying to differentiate between failures the developer already knows about, and failures they haven't addressed yet, have one more category:
"failed but being worked"
We shouldn't use specific terminology such as waiver, tolerated, poam, deviation, etc.  These are very specific terms and different organizations react differently (sometimes very emotionally) to their meaning and use at the policy level.

_For the new "failed but being worked" category, simply use a sub-section to provide the context._

The only other output categories will be "passed" "failed", "skipped", "no result" as it is now, and "na" per Aaron's suggestion: "na" should only be used if there is an absent component or the organization policy simply doesn't implement the control because they didn't select a particular related NIST 800-53 control for their baseline security requirements.

FYI, currently we have a rule of thumb when coding profiles:

Look carefully however at our "compliance score" =
[Not A Finding (pass) / (Not A Finding (pass) + Open (fail) + Not Reviewed (skipped) + Profile Error) * 100]

We have 5 buckets for InSpec output:
"Not a Finding" (All tests passed for a control)
"Open" (control has at least some tests failing)
"Not reviewed", aka **skipped**, is only done when a control can only be validated manually *or* the control is disabled because it runs too long. For these, no test is performed.
"Not Applicable", whereby impact=0, is only done when a component to be validated simply isn't installed (e.g., gui desktop on linux), *or* the organization doesn't implement the NIST 800-53 security control for their systems per policy on-high.  Here, we still run the test, but it doesn't count toward the compliance score either way: it is not in the numerator or denominator.
"Profile Error" (no result from tests - check profile run privileges or author of profile)

See: https://mitre.github.io/heimdall-lite/ 

So, for folks who want to be able to put in a caveat as to why certain controls still haven't passed can simply create an overlay, use "failed but being worked", and use description sub-sections. Example:
desc, caveat: "We can't fix this until February 30th, 2019, but have a POAM $1234 open tracking the issue"

**Comment by clintoncwolfe** [comment]
Thanks for all the feedback.  

One thing that I didn't mention in the notes above was that I found myself reminding my colleague that we don't have to use existing structures - as he tended to tell me how they were using only_if, or impact, or filters on a JSON report using descriptions, to implement the features we're describing on this issue.  This is similar to what was described above.

So just to be clear, we're looking for new mechanisms, that InSpec could directly implement and expose. They could be new conditionals, or new outcomes, or a combination; and likely using customized messaging so the jargon of the vertical industry can be used.  Of course, no one would be obliged to use such features.

#3174 covers the outcome of being unable to run tests.

**Comment by clintoncwolfe** [comment]
We could toggle controls on and off more easily if each control were associated with an input (attribute) - see #3845

**Comment by kekaichinose** [comment]
Unless anyone else thinks otherwise, I'm going to close out this issue in-lieu of #4408, which is the epic set to handle implementation of the waiver mechanism.

In short, control status should be dependent on waiver state. If a control is waived, its impact should be 0, as previous contributors mentioned. The control's status is still valid, but dependent on the "skip switch" optional configuration that's explained further in #4408. For example, if a control is waived and it's "skip switch" is enabled, it will not be evaluated and will carry a status of "skipped". If the "skip switch" is not set (we still should talk about default config), the control will be evaluated and its result included in the report. In this way, it will be left to the reporting mechanism to decide how best to display a waived control's result.

**Comment by aaronlippold** [comment]
We have to remember that in compliance skipped is a different concept than
not applicable.

Which is what you mean when you say waived a.k.a not applicable.

This doesn't have anything to do with the result of the control but rather
if the control is part of the final evaluation. The tests should always be
run and if they are applicable then they either are passed or failed. if
they are not applicable then the result of the test is not counted towards
the final evaluation of the system. If they are skipped tests then we have
no information one way or the other i.e compliant or are you not complaint.

Having accredited many systems the results of a test on a system are always
valuable to me.

What I decide to do with the data that I receive is a completely different
matter.

As ispec is trying to codify the compliance process we need to respect
these distinctions. I completely agree that the idea of waving controls or
setting them non-applicable in the more formal term it's an absolutely
valid use case we should not confuse it with the concept of a skipped test.

The pattern we should be moving towards in my opinion is that we have
controls which have passing and failing tests, we have controls which have
and selected as not applicable or waived, and we have a final set of tests
that are skipping due to insufficient data or some other misalignment such
as a missing package or file access permission on the system etc. these
final sets of tests are closer to errors than they are known conditions and
they need to be evaluated such that they're either marked as non-applicable
for known reason AKA gnome is not installed so this control is not
applicable, or the system does not use nsf so this control is not
applicable.

Take this example,

The main point here is that it wasn't that a test was not run it was that a
different test was run, if the NFS server package is installed and the
service is enabled then these configurations settings should be in place.
If the NSF package is installed but the service is not enabled then another
set of tests should be run. Otherwise if the NFS package is not installed
then this control is not applicable to the system because the system cannot
be out of compliance given that the service could not possibly be running.

In the above scenario in one case I had a set of tests that would either
pass or fail I had another set of tests that would pass your fail or I had
a final test that passed or failed, and given the scenario or branch of
logic that I was in the impact of that control was adjusted accordingly.

The final case was the waived control case. And notice that it was a very
deterministic state and there was an active test performed to validate that
state. it was not a skip test a test was performed to determine which state
we were in and in that state if the condition was met. Many times the
describe block AKA the reporting to the end user is the action provided by
the test, it tells the a creditor and the developer that the condition was
met.

**Comment by zenspider** [comment]
@kekaichinose this ^^^ comment is out of scope for V0... but you might want to use "..." and "Reference in New Issue" if you think this is something we should pull up
