### ISSUE TITLE
port resource should add special handling for 0.0.0.0

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#304]
0.0.0.0:80 is reachable on, say, 192.168.1.1:80. Currently the port resource does not catch those cases.

**Comment by chris-rock** [comment]
also see #303

**Comment by kekaichinose** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
