### ISSUE TITLE
Resource Aws_ec2_instance is not supported on platform redhat/7.5

### ISSUE THREAD

**Issue by Cmouli7** [inspec/inspec#3050]
### 🎛 Description:  Resource Aws_ec2_instance is not supported on platform redhat/7.5

**Choose one:** this a 🐛 bug report 

Briefly describe the issue and the expected behavior

### 🌍 InSpec and Platform Version

Use RHEL 7: Red Hat Enterprise Linux Server release 7.5 
Use Inspec version 2.1.72

### 🤔 Replication Case

Installed inspec in AWS EC2 instance and ran a very basic inspec tests
```ruby
describe aws_ec2_instance('i-01a2349e94458a507') do
  it { should exist }
end

describe aws_s3_bucket('test_bucket') do
  it { should exist }
end
```

and got the below response,
```
Profile: tests from test.rb (tests from test.rb)
Version: (not specified)
Target:  local://

  EC2 Instance
     ↺  Resource Aws_ec2_instance is not supported on platform redhat/7.5.
  S3 Bucket
     ↺  Resource Aws_s3_bucket is not supported on platform redhat/7.5.

Test Summary: 0 successful, 0 failures, 2 skipped
```

### 💻 Stacktrace

edit (@clintoncwolfe): added code block formatting

**Comment by clintoncwolfe** [comment]
This is intended behavior.

When run without an explicit `-t` (`--target`) option, `inspec exec` assumes you wish to audit the local system - here, an RHEL 7.5 machine.  When auditing an operating system, you can audit things internal to the OS, like processes, etc, but you can't audit AWS objects - for that, you'd need to target your AWS infrastructure:

```
inspec exec -t aws://us-east-1/some_aws_profile_name  some/inspec/profile
```

That's just one way of passing AWS creds; see [Setting up AWS credentials for Inspec](https://www.inspec.io/docs/reference/platforms/#setting-up-aws-credentials-for-inspec) for other options.

If you'd like InSpec to automatically pick up the credentials offered by the EC2 instance profile's role, that is an open feature request (#2560).  You'd still need to provide the `-t aws://` to the command line, though, to tell InSpec you want to talk to the AWS API instead of the local system.

If you have any suggestions regarding how we can make InSpec's behavior in this matter more clear (whether docs, CLI messaging or other UX), we'd be very interested.  Thanks!

**Comment by Cmouli7** [comment]
Thanks for your response. Inspec rpm is installed in RHEL 7.5 machine where AWS infrastructure is also built. I am trying to run inspec tests directly on the RHEL 7.5 machine. Does it still require AWS credentials to be set up?

**Comment by clintoncwolfe** [comment]
In order for any AWS client (which would include terraform, cloudformation, InSpec, etc - anything that must talk to the AWS API) to communicate with the API, it must authenticate to do (almost) everything.   While there are ways to do that implicitly with some tools, InSpec currently requires an explicit set of credentials in most cases (again, see #2560 for a request to enable implicit authentication more reliably).  Whether you provide credentials implicitly or not, you must also provide the `-t aws://` option so InSpec knows to talk to the AWS API, not your local machine.

**Comment by Cmouli7** [comment]
Gotcha! Thanks again for explaining it in detail. 

Will test it by setting up credentials and with -t aws://

**Comment by clintoncwolfe** [comment]
As this has been idle for a while, I'm closing this. If you have any further questions on this topic, please re-open the ticket.

**Comment by infa-ksatarka-zz** [comment]
×  check-vpc: Verify if the vpc with mentioned id exists
     ×  Control Source Code Error sample_profile/controls/infra-test.rb:3
     missing required parameter params[:role_arn]


Profile: Amazon Web Services  Resource Pack (inspec-aws)
Version: 0.1.0
Target:  aws://

     No tests executed.

Profile Summary: 0 successful controls, 1 control failure, 0 controls skipped
Test Summary: 0 successful, 1 failure, 0 skipped
