### ISSUE TITLE
Atom text editor plugin resides in the chef-training organization

### ISSUE THREAD

**Issue by burtlo** [inspec/inspec#3092]
### 🎛 Description

🙋 feature request

https://github.com/chef-training/language-inspec is a plugin for Atom that provides language and snippet support. 

I would like to transfer ownership to this organization.

To generate all the snippets I used ERB to specify a base snippet template. Then I collected the list of all the resources and generated the resulting output CSON. During the ChefConf 2018 hackday I was working on having the script automatically load the resource list from the `Inspec::Resource.registry`. By default it is going to use whatever version of InSpec I have installed on the system. During the demo during the hackday I noticed that it removed some of my snippets because my installed version was out-of-date.

To ensure the plugin generates the correct set of the snippets:

Have the script compare installed version to available version - similar to how InSpec operates now in reporting that it is out-of-date. If it was out-of-date then it could generate a warning and produce the snippets or halt unless an override flag is provided.

It would also be nice to have this package automatically generated when InSpec is released. I would enjoy adding the support to build kit to have this fire upon master changes for inspec/inspec.

**Comment by clintoncwolfe** [comment]
We're looking at improving the Registry API (or something similar) to allow the properties, etc to be enumerated more accurately.  And yes, we plan to add this to the build eventually.  Thanks for all your work on this!

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
