### ISSUE TITLE
add services plural resource

### ISSUE THREAD

**Issue by arlimus** [inspec/inspec#311]
we have `service(xyz)` to query a specific service, but it would be great to get access to the list of all services and interact with it. This gives more flexibility to tests and let's us interactively debug what inspec is considering a valid service on the node.

**Comment by kekaichinose** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
