### ISSUE TITLE
apache_conf resource parameter docs unclear

### ISSUE THREAD

**Issue by monoranjang** [inspec/inspec#3197]
### 🎛 Description

When I try to execute the following code I get error "Can't find file: path"

describe apache_conf('path') do
  its('setting_name') { should eq 'value' }
  end

Note that my apache dir is /appli/apache/conf

### 🌍 InSpec and Platform Version
inspec --version
2.1.83

### 💁 Possible Solutions
I think by default, inspec is looking for folder etc/apache/conf. We need to mention/configure somewhere that my path is appli/apache/conf

**Comment by clintoncwolfe** [comment]
The literal `'path'` is a documentation placeholder: you are intended to replace it with your own custom path, if needed.

So, since you have a custom path, you would use:

```
describe apache_conf('/appli/apache/conf') do
  its('AN_ACTUAL_SETTING_YOU_CARE_ABOUT') { should eq 'THE_VALUE_YOU_ARE_LOOKING_FOR' }
end
```

Likewise, the literal strings `'setting_name'` and `'value'` are placeholders: you should replace them with the Apach httpd directive you care about, and the expected value.

**Comment by monoranjang** [comment]
Doesn't work.
Here is my path:
[root@ONE-FTM6-REV1 conf]# pwd
/appli/apache/conf

I tried with "/appli/apache/conf","./appli/apache/conf", "/appli/apache",  "./appli/apache","/appli","./appli"

None of them worked

**Comment by monoranjang** [comment]
Finally worked for fully qualified path
