### ISSUE TITLE
not working under windows, installed from gem

### ISSUE THREAD

**Issue by graf0** [inspec/inspec#323]
- I installed inpsec from gem
- I ran (from privileged powershell) command: inspec detect
- I've got:

```
{"name":null,"family":null,"release":null,"arch":null}
```
- then I've created file test.rb with content (from inspec doc):

``` ruby
describe port(80) do
  it { should_not be_listening }
end

describe port(443) do
  it { should be_listening }
  its('protocols') {should include 'tcp'}
end
```
- I ran: inspec exec test.rb
- I've got:

```
Pending: (Failures listed here are expected and do not affect your suite's status)

  1) Port  80 The `port` resource is not supported on your OS yet.
     # Not yet implemented
     #

  2) Port  443 The `port` resource is not supported on your OS yet.
     # Not yet implemented
     #

Finished in 0.00174 seconds (files took 2.01 seconds to load)
```

I don't know, and couldn't find how to make it work :(

windows version 7 x64,  ruby 2.0.0p645 32-bit, inspec gem 0.9.6

**Comment by graf0** [comment]
Same situation after trying ruby 2.2.3 - both: 32-bit and 64-bit version

**Comment by geerzo** [comment]
I have a similar problem on Windows through Test Kitchen via the Chef DK 0.10.0. The os object doesn't seem to be functioning properly.

The following commands all return false.

puts os.redhat?
puts os.debian?
puts os.suse?
puts os.bsd?
puts os.solaris?
puts os.linux?
puts os.unix?
puts os.windows?

**Comment by chris-rock** [comment]
@graf0 Thanks you very much for your feedback. As you figured out, InSpec does not work properly with local mode on Windows. Currently InSpec only works well if used via WinRM. The problem is located in the os-family detection in https://github.com/chef/train/blob/master/lib/train/extras/os_common.rb#L90. I started working on a fix and got this working on Windows 10. We run some extra tests with Windows 7.

We expect to release a fix for InSpec by end of this week. In the meantime you can use InSpec via WinRM only.

**Comment by chris-rock** [comment]
@geerzo I assume this is a different issue, since the detection for Windows is working via WinRM. Which gem versions of `inspec` and `kitchen-inspec` are you using? Could you share your `gem list`?

**Comment by chris-rock** [comment]
The PR https://github.com/chef/train/pull/43 fixes this issues mentioned by @graf0 . To explain the issues:
Train detected Windows properly on local mode via https://github.com/chef/train/blob/master/lib/train/transports/local_os.rb#L39. Afterwards train tried to detect the windows version with our detection script: https://github.com/chef/train/blob/master/lib/train/extras/os_detect_windows.rb#L56. This script failed due to the fact that we get a `cmd` shell on Windows (in contrast to WinRM where we get a `PowerShell` shell automatically). The PR adds the required functionality to ensure commands are executed via powershell if inspec runs on Windows locally.

**Comment by arlimus** [comment]
Train 0.9.3 has been released and fixes this.
Please reopen this ticket if the issue persists.
