### ISSUE TITLE
add ipv6 iptables resource

### ISSUE THREAD

**Issue by thomascate** [inspec/inspec#325]
Currently there is no ip6tables resource, or flag on iptables to look at ip6tables for ipv6 rules.

**Comment by martinisoft** [comment]
I'd like to see this or even just a flag on the matcher.

**Comment by kekaichinose** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
