### ISSUE TITLE
Feature Request: OpenStack Platform support

### ISSUE THREAD

**Issue by kmf** [inspec/inspec#3542]
Would love the ability to test resources on an OpenStack environment 
    (got them from Terraform)

- openstack_blockstorage_volume_attach
- openstack_blockstorage_volume
- openstack_compute_flavor
- openstack_compute_floatingip_associate
- openstack_compute_floatingip
- openstack_compute_instance
- openstack_compute_keypair
- openstack_compute_secgroup
- openstack_compute_servergroup
- openstack_compute_volume_attach
- openstack_containerinfra_cluster
- openstack_containerinfra_clustertemplate
- openstack_db_configuration
- openstack_db_database
- openstack_db_instance
- openstack_db_user
- openstack_dns_recordset
- openstack_dns_zone
- openstack_fw_firewall
- openstack_fw_policy
- openstack_fw_rule
- openstack_identity_auth_scope
- openstack_identity_endpoint
- openstack_identity_group
- openstack_identity_project
- openstack_identity_role_assignment
- openstack_identity_role
- openstack_identity_user
- openstack_images_image
- openstack_lb_listener
- openstack_lb_loadbalancer
- openstack_lb_member
- openstack_lb_monitor
- openstack_lb_pool
- openstack_lb_vip
- openstack_networking_floatingip_associate
- openstack_networking_floatingip
- openstack_networking_network
- openstack_networking_port
- openstack_networking_router_interface
- openstack_networking_router_route
- openstack_networking_router
- openstack_networking_secgroup_rule
- openstack_networking_secgroup
- openstack_networking_subnet_route
- openstack_networking_subnet
- openstack_networking_subnetpool
- openstack_objectstorage_container
- openstack_objectstorage_object
- openstack_objectstorage_tempurl
- openstack_vpnaas_endpoint_group
- openstack_vpnaas_ike_policy
- openstack_vpnaas_ipsec_policy
- openstack_vpnaas_service
- openstack_vpnaas_site_connection

**Comment by zenspider** [comment]
Giving to @kekaichinose to weigh in.

**Comment by kekaichinose** [comment]
Thank you for filing this issue. As with many large open source projects, we have a backlog of bugs and issues of varying user impact. Some issues are perpetually subject to lower priority than others in our backlog. We have reviewed the issue, and we have determined this a very low priority when considered in the context of the entire backlog. We have elected to close it as "Declined" due to competing priorities.

However, we like the improvement offered here, but do not have time to address it. If you are passionate about this ask, please submit a PR so we can work together on getting this in.

We very much appreciate you bringing this to our attention.

Thank you!
__Chef InSpec Team__
