### ISSUE TITLE
run tests as a different user then the ssh login user

### ISSUE THREAD

**Issue by hack2learn** [inspec/inspec#362]
Is there a way that i can execute a test on a remote machine with sudo command or switch to a given user?

For example our postgresql configs and folders are all owned by postgres user without read rights for other users.
To perform those tests it would be nice if we could switch to the postgres user and execute the tests.

**Comment by chris-rock** [comment]
@hack2learn Sorry, that I missed your issue.

Currently, you have two ways:
- you can pass sudo options like `-u`
- add a public key to the postgres user

```
$ inspec help exec
Usage:
  inspec exec PATHS

Options:
      [--id=ID]                            # Attach a profile ID to all test results
  t, [--target=TARGET]                     # Simple targeting option using URIs, e.g. ssh://user:pass@host:port
  b, [--backend=BACKEND]                   # Choose a backend: local, ssh, winrm, docker.
      [--host=HOST]                        # Specify a remote host which is tested.
  p, [--port=N]                            # Specify the login port for a remote scan.
      [--user=USER]                        # The login user for a remote scan.
      [--password=PASSWORD]                # Login password for a remote scan, if required.
  i, [--key-files=one two three]           # Login key or certificate file for a remote scan.
      [--path=PATH]                        # Login path to use when connecting to the target (WinRM).
      [--sudo], [--no-sudo]                # Run scans with sudo. Only activates on Unix and non-root user.
      [--sudo-password=SUDO_PASSWORD]      # Specify a sudo password, if it is required.
      [--sudo-options=SUDO_OPTIONS]        # Additional sudo options for a remote scan.
      [--ssl], [--no-ssl]                  # Use SSL for transport layer encryption (WinRM).
      [--self-signed], [--no-self-signed]  # Allow remote scans with self-signed certificates (WinRM).
      [--json-config=JSON_CONFIG]          # Read configuration from JSON file (`-` reads from stdin).
      [--format=FORMAT]                    
      [--diagnose], [--no-diagnose]        # Show diagnostics (versions, configurations)

run all test files at the specified PATH.
```

**Comment by chris-rock** [comment]
@hack2learn does that solve your problem?

**Comment by hack2learn** [comment]
Hi Chris,

Didn't see the sudo option before. This will definitely solve the issue!
Thank you!

**Comment by chris-rock** [comment]
@hack2learn That sounds great. I am going to close this issue. Please reopen if this does not solve your need.

**Comment by vikatgithub** [comment]
Hi,

I am having a similar issues while trying to audit the .ssh/authorized_keys file for a user different from the target user. And the --sudo-options or --sudo-comands flags do not work, because the sudo command requires tty.

This can be verified by using simple ssh commands like this:

```
> ssh user1@hostname 'sudo -u root cat /home/user2/.ssh/authorized_keys'
stdin: is not a tty 
sudo: sorry, you must have a tty to run sudo

> ssh -t user1@hostname 'sudo -u root cat /home/user2/.ssh/authorized_keys'
normal output with keys

```

Note the '-t' option to ssh that made the difference.

I created a InSpec control with command resource

`describe command('cat /home/user2/.ssh/authorized_keys')`

and ran the test as:

`inspec exec control-path -i key/path --sudo-command='sudo -u root' -t ssh://user1@hostname`

and the test failed. If I use 

`inspec exec control-path -i key/path --sudo --sudo-options='-u root' -t ssh://user1@hostname`

It gives error:

`Sudo failed: Sudo requires a TTY. Please see README ....`

So, is there a way to pass the '-t' options to ssh target?
