### ISSUE TITLE
platform: Formatting of 'version' on Mac OSX

### ISSUE THREAD

**Issue by aaronlippold** [inspec/inspec#3722]
I think we should decide which version is our standard. I think most folks will 'assume' we are using the Apple version `10.x.y` - but from a technical perspective I can see why we are pulling the `darwin 17.x.y` data.

 chefdk to 3.6.57 on a mac machine (OSX 10.13) 

`inspec shell` cmd old output

```
You are currently running on:

    OS platform:  mac_os_x
    OS family:  darwin
    OS release: 10.13.6
```

Latest data:

```
You are currently running on:

    Name:      mac_os_x
    Families:  darwin, bsd, unix, os
    Release:   17.7.0
    Arch:      x86_64
```
https://en.wikipedia.org/wiki/Darwin_(operating_system)#Release_history

Darwin (operating system)
Darwin is an open-source Unix-like operating system first released by Apple Inc. in 2000. It is composed of code developed by Apple, as well as code derived from NeXTSTEP, BSD, Mach, and other free software projects.

Darwin forms the core set of components upon which macOS (previously OS X and Mac OS X), iOS, watchOS, tvOS, and audioOS are based. It is mostly POSIX-compatible, but has never, by itself, been certified as compatible with any version of POSIX. Starting with Leopard, macOS has been certified as compatible with the Single UNIX Specification version 3 (SUSv3).

Not sure which we ‘support’ but perhaps a note in the docs until we decide if we want to ‘override’ this for the same of user simplicity

**Comment by alex-w-k** [comment]
I'm experiencing this as well with `chef -v`:
```
Chef Development Kit Version: 3.0.36
chef-client version: 14.1.12
delivery version: master (7206afaf4cf29a17d2144bb39c55b7212cfafcc7)
berks version: 7.0.2
kitchen version: 1.21.2
inspec version: 2.1.72
```

**Comment by clintoncwolfe** [comment]
Hi! Thanks so much for reporting this.  However, the functionality you describe is actually handled by 
an underlying library, [train](https://github.com/inspec/train), which is used to detect platforms and
connect to remote scanning targets. Any new features or fixes would need to be contributed there.

In fact, an issue has been opened already in train on this topic, https://github.com/inspec/train/issues/395

Because this is already open on train, I'm closing the issue here as a duplicate.  Please continue discussion on https://github.com/inspec/train/issues/395 .
