### ISSUE TITLE
Specify non-default package systems

### ISSUE THREAD

**Issue by arthurbarr** [inspec/inspec#374]
I have a case where I am using RPMs on Ubuntu.  The `package` resource always uses the default package type for the OS, which in this case is apt/deb.  It would be useful if there were a way of overriding this (like `yum_package`).

**Comment by srenatus** [comment]
Great idea. :+1: 

We're working on a similar enhancement for services in #242. (This one can then be handled in an analogous way.)

**Comment by kekaichinose** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
