### ISSUE TITLE
Users resource causes high memory usage on windows domain controllers

### ISSUE THREAD

**Issue by teknofire** [inspec/inspec#3747]
### 🎛 Description

🐛 bug report

On a Windows DomainController node the `users` resource can cause a large amount of cpu and memory usage.  This happens because the resource will fetch all the user accounts from the DomainController and attempt to filter them in memory.  

Here are some examples of control code that will trigger this from cis-windows2012r2-level1-domaincontroller 2.2.1-1

```
# 2.3.1.1_L1_Ensure_Accounts_Administrator_account_status_is_set_to_Disabled
describe users.where { uid =~ /S\-1\-5\-21\-\d+\-\d+\-\d+\-500/ } do 
it { should exist } 
end 
describe users.where { uid =~ /S\-1\-5\-21\-\d+\-\d+\-\d+\-500/ } do 
it { should be_disabled } 
end 

# 2.3.1.3_L1_Ensure_Accounts_Guest_account_status_is_set_to_Disabled
describe users.where { uid =~ /S\-1\-5\-21\-\d+\-\d+\-\d+\-501/ } do 
it { should exist } 
end 
describe users.where { uid =~ /S\-1\-5\-21\-\d+\-\d+\-\d+\-501/ } do 
it { should be_disabled } 
end 

# 2.3.1.5_L1_Configure_Accounts_Rename_administrator_account
describe user("Administrator") do 
it { should_not exist } 
end 
# 4.6.4-Security Options_benchmarks_rule_2.3.1.6_L1Configure_Accounts_Rename_guest_account
describe user("Guest") do 
it { should_not exist } 
end 
```

### 🌍 InSpec and Platform Version

Inspec 2.2.102 but this looks like it also happens with the latest 3.2.6

### 🤔 Replication Case

You will need to configure a windows domain controller node with lots of users accounts and then try to run a profile that does a

```
describe users.where { uid =~ /S\-1\-5\-21\-\d+\-\d+\-\d+\-500/ } do 
it { should exist } 
end 
```

### 💁 Possible Solutions

Not sure what would be required to fix other than to attempt to do the filter in powershell rather than in memory of the Inspec process.  

### 💻 Stacktrace

Not available as running these controls usually causes the system to become unresponsive and requires a reboot.

**Comment by jerryaldrichiii** [comment]
The issue here I suspect is that all users are loaded into memory then acted upon. See: 
https://github.com/inspec/inspec/blob/master/lib/inspec/resources/users.rb#L614

**Comment by james-stocks** [comment]
I think we can fix the singular case `user` by adding a new method to get just 1 user from the backend instead of collecting all user details.

I see that the plural case `users` is not trivial because its an implementation of FilterTable and we might want something fundamentally different here.
Maybe we should just document a warning for `users` (and I expect also `groups`)?

**Comment by clintoncwolfe** [comment]
`user` should be fixable, as you mention - pass some identifier (username, possibly qualified) and then use PowerShell to query.  That should help.

For `users`, we have a problem.  FilterTable is built to fetch-all, then filter-in-memory.  The only way around that is to add a resource parameter which would be used to do target-side filtering in PowerShell.  We'd have to implement whatever criteria are needed; and there would be user confusion between the criteria you can use in the `where` and the criteria you can use in the initial call.

It's not impossible, just hard.

**Comment by james-stocks** [comment]
Spent time today trying to get the single user case working.

It is possible to cut the current loading of user data down to a single user by changing the `where` clause:

` $adsi.Children | where {$_.SchemaClassName -eq 'user'}` --> `$adsi.Children | where {$_.SchemaClassName -eq 'user' -and $_.Name[0] -eq 'Administrator'}`

However when I added 3000 users to the machine I found this got increasingly slow and is not a solution.

An alternative is:

```
Get-WmiObject -Class win32_useraccount -filter "name='Administrator'"
```

This command seems to complete immediately even with thousands of users.
However it is missing the following fields: `minpasswordlength` `badpasswordattempts` `maxbadpasswords` `home` `groups` 

These would need additional queries to fetch the relevant data. `groups` is noteworthy because enumerating groups may run into unusable performance - @clintoncwolfe suggests lazy loading groups so it is only calculated when actually asked for.

**Comment by james-stocks** [comment]
I think `groups` will have the same issue https://github.com/inspec/inspec/blob/master/lib/inspec/resources/groups.rb#L196

I'm not sure a separate issue should be filed for that.

**Comment by zenspider** [comment]
Moving to blocked and assigning to @kekaichinose... this is a resource issue at this point. We can't do anything real with this until we have something to test against. Maybe that means I should assign to @btm  as well...

**Comment by kekaichinose** [comment]
The Content team created a work-around to address this issue short-term. There's a longer term solution that will be tracked in a separate issue as time allows. Closing.
