### ISSUE TITLE
RFC: Rename 'attributes'

### ISSUE THREAD

**Issue by jerryaldrichiii** [inspec/inspec#3748]
The word `attributes` is a bit overloaded in Chef/InSpec. Do you folks have any suggestions on other names? 

The only requirement is that it cannot be mentioned in the [InSpec Glossary](https://github.com/inspec/inspec/blob/master/docs/glossary.md) and preferably doesn't conflict with the terminology used in Chef.

Like all breaking changes, this would be introduced over two major versions - n+1 would issue warnings when the word `attribute` is used, and n+2 would emit an error and halt the run when attribute is used; n+3 would remove it entirely.

**Comment by jerryaldrichiii** [comment]
Grr...early return while trying to hit `"` coupled with GitHub showing edits to the title is quite infuriating.

**Comment by aaronlippold** [comment]
Parameters?

**Comment by jerryaldrichiii** [comment]
@aaronlippold might conflict with a resource [parameter](https://github.com/inspec/inspec/blob/master/docs/glossary.md#resource-parameter).

**Comment by miah** [comment]
Some ideas:

trait, facet, characteristic, quirk

**Comment by aaronlippold** [comment]
Are you trying to separate the connection between InSpec and Chef attributes, if so, I don't think the name of `attributes` is really the source of the issue is the marketing of Chef and `Chef` InSpec placing too close a connection between the two distinct languages so that a fundamental confusion is formed that they are connected when in fact they are not.

`a Chef recipe is a collection of configuration actions in code that *set system settings* and have parameterized data values accessible via an attributes interface. An InSpec profile is a set of validation actions in code that *validate system settings* ….`  

The Ying/Yang of this is the function/capability we wanted to create. We need to make it clear that they are connected at a process level and stop. 

The fact that each collection has a need for dynamic influx of structured data and parameters, attributes and variables are the common construct of computer science to provide that interface. Just because C, Java, Ruby and Python all have variables and parameters we don’t see those languages having to rename the name of the axiom component. Nor do we call an object in ruby a `thing` or `collective` to avoid conflict with other OO languages use of the same common term. 

Chef and InSpec are separate languages and separate processes and it is *fundamentally important* that this be true given the need to maintain chain of trust but, not to get side tracked, it seems to me that the core of this confusion is that the community takes the `Chef` in `Chef InSpec` far too literally - not as a something akin other companies that have multiple projects but that InSpec is somehow a subproject of Chef itself rather than a distinct project which happens to be at this time supported by the Company Chef.

**Comment by aaronlippold** [comment]
Just my two cents here - I think our most effective approach here is to market as: 

`It isn't Chef InSpec` its `InSpec By Chef` or just `InSpec`. 

I think the Marketing folks will go with the first option - but I think `InSpec by Chef` or `InSpec supported by Chef` is really the way that we let folks know that the great open-source project InSpec has `big backing` which is really the concern we are wanting to let the community know. 

The *other* guys, for example, have no direct corporate connection other than a logo below but the community at large still knows its a corporately supported open-source project. This is good, it shows that there is people, funding and backing, which is great and really the key value that support brings to the open community.

**Comment by clintoncwolfe** [comment]
We're not really looking to drive *separation* between Chef Software, Inc. products. 

For this RFC, we're just looking to keep the scope to: "what if a different word was used for attributes, that doesn't collide across the Chef ecosystem?"

**Comment by clintoncwolfe** [comment]
My favorite so far is `vars` or `var`.

**Comment by lamont-granquist** [comment]
@aaronlippold no, the namespace collision between inspec attributes and chef attributes really is the start and the end of the problem.

we already ran into this problem within chef itself and spent the time to rename resource attributes to properties.  the lesson learned there was that the namespace collision caused a lot of issues, and those issues largely went away with the renaming, and it was worth it (even though it was a lot of work).  we have still never formally deprecated the word "attributes" in resources there, but the shift to properties in all our training and docs made the confusion go away.

and we already see confusion by users between inspec attributes and chef attributes.

**Comment by lamont-granquist** [comment]
and to plagiarize from chat the confusion arises when the two concepts naturally mix -- in the audit cookbook and in test-kitchen when you naturally are forced to deal with attributes and attributes and they're not the same thing.

**Comment by TheLonelyGhost** [comment]
If we're going this direction, to prevent future confusion, I feel like `attributes` is only one collision between `chef-client` and `inspec`. There are plenty of instances where "custom resource" needs more context.

I would think about naming it `input`, which might then lead to an optional interactive prompt (maybe hidden behind a CLI flag to enable it?) for each input if it's not given at the start of the `inspec exec` run. Obviously something that's out of scope for this discussion, but food for thought for future development efforts.

It might also persuade people to keep the inspec attributes (inputs?) as simple primitives instead of more complex data types.

**Comment by lamont-granquist** [comment]
yeah the conceptual overlap between chef resources and inspec resources is also poor, but we should keep this on topic just about renaming inspec attributes.

**Comment by clintoncwolfe** [comment]
Hrm, I'm liking input.  'inputs section of your kitchen.yml'.  'Use `--inputs <filename>`.  'In code, call `input('some_name')`'  'A custom `input_provider`'  Those all sound nice.


Though with `input`, a plugin that provides inputs could more naturally be called an `input_source plugin` - `inspec_input_prompt` would be a possible one.

**Comment by clintoncwolfe** [comment]
After internal discussion, we've decided to go with 'input'.  We intend 'input' to become available as an alternate in the 3.x series.

We also commit to an elongated deprecation schedule:
 * v4.0 - issue deprecation warning, but continue to document --attrs and `attribute` DSL
 * v5.0 - issue deprecation warning, only document `input`
 * v6.0 - immediately (but gracefully) exit with code 3 if attribute is encountered
 * v7.0 - --attrs and `attribute` is removed

Thanks for all the `input` on this topic!

**Comment by lamont-granquist** [comment]
One thing to consider is after the deprecation and you've scrubbed the docs in v5.0 that you're getting the bulk of the payoff.  You could gather information from users/customers after that point and decide on how aggressive to be with removal.  For example, I did a 2 year long deprecation cycle with `node.set` because I understood it would be painful.

**Comment by clintoncwolfe** [comment]
Thanks for all the discussion!  I'm closing this in favor of #3802, which will be the implementation tracking issue.
