### ISSUE TITLE
inspec habitat: Missing package name in last line of `create` output

### ISSUE THREAD

**Issue by clintoncwolfe** [inspec/inspec#3877]
### 🎛 Description

🐛 bug report

Refs #3818 

After running `inspec habitat profile create test-profile`, the .hart package is built, and this is the last few lines:

```
★ Signed artifact /hab/cache/artifacts/chef-inspec-profile-test-profile-0.1.0-20190308122429-x86_64-linux.hart.
<-- cleanuup stuff -->
[2019-03-08T07:25:01-05:00] INFO: Habitat artifact '' created.
```
The last line is intended to contain an artifact name, but it is an empty string.

### 🌍 InSpec and Platform Version

3.7.x

### 🤔 Replication Case

```
hab setup
inspec init profile test-profile
inspec habitat profile setup test-profile
inspec habitat profile create test-profile
```

**Comment by kekaichinose** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
