### ISSUE TITLE
Attribute->Input rename - Update Learn Chef materials

### ISSUE THREAD

**Issue by clintoncwolfe** [inspec/inspec#3881]
### 🎛 Description

As part of #3802, update the training materials for InSpec regarding attributes.

https://learn.chef.io/#/

Consider holding off until the plugin-ability is established (#3666).

Aha! Link: https://chef.aha.io/features/SH-2479

**Comment by Schwad** [comment]
At some point in my Chef leveling up I still did run across an `--attr` reference and let @kekaichinose know. I'm now doubting that it was actually in LearnChef but actually in our `inspec-gcp` README I'd used when setting up my GCP test/instance: https://github.com/inspec/inspec-gcp

**Comment by kekaichinose** [comment]
I'll get this into DevRel/Training team's queue to help us get updated

**Comment by kekaichinose** [comment]
I'll follow-up with LearnChef team on this

**Comment by kekaichinose** [comment]
I will consider this update if there's a large enough cry from our customers, but have not heard any around this issue since I started. Will close and look into this again if it comes up.

**Comment by aaronlippold** [comment]
Hello, yes there is a large cry from the community. Mainly because we've
renamed attributes to inputs and to provide outdated training is not a
service to the community. Please migrate all references to attributes to
inputs as prescribed in the 4.x and above guidance. If I recall the plan is
to totally deprecate a tribute in version 5.x so if we may as well get
ahead of the change.

**Comment by kekaichinose** [comment]
@aaronlippold, I did verify with the LearnChef folks that the material refresh that happened with ChefConf 2020 references the latest version of the product, which covers inputs. There is a separate issue for documentation references to be updated with attributes>inputs update so that can be tracked separately. This issue can remain closed.
