### ISSUE TITLE
Cannot load git-referenced bundled plugin 

### ISSUE THREAD

**Issue by james-stocks** [inspec/inspec#3904]
Using 3.7.11 from a gem install

```
➜  my-cool-project git:(my_branch) ✗ bundle exec inspec plugin install $(bundle show inspec-something)
Unrecognizable plugin structure - inspec-something-812f55372c8e - When installing from a path, please provide the path of the entry point file - installation failed.
```

The plugin source is at `/Users/jamesstocks/code/my-cool-project/vendor/bundle/ruby/2.3.0/bundler/gems/inspec-something-812f55372c8e/lib/inspec-something.rb`

Looking at the supported plugin loading cases [here](https://github.com/inspec/inspec/blob/master/lib/plugins/inspec-plugin-manager-cli/lib/inspec-plugin-manager-cli/cli_command.rb#L225) it looks like this setup does not match a supported case.

Workaround:
`ln -s $(bundle show inspec-something) ~/.inspec/plugins/inspec-something` works, but symlinking in a plugin like this is not recommended/supported.

**Comment by clintoncwolfe** [comment]
Thanks, the https://github.com/inspec/inspec/blob/master/lib/plugins/inspec-plugin-manager-cli/lib/inspec-plugin-manager-cli/cli_command.rb#L225 area is indeed where we would need to add a case in which the containing folder looks like a gem name with a hex digest suffix.  This is a fairly straightforward change, if a new contributor is interested!

**Comment by kekaichinose** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.

**Comment by james-stocks** [comment]
Still an issue.

**Comment by miah** [comment]
ref: https://github.com/inspec/inspec/issues/4006
