### ISSUE TITLE
question: what's the proper way to run inspec under Windows?

### ISSUE THREAD

**Issue by pkleanthous-zz** [inspec/inspec#3936]
### 🎛 Description

question: what's the proper way to run inspec under Windows?
I'm getting the error at the Stacktrace section when I'm running inspec from powershell.

### 🌍 InSpec and Platform Version

inspec --version
3.9.0

Windows 10

### 🤔 Replication Case

run inspec from a powershell terminal

### 💻 Stacktrace

inspec : Cannot process the XML from the 'Error' stream of 'c:\opscode\inspec\bin\inspec.bat': Root element is missing.
At C:\jenkins\workspace\\windows\3_test.ps1:18 char:1
+ inspec exec .\tests\uninstall.rb --reporter cli junit:artifacts/test_ ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : SyntaxError: (c:\opscode\inspec\bin\inspec.bat:String) [], XmlException
    + FullyQualifiedErrorId : ProcessStreamReader_CliXmlError

**Comment by kekaichinose** [comment]
@pkleanthous Apologies for letting this issue run long, but this looks to be support-related. We use GitHub issues to track bugs and feature requests. If you need support help (i.e. with using Chef InSpec), we recommend that if you are a:

* Chef customer:
  * Please reach out to your Customer Success manager and they can assist you
* Chef community member:
  * Please post to our Mailing List or join the Chef Community Slack
    * Chef Mailing List: https://discourse.chef.io/
    * Chef Community Slack: http://community-slack.chef.io/

Support issues opened here will be assumed to be from community members, and therefore closed and redirected to our Mailing List. Your issue can be found here:
https://discourse.chef.io/t/q-whats-the-proper-way-to-run-inspec-under-windows/16211

To read up more on how to file a support issue, check out:
https://github.com/inspec/.github/blob/master/SUPPORT.md

Thank you!
__Chef InSpec Team__

**Comment by gregbeck-cms** [comment]
BTW, I got this error in Windows 2016 Server when using a zipped archive with long pathnames for the profile in my depends: statement. Windows doesn't tolerate long pathnames when extracting archives, but that error message doesn't make it to stdout or stderr when running inspec. You can see this error if you try to extract the zipped archive directly in Windows. This error went away and I got my scan results once I extracted all the files in the archive and updated my depends: statement to point to the directory of extracted files instead of a zip archive.
