### ISSUE TITLE
Attribute has to be defined prior to being called.

### ISSUE THREAD

**Issue by TheLunaticScripter** [inspec/inspec#3955]
### 🎛 Description

🐛 I have a boolean attribute in a profile if the attribute is not scoped out in either the `inspec.yml` or the profile itself. When I use the attribute in an `only_if` there is no warning or error that the attribute is being ignored. If I use a `puts` with the attribute I get a message that the profile doesn't have an attribute with that name. 

### 🌍 InSpec and Platform Version

3.9.0 on windows and linux

### 🤔 Replication Case
test file
```ruby
puts ''
puts ''
puts attribute('bar')

control 'foo' do 
  title 'foo'
  desc 'foo'
  only_if { attribute('bar') != false }
  describe file('foo') do
    it{ should exist }
  end
end
```

insepce.yml
```
name: foo
title: foo
summary: foo
version: 0.1.0
maintainer: foo
```

Output
```
Profile 'foo' does not have an input with the name 'bar'
```

if the profile is run without the puts and using the `--attrs` with the `bar` attribute set to false there is no error and the control is not skipped.

### 💁 Possible Solutions

When an attribute is specified that is not declared even in an only_if produce an error, or when an attribute is used in a profile that has not been defined infer it's type and warn in the output or debug log that the attribute has been used but had a value of `nil`.

**Comment by clintoncwolfe** [comment]
~~Work has started on branch `cw/undeclared-inputs`. Confirmed that a bare valueless input will halt the run with the error `Profile 'undeclared_attribute' does not have an input with name 'undeclared_03'` (or similar). Undeclared inputs inside `control` blocks would not be evaluated until control evaluation - but the bare input aborts the run before then, so the reported problem (no error for undeclared inputs in only_if blocks) is due to to that code never even being reached.~~

EDIT: I was on a stale branch, never mind. This works in 4.2+.

I believe the intent for the input system, especially in the context of plugins, is for undeclared inputs to be permitted anywhere (including bare) in a control file. When an input is used that has not been assigned a value, a special `NO_VALUE_SET` class is returned that evaluates to a string with a warning, as well as emitting a `warn` level log message. So, that part of the suggested solution is in place:

```
[cwolfe@lodi inspec-inputs]$ be inspec exec test/unit/mock/profiles/inputs/undeclared
[2019-04-30T22:44:19-04:00] WARN: Input 'undeclared_01' does not have a value. Use --input-file to provide a value for 'undeclared_01' or specify a  value with `attribute('undeclared_01', value: 'somevalue', ...)`.
[2019-04-30T22:44:19-04:00] WARN: Input 'undeclared_02' does not have a value. Use --input-file to provide a value for 'undeclared_02' or specify a  value with `attribute('undeclared_02', value: 'somevalue', ...)`.
[2019-04-30T22:44:19-04:00] WARN: Input 'undeclared_03' does not have a value. Use --input-file to provide a value for 'undeclared_03' or specify a  value with `attribute('undeclared_03', value: 'somevalue', ...)`.
[2019-04-30T22:44:19-04:00] WARN: Input 'undeclared_03' does not have a value. Use --input-file to provide a value for 'undeclared_03' or specify a  value with `attribute('undeclared_03', value: 'somevalue', ...)`.

Profile: InSpec Profile (undeclared_attribute)
Version: 0.1.0
Target:  local://

  ✔  start_marker: dummy_test_01
     ✔  dummy_test_01 should cmp == "dummy_test_01"
  ✔  undeclared_in_control_body: dummy_test_02
     ✔  dummy_test_02 should cmp == "dummy_test_02"
  ✔  undeclared_in_only_if: dummy_test_03
     ✔  dummy_test_03 should cmp == "dummy_test_03"
  ✔  end_marker: dummy_test_04
     ✔  dummy_test_04 should cmp == "dummy_test_04"


Profile Summary: 4 successful controls, 0 control failures, 0 controls skipped
Test Summary: 4 successful, 0 failures, 0 skipped
```
