### ISSUE TITLE
gem install of 4.3.2 does not install executable

### ISSUE THREAD

**Issue by micheelengronne** [inspec/inspec#3999]
### 🎛 Description

🐛 bug report

The last version 4.3.2 does not simply work on debian and ubuntu. 3.9.3 works like a charm.

    inspec: command not found

### 🌍 InSpec and Platform Version

inspec:4.3.2

OS: debian (via Docker image ruby:latest ) & ubuntu (via Docker image ubuntu:bionic )

### 🤔 Replication Case

Install inspec 4.3.2 on these systems via a Gemfile and try to call inspec. The terminal gives:

    inspec: command not found

### 💁 Possible Solutions

Check the inspec binary path and ensure it is in the regular binaries paths for Debian & Ubuntu.

### 💻 Stacktrace

    inspec: command not found

**Comment by clintoncwolfe** [comment]
Thanks for the report! However, this is intentional behavior. As of version 4, Chef InSpec is distributed as two gems: `inspec`, a library gem which does not contain the executable, and the `inspec-bin` gem that contains the executable which requires accepting the Chef License. See the [FAQ](https://www.chef.io/bmc-faq/) and [Licensing Info](https://docs.chef.io/chef_license.html) for more information.

Alternatively, consider using the binary distributions (.deb files from download.chef.io) which contain the executable, and should "just work", after accepting the license.  That may be easier than using a Gemfile approach.

Refs #3982

**Comment by arothian** [comment]
Does it make sense to add some documentation around inspec-bin to this section: https://github.com/inspec/inspec/blob/master/README.md#install-it-via-rubygemsorg?

This is kinda confusing for folks that have used this gem for quite some time. Perhaps even a better callout in the changelog about the changed behavior as well.

**Comment by clintoncwolfe** [comment]
Good idea - #4011

**Comment by darkn3rd** [comment]
Note the instructions online and just about everywhere from site:inspec.io, state to get inspec, you need to do `gem install inspec`.
