### ISSUE TITLE
Inspec for Alicloud resource

### ISSUE THREAD

**Issue by kamalika-majumder** [inspec/inspec#4061]
### 🎛 Description

 🙋 feature request

I would like to use inspec to test terraform alicloud code. I would like to run it in testkitchen for integration tests and unit tests. 

### 💁 Possible Solutions

After having looked at the code I see that some of the cloud provider libraries are here:
https://github.com/inspec/inspec/tree/master/lib/resources/aws
I would like to add alicloud as well in the list. 
Please let me know if this feature can be added or if there is already any way to do that.

**Comment by kekaichinose** [comment]
Thank you for filing this issue. As with many large open source projects, we have a backlog of bugs and issues of varying user impact. Some issues are perpetually subject to lower priority than others in our backlog. We have reviewed the issue, and we have determined this a very low priority when considered in the context of the entire backlog. We have elected to close it as "Declined" due to competing priorities. We very much appreciate you bringing this to our attention.

Thank you!
__Chef InSpec Team__
