### ISSUE TITLE
Service resource `be_running?` is deprecated but `be_active?` throws an error

### ISSUE THREAD

**Issue by russellseymour** [inspec/inspec#4291]
When a service is being tests the documentation states that to see if the service is running the matcher `be_running` should be used.

However when run a deprecation notice is output stating that this is only for backward compatibility:

```
DEPRECATION: The service `be_running?` matcher is deprecated. This is only allowed for compatibility with ServerSpec (used at C:/Users/russells/workspaces/azure/camsa-setup/test/integration/camsa/monitoring.rb:82)
```

If this is changed to use `be_active` the error on the test is as follows:

```
  Service statsd
     [PASS]  should be enabled
     [FAIL]  should be active
     expected Service statsd to respond to `active?`
```

Looking at the code the command that runs the `active?` check runs the command

systemctl is-active statsd --quiet

The service is installed on the machine as a systemd service. If I run this command on the machine I get the the output of `active` if running or `inactive` of not running.

Indeed if running the exit code is 0 and if not running it is 3 which is what is required. However the output of the test states that `active?` is not responded to.

**Comment by jeremymv2** [comment]
Some additional context:
https://github.com/inspec/inspec/issues/4059#issuecomment-499397982

**Comment by clintoncwolfe** [comment]
It looks like `active?` is an internal predicate used by some of the OS-specific implementations, not intended to be exposed as a resource matcher - so I don't think it is expected to work. "active" is a concept specific to certain service systems, and I think the `service` resource is trying to be more generic - I say that simply because I don't see something like `be_active` documented anywhere.

Instead, calling `be_running` really is the right thing to do here - and I've opened a PR #4295 to remove that deprecation warning.

**Comment by kekaichinose** [comment]
@russellseymour per @clintoncwolfe's explanation, it sounds like your issue with `be_running?` will be resolved with the removal of the deprecation warning in PR #4295. Can you confirm?

If so, we'll make sure to link them so this issue will be closed when that PR is merged. Thanks!

**Comment by clintoncwolfe** [comment]
Closing, #4295 is merged!
