### ISSUE TITLE
podman support

### ISSUE THREAD

**Issue by rhatdan** [inspec/inspec#4299]
Is this something the inspec would consider?

**Comment by rhatdan** [comment]
https://github.com/containers/libpod/issues/3570

**Comment by clintoncwolfe** [comment]
Since InSpec is an open-source project, contributions are welcome. I don't think we'd be likely to implement directly as Chef engineers as we haven't heard much demand for it. I encourage you to look into it.

The actual work would occur on the inspec/train repo, not here, though - train handles all the connection setup work.

**Comment by kmf** [comment]
I honestly think that it would be a great edition.

**Comment by zenspider** [comment]
This is a train request, not an inspec request. Closing.
