### ISSUE TITLE
Waiver (Epic)

### ISSUE THREAD

**Issue by kekaichinose** [inspec/inspec#4408]
__PROBLEM STATEMENT:__

As a customer of InSpec, I want to be able to waive controls in profiles so that I can maintain my compliance posture at the speed of my business.

This is the first step towards waiver support in Chef InSpec. This work covers being able to ingest waivers for a set of controls, processing it during an`inspec exec` run, and outputting the results in the reporter.

__CUSTOMER IMPACT:__

Users need a way to waive controls and apply the waivers to their inspec runs.

__ACCEPTANCE CRITERIA:__

* Read in waiver(s)
* Overlay waiver(s) onto controls
* Run scan with modified control manifest
* Generate result output
* Send result output via reporter

__TEST SCENARIO:__

* run a inspec exec on the command line
  * with a waiver input
  * with a profile that has controls specified to be waived in the waiver input
* review the report
  * ensure waived controls do not affect report status
  * ensure the reasons the controls were waived are visible

Aha! Link: https://chef.aha.io/epics/INSPEC-E-30

**Comment by aaronlippold** [comment]
We have to remember that in compliance skipped is a different concept than not applicable. 

Which is what you mean when you say waived a.k.a not applicable. 

This doesn't have anything to do with the result of the control but rather if the control is part of the final evaluation. The tests should always be run and if they are applicable then they either are passed or failed. if they are not applicable then the result of the test is not counted towards the final evaluation of the system. If they are skipped tests then we have no information one way or the other i.e compliant or are you not complaint. 

Having accredited many systems the results of a test on a system are always valuable to me. 

What I decide to do with the data that I receive is a completely different matter.

As ispec is trying to codify the compliance process we need to respect these distinctions. I completely agree that the idea of waving controls or setting them non-applicable in the more formal term it's an absolutely valid use case we should not confuse it with the concept of a skipped test.

The pattern we should be moving towards in my opinion is that we have controls which have passing and failing tests, we have controls which have and selected as not applicable or waived, and we have a final set of tests that are skipping due to insufficient data or some other misalignment such as a missing package or file access permission on the system etc. these final sets of tests are closer to errors than they are known conditions and they need to be evaluated such that they're either marked as non-applicable for known reason AKA gnome is not installed so this control is not applicable, or the system does not use nsf so this control is not applicable.

Take this example,

The main point here is that it wasn't that a test was not run it was that a different test was run, if the NFS server package is installed and the service is enabled then these configurations settings should be in place. If the NSF package is installed but the service is not enabled then another set of tests should be run. Otherwise if the NFS package is not installed then this control is not applicable to the system because the system cannot be out of compliance given that the service could not possibly be running.

In the above scenario in one case I had a set of tests that would either pass or fail I had another set of tests that would pass your fail or I had a final test that passed or failed, and given the scenario or branch of logic that I was in the impact of that control was adjusted accordingly.

The final case was the waived control case. And notice that it was a very deterministic state and there was an active test performed to validate that state. it was not a skip test a test was performed to determine which state we were in and in that state if the condition was met. Many times the describe block AKA the reporting to the end user is the action provided by the test, it tells the a creditor and the developer that the condition was met.

**Comment by galenemery** [comment]
(please excuse typos, i am typing one handed due to injury here)

I think for the purposes of this discussion, on how Chef InSpec treats controls that are some other state than expected to pass and report; we need to be very clear on our language and not confuse it with capital C Compliance language.  We may use the word waiver here, I don't think its valuable (yet) to argue that other places use the word differently.  We can deal with that after we have gotten clear on what the expected control states are.

We also understand that there are multiple ways in which people may want this information; so it needs to be flexible to accommodate.

I see several expected states that InSpec controls could be in:

These first two are not in question:
```
Control ran and passed = not a finding, compliant
Control ran and failed = finding, not-compliant
```
The other options require some context as to either what the expected state is, or the expected impact of the result.  I think the simplest of these is:

`This control is not applicable to this system; do not run control.`

For reasons X, we are not running this control because it is not something we care about on the system.  Because we don't care about it, do not waste resources running it.  Possible example use case: permanent exception to the system policy.

`This control's output is not applicable to whether the system is deemed compliant, run control but do not count as a finding`

`control ran, output passed/failed = not a finding, compliant`

For reasons X, the state of this control is not applicable to whether the system is in or out of compliance, but I do want the system to run the control.  It's possible I may care about the result in the future, but not guaranteed.  Possible example use cases: temporary exceptions to policy, controls I want to be informed upon that have no impact.

There are a number of reasons we may want a control in this state, but I feel most of our discussion has been around the reasons why.  Whereas if we build the correct state with the ability to be flexible as to reason, we can simplify the design.

@aaronlippold I view your NFS example as more of a conditional.  Policy says I should secure running NFS this way, installed NFS this other way and if NFS isn't installed then don't bother checking the config.  Doesn't feel like a waiver event.

**Comment by zenspider** [comment]
Both comments are hidden as "off topic", only because github doesn't have "out of scope" as a reason.

**Comment by kekaichinose** [comment]
Epic completed as part of 4.17 release. Closing.
