### ISSUE TITLE
resource 'command' not including PATH items '/sbin' and '/usr/sbin'

### ISSUE THREAD

**Issue by jeremymv2** [inspec/inspec#450]
When I use the 'command' resource I need to specify the entire path to the command when the command exists in /sbin or /usr/sbin or /usr/local/sbin.

With serverspec I can optionally define a PATH this way:
PATH environment variable
You can add PATH environment variable in spec_helper.rb or other places like this.
`set :path, '/sbin:/usr/local/sbin:$PATH'`

Is this something that can be added to inspec? This could make migrating existing serverspec tests to inspec easier for folks.

**Comment by chris-rock** [comment]
@jeremymv2 Thank you very much for bringing this topic up. I have some questions, I'd like to understand:

Is the PATH set, when you log into the machine directly? Could you please elaborate a little bit more, why you need the PATH? Is the reason multi os support? May it happen, that the command is available in various locations on the same systems?

I get the use case and I can see value in adding a feature that helps to address the topic. We need to find some answer before we are implementing a solution:
- Is the path only valid for one, multiple or a group of rules?
- setting `path` vs `mybin='/sbin/command'; describe command(mybin) ...`
- how is this portable across multiple operating systems? The path may be dependent on the OS, but in some cases may not?

**Comment by jeremymv2** [comment]
@chris-rock 
- Testing primarily with the centos-6.6 and centos-7.1 images I see that the PATH for the 'vagrant' user does include the sbin dirs: `/usr/local/sbin:/usr/sbin:/sbin`.
- The command resource for things in sbin dirs only seems to work if I specify the full path like: `describe command('/usr/sbin/sestatus -v') do`
- The `sestatus` command only exists as `/usr/sbin/sestatus`
- With serverspec I can utilize a spec_helper.rb that has `set :path, '/sbin:/usr/local/sbin:/usr/sbin:$PATH' unless os[:family] == 'windows'`
- When I set the PATH just in one place in the spec_helper.rb for serverspec, I can then utilize it across all of my spec files and rules.
- For organizations that have many spec files, this is helpful to them to only have to define the PATH in one place when converting a lot of serverspec rules to inspec

**Comment by jerryaldrichiii** [comment]
Quick notes that may help. All of the below is executed on a CentOS 7.3 node.

It seems like executing with `--sudo` will "fix" the issue, but the real issue is related to `PATH`

## SSH remote command (without sudo)
```
[/tmp/foobar]$ ssh vagrant@127.0.0.1 -p 2202 -i OMITTED 'env | grep PATH'
PATH=/usr/local/bin:/usr/bin
```

## SSH remote command (with sudo)
```
[/tmp/foobar]$ ssh vagrant@127.0.0.1 -p 2202 -i OMITTED 'sudo env | grep PATH'
PATH=/sbin:/bin:/usr/sbin:/usr/bin
```

## Command executed after logging in via SSH (without sudo)
```
[/tmp/foobar]$ ssh vagrant@127.0.0.1 -p 2202 -i OMITTED 
[vagrant@default-centos-73 ~]$ env | grep PATH
PATH=/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/vagrant/.local/bin:/home/vagrant/bin
```

## Command executed after logging in via SSH (with sudo)
```
[/tmp/foobar]$ ssh vagrant@127.0.0.1 -p 2202 -i OMITTED 
[vagrant@default-centos-73 ~]$ sudo env | grep PATH
PATH=/sbin:/bin:/usr/sbin:/usr/bin
```

**Comment by alecxvs** [comment]
I encountered an issue with the path while using the port resource. On my Vagrant VM, the `ss` binary is located in `/usr/sbin` but that's not specified in the PATH when inspec runs a command (whether sudo or not). The workaround for me is to install the deprecated net-tools during my tests and use netstat just because it lands in another bin directory that inspec can see, which really doesn't feel like a good solution.

(By all accounts though I would expect sudo or root to have access to sbin directories since they are meant to be executed by the root user, but it's another case where being able to change the path would be helpful)

**Comment by scalp42** [comment]
Has anyone figured a workaround regarding passing ENV variables while still using sudo?

**Comment by kekaichinose** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.

**Comment by scalp42** [comment]
It's really a shame that all issues are getting closed.
