### ISSUE TITLE
InSpec should use vendor directory to resolve dependencies for an archived profile

### ISSUE THREAD

**Issue by james-stocks** [inspec/inspec#4519]
InSpec 4.7.3 shipped with ChefDK 4.2.0

# Describe the problem

We have a "resource pack" InSpec profile in a Github repo.
We then create compliance profiles that depend on the resource pack. We `vendor` these and ship the tar.gz as part of Chef Automate.
Airgapped customers are unable to create wrapper profiles to customise the controls that run, because they do not have access to the source for the resource pack - even though the compliance profile is vendored and the resource code is available in the `vendor` directory.

```
➜  vendor-test inspec vendor my_wrapper_profile
Traceback (most recent call last):
	27: from /usr/local/bin/inspec:343:in `<main>'
	26: from /usr/local/bin/inspec:343:in `load'
	25: from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/inspec-bin-4.7.3/bin/inspec:11:in `<top (required)>'
	24: from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.7.3/lib/inspec/base_cli.rb:31:in `start'
	23: from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	22: from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	21: from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	20: from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	19: from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.7.3/lib/inspec/cli.rb:171:in `vendor'
	18: from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.7.3/lib/inspec/base_cli.rb:274:in `vendor_deps'
	17: from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.7.3/lib/inspec/profile_vendor.rb:13:in `vendor!'
	16: from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.7.3/lib/inspec/profile_vendor.rb:56:in `vendor_dependencies'
	15: from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.7.3/lib/inspec/profile.rb:521:in `generate_lockfile'
	14: from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.7.3/lib/inspec/dependencies/dependency_set.rb:88:in `vendor'
	13: from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.7.3/lib/inspec/dependencies/resolver.rb:30:in `resolve'
	12: from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.7.3/lib/inspec/dependencies/resolver.rb:59:in `resolve'
	11: from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.7.3/lib/inspec/dependencies/resolver.rb:59:in `each'
	10: from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.7.3/lib/inspec/dependencies/resolver.rb:78:in `block in resolve'
	 9: from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.7.3/lib/inspec/dependencies/resolver.rb:59:in `resolve'
	 8: from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.7.3/lib/inspec/dependencies/resolver.rb:59:in `each'
	 7: from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.7.3/lib/inspec/dependencies/resolver.rb:67:in `block in resolve'
	 6: from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.7.3/lib/inspec/dependencies/requirement.rb:79:in `resolved_source'
	 5: from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.7.3/lib/inspec/cached_fetcher.rb:21:in `resolved_source'
	 4: from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.7.3/lib/inspec/cached_fetcher.rb:38:in `fetch'
	 3: from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.7.3/lib/inspec/cached_fetcher.rb:31:in `cache_key'
	 2: from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.7.3/lib/fetchers/git.rb:63:in `cache_key'
	 1: from /opt/chefdk/embedded/lib/ruby/gems/2.6.0/gems/inspec-4.7.3/lib/fetchers/git.rb:84:in `resolved_ref'
 (RuntimeError)edded/lib/ruby/gems/2.6.0/gems/inspec-4.7.3/lib/fetchers/git.rb:91:in `resolve_ref': Error running 'git ls-remote "git@github.com:james-stocks/my-resources.git" "master*"': ssh: Could not resolve hostname github.com: nodename nor servname provided, or not known
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

## Example reproduction case

 * `inspec init` profile A
 * `inspec archive` profile A
 * `inspec init` profile B
 * in the inspec.yml for profile B add a `path` dependency to the archived tar.gz for profile A
 * `inspec archive` profile B
 * Move the tar for profile B to some other directory and cd into it (so that the source directories for A and B and the tar file for A are no longer immediately available).
 * `inspec init` profile C
 * in the inspec.yml for profile C add a path dependency to the tar file for B
 * `inspec archive` profile C

### Expected behaviour

Profile C is archived to a tar.gz.  InSpec does not need to resolve profile B's path dependency for profile A because B has been vendored and all dependency source is already available in profile B's `vendor` directory.

### Actual behaviour

InSpec still needs to resolve profile B's path dependency on A and tries to find the tar file for profile A at the specified `path`.

```
/Users/jamesstocks/code/inspec/lib/fetchers/local.rb:104:in `read': No such file or directory @ rb_sysopen - /Users/jamesstocks/vendor-test/sub/my-resource-profile-1.0.0.tar.gz (Errno::ENOENT)
```

**Comment by frezbo** [comment]
I also faced the same issue in our offline environment, but I had an internal artifactory available where I could pull the dependent profiles from. I ended up calling the Inspec `vendor` API before executing the profiles.

**Comment by clintoncwolfe** [comment]
Clarifications:

1. A closed-source profile or resource pack distributor runs `inspec archive` to pack up their profile. The tarball is delivered to the user.
2. The use may or may not untar the tarball?
3. The use creates a wrapper profile that depends on the possibly untarred tarball. Is the dependency local?
4. The wrapper profile is exec'd or archived. No network traffic to fetch deps must occur.

**Comment by james-stocks** [comment]
Regarding 4., There has to be at least 1 pathway for airgapped users to work with only the code we vendor and ship to them in Automate; but I imagine there are other users who will need InSpec to continue its current behaviour of resolving all dependencies recursively from source.

I would expect (just my opinion) that when I run `archive` all my code is packed into a tar that will be 100% usable even when the declared dependency sources (Github or local paths) are no longer available.

**Comment by clintoncwolfe** [comment]
I believe we have identified a solution using existing functionality. This approach has not been tested thoroughly, but here's the idea:
1. On a connected machine, clone or otherwise obtain a copy of the resource pack or other baseline profile.
2. Run `inspec archive <base-profile-name>` . The file <base-profile-name>.<version>.tar.gz (or .zip) is created.
3. Send that file to the disconnected machine, using sideband means such as SSH, artifact server, etc.
4. On the disconnected machine, the profile may already exist or may be constructed using `inspec init profile <main-profile-name>`
5. *IMPORTANT - THIS IS THE TRICK:*: Edit <main-profile-name>/inspec.yaml> to have the following dependency:
```
depends:
  - name: <base-profile-name>
    path: ../<base-profile-name>-<version>.tar.gz
```
I have not yet seen network traffic from profile fetching, but I may be wrong.

**Comment by kekaichinose** [comment]
@james-stocks or @skpaterson just trying to clarify impact, but per the customer or CFT, when was the last version they said this functionality worked in?

**Comment by clintoncwolfe** [comment]
From internal conversations, two more points:
 * @james-stocks says the workaround does not work (that is, it still talks on the network)
 * @skpaterson says this is actually a regression. I do not know the last working version.

I emphasize that the `vendor` command is not intended to support this usage. You are looking for `archive`.

**Comment by clintoncwolfe** [comment]
For what it is worth, I just archived the inspec-aws resource pack, then made a wrapper profile for it with a local path dependency on inspec-aws-1.2.1.tar.gz, disabled my wifi, and archived the wrapper profile. It didn't hang or anything. This is on inspec 4.17.26.

So, I think repeated archiving does work, and you can rely on an archive file to work for you in an airgapped environment, even if there are dependencies.

What are the other angles to this? I want to help make sure this work for you.

**Comment by james-stocks** [comment]
>  just archived the inspec-aws resource pack, then made a wrapper profile for it with a local path dependency on inspec-aws-1.2.1.tar.gz, disabled my wifi, and archived the wrapper profile

This differs from the issue reproduction, there's 3 profiles at play in this use case rather than 2:
 * Have a "resource pack" profile (like inspec-aws) in a Github repo
 * Create a profile that depends on the resource pack via a git reference
 * Archive that profile (this.tar.gz is now the Chef compliance profile we ship to customers in Automate)
 * On a workstation that does not have access to Github, create a wrapper profile that depends on the compliance profile (using a `path` reference to the tar.gz file) and try to `archive` it.

**Comment by skpaterson** [comment]
To clarify, we're not sure if ^ is a regression or not but our understanding thus far has been it should be possible to create further wrapper profiles in isolation based on archived content.

**Comment by clintoncwolfe** [comment]
OK, I'm with you, in that I can reproduce the issue as described. Here's what I found.

If I always use a path reference - that is, if I tarball the inspec-aws resource pack, then make a wrapper profile with a local tarball reference PRIOR to sending to the customer - it works fine. You can repeatedly wrap and archive profiles without network access so long as they local path references. I was able to do this 4 levels deep.

It appears, however, if you introduce a git dependency at any point in the chain, it will check it.

Is this a livable workaround? It's a change in procedure to how tarballs for airgapped customers are created - always make sure it is an archived tarball, with a local path dependency in the wrapper profile.

**Comment by james-stocks** [comment]
That sounds promising @clintoncwolfe I'll test that out - thanks!
If that's the case, we can figure out some workaround where our CI does the git fetch for the tarball that our profiles can then refer to by path.

It would still be ideal to fix this. At least it should be documented or `archive` should generate warnings that the git ref you're archiving might not do what you expect it to.

**Comment by frezbo** [comment]
Ok the actual issue seems to be left out. I will try to explain the use-case to my best.

*All things happening on a box with network connectivity to Remote Server X*

Profile *B* depends on profile A from an http remote server **X.**
Profile *B* is archived. It includes the `vendor` folder containing profile *A*.
Profile *B* is pushed to remote server **X**
Create a new profile *C* that depends on profile *B*
Profile *C* is pushed to **Y**

*Now things happening on a machine having access to remote server Y and no local `~/.inspec` folder present (this is an important factor)*

Pull the profile *C* from **Y**
Try to `inspec exec`, profile *C* still tries to fetch profile *A* and *B* even though profile *C* has the `vendor` folder with profiles *A* and *B*.

This scenario also happens with git or other remote profile specs.

**Comment by james-stocks** [comment]
> If I always use a path reference - that is, if I tarball the inspec-aws resource pack, then make a wrapper profile with a local tarball reference PRIOR to sending to the customer - it works fine. You can repeatedly wrap and archive profiles without network access so long as they local path references.

I'm trying this with the following steps:
 * Create profile A
 * Archive profile A
 * Create profile B with a `path` dependency to archived A
 * `archive` profile B
 * Move the tar for profile B to some other directory and cd into it (so you only have the archived B. The source directories for A and B and the tar file for A are no longer immediately available).
 * Create profile C with a path dependency to the tar file for B
 * `archive` profile C

It still needs to resolve B's dependency on A and tries to find it at the specified `path`

```
/Users/jamesstocks/code/inspec/lib/fetchers/local.rb:104:in `read': No such file or directory @ rb_sysopen - /Users/jamesstocks/vendor-test/sub/my-resource-profile-1.0.0.tar.gz (Errno::ENOENT)
```

**Comment by frezbo** [comment]
@james-stocks yeh this is a strange issue, it still tries to load the profiles even though the *archived* tar's `vendor` folder has all dependencies present. What I have seen is that if the lockfile has a `sha` or `ref` and even if a `vendor/{sha,ref}` folder exists Inspec exec still tries to fetch from the source mentioned in the inspec.yml/inspec.lock whereas it should have used the ones from the vendor directory. This just defeats the purpose of having the vendored profiles along with the archives. It should only try to fetch the remotes only if local vendor is missing the dependent profiles. FYI: @clintoncwolfe

**Comment by clintoncwolfe** [comment]
Does this statement accurately distill the desired behavior?

`Given an archived profile with deeply nested dependencies with non-local fetchers, inspec should recursively descend into the dependencies, and use the copy of any dependencies already present in the archive, rather than attempting to re-acquire them.`

**Comment by frezbo** [comment]
@clintoncwolfe yes the statement is correct. 👍

**Comment by clintoncwolfe** [comment]
Still having trouble with the repro on this. Based on the above statement, having "an archived profile that depends via git on a profile that then depends on another profile via git" should be enough to trigger faulty behavior with networking disabled. But in fact, `inspec exec git2git-0.1.0.tar.gz` works for me with wifi disabled; debugging shows cache copying activity but no git fetch attempts.

My top-level profile inspec.yml looks like this - there are no controls or libraries - 
```
name: git2git
license: Apache-2.0
summary: An InSpec Compliance Profile
version: 0.1.0
supports:
  platform: os
depends:
  - name: inspec-test-dep-profile
    git: git@github.com:clintoncwolfe/inspec-test-dep-profile.git
```

inspec-test-dep-profile is very light as well, and simply depends via git on devsec/ssh-baseline.

It is conceivable that the problem is isolated to certain fetchers - perhaps the `url` fetcher is faulty, while the git fetcher is not. I will also test the `compliance` fetcher.

**Comment by frezbo** [comment]
@clintoncwolfe I'm using the url fetcher, not sure if the git fetcher is affected. Can you also make sure the inspec cache (`~/.inspec/`) is removed after the profile has been archived. 

ok, I see a difference in the workflow. `inspec exec <profile tar.gz` whereas I use inspec exec on a profile has a dependency on a profile with a dependency on another profile.

**Comment by clintoncwolfe** [comment]
Nod, I'm being careful to purge the cache. 

~~It "shouldn't" matter if you're running a bare profile (which has deep, remote dependencies) or if you're running it from an archive - at that point you're reading it locally from the local file reader (either directories or tar-based), which seem to be well-behaved. Point being that "first order" step seems to work fine - I'll be sure to keep testing either way.~~

Waitaminit, this should *only* work with an archive airgapped environment - a bare profile wouldn't have the deps. An archive is a profile with its dependencies pre-bundled; how would one expect it to work otherwise? How else should `inspec` find its dependencies?

**Comment by clintoncwolfe** [comment]
Looks like the `url` fetcher works OK, too:

```
name: url2url
license: Apache-2.0
summary: A profile that accesses a profile by URL, which accesses a profile by URL
version: 0.1.0
supports:
  platform: os
depends:
  - name: inspec-test-dep-profile-url
    url: https://github.com/clintoncwolfe/inspec-test-dep-profile-url
```

**Comment by clintoncwolfe** [comment]
I've now tested the `compliance` fetcher (which fetches things from Automate) and tried various combinations of fetchers - [this](https://github.com/inspec/inspec/issues/4519#issuecomment-546463236) all seems to work, in the sense of being able to run archives in an offline environment.

**Comment by frezbo** [comment]
@clintoncwolfe let me set up a scenario and see if the issue is indeed resolved. I will revert back in a day or two.

**Comment by frezbo** [comment]
@clintoncwolfe I'm so sorry for making a lot of confusion.

My test case:

*library profile inspec.yml*
```
name: library
title: InSpec Profile
maintainer: The Authors
copyright: The Authors
copyright_email: you@example.com
license: Apache-2.0
summary: An InSpec Compliance Profile
version: 0.1.0
supports:
  platform: os
```

*library profile inspec.lock*
```
---
lockfile_version: 1
depends: []
```

*dependent profile inspec.yml*
```
name: dependent
title: InSpec Profile
maintainer: The Authors
copyright: The Authors
copyright_email: you@example.com
license: Apache-2.0
summary: An InSpec Compliance Profile
version: 0.1.0
supports:
  platform: os
depends:
  - name: library
    url: http://localhost:8000/library-0.1.0.tar.gz
    username: admin
    password: password
```

*dependent profile inspec.lock*
```
---
lockfile_version: 1
depends:
- name: library
  resolved_source:
    url: http://localhost:8000/library-0.1.0.tar.gz
    sha256: cb6a950746ae15e77d50a8fd33150ca9a1f977714667880c6c2eb060346854bc
  version_constraints: []
```

If I remove the http auth from the inspec.yml and regenerate the lock file and have the library profile on an HTTP server with no-auth `inspec exec` without `~/.inspec/cache` and `dependent/vendor` folders works fine,

adding auth breaks.

 I was relating this to an old issue I faced when the dependent profiles require authentication, inspec exec does not pass in auth related info. I had an old issue created for this: #3510

When inspec does an exec with having a dependent profile requiring http auth, since the lockfile does not contain auth info it does not pass that in.

**Comment by kekaichinose** [comment]
@frezbo the OP's ask here was resolved, but I think you're coming up with an interesting feature request that would best be put into a new issue. Since you already have that in #3510, we can track that there. Thanks!

**Comment by james-stocks** [comment]
Hi @kekaichinose -
I don't believe this is resolved. The reproduction steps in [this comment](https://github.com/inspec/inspec/issues/4519#issuecomment-541589057) are still current.

**Comment by clintoncwolfe** [comment]
After discussion with @james-stocks, it looks like the most general (though internal) description of the problem is this: whenever a fetcher is used to fetch a profile, if the fetcher fails, and an archive is available, use the copy from the archive. This pattern should be applied recursively each time a fetch occurs.

Future work might go to skipping the initial fetch attempt entirely (#3297).

With this understanding in place, I'm going to close this issue in favor of #4726 (make fetchers fail cleanly) and #4727 (make fetchers fallback to using the archive after a failure).

Thank you for all the discussion, everyone!
