### ISSUE TITLE
Inspec.io Docs Design Update

### ISSUE THREAD

**Issue by kekaichinose** [inspec/inspec#4527]
### 🎛 Description

This is an epic to track the efforts around improving the inspec.io docs design to match with the larger chef.io docs site.

Issues to Address:
* Similar to automate docs, sometimes exposed (and closed) menus go away visually but remain in the code, preventing interaction with links on the page (i.e., some invisible box covering links).
* Resource list is difficult to consume, needs content design
* Needs visual indicator of anchor links, and ability to interact with them
* Fix to headings so when using anchor links, the heading is visible instead of hidden behind the fixed nav
* Currently, code related names are purple and links are purple, links need a distinct style, so the code related names need their own (non-purple) style
* Consider a page table of contents (really more a question for the docs team than the design team)
* There is a heading style that's all caps, that needs to be reconsidered
* Bugs related to syntax highlighting, some keywords are not highlighted (may be related to spacing around said keywords) (e.g., check out resources -> iptables, under syntax for an example)
* Headings needs a standard design pattern of margins, currently `<br>`'s are used in the markdown to create white space
* May have some issues with search functionality, needs more investigation
* *Inspec and Friends* heading needs to be reconsidered, content may no longer be relevant (again, probably more a question for the docs team)

**Comment by phiggins** [comment]
EDIT: Turns out I'm describing #4590. Nothing to see here...

As reported in the #docs-support slack channel:

I just ran into a weird behavior on the inspec docs page, repro'able in firefox and chrome on my machine:
* Visit an inspec docs page, eg https://www.inspec.io/docs/reference/resources/groups/
* Type something in the search box (not necessary, but helpful for demo purposes)
* Click somewhere else on the page
* The search box and the search button are now unable to be interacted with via the mouse
* Hit tab
* Now the search box and search button are able to be interacted with
