### ISSUE TITLE
Windows 2008 Still not detected correctly

### ISSUE THREAD

**Issue by username-is-already-taken2** [inspec/inspec#453]
Hi there

Sorry to reopen this issue but I just wanted to confirm the status, for windows 2008 support do I need to install the windows management framework 3+ on my boxes?
My local machine detects fine
`PS C:\WINDOWS\system32> inspec version`
`0.9.11`
`PS C:\WINDOWS\system32> inspec detect`
`{"name":null,"family":"windows","release":"10","arch":null}`

but when I winrm to 2008 r2 box I get unknown

`PS C:\WINDOWS\system32> inspec shell -t winrm://***.***.com --user *** --password *** --ssl --self-signed`
`Welcome to the interactive InSpec Shell`
`To find out how to use it, type: help`
`inspec> help`
`Available commands:`
``[resource]` - run resource on target machine`
``help resources` - show all available resources that can be used as commands`
``help [resource]` - information about a specific resource`
``exit` - exit the InSpec shell`
`You can use resources in this environment to test the target machine. For example:`
`command('uname -a').stdout`
`file('/proc/cpuinfo').content => "value",`

`You are currently running on:`
`OS family:  unknown`
`OS release: unknown`
`inspec>`

My server is Windows 2008 R2
`C:\Windows\system32>ver`
`Microsoft Windows [Version 6.1.7601]`

**Comment by chris-rock** [comment]
@username-is-already-taken2 Your are right, this is not yet fix unless you updated the Windows Management Framework on Windows 2008. This is addressed here: https://github.com/chef/train/pull/70

Even if the detection has been fixed and do not require powershell, the most windows resources will still require an up-to-date WMF, since we rely on `Convert-ToJson` a lot. `command`, `file` and `script` will still work though.

**Comment by chris-rock** [comment]
brings up again #346

**Comment by chris-rock** [comment]
This is solved with https://github.com/chef/train/pull/70 now
