### ISSUE TITLE
Potential bug in filter code or users resource

### ISSUE THREAD

**Issue by djhaynes** [inspec/inspec#4629]
I just tried to run the following code from [1] with InSpec 4.18 and it produces an "invalid date" error message. 

It does not appear to be an issue with InSpec v3.9.3. I haven't tested any versions in between.
```
allowed_users = %w(user1 user2 user3)
users.where { uid > 1000 && uid < 65534 }.usernames.sort.each do |u|
  describe user(u) do
    if allowed_users.include?(u)
      it { should exist }
    else
      it { should_not exist }
    end
  end
end
```
[1] https://www.inspec.io/docs/reference/resources/users/

**Comment by zenspider** [comment]
This bug is really about an "invalid date" error and I want to focus on that... *but first* I have to say that this test as a whole is NOT a good way to write this sort of thing. I realize that it is from our doco. I've spotted several other examples that are decided Not Good Testing™.

For example, in the code above, any user from `allowed_users` that does NOT exist does NOT trip a failure. And any user that does exist has already been vetted by the initial query, so the `user(u)` and `should exist` parts are churn for no reason.

That said, I'd like to dig in to find the source of the `invalid date` error.
