### ISSUE TITLE
We don't have unit tests for Rule/Control

### ISSUE THREAD

**Issue by zenspider** [inspec/inspec#4647]
While working on #4587 and #4524, I found that we do not have an entry point to put tests for rule-level constructs. dsl/control_test.rb is just about metadata and doesn't have anything to do with our runtime or integration with rspec.

**Comment by clintoncwolfe** [comment]
I suggest we broaden this issue a bit to be a facility for unit testing test fixture profiles in general - like here - https://github.com/inspec/inspec/pull/4648/files#diff-96f66fac5b1b5f40bb9fc4fb8f2a2a61R26 Imagine that, but with the profile code read from disk in the test/unit/mock/profiles area.

This would allow us to write test profiles on disk (for easy generation, editing and diagnosis) execute them directly if needed, but then execute them in-process as unit tests for speed (instead of relying on starting slow sub-processes).

**Comment by clintoncwolfe** [comment]
Along those lines, if this facility were available:
 [ ] #4666 adds a functional test that is easily converted into a unit test
