### ISSUE TITLE
Unify deprecation handling in resources

### ISSUE THREAD

**Issue by arlimus** [inspec/inspec#465]
Get here:

``` ruby
if condition
  deprecated 'Please use xyz instead of abc', '1.0'
end
```

Which leads to

``` bash
[DEPRECATION] Please use xyz instead of abc. This method will be remove in version 1.0.
```

Global access for deprecation call
Ability to enable/disable deprecations

**Comment by clintoncwolfe** [comment]
My personal desired approach would allow this sort of behavior.
* A deprecation facility that is available throughout InSpec, core code or core resources.  It is less likely to be useful to resource pack authors, but it could be.

Using it, you might say:

```
class Inspec::SomeThingus
  def some_crufty_function(...)
    Inspec.deprecate :stone_tools, 'Please use bronze-era tools now'
  end
end

class Inspec::AnotherThingus
  def another_crufty_function(...)
    Inspec.deprecate :dinosaurs, 'Consider migrating to mammals'
  end
end
```

There are other ways we could call Inspec.deprecate, of course.

Next, along with the calling mechanism, we have a config file, perhaps `inspec/etc/deprecations.json` (same area we keep the plugin filter config file).  

```
{
  "file_version": "1.0",
  "deprecation_groups": {
    "dinosaurs": {
      "action": "warn",
      "suffix": "This feature will be removed in InSpec 4.0"
    },
    "stone_tools": {
      "action": "fail_control",
      "suffix": "This feature was removed in InSpec 3.0"
    },
    "mammoths": {
      "action": "abort_run",
      "suffix": "This feature was removed in InSpec 2.0",
      "exit_status": "5"
    },
    "monotremes": {
      "action": "ignore",
    }
  }
}
```

We could come up with a limited vocabulary of actions, and when `Inspec.deprecate` is called, look up the action for the corresponding group, and then do what it says (possibly exiting!).  Because the actions may entail more than simply output, this is not part of logging - it's more similar to a feature flag system (or an "unfeature flag system").
