### ISSUE TITLE
Alert Mode

### ISSUE THREAD

**Issue by miah** [inspec/inspec#4786]
I would like to write tests using InSpec that when run are able to work with a monitoring system like Sensu/Nagios or Prometheus/Alertmanager.

Imagine any series of tests as a profile. If there is _any_ failure we send an alert. 

Sensu/Nagios both work by executing the program, capturing STDOUT/STDERR, and checking the return value. This would almost work with our existing 'exec' today, but our return values don't line up in a useful way.

https://docs.sensu.io/sensu-go/5.15/reference/checks/#check-commands

I don't know Prometheus at all, but I believe we would [send alerts through the api](https://prometheus.io/docs/alerting/clients/). Also, you would need to tie this up to a scheduler. (Clearly I need to experiment with schedules in k8s, that is probably the right way.)

**Comment by Swetad90** [comment]
@miah Were you able to tie inspec with any alerting solutions? We also have similar usecase of alerting when any test fails

**Comment by clintoncwolfe** [comment]
Two things come to mind:

For sensu-style, exit-code-based scripting, the `--no-distinct-exit` option will narrow things down to a simple 0 for all pass, 1 for at least one failure.

If your monitoring system has a Ruby API client, you might be better off writing a reporter plugin, a new feature in 4.18.118. That allows you to examine the full details of the run and do anything you like, with any gem you want installed and loaded for you.  See https://github.com/inspec/inspec/blob/master/docs/dev/plugins.md#implementing-reporter-plugins . Instead of being concerned about rendering output, you'd mainly want to be concerned about talking to your monitoring API.
