### ISSUE TITLE
Update the OS Resource to match the naming conventions of other Chef products

### ISSUE THREAD

**Issue by johnmccrae** [inspec/inspec#4893]
## Detailed Description
The OS resource for Inspec uses the label of 'darwin' to describe OSX. This is not in keeping with the nomenclature used by the other chef products. Can you please 1) Change the name to 'mac_os_x' to match everyone else and 2) Update hte docs here - https://www.inspec.io/docs/reference/resources/os/ to actually show OSX support?

## Context
It creates a LOT of confusion and contributes to the idea that chef is hard to use when there is no consistency around naming things. 

## Possible Implementation
Not sure how to do this other than change the labeling to reflect 'mac_os_x'

Aha! Link: https://chef.aha.io/features/SH-2485

**Comment by james-stocks** [comment]
This is a valid annoyance; but harmonizing the platform names needs to happen across InSpec/train/Chef/Ohai and can't be fixed in this repo.
@tas50 is the gap between ohai and train platforms being actively discussed anywhere?
I'd like to close this issue but not without pointing to where to keep reading.

**Comment by btm** [comment]
@james-stocks I think the last/only place this was discussed in writing was https://chefio.atlassian.net/browse/SUSTAIN-987.

**Comment by james-stocks** [comment]
@johnmccrae I'm going to close this as it's not an InSpec issue, it can be discussed further in Slack. The link given by @btm isn't recent but it does summarise the issue.
