### ISSUE TITLE
Profile git dependency failed for cis-rhel7-level2-server-2.2.0-25.tar.gz - error running 'git ls-remote 

### ISSUE THREAD

**Issue by Mukund-UBS** [inspec/inspec#4909]
Hi,

I have created my Wrapper profile and in inspec.yml i have given my dependencies like below - 

depends:
- name: cis-rhel7-level2-server
  git:  Address of cis-rhel7-level2-server-2.2.0-25.tar.gz file present in my github. 

While running the inspec vendor . i am getting error of git dependency failed.  Please let me know if i am not giving dependency in correct manner. 

PS:- This issue is only while using the git else if i am keeping the cis-rhel7-level2-server-2.2.0-25.tar.gz profile locally and then running this wrapper profile there is no issue. 

Regards,
Mukund

Aha! Link: https://chef.aha.io/features/SH-2511

**Comment by lmayorga1980** [comment]
:+1:

**Comment by clintoncwolfe** [comment]
Please provide the entire error message.

**Comment by ObiH15** [comment]
I am having the same issue. Please see #4922 

**ERROR:**
Failed to complete #verify action: [Profile git dependency failed for http://authToken@path-to-profile.git - error running 'git ls-remote "http://authToken@path-to-profile.git" "master*"': fatal: http://authToken@path-to-profile.git/info/refs not valid: is this a git repository?`

**Comment by james-stocks** [comment]
If you're referencing a .tar.gz then you might need to change the `git:` reference to a `url:`

**Comment by james-stocks** [comment]
Hello Mukund -

The issue you describe looks like you are referencing the URL for a tar.gz file but telling InSpec it is a git repo - and you should use a `url` dependency instead of a `git` one.

If this is still an issue, can you please re-open this issue with the full error output you are seeing? I'm happy to take a look via email if you'd like us to privately review your setup.
