### ISSUE TITLE
[SPIKE] Inputs do not work in describe.one blocks

### ISSUE THREAD

**Issue by burnsjared0415** [inspec/inspec#4962]
Running code that allows for inputs to be added to the inspec.yml and called by a control for easy changes. Put together code to do a describe one block and have found that for some reason describe one is having issues getting the input value. here is the code:
```
describe.one do
    describe security_policy do
      its('LockoutDuration') { should cmp >= input('time') }
    end
    describe security_policy do
      its('LockoutDuration') { should cmp 0 }
    end
  end
```
# Describe the problem

If you run the above control it will fail out with unable to get input value, i have tested this through cli with inputs attached.
## Possible Solution

Aha! Link: https://chef.aha.io/features/SH-462

**Comment by aaronlippold** [comment]
The following block fails because the `inputs` are not correctly dereferenced.

If we put the assignment of the input outside the `describe.one` block as local instance variables it works fine.

I think we just need to shift the eval context so that input is done I would guess.

This is broken:

```ruby
describe.one do
  describe security_policy do
    its('LockoutDuration') { should cmp >= input('time') }
  end
  describe security_policy do
    its('LockoutDuration') { should cmp 0 }
  end
end
```
This works:

```ruby
my_time = input('time')

describe.one do
  describe security_policy do
    its('LockoutDuration') { should cmp >= my_time }
  end
  describe security_policy do
    its('LockoutDuration') { should cmp 0 }
  end
end
```

**Comment by aaronlippold** [comment]
Is this on the backlog?

**Comment by Vasu1105** [comment]
I have spent sometime to debug and work on this issue. Currently the challenge which I am facing to access the profile_id in this class here https://github.com/inspec/inspec/blob/master/lib/inspec/rspec_extensions.rb#L89, which currently comes as nil due to which it fails.  I have tried to hack something in here https://github.com/inspec/inspec/blob/master/lib/inspec/describe_base.rb#L22 and https://github.com/inspec/inspec/blob/master/lib/inspec/describe_base.rb#L38 by adding with_dsl method as it is used in rule.rb here https://github.com/inspec/inspec/blob/master/lib/inspec/rule.rb#L400 but that did not made any difference. 

Following is the difference which I found between metadata that we are fetching here https://github.com/inspec/inspec/blob/master/lib/inspec/rspec_extensions.rb#L89

metadata when input is used within describe under describe.one
```
{:block=>#<Proc:0x000000000649c9a0 my-test-profiles/test-input-profile/controls/example.rb:3>,
 :description_args=>[20],
 :description=>"20",
 :full_description=>"20",
 :described_class=>20,
 :file_path=>"my-test-profiles/test-input-profile/controls/example.rb",
 :line_number=>3,
 :location=>"my-test-profiles/test-input-profile/controls/example.rb:3",
 :absolute_file_path=>"/home/msys/workspace/inspec/my-test-profiles/test-input-profile/controls/example.rb",
 :rerun_file_path=>"my-test-profiles/test-input-profile/controls/example.rb",
 :scoped_id=>"1",
 "file_path"=>"my-test-profiles/test-input-profile/controls/example.rb",
 "line_number"=>3}
```
metadata when input used only describe block
```
 {:block=>#<Proc:0x00000000094d8bf0 /home/msys/workspace/inspec/lib/inspec/rule.rb:402>,
 :description_args=>[20],
 :description=>"20",
 :full_description=>"20",
 :described_class=>20,
 :file_path=>"./lib/inspec/rule.rb",
 :line_number=>402,
 :location=>"./lib/inspec/rule.rb:402",
 :absolute_file_path=>"/home/msys/workspace/inspec/lib/inspec/rule.rb",
 :rerun_file_path=>"./lib/inspec/rule.rb",
 :scoped_id=>"1",
 :backend=>Inspec::Backend::Class @transport=Train::Transports::Local::Connection,
 "file_path"=>"/home/msys/workspace/inspec/lib/inspec/rule.rb",
 "line_number"=>402,
 :id=>"(generated from example.rb:1 597d220be5bd128a5ac3c2ffb45f30c9)",
 :profile_id=>"test-input-profile",
 :impact=>nil,
 :title=>nil,
 :descriptions=>{},
 :code=>nil,
 :source_location=>{:ref=>"/home/msys/workspace/inspec/lib/inspec/control_eval_context.rb", :line=>74},
 :waiver_data=>nil}

```
I have dig into the DSL code but currently wasn't able to get any fix on this. May be it will be good for now if user uses something like below to get this work.

```
describe.one do
  val = input('my_value')
  describe 20 do
    it { should cmp val }
  end
end```

**Comment by Vasu1105** [comment]
Closing this as we have a workaround on this as suggested above.

**Comment by aaronlippold** [comment]
Hi, the workaround is generally the same as the one I posted above. Can we keep this open just so we can keep it on the backlog and Clinton can look at it a bit later.￼
