### ISSUE TITLE
Remove Ruby 2.4 Support

### ISSUE THREAD

**Issue by clintoncwolfe** [inspec/inspec#5067]
# Describe the problem
Ruby 2.4 was EOL'd on March 31, 2020. 
https://www.ruby-lang.org/en/news/2020/04/05/support-of-ruby-2-4-has-ended/

Remove 2.4 from testing and packaging.

Aha! Link: https://chef.aha.io/features/SH-2148

**Comment by Schwad** [comment]
+1 this

Another reason this would be great to do is we've had to pin ActiveSupport < 6.0 because newer versions no longer work with Ruby 2.4. https://github.com/inspec/train/pull/589/files

Maybe this could be a candidate for 5.0? :)

**Comment by Schwad** [comment]
@inspec/foundation-team-reviewers 

I am moving this PR to 'in-progress'. I am considering this because today we have another bug that will require version pinning to support Ruby 2.4: https://github.com/inspec/inspec/pull/5302

Please let me know of any serious thoughts or concerns about dropping Ruby 2.4 support in the next InSpec minor version.

**Comment by aaronlippold** [comment]
What drives our requirements for ruby support levels? Do we have a supported version matrix that we have agreed to as a community?

**Comment by lamont-granquist** [comment]
Yeah the version pinning is worrisome.  I just manually checked the parallel gem against the chef and chef-workstation Gemfile.locks and don't see any conflicts, but you can very easily wind up producing pins which are unshippable when mixed with those other products.  You may also wind up with gems which are pinned to work on ruby 2.4 which don't actually work on ruby-latest.  Those gems may provide only a floor constraint on the ruby version, but fail on edge conditions on e.g. ruby 2.7 which they were never tested against, which then cause problems as users install other gems which depend on them.  Other gems may also start to insert semver pins on e.g. activesupport ~> 6.0 (even though they may work fine on 5.x just because the authors don't want to test that) and that may cause conflicts for users installing gems.  This is the problem with having an open system where users can install any arbitrary ruby gem which needs to be mixed with your product and you have to support the whole current universe.

Sorta TL;DR is that instead of pinning gems you should really be dropping support for ruby versions more aggressively.  It favors the concerns of users that are doing the wrong thing (installing gems manually on old versions of ruby) over users that are doing the right thing (using our current omnibus builds).

**Comment by Schwad** [comment]
Thanks for the thoughts Lamont

> instead of pinning gems you should really be dropping support for ruby versions more aggressively.

That's where I'm sitting at the moment

**Comment by aaronlippold** [comment]
I agree - what is the sunset date on 2.4 is it past? From the manager's point of view, I would just ask if major platforms - like rhel7 or rhel6 - ubuntu 14x, etc. would be affected as we publish supported packages for those - aka are their downstream effects to this action?

**Comment by aaronlippold** [comment]
If not then I would say - drop it and move ahead
