### ISSUE TITLE
Question: Where is the serverspec migration guide?

### ISSUE THREAD

**Issue by squaresurf** [inspec/inspec#514]
There is mention of a migration guide from serverspec at the end of  the [inspec_and_friends.rst](https://github.com/chef/inspec/blob/master/docs/inspec_and_friends.rst) document. Where is that guide?

Also, is there a freenode irc channel for inspec or some other community chat tool?

**Comment by chris-rock** [comment]
Thanks @squaresurf

Unfortunately we have not finalized the Serverspec migration guide. In general it includes the following steps:
- remove `spec_helper.rb`
- if used in test-kitchen, rename `test/integration/%suite%/serverspec` to `test/integration/%suite%/inspec`
- ensure the `serverspec` gem is not loaded, since inspec and serverspec add types to the RSpec runtime
- most test should work out of the box with InSpec, because InSpec uses the same syntax as Serverspec
- some Serverspec resources have not been implemented yet

Implemented Serverspec resources in InSpec:
- [x] bond
- [x] bridge
- [ ] cgroup
- [x] command
- [ ] ~~cron~~, we implemented it differently in crontab
- [ ] default_gateway
- [ ] docker_container
- [ ] docker_image
- [x] file
- [x] group
- [x] host
- [x] iis_app_pool
- [x] iis_website
- [x] interface
- [ ] ip6tables
- [ ] ipfilter
- [ ] ipnat
- [x] iptables
- [x] kernel_module
- [x] linux_audit_system
- [x] linux_kernel_parameter
- [ ] lxc
- [ ] mail_alias
- [x] mysql_config
- [x] package
- [ ] php_config
- [x] port
- [x] ppa
- [x] process
- [ ] routing_table
- [ ] selinux
- [ ] selinux_module
- [x] service
- [x] user
- [ ] x509_certificate
- [ ] x509_private_key
- [x] windows_feature
- [x] windows_registry_key
- [x] yumrepo
- [ ] zfs

On top, InSpec ships with additional resources eg. `ssh_config` (linux), `security_policy` (windows). Have a look at https://github.com/chef/inspec/tree/master/lib/resources

Please use the default https://www.chef.io/support/ IRC channel.

**Comment by squaresurf** [comment]
Awesome! Thank you @chris-rock. Is there a public place that list is posted? I'd love to start using inspec and implement the missing resources as if I have a need.

**Comment by chris-rock** [comment]
You could just open a PR to add this to our docs. PRs are always welcome. I just compiled it for you.It may make sense to start the Serverspec migration guide in our docs. Just add everything you encounter and that I have not covered. This would also a great help for our community.

**Comment by squaresurf** [comment]
Awesome. I'll look into it.

**Comment by nvtkaszpir** [comment]
I find lack of cron not yet migrated as disturbing :)

**Comment by chris-rock** [comment]
@nvtkaszpir PRs are welcome to add this feature

**Comment by chris-rock** [comment]
@nvtkaszpir We have a `crontab` resource now https://github.com/chef/inspec/pull/1482

**Comment by chris-rock** [comment]
The x509 resources are tracked in https://github.com/chef/inspec/issues/514
