### ISSUE TITLE
Better Output/Error for Profile OS Families

### ISSUE THREAD

**Issue by supertylerc** [inspec/inspec#515]
Recently, I created a profile and gave it a supported os-family.  I tried to test it against something that wasn't being detected correctly.  I spent a good bit of time chasing my own tail, then decided to spin up an Ubuntu VM and test.  I was mildly annoyed to see that it worked with Ubuntu, with led to more tail-chasing.  Finally, I changed the supported OS to Windows and tried to run a profile against Ubuntu.  There's nothing that says the OS is unsupported for that profile--it just says 0 examples.

Here's an example:

```
$ inspec exec . -t ssh://vagrant@127.0.0.1 -p 2201 --key-files=/Users/tylerchristiansen/Drop
box/vagrant/ubuntu/.vagrant/machines/default/virtualbox/private_key


Finished in 0.00027 seconds (files took 1.04 seconds to load)
0 examples, 0 failures
```

But using check, it says there's 1 control to run:

```
$ inspec check .
Summary
-------
Location: .
Profile: test-profile
Controls: 1
Timestamp: 2016-03-02T11:07:08-08:00
Valid: true

Errors
------

Warnings
--------
```

My expectation would be that InSpec would yell at me and tell me that I'm trying to run against an unsupported target platform, but that wasn't the case.  I think there should be _some_ sort of note that there are controls/tests to run, but none were run due to unsupported platform.

**Comment by chris-rock** [comment]
@supertylerc Thanks for sharing your feedback. InSpec `check` is right to highlight, that one control is part of the profile, because it only verifies the profile for sanity.

InSpec `exec` should really throw an error an say that this could not be executed. There are two ways to solve it:
- throw an error message and exit code (may not be a good solution, if you run 10 profiles)
- skip all controls and highlight that the operating system is not supported. In addition a warning should be written to the CLI

Would that solve your problem? 

Also related to https://github.com/chef/inspec/issues/354

**Comment by supertylerc** [comment]
@chris-rock, I think that this would work.

**Comment by jquick** [comment]
This has been resolved with the new platform supports system which shows proper errors.
