### ISSUE TITLE
executing profile from remote repository expects default branch named 'master'

### ISSUE THREAD

**Issue by mjmenger** [inspec/inspec#5233]
# Describe the problem

when executing an inspec profile from a remote repository with a default branch not named *master* the following error is returned.
```
inspec exec https://github.com/org/profile.git

Profile git dependency failed - unable to resolve master to a specific git commit for https://github.com/org/profile.git
```
The expected behavior is that the profile should execute independent of the name of the default branch (e.g. master, primary, main, production) without having to designate the name of the branch.

**Comment by Schwad** [comment]
Hey @mjmenger thanks for filing this issue. That is correct I believe it is expected behavior that whatever the `default` branch is if we exec directly against github we should be using that one. 

For anyone looking to pick this up in a PR - it would appear that these requisite lines are a good place to start for untangling this issue:

https://github.com/inspec/inspec/blob/d00706b9a6c01d4a345d70f082d612e06b5c60db/lib/inspec/fetcher/git.rb#L121-L131

**Comment by deric4** [comment]
Would implementing this using the  output of `git remote show <repo url>`  and parsing the `HEAD branch:` line make sense?

```shell-session
# random repo with default branch set to 'main'
$ git remote show https://github.com/github/docs
* remote https://github.com/github/docs
  Fetch URL: https://github.com/github/docs
  Push  URL: https://github.com/github/docs
  HEAD branch: main
  ...

# repo with default still using 'master'
$ git remote show git@github.com:inspec/inspec.git
* remote git@github.com:inspec/inspec.git
  Fetch URL: git@github.com:inspec/inspec.git
  Push  URL: git@github.com:inspec/inspec.git
  HEAD branch: master
  ...
```
