### ISSUE TITLE
Cannot skip_control for a wrapper when there are 2 levels of child profiles 

### ISSUE THREAD

**Issue by anthonygrees** [inspec/inspec#5300]
## Overview
A customer based in NZ is trying to `skip_control` in a Wrapper profile that includes a Child profile that is a wrapper and that includes a Child profile.  
  
```bash
Wrapper Profile
 |_ includes Child Profile
       |_ includes Child2 Profile
```
  
# Describe the problem
The Wrapper Profile includes `child`
```ruby
include_controls 'child' do
  skip_control 'Child2 - Small Rock Show'
end
```
  
The Child Profile includes `child2`.
  
The `skip_control` in the Wrapper does not skip Child 2 from running

## Example Code
Here is an example to show the issue described above - https://github.com/rohan-molloy/inspec_wrapper_with_input
  
## Chef Support Ticket
No Chef support ticket has been raised as yet.

**Comment by james-stocks** [comment]
Just to note - we should ignore the README in https://github.com/rohan-molloy/inspec_wrapper_with_input because it describes a different scenario (single level inheritance). The actual profiles in that repo do use nested inheritance like the issue description here.

I understand what the user wants to do here. The output you get from InSpec hints what is going on:

```
Profile: InSpec Profile (wrapper)
Version: 0.1.0
Target:  local://

     No tests executed.

Profile: InSpec Profile (child)
Version: 0.1.0
Target:  local://

  ×  Child 1 - Big Rock Show: 2 (3 failed)
     ×  2 is expected to cmp == 11
     
     expected: 11
          got: 2
     
     (compared using `cmp` matcher)

     ×  200 is expected to cmp == 110
     
     expected: 110
          got: 200
     
     (compared using `cmp` matcher)

     ×  test2 is expected to cmp == "anthony"
     
     expected: anthony
          got: test2
     
     (compared using `cmp` matcher)



Profile: InSpec Profile (child2)
Version: 0.1.0
Target:  local://

  ×  Child2 - Small Rock Show: 6 (3 failed)
     ×  6 is expected to cmp == 11
     
     expected: 11
          got: 6
     
     (compared using `cmp` matcher)

     ×  600 is expected to cmp == 110
     
     expected: 110
          got: 600
     
     (compared using `cmp` matcher)

     ×  test is expected to cmp == "rees"
     
     expected: rees
          got: test
     
     (compared using `cmp` matcher)



Profile Summary: 0 successful controls, 2 control failures, 0 controls skipped
Test Summary: 0 successful, 6 failures, 0 skipped
```

The `Child2 - Small Rock Show` control is considered to be part of the `child2` profile. The `wrapper` profile needs to skip it by referencing the `child2` profile

```
include_controls 'child2' do
  skip_control "Child2 - Small Rock Show"
end
```

It does feel like a bug that you can't exclude the control in the immediate `child` profile and we could fix this, but rather than being an outright fault it seems more like it's just how InSpec behaves.

**Comment by anthonygrees** [comment]
As always, thank you @james-stocks I will take this information back to the customer and see if they wish to raise a ticket

**Comment by anthonygrees** [comment]
Customer has raised a ticket - #26458
