### ISSUE TITLE
Undefined local variable or method error for "aws_eks_clusters" resource

### ISSUE THREAD

**Issue by Aniket281292** [inspec/inspec#5475]
Undefined local variable or method while trying to test "aws_eks_clusters" resource for Chef inspec

# Describe the problem

Getting an error while trying to test a specific aws resource. "aws_eks_clusters". trying to verify property of EKS clusters. 
Error:
**"undefined local variable or method `aws_eks_clusters' for #<Inspec::Rule:0x00007fb36.......> "**

**control 'Multiple Clusters' do
impact 1.0
title 'Check prop of mul EKS clusters'
desc 'Verify the prop of EKS Clusters'
describe aws_eks_clusters.where( failed: true ) do
    it { should_not exist }
end
end**

**Comment by clintoncwolfe** [comment]
Hi, in order to use the AWS resources, you must define an inspec profile with a dependency on the inspec-aws resource pack.  Do that by following the instructions in the [inspec-aws README](https://github.com/inspec/inspec-aws#use-the-resources).

@Nik08 This is a good one for the #5477 Common Errors page.

**Comment by Aniket281292** [comment]
Hi @clintoncwolfe , i already have this dependency added in my inspec.yml file as follows:
**depends:
  - name: inspec-aws
    url: https://github.com/inspec/inspec-aws/archive/master.tar.gz**

Also, i am able to test the resource aws_eks_cluster successfully with inspec tests, however i am facing this issue with resource aws_eks_cluster**s**

**Comment by clintoncwolfe** [comment]
@sathish-progress any ideas?

**Comment by sathish-progress** [comment]
Sorry, I missed this notification somehow!

_On my initial investigation, I was not able to reproduce this!!_

@Aniket281292 This is possibly because of the old dependency cache. Could you try updating the cache! and try again .. 
Follow below command to update cache. And please try running it from within the profile directory
```
inspec vendor --overwrite
```

**Comment by Aniket281292** [comment]
@sathish-progress i followed the steps and retried running the same command , i see the same error.
"undefined local variable or method `aws_eks_clusters' for #<Inspec::Rule:0x00007feb1b236fa0>"

**Comment by Aniket281292** [comment]
This issue was not encountered once inspec is upgraded to version 4.36.4 . I suppose the train-aws update that was included with the upgrade helped resolved the issue.
