### ISSUE TITLE
Add Fedora Linux support

### ISSUE THREAD

**Issue by lokeshk1987** [inspec/inspec#5612]
## Detailed Description

To provide Fedora linux support (current non eol releases) supporting x86_64, aarch64 architecture

## Context

CIS Benchmarks

**Comment by clintoncwolfe** [comment]
Hey, it would be a great help if you could please create more detailed issues. I'm not clear if you need a specific client package for Fedora? That seems unlikely, since we make RHEL packages already; are the RHEL packages known not to work on Fedora? You mention CIS Benchmakrs but don't specify which ones. Are you looking for increased resource overage to help cover a specific CIS Benchmark? Which Benchmark? Which resources are missing support? We'd like to help, but we need to know what to do. 

Thanks!

**Comment by clintoncwolfe** [comment]
The task here is to verify client support on Fedora, and if so, document it on the platform support pages.
