### ISSUE TITLE
git fetchers need to assume default branch is now named "main"

### ISSUE THREAD

**Issue by clintoncwolfe** [inspec/inspec#5635]
# Describe the problem

The `git` fetcher currently assumes the default branch is named "master", but on August 24th, most github repos had their default branch renamed to be "main".  This breaks running exec from the command line against git repos.

**Comment by Nik08** [comment]
@clintoncwolfe need clarity on some fronts.
I tried, 

1. `inspec exec https://github.com/inspec/inspec-test-profile-run-context-audit.git` - this picks up `main` as a default branch, so git fetcher seems to be working fine. Reason being we fetch the default branch from git and master is not hardcoded.
2. `inspec exec https://github.com/inspec/inspec-test-profile-run-context-audit` - this is transformed to `https://github.com/inspec/inspec-test-profile-run-context-audit/archive/master.tar.gz` by **Url fetcher**, since **master** is taken as default branch for transformation in Url fetcher logic.
So just trying to understand, should we be making change for the default branch in transformation logic inside URL fetcher? Or is there something else I am missing?

**Comment by Nik08** [comment]
An area of concern, if we change default **master** to **main** in Url fetcher's transformation logic, it could break those profiles which still have **master** as their default branch.

**Comment by aaronlippold** [comment]
Can't we just ping and find out which default is in use? wouldn't we use a turnary looking for a 404 on the assumed default - or perhaps is there a ways we can ask a repo what its default branch name is?

**Comment by Nik08** [comment]
@aaronlippold do check this out [https://github.com/inspec/inspec/pull/5638](https://github.com/inspec/inspec/pull/5638) for this.

**Comment by aaronlippold** [comment]
https://stackoverflow.com/questions/28666357/git-how-to-get-default-branch

**Comment by aaronlippold** [comment]
Would a helper function that just finds the default branch - reguardless of its name - more stable? What happens when someone makes the default branch 'dev' or 'testing' prior to a 1.x release?
