### ISSUE TITLE
Requirement template for Compliance profiles

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#564]
As discusses with @aaronlippold

We need a to find a way to define a requirement template e.g. DOD requires profiles where all controls have a cce, cci, nist, disa tag. This should be customizable.

**Comment by aaronlippold** [comment]
This could also be framed as a more general requirement that organizations may want to define content guides for their own compliance profiles - which may include a set of 'tags' or 'refs' that is useful in their business domain.

**Comment by clintoncwolfe** [comment]
This sounds like a desire for `inspec check` to be extensible - to allow you to author custom rules, and have them applied when you run the check.

refs #3549

**Comment by kekaichinose** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
