### ISSUE TITLE
create human-friendly permission output

### ISSUE THREAD

**Issue by srenatus** [inspec/inspec#566]
Besides what we gained with `cmp '0644'`, it'd be great to display a more human-friendly output when matches fail: e.g. `rw-r--r--` or `o:rw,g:r,w:r`.

/cc @ncerny @ricardolupo

**Comment by kekaichinose** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
