### ISSUE TITLE
[SPIKE] Add resources for Podman

### ISSUE THREAD

**Issue by lokeshk1987** [inspec/inspec#5682]
## Detailed Description

 Podman is a container engine, developed by Red Hat, that’s designed to be a drop-in Docker replacement. Podman is now the default container engine used by Red Hat Enterprise Linux (RHEL), and it allows you to develop, run, and manage OCI containers on Linux — all without a daemon! Podman also has the ability to share containers and pods with Kubernetes, as well as create systemd containers and pods.

Similar to docker resources mentioned Podman resources to be created:
- docker resource
- docker_container resource
- docker_image resource
- docker_plugin resource
- docker_service resource

 - podman resource : to test configuration data of the podman
 - podman_container resource : to test podman container
- podman_image resource : to verify podman image
- podman_plugin resource : to verify podman plugin
- podman_service resource : to test podman service

## Context

* To Inspec users who are considering Podman (as a Docker alternative)

**Comment by clintoncwolfe** [comment]
First, let's determine if we need a new train transport for this.

**Comment by Vasu1105** [comment]
Just linking the train issue created to add support for Podman in train https://github.com/inspec/train/issues/525

**Comment by Vasu1105** [comment]
For now, we won't be able to support Podman as there is no ruby library that we can use to fetch the Podman API's.
 
The workaround to use InSpec for Podman can be to use the systemd to activate the Podman socket.
and Enable programs using Docker to interact with the rootless Podman socket by setting DOCKER_HOST environment variable as mentioned in this doc https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/building_running_and_managing_containers/assembly_using-the-container-tools-api_using-the-container-tools-cli
 
So steps that worked for me and which I have tried is
 
1) I created the vagrant centos8 machine installed the Podman on it
2) installed the podman-remote package using `yum install podman-remore` command
3) Activated the podman socket using the `systemctl --user enable --now podman.socket` command
4) set the DOCKER_HOST environment variable using `export DOCKER_HOST=unix:///run/user/<uid>/podman//podman.sock`
5) Installed the InSpec on the VM where the Podman is running
and then I ran the below commands which are mentioned by @zipoah in his blog.
```
export CT=alpine:latest
CID=$(podman run --rm -d -i --init --entrypoint=/bin/cat ${CT})
inspec exec linux-baseline/ -t docker://${CID}
```
 
This all is explored on Centos-8 system.
 
I also tried installing the `podman-docker` package to check whether I will be able to use the docker resources.
I used all the same steps, only instead of installing the Podman I installed the Podman-docker so that I can emulate docker commands using Podman, as I felt that doing this I will able to use the docker resources like docker_image and docker_container but that did not work as it's unable to parse the data correctly.
 
So looking at overall things we currently feel people can use the workaround to work with InSpec. And wait for the podman ruby library supporting Podman API's
