### ISSUE TITLE
Compliance Server: ssh-key login

### ISSUE THREAD

**Issue by aaronlippold** [inspec/inspec#579]
There seems to be an issue with using ssh-keys to log into nodes. User/pass works fine but when I copy in the RSA pem private key for the login I always get connection failed.

**Comment by aaronlippold** [comment]
The error is sshkey: /// failed. Error code -1

**Comment by alexpop** [comment]
Thanks for the report Aaron. We've released a new version today that gives a full stack trace on connection failures:
https://www.chef.io/blog/2016/03/23/chef-compliance-0-16-19-release/

Please upgrade and let us know the full error message.

**Comment by srenatus** [comment]
Just a thought -- the key doesn't have a passphrase, does it? (Those aren't supported.)

**Comment by spuranam** [comment]
Make sure that your RSA pem is not protected by passphrase, i ran into the same issue with a passphrase protected SSH key.

**Comment by aaronlippold** [comment]
I upgraded to the new version today as well. 16.19 and did a cleanse and a reconfigure. I then uploaded the RSA key agian and it worked. I think before there were some newline issues and all that jazz. ( I wonder if there is a way to make sure other users done have that cut/paste issue ). Can't say if it was the version 14 server that was the issue or how I pasted my key. 

If someone can point me to the right log file I will see if I can dig out the errors I was getting.

**Comment by alexpop** [comment]
You can find the logs under `/var/log/chef-compliance/core/`
At some point, we will implement private key validation on upload.

**Comment by aaronlippold** [comment]
That would be a very good usability enhancement - especially given a mix of win, linux and OS X users.

**Comment by aaronlippold** [comment]
👍

**Comment by djhaynes** [comment]
Just curious, is there a timeline for when this feature might be supported?

**Comment by kekaichinose** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
