### ISSUE TITLE
Add note about multiple inspec gem versions installed on the compliance server

### ISSUE THREAD

**Issue by aaronlippold** [inspec/inspec#585]
@srenatus and @aaronlippold tracked down and issue in 16.19 with the cli and web upload of profiles to the compliance server that was connected to the fact that I had multiple versions of inspec installed into /opt/chef-compliance/embedded/bin. Removing the extra installs and leaving only the most current version of inspec resolved the issue and should perhaps be added as a note to the docs and perhaps as a part of the chef config recipes and maintenance scripts to ensure the issue does not cause problems for other users.

**Comment by chris-rock** [comment]
That is a good point @aaronlippold

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
