### ISSUE TITLE
add dhcpd_conf resource

### ISSUE THREAD

**Issue by kdshah1** [inspec/inspec#599]
There are few security rules related to DHCP server and client and it will be useful to have a dhcpd_conf resource.

**Comment by chris-rock** [comment]
@kdshah1 could you share an example that you would like to test. How you are testing it at the moment via CLI?

**Comment by kdshah1** [comment]
These are some of the security requirements that I am trying to test:
1. Do Not Use Dynamic DNS

To prevent the DHCP server from receiving DNS information from clients, edit /etc/dhcp/dhcpd.conf, and add or correct the following global option: ddns-update-style none; 

2.Deny Decline Messagesrule

Edit /etc/dhcp/dhcpd.conf and add or correct the following global option to prevent the DHCP server from responding the DHCPDECLINE messages, if possible: deny declines;

3.Deny BOOTP Queries

Unless your network needs to support older BOOTP clients, disable support for the bootp protocol by adding or correcting the global option: deny bootp;

**Comment by kekaichinose** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
