### ISSUE TITLE
processes: Clarify docs to indicate it searches using a Regexp

### ISSUE THREAD

**Issue by elijah** [inspec/inspec#601]
Working with the processes resource today - I had quite a bit of trouble getting it to properly match on my test VM's executables.

Backstory - building integration tests using inspec for a product that runs multiple java services in an all-in-one VM under certain configurations.

I wrote several resources that looked like this:

```
describe processes('/opt/vendor/product/share/jdk/bin/java -classpath /opt/product/something/conf/something/router') do
    its('list.length') { should eq 1 }
end
```

And some of them matched, and some of them did not.  

The processes resource seems to work just fine, always,  _if_ I don't need the arguments - my read of the code at line https://github.com/chef/inspec/blob/master/lib/resources/processes.rb#L55 is that it should dump into 'command: m[11]' everything from the name of the executable to the end of that line of 'ps aux' output.  

I still have one resource that doesn't match with a simple string passed in (and transformed into a regex to grep for...) - and I'm not sure why.  

Like several of my other processes, it's a java app -- so `/opt/somepath/java -someargs=something` - but it only successfully matched when I passed the processes() resource a significant chunk of the program's environment to match on -- two lines of a ~12 line cassandra runtime environment.

**Comment by chris-rock** [comment]
@elijah Thanks for reporting. I get the point that this is annoying and we should find a way to improve the behavior.

**Comment by kekaichinose** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
