### ISSUE TITLE
Service resource should have a fail code - "package not installed" - when failing 'should be_enabled' test fails

### ISSUE THREAD

**Issue by aaronlippold** [inspec/inspec#616]
When we test that a service should be enabled we should keep in mind the case where the service package is not installed and perhaps we should have that as part of the output - we could even suggest adding a test for the installation of the package.

**Comment by chris-rock** [comment]
@aaronlippold how would you build up the relationship between a service and a package. Lets say we detect a service is not installed, how should we determine the associated package? Do you have any ideas around that?

**Comment by aaronlippold** [comment]
@chris-rock well my first instinct said we could try to use the --whatprovides of yum/rpm and the equ in dpkg etc. but then I got to thinking that perhaps we could look and see if init.d, systemd, etc may have the ability to help answer that question. I would see if @fcaviggia has any input on this.

**Comment by aaronlippold** [comment]
@fcavigga is now with MITRE and working on the 'codename: compliance project'

**Comment by chris-rock** [comment]
I am really open to see a solution. Maybe we can ask yum to retrieve that information from packages. I think it really depends on how we are able to pull the required data. If we get that, I would love to see that in InSpec

**Comment by aaronlippold** [comment]
I would look at a combination of rpm,dpkg,init.d and systemd. I know that I have tried to start a service and it has told me to install a package before.

**Comment by aaronlippold** [comment]
RPM:https://docs.fedoraproject.org/ro/Fedora_Draft_Documentation/0.1/html/RPM_Guide/ch05s02s04.html
DPKG:http://www.cyberciti.biz/faq/equivalent-of-rpm-qf-command/
PACMAN: https://wiki.archlinux.org/index.php/Pkgfile#Command_not_found
Windows: :laughing:

**Comment by nvtkaszpir** [comment]
Notice, sometimes you really do not have packages which provide certain services. This is especially true if you want to run your own app as service, and you are actually not needing system package to run it.
Not to mention that in containers this will be a nightmare :)

**Comment by miah** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
