### ISSUE TITLE
The Chef Compliance server should direct users to use yum rather than rpm

### ISSUE THREAD

**Issue by aaronlippold** [inspec/inspec#624]
### Description

The upgrade instructions provide instructions on upgrade for the compliance server, however, it is not good form or standard convention to upgrade a package outside yum. ( old habits die hard Ja )

Does the instructions for ubuntu, packman, etc?
### Possible Solutions

Update the documentation to use the: 

```
yum upgrade < your package > 
```

**Comment by chris-rock** [comment]
The installation for packages via repositories is documented here: https://docs.chef.io/packages.html I agree that we need to make this more prominent in our install and upgrade instructions.

**Comment by kekaichinose** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
