### ISSUE TITLE
Undocumented Dependency on ActiveSupport

### ISSUE THREAD

**Issue by bdwyertech** [inspec/inspec#6527]
# Describe the problem
https://github.com/inspec/inspec/pull/6410 introduced an undocumented dependency on ActiveSupport due to its usage of the .blank? method on string values.  This function is provided by ActiveSupport

## Possible Solution
Use something other than .blank? e.g. .empty? instead

**Comment by Nik08** [comment]
This bug might only be replicable for `inspec-core` since inspec has a listed dependency for `active-support` on train gem, https://github.com/inspec/train/blob/main/train.gemspec#L34

**Comment by evandam** [comment]
I'm currently seeing an issue with this as well, I think because of a recent version of ActiveSupport that came out. I opened an issue in https://github.com/inspec/train/issues/750 if it helps.

If you install InSpec with bundler (ex: `bundle add inspec-bin`), version 7.1.0 is installed.

Seems like there are some breaking changes in here:

```
❯ inspec exec ./kubernetes -t k8s://
/Users/evan/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/activesupport-7.1.0/lib/active_support/core_ext/array/conversions.rb:108:in `<class:Array>': undefined method `deprecator' for ActiveSupport:Module (NoMethodError)

  deprecate to_default_s: :to_s, deprecator: ActiveSupport.deprecator
                                                          ^^^^^^^^^^^
Did you mean?  deprecate_constant
...
```

If I pin the dependency to `gem "activesupport", "~> 7.0.0"` it works as expected.
