### ISSUE TITLE
Octal Permissions Match

### ISSUE THREAD

**Issue by fcaviggia** [inspec/inspec#666]
### Description

Inspec should be able to allow more restrictive permissions in checking the octal permission value of a file. For example,  the following test should work:

``` ruby
describe file('/etc/shadow') do
  it { should be_file }
  its('mode') { should match (/0(0|4)00/) }
end
```

This test should allow the check to allow either 0000 or 0400 as valid.
### InSpec and Platform Version

$ inspec version
0.14.2

**Comment by arlimus** [comment]
@fcaviggia Mode comes in the form of an integer, which makes means that you cannot `match` it to a regex. Even with the integer-regex matcher in #667, it remains tricky, since mode comes in the form of an octal. @alexpop presented one workaround via `mode.to_s(8)` and `cmp` in that MR. Another would require a special matcher for mode...

**Comment by fcaviggia** [comment]
Very awesome work - I saw the commits a few seconds ago!  That will allow me to compare for more restrictive permissions (which should satisfy requirements).
