### ISSUE TITLE
RFC Attributes

### ISSUE THREAD

**Issue by arlimus** [inspec/inspec#719]
InSpec requires attributes to configure:
- per-machine information
- secrets / credentials

At the same time the philosophy here should be to keep attributes to a bare minimum, as more attributes raise complexity and more complex tests will likely lead to false positives/negatives in inspec.

The current idea for the interface from internal testing has been:

``` ruby
user = attribute('user', required: true)
password = attribute('password', required: true)

attribute(
  field_name,
  required: [true]/false
  validate: [nil]/regex/block
  type: [any]/string/int/numeric/boolean/regex/array/hash
)
```

attributes are always scoped to the profile, i.e. `profile/attribute_name` is required. When profiles are renamed/rescoped through dependency resolution, their new name is applied.

This addresses the following issues:
- Fixes https://github.com/chef/inspec/issues/664
- Fixes https://github.com/chef/inspec/issues/626
- Fixes https://github.com/chef/inspec/issues/611
- Fixes https://github.com/chef/inspec/issues/617

It will also lead to:
- https://github.com/chef/inspec/issues/609 by adding a provider for chef-vault

To fully implement this RFC, we should have a reference implementation for:
- All attribures are scoped https://github.com/chef/inspec/issues/1059
- implement [vault](https://www.vaultproject.io/) secrets backend
- implement [chef-vault](https://github.com/chef/chef-vault) secrets backend
- optional: parse attributes from CLI `INSPEC_ATTR_user=john`

**Comment by chris-rock** [comment]
Things we should consider:
- default values for attributes
- description

```
attribute(
  field_name,
  default: 'value'
  description: 'This is a longer-description, why this is required'
  required: [true]/false
  validate: [nil]/regex/block
  type: [any]/string/int/numeric/boolean/regex/array/hash
)
```

Also I propose that we allow different input methods for attributes. This could be done as following:

```
INSPEC_ATTR_user=john INSPEC_ATTR_password=doe inspec exec my-profile
inspec exec my-profile -attr-file=variables.yml variables2.yml
```

We should also think about an interactive-mode for quick testing different results:

```
inspec exec my-profile --interactive
The profile `my-profile` requests 2 attributes. Abort with Ctrl-C.
  `user`:_
  `password`:_

InSpec executes `my-profile` now.
...
```

During my work on #723, a couple of questions came up:
- What happens if required is set to false? Should the profile fail, when the attribute is not set? Wouldn't a default value have the same impact as required?
- Should execution fail before we execute if not all attributes are specifically set or have default values?
- In case we add a type field to attributes, are we doing type conversion internally eg. for parameter passed via ENV variable?
- The behaviour for profile inheritance need to be discussed. The current draft re-uses the same values with the same name (attributes are scoped per ruby file internally under a profile, but gathered from a simple input yaml)

**Comment by aaronlippold** [comment]
I like @chris-rock suggestions of an interactive mode. 👍  That paired with the --controls= should make it very easy to actively test. 👍 

"_**What happens if required is set to false?**_ 
In thinking about this 'Required == false' is the same as saying the attrib will always have a default value. Required == true is saying 'requiring the user to provide a value or else we can't execute the test.'  So 'required == false' means that we have a default value defined.

Though I am not sure why an attrib would be in a profile if some value for it was not required? Saying required == false would be saying that the "user did not need to provide a value, which means we have some kind of default value we can use"

_This is the same problem/area of problem as an undefined variable correct - compiler error?_

It seems to me that attribs ALWAYS need to have some kind of value given that they are the data point or a part of the data set of the test. I would say this depending on what the missing value is, If the ATTRIB has a default it should be set to the default value. If it does not have a default value, inspec should prompt the user to provide the value.

_**Should the profile fail, when the attribute is not set?**_ 

Prompt, then "skip/fail'. I am of both minds on this. One part of me wants to say that we should fail the whole set of tests if a required attrib is not provided because we want that issue resolved right away. Another part of me says that we should skip / warn the user and provide the results of the tests we can run - putting the WARN / ERROR in BIG BIG bold letters at the top to fix it.

_**Wouldn't a default value have the same impact as required?**_"

The effect would be that it would provide the required value. Though I think they each provide a different function or concept. The fact that a variable needs to be defined in the scope of the users environment makes sense. We can generalize the tests but we need a way to say -

"_This is the test in general, the details / specifics I leave to the users_"

The default value would be there so that we can 'ship a working test' though the default value may not be close to a real work value that would be used. A min_pass of 2 for example. However, the concept of the 'variable needing to be defined to have a valid test - i.e. required' - and having a concept of 'default value' I think are separate. 

_perhaps we make the defaults value for the datatype but useless_ - #=42, text = "fixme" 

I think what this does is if someone inherits tests and asks us to verify them, it gives us a way to say - 

"_In your attributes.yml file you need to provide values for A and B and C, and then we will say your profile is valid. At the moment we are using default values of A=x and B=y and C=z which may not be correct_"

**Comment by chris-rock** [comment]
@arlimus and I discussed the attributes file this morning. We agreed that the file should:
- It should be a yml or json file
- We should leverage existing values from existing systems, therefore we should be able to work with mapped values, eg. retrieve this value from chef databag x
- We should allow mixed mapping, eg. fetch parts from system x, parts from system y and complement all missing files

State of the discussion:

```
# values should be scoped by profile
'cis-docker-bechmark':
  trusted_user: 'vagrant'
  test: 

'cis-mysql':
  user: mysql
  password: mypassword

# an attributes file should be able to override default profile values, think of a profile overlay
'demo-docker-env':
  'cis-mysql':
    user: mysql
   # how do we implement a mapping to a path within this file?
    password: yml://cis-mysql/password 

  'cis-postgres':
    user: 'postgres'
    # if we do mapping via uris, how do we distingush between real urls? 
    password: vault://cis-mysql/password
    url: http://test.com
```

**Comment by mhedgpeth** [comment]
The other thing to consider in this model is how to do things differently in different environments. For my QA environment I might have one set of servers I'm accessing and a different one in Production. If the locations are hard-coded, that will be difficult to do.

**Comment by chris-rock** [comment]
@mhedgpeth Would it work to have two different attribute files? One for qa and one for production? The implementation allows you to use the same profile with different attribute files. Not sure if I got your concern right?

**Comment by mhedgpeth** [comment]
Yes, that would work, but would you provide the attribute file name every time you ran it? How would you use that feature?

**Comment by chris-rock** [comment]
@mhedgpeth The first iteration would expect to name the attribute file with the profile. Once we have that implemented we need to figure out, how the management works for multiple nodes with different profiles per server.

**Comment by chris-rock** [comment]
To fully implement this RFC, we should have a reference implementation for:

- [ ] implement [vault](https://www.vaultproject.io/) secrets backend
- [ ] implement [chef-vault](https://github.com/chef/chef-vault) secrets backend
- [ ] optional: parse attributes from CLI `INSPEC_ATTR_user=john`

**Comment by aaronlippold** [comment]
Use case: I will have 100+ control files profile and I would like a way to centralize the attribute definitions so I can avoid: 

1. duplication of attribute definitions
2. ensure that people don't create more than one attribute to represent the same data
3. have an easy way to modify an attributes should we decide we want to rename one
4. have an easy way to scan all the files to collect the attributes across the 100+ files to create the attributes.xml file.
5. An easy way to report back which control files utilize which attributes.

**Comment by aaronlippold** [comment]
I would perhaps set env_vars for the list of attributes and just use a $INSPEC_ATTRIBS if I was hacking, testing, hacking testing etc. 

In this version,`--attr-vars=user:john password:doe` may make more sense and `--attr-var=<attr>:<var>` for the singular.

Now, last but not least, with the addition of these command line options, the question of precedence comes into play. If I assume that I have  
```inspec exec my-profile --attr-var=user:john --attr-var=password:doe --attrs=example/attributes.xml```

The side case to consider is, what we would need to throw an error when someone double defines an attrib on the command line or at least tell them which one 'wins'.

```inspec exec my-profile --attr-vars="user:john password:doe" --attrs=example/attributes.xml --attr-var="password:jill"```

The assumption is that PASSWORD is defined in all three sources, so we would have to be very clear about which version of the definition will win.

**Comment by aaronlippold** [comment]
When using the same attributes in multiple .rb files - I noticed I got a waring of an already defined constant. I expect this but just something to keep in mind to handle once we refactor.

**Comment by aaronlippold** [comment]
One thing i forgot to add on this was:

I believe that the command line `attr-var` and `attr-vars` should overide the `--attrs=` file values. Second, the `--attrs=` would have precedence over the values in the profile files themselves. 

So it would be a FILO with the flow: rb file attribs load, then command line --attrs file, then CLI values. The override case would be that we could have a `force` param that would tell inspec to use this value for the attrib no matter what - a hard set - if we think that would be needed.

**Comment by aaronlippold** [comment]
@chris-rock @arlimus how is the progress going on this? Thanks.

**Comment by burtlo** [comment]
While exploring profiles I had a similar question to this:

> The behaviour for profile inheritance need to be discussed. The current draft re-uses the same values with the same name (attributes are scoped per ruby file internally under a profile, but gathered from a simple input yaml)

```cucumber
Given a profile named 'app-security' that defines an attribute with the name 'user'.
And a profile named 'system-security' that defines an attribute with the name 'user'.
And an attributes file named 'scan-attributes.yml' which defines:
    """
    user: root 
    """
When I run 'inspec exec app-security system-security --attrs my-attributes.yml'
Then the user is 'root' within both profiles.
```

In the event that a profile has defined an attribute that conflicts with another profile makes me think that we should:

1. As a best practice suggest that individuals use attribute names which incorporate the name of the profile:

```yaml
app-security.user: root
team-security.user: wheel
```

2. Change the way that attributes are defined in the attributes file to namespace them under the profile name. Within the controls of a profile itself there would be no change.

```yaml
app-security:
  user: root
team-security:
  user: wheel
```

**Comment by arlimus** [comment]
Closing this in favor of https://github.com/inspec/inspec/issues/3176
