### ISSUE TITLE
What does 'should cmp' mean?

### ISSUE THREAD

**Issue by chef09210** [inspec/inspec#727]
This is listed in the documentation but not specified anywhere. What does 'should cmp' mean?

**Comment by alexpop** [comment]
It's a matcher like `eq`, but on steroids :)
https://github.com/chef/inspec/blob/master/docs/matchers.rst

**Comment by chris-rock** [comment]
@chef09210 Thanks for highlighting that question. The challenge that we faced a lot, is type conversion. Take one example:

```
describe sshd_config do
  its('Protocol') { should eq '2' }
end
```

Users complained, that they have to type `'2'` instead `2`. And they are right. We had two options to achieve that goal:
1) auto-convert the datatypes
2) resource returns the native datatype and we do the conversion within the matcher

We decided for 2, because the mechanism should be obvious to the user. Lets say we would have done 1: the resource would try to be smart and do auto-conversion. User may not want this, because it eliminates the possibility to an equality check, since we may change the data type. Therefore we created the `cmp` matcher. That handles all the smart auto-conversion, but makes it obvious to the user. Again, same example with the cmp matcher:

```
describe sshd_config do
  its('Protocol') { should cmp 2 }
  its('Protocol') { should eq '2' }
end
```

Therefore we keep the datatype, but give users the flexibility to say: I don't care for the datatype. It is 2.

We use the following examples for our integration tests https://github.com/chef/inspec/blob/master/test/integration/default/compare_matcher_spec.rb 

```
  describe 122 do
    it { should cmp 122 }
    it { should cmp < 133 }
    it { should cmp > 111 }
    it { should_not cmp < 122 }
    it { should_not cmp > 122 }
    it { should cmp <= 122 }
    it { should cmp >= 122 }
    it { should cmp >= -666 }
    it { should_not cmp <= 111 }
    it { should_not cmp >= 133 }
    it { should cmp /122/ }
    it { should_not cmp /133/ }
  end

  describe 0o640 do
    it { should cmp 0o640 }
    it { should cmp > 100 }
    it { should_not cmp <= 0 }
    it { should cmp == '416' }
    it { should cmp /416$/ }
  end

  describe '12' do
    it { should cmp 12 }
    it { should cmp < 13 }
    it { should cmp > 11 }
    it { should_not cmp < 12 }
    it { should_not cmp > 12 }
    it { should cmp <= 12 }
    it { should cmp >= 12 }
    it { should cmp >= -666 }
    it { should_not cmp <= 11 }
    it { should_not cmp >= 13 }
  end

  describe 'some 123' do
    it { should cmp 'some 123' }
    it { should cmp /^SOME\s\d+(1|2|3)3/i }
    it { should_not cmp /^SOME/ }
  end

  describe ['some-array'] do
    it { should cmp 'some-array' }
    it { should cmp /.+/ }
    it { should_not cmp /^SOME/ }
  end

  describe '' do
    it { should_not cmp >= 3 }
    it { should_not cmp < 3 }
    it { should_not cmp /.+/ }
  end

  describe nil do
    it { should cmp nil }
    it { should_not cmp >= 3 }
    it { should_not cmp < 3 }
    it { should_not cmp /something/ }
  end
```

I hope that brought in some light into the darkness?

**Comment by chef09210** [comment]
Yes, thank you both.
