### ISSUE TITLE
document only_if for controls

### ISSUE THREAD

**Issue by chris-rock** [inspec/inspec#760]
### Description

With https://github.com/chef/inspec/pull/619 we introduced `only_if` for controls, but we have not documented it yet.

```
control 'hello' do
  only_if { os[:family] != 'arch' }
  describe 1 do
    it { should eq 2 }
  end
end
```
### InSpec and Platform Version

0.22.0

Aha! Link: https://chef.aha.io/features/SH-2193

**Comment by nvtkaszpir** [comment]
+1

**Comment by Zeerg** [comment]
Any update on this?

**Comment by avishefi** [comment]
I think this is already documented: https://www.inspec.io/docs/reference/dsl_inspec/#exclude-specific-test

**Comment by walterdolce** [comment]
Is there any chance when someone types `only_if` in the website's search bar the comment above (and/or any additional piece of documentation related to this) could appear as a search result?

**Comment by calebwhitt** [comment]
@walterdolce sounds like a great idea. This is still not the case, and I only found https://www.inspec.io/docs/reference/dsl_inspec/#exclude-specific-test because I remembered where I'd seen a mention of `only_if` before in the docs. Are there any updates on this? I feel the current documentation for `only_if` isn't extensive enough.

**Comment by rdonkin** [comment]
I agree that the documentation is not complete for `only_if` - from reading https://www.inspec.io/docs/reference/dsl_inspec/#exclude-specific-test it's not clear whether this applies to the whole `control` clause, or is tied to the next `describe` only.

It would also be good to have documented somewhere how this differs from using `skip if ...`:
```
    before do
      skip if some_condition
    end
```
Examples like in that page are great, but deeper docs are also needed for reference - Ansible and Terraform are reasonable examples here.

**Comment by walterdolce** [comment]
Here's some _activity_ 😉

**Comment by james-stocks** [comment]
A couple of points worth documenting:
 * it applies to the control (maybe document what happens if an `only_if` is attempted outside of a `control` block)
 * Only one is allowed per control, but you can `&&` multiple conditions
 * it results in a skip and not a pass - it should not be used where the "only if" condition means that the system-under-test is compliant.
