### ISSUE TITLE
Inspec exec tests fail if using a one time sudo password(Example: RSA Token)

### ISSUE THREAD

**Issue by daxgames** [inspec/inspec#936]
### Description

Inspec tests run but most fail when using a one time sudo password on the command line.  Manually logging into the server and executing sudo after an inspec run indicates the token is in next token mode.
### InSpec and Platform Version

Inspec version: 0.22.0
Client: MacOS 10.10.5 
Target: RHEL 6.7
### Replication Case

inspec exec --format=documentation test/integration/default/inspec --target=ssh://user@target.host.com --password [user_password] --sudo --sudo-password=[one_time_password]
### Stacktrace

None:  Tests actually run but most fail.  I can run the same test suite against a Vagrant box with passwordless sudo and it works perfectly.

**Comment by chris-rock** [comment]
@daxgames are you still using the original sudo or a custom sudo?

**Comment by daxgames** [comment]
@chris-rock We have both.  The system I was testing with was just plain sudo.

**Comment by chris-rock** [comment]
@daxgames we use plain authentication via ssh. How do you enter it on a cli? We use this in our backend: https://github.com/chef/train/blob/master/lib/train/extras/command_wrapper.rb#L93-L102

**Comment by daxgames** [comment]
@chris-rock I included the command line I am using in my original post.  I arrived at this command line by looking at inspec exec command line Help.

**Comment by chris-rock** [comment]
@daxgames I was asking how you use it without inspec?

**Comment by daxgames** [comment]
How I use what?  Sudo?  I type 'sudo [command]' and it prompts me for rsa tokencode.

**Comment by daxgames** [comment]
@chris-rock - Did my previous answer your question?

**Comment by chris-rock** [comment]
@daxgames we would love to fix this but we do not have a system to validate this against? is there an open source solution available that works similar?

**Comment by kekaichinose** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
