### ISSUE TITLE
Signed compliance profiles

### ISSUE THREAD

**Issue by arlimus** [inspec/inspec#966]
### Description

Support profile signing so that users are certain that the profiles they use and share are not manipulated and produce the expected results. Especially important for all organization putting high trust in this type of compliance automation, anyone working in the federal space, and inheritance from existing profiles.

**Comment by chris-rock** [comment]
As a reference, we should take a look how its done for container images: https://coreos.com/rkt/docs/latest/signing-and-verification-guide.html

**Comment by chris-rock** [comment]
The habitat format is also looking great:
https://github.com/habitat-sh/habitat/blob/master/components/core/src/crypto/mod.rs#L123-L190

**Comment by chris-rock** [comment]
Very good comparison for JSON signing https://medium.facilelogin.com/json-message-signing-alternatives-897f90d411c#.rkh1114mz

**Comment by kekaichinose** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
