### ISSUE TITLE
Signed scan reports

### ISSUE THREAD

**Issue by arlimus** [inspec/inspec#967]
### Description

Support test report signing so that users are certain that the results they gather are not manipulated and produce the expected level of assurance. Especially important for all organization putting high trust in this type of compliance automation, anyone working in the federal space.

**Comment by chris-rock** [comment]
@arlimus What should the format look like. Is this a archive or a plain signed json?

**Comment by chris-rock** [comment]
We should also think about reusing some well-defined standards for reports: https://tools.ietf.org/html/rfc7515#section-3

**Comment by kekaichinose** [comment]
__What’s happening? Why was this issue closed?__
This issue was closed due to some much needed review of legacy issues or issues that were spawned in older versions of InSpec, i.e. < v3.

__Why do I care?__
You would care about this if this was an issue that you are still seeing and/or feel needs to be addressed in the current version of InSpec.

__What do I need to do?__
If this issue is no longer important, no further action is necessary. However, if you think this is something that should be addressed, please open a new issue and refer to the original issue in the description.
